package com.facebook.contacts.graphql;

import X.28Q;
import X.4iJ;
import X.AbstractC11224vw;
import X.C26c;
import androidx.credentials.playservices.controllers.CreatePublicKeyCredential.PublicKeyCredentialControllerUtility;
import com.fasterxml.jackson.databind.JsonSerializer;

/* loaded from: ContactSerializer.class */
public class ContactSerializer extends JsonSerializer {
    /* JADX WARN: Type inference failed for: r0v0, types: [com.fasterxml.jackson.databind.JsonSerializer, java.lang.Object] */
    static {
        4iJ.A03((JsonSerializer) new Object(), Contact.class);
    }

    @Override // com.fasterxml.jackson.databind.JsonSerializer
    public /* bridge */ /* synthetic */ void A0A(28Q r302, C26c c26c, Object obj) {
        Contact contact = (Contact) obj;
        if (contact == null) {
            r302.A0Z();
        }
        r302.A0b();
        AbstractC11224vw.A0D(r302, "contactId", contact.mContactId);
        AbstractC11224vw.A0D(r302, "profileFbid", contact.mProfileFbid);
        AbstractC11224vw.A0D(r302, "graphApiWriteId", contact.mGraphApiWriteId);
        AbstractC11224vw.A05(r302, c26c, contact.mName, PublicKeyCredentialControllerUtility.JSON_KEY_NAME);
        AbstractC11224vw.A05(r302, c26c, contact.mPhoneticName, "phoneticName");
        AbstractC11224vw.A0D(r302, "smallPictureUrl", contact.mSmallPictureUrl);
        AbstractC11224vw.A0D(r302, "bigPictureUrl", contact.mBigPictureUrl);
        AbstractC11224vw.A0D(r302, "hugePictureUrl", contact.mHugePictureUrl);
        int i = contact.mSmallPictureSize;
        r302.A0o("smallPictureSize");
        r302.A0f(i);
        int i2 = contact.mBigPictureSize;
        r302.A0o("bigPictureSize");
        r302.A0f(i2);
        int i3 = contact.mHugePictureSize;
        r302.A0o("hugePictureSize");
        r302.A0f(i3);
        float f = contact.mCommunicationRank;
        r302.A0o("communicationRank");
        r302.A0e(f);
        float f2 = contact.mWithTaggingRank;
        r302.A0o("withTaggingRank");
        r302.A0e(f2);
        AbstractC11224vw.A06(r302, c26c, "phones", contact.mPhones);
        AbstractC11224vw.A06(r302, c26c, "nameSearchTokens", contact.mNameSearchTokens);
        boolean z = contact.mIsMessageBlockedByViewer;
        r302.A0o("isMessageBlockedByViewer");
        r302.A0v(z);
        boolean z2 = contact.mCanMessage;
        r302.A0o("canMessage");
        r302.A0v(z2);
        AbstractC11224vw.A05(r302, c26c, contact.mIsMobilePushable, "isMobilePushable");
        boolean z3 = contact.mIsMessengerUser;
        r302.A0o("isMessengerUser");
        r302.A0v(z3);
        long j = contact.mMessengerInstallTimeInMS;
        r302.A0o("messengerInstallTime");
        r302.A0g(j);
        boolean z4 = contact.mIsMemorialized;
        r302.A0o("isMemorialized");
        r302.A0v(z4);
        boolean z5 = contact.mIsBroadcastRecipientHoldout;
        r302.A0o("isBroadcastRecipientHoldout");
        r302.A0v(z5);
        AbstractC11224vw.A05(r302, c26c, contact.mContactRelationshipStatus, "contactRelationshipStatus");
        long j2 = contact.mAddedTimeInMS;
        r302.A0o("addedTime");
        r302.A0g(j2);
        AbstractC11224vw.A05(r302, c26c, contact.mFriendshipStatus, "friendshipStatus");
        int i4 = contact.mMutualFriendsCount;
        r302.A0o("mutualFriendsCount");
        r302.A0f(i4);
        AbstractC11224vw.A05(r302, c26c, contact.mContactProfileType, "contactType");
        AbstractC11224vw.A06(r302, c26c, "nameEntries", contact.mNameEntries);
        int i5 = contact.mBirthdayDay;
        r302.A0o("birthdayDay");
        r302.A0f(i5);
        int i6 = contact.mBirthdayMonth;
        r302.A0o("birthdayMonth");
        r302.A0f(i6);
        AbstractC11224vw.A0D(r302, "cityName", contact.mCityName);
        boolean z6 = contact.mIsPartial;
        r302.A0o("isPartial");
        r302.A0v(z6);
        long j3 = contact.mLastFetchTime;
        r302.A0o("lastFetchTime");
        r302.A0g(j3);
        long j4 = contact.mMontageThreadFBID;
        r302.A0o("montageThreadFBID");
        r302.A0g(j4);
        float f3 = contact.mPhatRank;
        r302.A0o("phatRank");
        r302.A0e(f3);
        AbstractC11224vw.A0D(r302, "username", contact.mUsername);
        float f4 = contact.mMessengerInvitePriority;
        r302.A0o("messengerInvitePriority");
        r302.A0e(f4);
        boolean z7 = contact.mCanViewerSendMoney;
        r302.A0o("canViewerSendMoney");
        r302.A0v(z7);
        AbstractC11224vw.A05(r302, c26c, contact.mViewerIGFollowStatus, "viewerIGFollowStatus");
        AbstractC11224vw.A05(r302, c26c, contact.mUnifiedStoriesConnectionType, "unifiedStoriesConnectionType");
        boolean z8 = contact.mIsAlohaProxyConfirmed;
        r302.A0o("isAlohaProxyConfirmed");
        r302.A0v(z8);
        AbstractC11224vw.A06(r302, c26c, "alohaProxyUserOwners", contact.mAlohaProxyUserOwners);
        AbstractC11224vw.A06(r302, c26c, "alohaProxyUsersOwned", contact.mAlohaProxyUsersOwned);
        boolean z9 = contact.mIsMessageIgnoredByViewer;
        r302.A0o("isMessageIgnoredByViewer");
        r302.A0v(z9);
        AbstractC11224vw.A05(r302, c26c, contact.mAccountClaimStatus, "accountClaimStatus");
        AbstractC11224vw.A0D(r302, "favoriteColor", contact.mFavoriteColor);
        AbstractC11224vw.A05(r302, c26c, contact.mWorkUserInfo, "workUserInfo");
        boolean z10 = contact.mIsIgCreatorAccount;
        r302.A0o("isIgCreatorAccount");
        r302.A0v(z10);
        boolean z11 = contact.mIsIgBusinessAccount;
        r302.A0o("isIgBusinessAccount");
        r302.A0v(z11);
        boolean z12 = contact.mIsViewerManagingParent;
        r302.A0o("isViewerManagingParent");
        r302.A0v(z12);
        boolean z13 = contact.mIsManagingParentApprovedUser;
        r302.A0o("isManagingParentApprovedUser");
        r302.A0v(z13);
        AbstractC11224vw.A0D(r302, "avatarId", contact.mAvatarId);
        boolean z14 = contact.mIsAvatarPublicAndUsableByViewer;
        r302.A0o("isAvatarPublicAndUsableByViewer");
        r302.A0v(z14);
        AbstractC11224vw.A0D(r302, "avatarPreviewUri", contact.mAvatarPreviewUri);
        boolean z15 = contact.mIsFavoriteMessengerContact;
        r302.A0o("isFavoriteMessengerContact");
        r302.A0v(z15);
        AbstractC11224vw.A0D(r302, "nicknameForViewer", contact.mNicknameForViewer);
        AbstractC11224vw.A05(r302, c26c, contact.mNeoUserStatusSetting, "neoUserStatusSetting");
        boolean z16 = contact.mIsPseudoBlockedByViewer;
        r302.A0o("isPseudoBlockedByViewer");
        r302.A0v(z16);
        boolean z17 = contact.mIsInteropEligible;
        r302.A0o("isInteropEligible");
        r302.A0v(z17);
        AbstractC11224vw.A05(r302, c26c, contact.mReachabilityStatusType, "reachability_status_type");
        AbstractC11224vw.A05(r302, c26c, contact.mRestrictionType, "restrictionType");
        int i7 = contact.mMessageCapabilities;
        r302.A0o("messageCapabilities");
        r302.A0f(i7);
        long j5 = contact.mMessageCapabilities2;
        r302.A0o("messageCapabilities2");
        r302.A0g(j5);
        boolean z18 = contact.mIsGroupXacCallingEligible;
        r302.A0o("isGroupXacCallingEligible");
        r302.A0v(z18);
        float f5 = contact.mMentionsMessengerSharingScore;
        r302.A0o("mentionsMessengerSharingScore");
        r302.A0e(f5);
        AbstractC11224vw.A0D(r302, "avatarAnimationContactOnlineUrl", contact.mAvatarAnimationContactOnlineUrl);
        r302.A0Y();
    }
}
