package com.facebook.video.common.livestreaming.protocol;

import java.util.List;
import java.util.Map;

/* loaded from: VideoBroadcastInitResponse.class */
public abstract class VideoBroadcastInitResponse {
    public final String actorId;
    public final boolean allowBFrame;
    public final Boolean audienceRestrictionsEnabled;
    public final int audioOnlyFormatBitRate;
    public final VideoBroadcastVideoStreamingConfig audioOnlyVideoStreamingConfig;
    public final VideoBroadcastAudioStreamingConfig audioStreamingConfig;
    public final List availableTabs;
    public final String boostedLiveAdsStatus;
    public final int boostedLiveStartTime;
    public final String broadcastId;
    public final int broadcastInterruptionLimitInSeconds;
    public final Integer broadcasterUpdateLogIntervalInSeconds;
    public final boolean canHostInviteGuestAudioOnly;
    public final boolean canHostInviteGuestsWhileLive;
    public final boolean canViewerAdminister;
    public final boolean canViewerSeeCommunityModerationTools;
    public final List defaultShareToGroupIds;
    public final Boolean disableSpeedTest;
    public final String fbLiveFallbackPublishUrl;
    public final String fbLivePublishUrl;
    public final String fbLiveQuicPublishUrl;
    public final String fbLiveTransportHeaderBase64;
    public final boolean hasProfessionalFeaturesForWatch;
    public final String iBPHybridModelConfig;
    public Map initialBitratePrediction;
    public final Boolean isARGiftingEnabled;
    public final Boolean isEligibleMonetizationOnboardingInLive;
    public final boolean isGamingVideo;
    public final Boolean isReceivingStarsEnabled;
    public final boolean isViewerClippingEnabled;
    public final Boolean latencySensitive;
    public final String latencySetting;
    public final String latencyTargetType;
    public final VideoBroadcastLiveOnlineEventConfig liveOnlineEventConfig;
    public final VideoBroadcastLiveTraceConfig liveTraceConfig;
    public final int liveWithMaxParticipants;
    public final Integer llDesiredLatencyMs;
    public final long maxBroadcastDurationSeconds;
    public final long minBroadcastDurationSeconds;
    public final List minimumAgeAudienceRestrictions;
    public final Double networkLagResumeThreshold;
    public final Double networkLagStopThreshold;
    public final boolean passThroughEnabled;
    public final String profileIdIfViewerCanSeeStarsDefaultOnUpsell;
    public final String rawJsonConfig;
    public final String resolutionMappingString;
    public final String riskModel;
    public final String roiType;
    public final String rtcActorId;
    public final String rtmpPublishHeaderBase64;
    public final String rtmpPublishUrl;
    public final Integer savedFeaturedLinksCount;
    public final boolean shouldShowNotifySubscriberPlugin;
    public final Double speedTestMinimumBandwidthThreshold;
    public final String starsCreatorARSettingsID;
    public final Integer streamNetworkConnectionRetryCount;
    public final Integer streamNetworkConnectionRetryDelayInSeconds;
    public final Integer streamNetworkMeasurementsIntervalInMs;
    public final Integer streamNetworkQueueCapacityInBytes;
    public final Integer streamNetworkQueuePercentageOfCapacityToDrop;
    public final Integer streamNetworkQueueVideoCapacityInSeconds;
    public final Integer streamNetworkSendCheckTimeoutMs;
    public final Boolean streamNetworkShouldProbeRttWithPings;
    public final Integer streamNetworkSpeedTestPayloadChunkSizeInBytes;
    public final Integer streamNetworkSpeedTestPayloadSizeInBytes;
    public final Integer streamNetworkSpeedTestPayloadTimeoutInSeconds;
    public final Boolean streamNetworkUseSslFactory;
    public final Double streamThroughputDecayConstant;
    public final String streamVideoAdaptiveBitrateConfig;
    public final Boolean use1RTTConnectionSetup;
    public final VideoBroadcastEndscreenConfig videoBroadcastEndscreenConfig;
    public final VideoBroadcastLiveWithConfig videoBroadcastLiveWithConfig;
    public final String videoId;
    public final String videoQualityModel;
    public final VideoBroadcastVideoStreamingConfig videoStreamingConfig;
}
