package com.facebook.payments.logging;

import X.C0e1;
import X.DKF;
import X.GEP;
import com.facebook.acra.constants.ActionId;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: PaymentsFlowStep.class */
public final class PaymentsFlowStep implements GEP {
    public static final /* synthetic */ PaymentsFlowStep[] A00;
    public static final PaymentsFlowStep A01;
    public static final PaymentsFlowStep A02;
    public static final PaymentsFlowStep A03;
    public static final PaymentsFlowStep A04;
    public static final PaymentsFlowStep A05;
    public static final PaymentsFlowStep A06;
    public static final PaymentsFlowStep A07;
    public static final PaymentsFlowStep A08;
    public static final PaymentsFlowStep A09;
    public static final PaymentsFlowStep A0A;
    public static final PaymentsFlowStep A0B;
    public static final PaymentsFlowStep A0C;
    public static final PaymentsFlowStep A0D;
    public static final PaymentsFlowStep A0E;
    public static final PaymentsFlowStep A0F;
    public static final PaymentsFlowStep A0G;
    public static final PaymentsFlowStep A0H;
    public static final PaymentsFlowStep A0I;
    public static final PaymentsFlowStep A0J;
    public static final PaymentsFlowStep A0K;
    public static final PaymentsFlowStep A0L;
    public static final PaymentsFlowStep A0M;
    public static final PaymentsFlowStep A0N;
    public static final PaymentsFlowStep A0O;
    public static final PaymentsFlowStep A0P;
    public static final PaymentsFlowStep A0Q;
    public static final PaymentsFlowStep A0R;
    public static final PaymentsFlowStep A0S;
    public static final PaymentsFlowStep A0T;
    public static final PaymentsFlowStep A0U;
    public static final PaymentsFlowStep A0V;
    public static final PaymentsFlowStep A0W;
    public static final PaymentsFlowStep A0X;
    public static final PaymentsFlowStep A0Y;
    public static final PaymentsFlowStep A0Z;
    public static final PaymentsFlowStep A0a;
    public static final PaymentsFlowStep A0b;
    public static final PaymentsFlowStep A0c;
    public static final PaymentsFlowStep A0d;
    public static final PaymentsFlowStep A0e;
    public static final PaymentsFlowStep A0f;
    public static final PaymentsFlowStep A0g;
    public static final PaymentsFlowStep A0h;
    public static final PaymentsFlowStep A0i;
    public static final PaymentsFlowStep A0j;
    public static final PaymentsFlowStep A0k;
    public static final PaymentsFlowStep A0l;
    public static final PaymentsFlowStep A0m;
    public static final PaymentsFlowStep A0n;
    public static final PaymentsFlowStep A0o;
    public static final PaymentsFlowStep A0p;
    public static final PaymentsFlowStep A0q;
    public static final PaymentsFlowStep A0r;
    public static final PaymentsFlowStep A0s;
    public static final PaymentsFlowStep A0t;
    public static final PaymentsFlowStep A0u;
    public static final PaymentsFlowStep A0v;
    public static final PaymentsFlowStep A0w;
    public static final PaymentsFlowStep A0x;
    public static final PaymentsFlowStep A0y;
    public static final PaymentsFlowStep A0z;
    public static final PaymentsFlowStep A10;
    public static final PaymentsFlowStep A11;
    public static final PaymentsFlowStep A12;
    public static final PaymentsFlowStep A13;
    public static final PaymentsFlowStep A14;
    public static final PaymentsFlowStep A15;
    public static final PaymentsFlowStep A16;
    public static final PaymentsFlowStep A17;
    public static final PaymentsFlowStep A18;
    public static final PaymentsFlowStep A19;
    public static final PaymentsFlowStep A1A;
    public static final PaymentsFlowStep A1B;
    public static final PaymentsFlowStep A1C;
    public static final PaymentsFlowStep A1D;
    public static final PaymentsFlowStep A1E;
    public static final PaymentsFlowStep A1F;
    public static final PaymentsFlowStep A1G;
    public static final PaymentsFlowStep A1H;
    public static final PaymentsFlowStep A1I;
    public static final PaymentsFlowStep A1J;
    public static final PaymentsFlowStep A1K;
    public static final PaymentsFlowStep A1L;
    public static final PaymentsFlowStep A1M;
    public static final PaymentsFlowStep A1N;
    public static final PaymentsFlowStep A1O;
    public static final PaymentsFlowStep A1P;
    public static final PaymentsFlowStep A1Q;
    public static final PaymentsFlowStep A1R;
    public static final PaymentsFlowStep A1S;
    public static final PaymentsFlowStep A1T;
    public static final PaymentsFlowStep A1U;
    public static final PaymentsFlowStep A1V;
    public static final PaymentsFlowStep A1W;
    public static final PaymentsFlowStep A1X;
    public static final PaymentsFlowStep A1Y;
    public static final PaymentsFlowStep A1Z;
    public static final PaymentsFlowStep A1a;
    public static final PaymentsFlowStep A1b;
    public static final PaymentsFlowStep A1c;
    public static final PaymentsFlowStep A1d;
    public static final PaymentsFlowStep A1e;
    public static final PaymentsFlowStep A1f;
    public static final PaymentsFlowStep A1g;
    public static final PaymentsFlowStep A1h;
    public static final PaymentsFlowStep A1i;
    public static final PaymentsFlowStep A1j;
    public static final PaymentsFlowStep A1k;
    public static final PaymentsFlowStep A1l;
    public static final PaymentsFlowStep A1m;
    public static final PaymentsFlowStep A1n;
    public static final PaymentsFlowStep A1o;
    public static final PaymentsFlowStep A1p;
    public static final PaymentsFlowStep A1q;
    public static final PaymentsFlowStep A1r;
    public static final PaymentsFlowStep A1s;
    public static final PaymentsFlowStep A1t;
    public static final PaymentsFlowStep A1u;
    public static final PaymentsFlowStep A1v;
    public static final PaymentsFlowStep A1w;
    public static final PaymentsFlowStep A1x;
    public static final PaymentsFlowStep A1y;
    public static final PaymentsFlowStep A1z;
    public static final PaymentsFlowStep A20;
    public static final PaymentsFlowStep A21;
    public static final PaymentsFlowStep A22;
    public static final PaymentsFlowStep A23;
    public static final PaymentsFlowStep A24;
    public static final PaymentsFlowStep A25;
    public static final PaymentsFlowStep A26;
    public static final PaymentsFlowStep A27;
    public static final PaymentsFlowStep A28;
    public static final PaymentsFlowStep A29;
    public static final PaymentsFlowStep A2A;
    public static final PaymentsFlowStep A2B;
    public static final PaymentsFlowStep A2C;
    public static final PaymentsFlowStep A2D;
    public static final PaymentsFlowStep A2E;
    public static final PaymentsFlowStep A2F;
    public static final PaymentsFlowStep A2G;
    public static final PaymentsFlowStep A2H;
    public static final PaymentsFlowStep A2I;
    public static final PaymentsFlowStep A2J;
    public static final PaymentsFlowStep A2K;
    public static final PaymentsFlowStep A2L;
    public static final PaymentsFlowStep A2M;
    public static final PaymentsFlowStep A2N;
    public static final PaymentsFlowStep A2O;
    public static final PaymentsFlowStep A2P;
    public static final PaymentsFlowStep A2Q;
    public static final PaymentsFlowStep A2R;
    public static final PaymentsFlowStep A2S;
    public static final PaymentsFlowStep A2T;
    public static final PaymentsFlowStep A2U;
    public static final PaymentsFlowStep A2V;
    public static final PaymentsFlowStep A2W;
    public static final PaymentsFlowStep A2X;
    public static final PaymentsFlowStep A2Y;
    public static final PaymentsFlowStep A2Z;
    public static final PaymentsFlowStep A2a;
    public static final PaymentsFlowStep A2b;
    public static final PaymentsFlowStep A2c;
    public static final PaymentsFlowStep A2d;
    public String mValue;

    static {
        PaymentsFlowStep A0Y2 = DKF.A0Y("ADD_BANK_ACCOUNT", "add_bank_account", 0);
        A02 = A0Y2;
        PaymentsFlowStep A0Y3 = DKF.A0Y("ADD_CARD", "add_card", 1);
        A03 = A0Y3;
        PaymentsFlowStep A0Y4 = DKF.A0Y("ADD_EMAIL", "add_email", 2);
        A04 = A0Y4;
        PaymentsFlowStep A0Y5 = DKF.A0Y("ADD_PAYPAL", "add_paypal", 3);
        A06 = A0Y5;
        PaymentsFlowStep A0Y6 = DKF.A0Y("ADD_PHONE", "add_phone", 4);
        A07 = A0Y6;
        PaymentsFlowStep A0Y7 = DKF.A0Y("ADD_NAME", "add_name", 5);
        A05 = A0Y7;
        PaymentsFlowStep A0Y8 = DKF.A0Y("ADDRESS_TYPEAHEAD", "address_typeahead", 6);
        A01 = A0Y8;
        PaymentsFlowStep A0Y9 = DKF.A0Y("ADD_SHIPPING_ADDRESS", "add_shipping_address", 7);
        A08 = A0Y9;
        PaymentsFlowStep A0Y10 = DKF.A0Y("ADD_SIMPLE_CONTACT", "add_simple_contact", 8);
        A09 = A0Y10;
        PaymentsFlowStep A0Y11 = DKF.A0Y("SCAN_CARD", "scan_card", 9);
        A1u = A0Y11;
        PaymentsFlowStep A0Y12 = DKF.A0Y("CART_ITEM_SEARCH", "item_search", 10);
        A0F = A0Y12;
        PaymentsFlowStep A0Y13 = DKF.A0Y("CHECKOUT_EXIT_DIALOG", "checkout_exit_dialog", 11);
        A0J = A0Y13;
        PaymentsFlowStep A0Y14 = DKF.A0Y("CHECKOUT_INFORMATION", "checkout_information", 12);
        A0K = A0Y14;
        PaymentsFlowStep A0Y15 = DKF.A0Y("CHECKOUT_MODULE", "checkout_module", 13);
        A0L = A0Y15;
        PaymentsFlowStep A0Y16 = DKF.A0Y("CHECKOUT_SCREEN", "checkout_screen", 14);
        A0M = A0Y16;
        PaymentsFlowStep A0Y17 = DKF.A0Y("CHECKOUT", "checkout", 15);
        A0I = A0Y17;
        PaymentsFlowStep A0Y18 = DKF.A0Y("CONFIRMATION", "confirmation", 16);
        A0O = A0Y18;
        PaymentsFlowStep A0Y19 = DKF.A0Y("COUPON_CODE", "coupon_code", 17);
        A0S = A0Y19;
        PaymentsFlowStep A0Y20 = DKF.A0Y("COUPON_CODE_FORM", "coupon_code_form", 18);
        A0T = A0Y20;
        PaymentsFlowStep A0Y21 = DKF.A0Y("DELETE_SHIPPING_ADDRESS", "delete_shipping_address", 19);
        A0h = A0Y21;
        PaymentsFlowStep A0Y22 = DKF.A0Y("DCP", "dcp", 20);
        A0b = A0Y22;
        PaymentsFlowStep A0Y23 = DKF.A0Y("DELETE_EMAIL", "delete_email", 21);
        A0c = A0Y23;
        PaymentsFlowStep A0Y24 = DKF.A0Y("DELETE_PHONE", "delete_phone", 22);
        A0e = A0Y24;
        PaymentsFlowStep A0Y25 = DKF.A0Y("EDIT_BANK_ACCOUNT", "edit_bank_account", 23);
        A0k = A0Y25;
        PaymentsFlowStep A0Y26 = DKF.A0Y("EDIT_PAYPAL", "edit_paypal", 24);
        A0n = A0Y26;
        PaymentsFlowStep A0Y27 = DKF.A0Y("EMAIL_PHONE_FETCH", "email_phone_fetch", 25);
        A0q = A0Y27;
        PaymentsFlowStep A0Y28 = DKF.A0Y("CONFIRM_SECURITY_CODE", "confirm_security_code", 26);
        A0P = A0Y28;
        PaymentsFlowStep A0Y29 = DKF.A0Y("CONTACT_SUPPORT", "contact_support", 27);
        A0R = A0Y29;
        PaymentsFlowStep A0Y30 = DKF.A0Y("REMOVE_CARD", "remove_card", 28);
        A1p = A0Y30;
        PaymentsFlowStep A0Y31 = DKF.A0Y("REMOVE_PAYPAL", "remove_paypal", 29);
        A1r = A0Y31;
        PaymentsFlowStep A0Y32 = DKF.A0Y("HUB_LANDING", "hub_landing", 30);
        A12 = A0Y32;
        PaymentsFlowStep A0Y33 = DKF.A0Y("HUB_TRANSACTION_HISTORY", "hub_transaction_history", 31);
        A1C = A0Y33;
        PaymentsFlowStep A0Y34 = DKF.A0Y("HUB_TRANSACTION_HISTORY_FETCH", "hub_transaction_history_fetch", 32);
        A1D = A0Y34;
        PaymentsFlowStep A0Y35 = DKF.A0Y("HUB_TXN_HISTORY_SEE_MORE", "hub_txn_history_see_more", 33);
        A1E = A0Y35;
        PaymentsFlowStep A0Y36 = DKF.A0Y("HUB_SUBSCRIPTION_SEE_MORE", "hub_subscription_see_more", 34);
        A17 = A0Y36;
        PaymentsFlowStep A0Y37 = DKF.A0Y("HUB_CASH_BACK_SEE_MORE", "hub_cash_back_see_more", 35);
        A0y = A0Y37;
        PaymentsFlowStep A0Y38 = DKF.A0Y("HUB_BRANDING_PAGE", "hub_branding_page", 36);
        A0x = A0Y38;
        PaymentsFlowStep A0Y39 = DKF.A0Y("HUB_TRANSACTION_DETAILS", "hub_transaction_details", 37);
        A18 = A0Y39;
        PaymentsFlowStep A0Y40 = DKF.A0Y("HUB_GAMES_BALANCE_DETAILS", "hub_games_balance_details", 38);
        A0z = A0Y40;
        PaymentsFlowStep A0Y41 = DKF.A0Y("OPEN_HUB_SETTINGS_FROM_CONFIRMATION_SCREEN", "open_hub_settings_from_confirmation_screen", 39);
        A1P = A0Y41;
        PaymentsFlowStep A0Y42 = DKF.A0Y("OPEN_HUB_SETTINGS_FROM_HUB_LANDING", "open_hub_settings_from_hub_landing", 40);
        A1Q = A0Y42;
        PaymentsFlowStep A0Y43 = DKF.A0Y("OPEN_CASH_BACK", "open_cash_back", 41);
        A1O = A0Y43;
        PaymentsFlowStep A0Y44 = DKF.A0Y("OPEN_OFFERS_PAGE", "open_offers_page", 42);
        A1S = A0Y44;
        PaymentsFlowStep A0Y45 = DKF.A0Y("OPEN_META_REWARD_CENTER", "open_meta_reward_center", 43);
        A1R = A0Y45;
        PaymentsFlowStep A0Y46 = DKF.A0Y("HELP_SUPPORT", "help_support", 44);
        A0w = A0Y46;
        PaymentsFlowStep A0Y47 = DKF.A0Y("TERMS_PRIVACY", "terms_privacy", 45);
        A2D = A0Y47;
        PaymentsFlowStep A0Y48 = DKF.A0Y("HUB_LEARN_MORE", "hub_learn_more", 46);
        A14 = A0Y48;
        PaymentsFlowStep A0Y49 = DKF.A0Y("HUB_LANDING_FETCH", "hub_landing_fetch", 47);
        A13 = A0Y49;
        PaymentsFlowStep A0Y50 = DKF.A0Y("HUB_TRANSACTION_DETAILS_BUTTON", "hub_transaction_details_button", 48);
        A19 = A0Y50;
        PaymentsFlowStep A0Y51 = DKF.A0Y("HUB_TRANSACTION_DETAILS_SUPPORT_LINK", "hub_transaction_support_link", 49);
        A1B = A0Y51;
        PaymentsFlowStep A0Y52 = DKF.A0Y("HUB_TRANSACTION_DETAILS_FETCH", "hub_transaction_details_fetch", 50);
        A1A = A0Y52;
        PaymentsFlowStep A0Y53 = DKF.A0Y("HUB_GO_TO_FACEBOOK_GAMES_BUTTON", "hub_go_to_facebook_games_button", 51);
        A11 = A0Y53;
        PaymentsFlowStep A0Y54 = DKF.A0Y("HUB_GAMES_BALANCE_DETAILS_FETCH", "hub_games_balance_details_fetch", 52);
        A10 = A0Y54;
        PaymentsFlowStep A0Y55 = DKF.A0Y("HUB_SETTINGS", "hub_settings", 53);
        A15 = A0Y55;
        PaymentsFlowStep A0Y56 = DKF.A0Y("HUB_SETTINGS_FETCH", "hub_settings_fetch", 54);
        A16 = A0Y56;
        PaymentsFlowStep A0Y57 = DKF.A0Y("P2P_NUX_FETCH", "p2p_nux_fetch", 55);
        A1T = A0Y57;
        PaymentsFlowStep A0Y58 = DKF.A0Y("P2P_WIDGET_FETCH", "p2p_widget_fetch", 56);
        A1V = A0Y58;
        PaymentsFlowStep A0Y59 = DKF.A0Y("P2P_WIDGET", "p2p_widget", 57);
        A1U = A0Y59;
        PaymentsFlowStep A0Y60 = DKF.A0Y("SET_DEFAULT_PAYMENT_METHOD", "set_default_payment_method", 58);
        A25 = A0Y60;
        PaymentsFlowStep A0Y61 = DKF.A0Y("SET_B2C_DEFAULT_METHOD", "set_B2C_default_method", 59);
        A24 = A0Y61;
        PaymentsFlowStep A0Y62 = DKF.A0Y("SET_P2P_DEFAULT_METHOD", "set_B2C_default_method", 60);
        A26 = A0Y62;
        PaymentsFlowStep A0Y63 = DKF.A0Y("INVOICE", "invoice", 61);
        A1G = A0Y63;
        PaymentsFlowStep A0Y64 = DKF.A0Y("INTENT_HANDLING", "intent", 62);
        A1F = A0Y64;
        PaymentsFlowStep A0Y65 = DKF.A0Y("LOADING", "loading", 63);
        A1I = A0Y65;
        PaymentsFlowStep A0Y66 = DKF.A0Y("LOADING_FAILURE", "loading_failure", 64);
        A1J = A0Y66;
        PaymentsFlowStep A0Y67 = DKF.A0Y("REVIEW", "review", 65);
        A1t = A0Y67;
        PaymentsFlowStep A0Y68 = DKF.A0Y("SEND", "send", 66);
        A23 = A0Y68;
        PaymentsFlowStep A0Y69 = DKF.A0Y("PAYMENT_HISTORY_PICKER_LIST", "payment_history_picker_list", 67);
        A1Z = A0Y69;
        PaymentsFlowStep A0Y70 = DKF.A0Y("STARS_HISTORY_PICKER_LIST", "stars_history_picker_list", 68);
        A2A = A0Y70;
        PaymentsFlowStep A0Y71 = DKF.A0Y("SUBSCRIPTION_HISTORY_PICKER_LIST", "subscription history_picker_list", 69);
        A2B = A0Y71;
        PaymentsFlowStep A0Y72 = DKF.A0Y("CONTACT_INFO_PICKER_LIST", "contact_info_picker_list", 70);
        A0Q = A0Y72;
        PaymentsFlowStep A0Y73 = DKF.A0Y("SHIPPING_ADDRESS_FETCH", "shipping_address_fetch", 71);
        A27 = A0Y73;
        PaymentsFlowStep A0Y74 = DKF.A0Y("MANUAL_BANK_TRANSFER", "manual_bank_transfer", 72);
        A1L = A0Y74;
        PaymentsFlowStep A0Y75 = DKF.A0Y("PAYMENT", "payment", 73);
        A1W = A0Y75;
        PaymentsFlowStep A0Y76 = DKF.A0Y("PAYMENT_ALT_PAY", "payment_alt_pay", 74);
        A1X = A0Y76;
        PaymentsFlowStep A0Y77 = DKF.A0Y("PAYMENT_SUBSCRIPTION", "payment_subscription", 75);
        A1c = A0Y77;
        PaymentsFlowStep A0Y78 = DKF.A0Y("PAYMENT_CHARGE", "payment_charge", 76);
        A1Y = A0Y78;
        PaymentsFlowStep A0Y79 = DKF.A0Y("PAYMENT_POLLING", "payment_polling", 77);
        A1a = A0Y79;
        PaymentsFlowStep A0Y80 = DKF.A0Y("PAYPAL_CONSENT", "paypal_consent", 78);
        A1e = A0Y80;
        PaymentsFlowStep A0Y81 = DKF.A0Y("PAYMENT_SETTINGS", "payment_settings", 79);
        A1b = A0Y81;
        PaymentsFlowStep A0Y82 = DKF.A0Y("PAYOUT_SETUP", "payout_setup", 80);
        A1d = A0Y82;
        PaymentsFlowStep A0Y83 = DKF.A0Y("PIN_SETTINGS", "pin_settings", 81);
        A1g = A0Y83;
        PaymentsFlowStep A0Y84 = DKF.A0Y("ENTER_PIN", "enter_pin", 82);
        A0s = A0Y84;
        PaymentsFlowStep A0Y85 = DKF.A0Y("VERIFY_PIN", "verify_pin", 83);
        A2c = A0Y85;
        PaymentsFlowStep A0Y86 = DKF.A0Y("VERIFY_PASSWORD", "verify_password", 84);
        A2b = A0Y86;
        PaymentsFlowStep A0Y87 = DKF.A0Y("CREATE_PIN_NUX_FROM_CONFIRMATION_SCREEN_LINK", "create_pin_nux_from_confirmation_screen_link", 85);
        A0a = A0Y87;
        PaymentsFlowStep A0Y88 = DKF.A0Y("CREATE_PIN_NUX_FROM_CONFIRMATION_SCREEN_DONE", "create_pin_nux_from_confirmation_screen_done", 86);
        A0Z = A0Y88;
        PaymentsFlowStep A0Y89 = DKF.A0Y("CREATE_PIN_NUX", "create_pin_nux", 87);
        A0Y = A0Y89;
        PaymentsFlowStep A0Y90 = DKF.A0Y("CREATE_FINGERPRINT_NUX", "create_fingerprint_nux", 88);
        A0V = A0Y90;
        PaymentsFlowStep A0Y91 = DKF.A0Y("CREATE_FINGERPRINT_PUX", "create_fingerprint_pux", 89);
        A0W = A0Y91;
        PaymentsFlowStep A0Y92 = DKF.A0Y("LOAD_PIN_FLOW", "load_pin_flow", 90);
        A1K = A0Y92;
        PaymentsFlowStep A0Y93 = DKF.A0Y("CREATE_PIN", "create_pin", 91);
        A0X = A0Y93;
        PaymentsFlowStep A0Y94 = DKF.A0Y("CHANGE_PIN", "change_pin", 92);
        A0H = A0Y94;
        PaymentsFlowStep A0Y95 = DKF.A0Y("RESET_PIN", "reset_pin", 93);
        A1s = A0Y95;
        PaymentsFlowStep A0Y96 = DKF.A0Y("UPDATE_PIN", "update_pin", 94);
        A2T = A0Y96;
        PaymentsFlowStep A0Y97 = DKF.A0Y("UPDATE_LEGAL_NAME", "update_legal_name", 95);
        A2S = A0Y97;
        PaymentsFlowStep A0Y98 = DKF.A0Y("VERIFY_BEFORE_CHANGE_PIN", "verify_before_change_pin", 96);
        A2Y = A0Y98;
        PaymentsFlowStep A0Y99 = DKF.A0Y("DELETE_PIN", "delete_pin", 97);
        A0f = A0Y99;
        PaymentsFlowStep A0Y100 = DKF.A0Y("DELETE_PIN_WITH_PASSWORD", "delete_pin_with_password", 98);
        A0g = A0Y100;
        PaymentsFlowStep A0Y101 = DKF.A0Y("DISABLE_PIN_WITH_PASSWORD", "disable_pin_with_password", 99);
        A0j = A0Y101;
        PaymentsFlowStep A0Y102 = DKF.A0Y("PIN_LOCKED", "pin_locked", 100);
        A1f = A0Y102;
        PaymentsFlowStep A0Y103 = DKF.A0Y("VERIFY_FINGERPRINT", "verify_fingerprint", ActionId.ON_VIEW_CREATED_END);
        A2a = A0Y103;
        PaymentsFlowStep A0Y104 = DKF.A0Y("CREATE_FINGERPRINT", "create_fingerprint", ActionId.DATA_LOAD_START);
        A0U = A0Y104;
        PaymentsFlowStep A0Y105 = DKF.A0Y("DELETE_FINGERPRINT", "delete_fingerprint", ActionId.LEGACY_MARKER);
        A0d = A0Y105;
        PaymentsFlowStep A0Y106 = DKF.A0Y("REGISTER_FBPAY_CLIENT_AUTH_KEY", "register_fbpay_client_auth_key", ActionId.ACTION_BAR_COMPLETE);
        A1l = A0Y106;
        PaymentsFlowStep A0Y107 = DKF.A0Y("REGISTER_FBPAY_CLIENT_AUTH_KEY_NUX", "register_fbpay_client_auth_key_nux", ActionId.ABORTED);
        A1n = A0Y107;
        PaymentsFlowStep A0Y108 = DKF.A0Y("REGISTER_FBPAY_CLIENT_AUTH_KEY_PUX", "register_fbpay_client_auth_key_nux", ActionId.QUERY_READY);
        A1o = A0Y108;
        PaymentsFlowStep A0Y109 = DKF.A0Y("REGISTER_FBPAY_CLIENT_AUTH_KEY_MIGRATION", "register_fbpay_client_auth_key_migration", ActionId.RTMP_PACKET_RECEIVED);
        A1m = A0Y109;
        PaymentsFlowStep A0Y110 = DKF.A0Y("REMOVE_FBPAY_CLIENT_AUTH_KEY", "remove_fbpay_client_auth_key", 108);
        A1q = A0Y110;
        PaymentsFlowStep A0Y111 = DKF.A0Y("VERIFY_FBPAY_CLIENT_AUTH_TOKEN", "verify_fbpay_client_auth_token", ActionId.RTMP_CONNECTION_REQUESTED);
        A2Z = A0Y111;
        PaymentsFlowStep A0Y112 = DKF.A0Y("CHECK_FINGERPRINT_AVAILABILITY", "check_fingerprint_availability", ActionId.RTMP_CONNECTION_RELEASE);
        A0N = A0Y112;
        PaymentsFlowStep A0Y113 = DKF.A0Y("PRICE_TABLE", "price_table", ActionId.NEW_START_FOUND);
        A1h = A0Y113;
        PaymentsFlowStep A0Y114 = DKF.A0Y("PURCHASE_PROTECTION_TOGGLE", "purchase_protection_toggle", ActionId.MISSED_EVENT);
        A1k = A0Y114;
        PaymentsFlowStep A0Y115 = DKF.A0Y("PROOF_OF_PAYMENT", "proof_of_payment", ActionId.TIMEOUT);
        A1i = A0Y115;
        PaymentsFlowStep A0Y116 = DKF.A0Y("STANDALONE_PAYMENT_METHOD_PICKER", "standalone_payment_method_picker", ActionId.CONTROLLER_INITIATED);
        A29 = A0Y116;
        PaymentsFlowStep A0Y117 = DKF.A0Y("SEE_RECEIPT", "see_receipt", ActionId.RTMP_STREAM_PREPARED);
        A1v = A0Y117;
        PaymentsFlowStep A0Y118 = DKF.A0Y("SELECT_UPI", "select_upi", ActionId.VIDEO_PLAYING);
        A22 = A0Y118;
        PaymentsFlowStep A0Y119 = DKF.A0Y("SELECT_BANK_ACCOUNT", "select_bank_account", ActionId.RTMP_CONNECTION_CONNECTED);
        A1w = A0Y119;
        PaymentsFlowStep A0Y120 = DKF.A0Y("SELECT_CONTACT_INFO", "select_contact_info", ActionId.RTMP_CONNECTION_FAILED);
        A1y = A0Y120;
        PaymentsFlowStep A0Y121 = DKF.A0Y("SELECT_PAYMENT_METHOD", "select_payment_method", ActionId.RTMP_CONNECTION_INTERCEPTED);
        A1z = A0Y121;
        PaymentsFlowStep A0Y122 = DKF.A0Y("SELECT_CHECKOUT_OPTION", "select_checkout_option", ActionId.VIDEO_SET_RENDERER_CONTEXT);
        A1x = A0Y122;
        PaymentsFlowStep A0Y123 = DKF.A0Y("SELECT_SHIPPING_ADDRESS", "select_shipping_address", ActionId.HEADER_DATA_LOADED);
        A20 = A0Y123;
        PaymentsFlowStep A0Y124 = DKF.A0Y("SELECT_SHIPPING_METHOD", "select_shipping_method", ActionId.CARD_DATA_LOADED);
        A21 = A0Y124;
        PaymentsFlowStep A0Y125 = DKF.A0Y("SHOW_WEB_VIEW", "show_web_view", ActionId.VIEW_WILL_APPEAR_BEGIN);
        A28 = A0Y125;
        PaymentsFlowStep A0Y126 = DKF.A0Y("APP_SWITCH_INTERSTITIAL", "app_switch_interstitial", ActionId.VIEW_DID_LOAD_BEGIN);
        A0B = A0Y126;
        PaymentsFlowStep A0Y127 = DKF.A0Y("APP_SWITCH_RESULT", "app_switch_result", 125);
        A0C = A0Y127;
        PaymentsFlowStep A0Y128 = DKF.A0Y("APP_SWITCH_INBOUND_STATUS_UPDATE", "app_switch_inbound_status_update", ActionId.COMPONENTS_DATA_SOURCE_DID_END_UPDATES);
        A0A = A0Y128;
        PaymentsFlowStep A0Y129 = DKF.A0Y("CC_3DS_STATUS_UPDATE", "cc_3ds_status_update", 127);
        A0G = A0Y129;
        PaymentsFlowStep A0Y130 = DKF.A0Y("TERMS_FETCH", "terms_fetch", 128);
        A2C = A0Y130;
        PaymentsFlowStep A0Y131 = DKF.A0Y("TOP_OP_OTP_SUBMIT", "top_up_otp_submit", ActionId.MESSENGER_QUEUE_CREATION);
        A2E = A0Y131;
        PaymentsFlowStep A0Y132 = DKF.A0Y("TOP_UP_OTP_RESEND", "top_up_otp_resend", ActionId.APP_DID_FINISH_LAUNCHING);
        A2K = A0Y132;
        PaymentsFlowStep A0Y133 = DKF.A0Y("TOP_UP_OTP_TO_3DS", "top_up_otp_to_3ds", ActionId.APP_DID_BECOME_ACTIVE);
        A2L = A0Y133;
        PaymentsFlowStep A0Y134 = DKF.A0Y("TOP_UP", "top_up", ActionId.APP_WILL_ENTER_FOREGROUND);
        A2F = A0Y134;
        PaymentsFlowStep A0Y135 = DKF.A0Y("TOP_UP_SELECT_CARRIER", "select_carrier", ActionId.APP_DID_ENTER_BACKGROUND);
        A2O = A0Y135;
        PaymentsFlowStep A0Y136 = DKF.A0Y("TOP_UP_AUTO_SELECT_CARRIER", "auto_select_carrier", ActionId.APP_MAIN);
        A2G = A0Y136;
        PaymentsFlowStep A0Y137 = DKF.A0Y("TOP_UP_SELECT_REGION", "select_region", ActionId.MQTT_CONNECTING);
        A2P = A0Y137;
        PaymentsFlowStep A0Y138 = DKF.A0Y("TOP_UP_BROWSE_PLAN", "browse_plan", ActionId.MQTT_CONNECTED);
        A2I = A0Y138;
        PaymentsFlowStep A0Y139 = DKF.A0Y("TOP_UP_CONTINUE", "top_up_cont", ActionId.MQTT_DISCONNECTED);
        A2J = A0Y139;
        PaymentsFlowStep A0Y140 = DKF.A0Y("TOP_UP_BMS_LEARN_MORE", "top_up_bms_learn_more", ActionId.MESSENGER_DELTA_REQUEST);
        A2H = A0Y140;
        PaymentsFlowStep A0Y141 = DKF.A0Y("TOP_UP_PREVIOUS_RECHARGE", "top_up_previous_recharge", ActionId.APP_FIRST_VIEW_CONTROLLER);
        A2M = A0Y141;
        PaymentsFlowStep A0Y142 = DKF.A0Y("TOP_UP_REPEAT_RECHARGE", "top_up_repeat_recharge", ActionId.MESSENGER_THREAD_LIST_LOADED);
        A2N = A0Y142;
        PaymentsFlowStep A0Y143 = DKF.A0Y("UPDATE_CARD", "update_card", ActionId.MESSENGER_THREAD_LIST_DISPLAYED);
        A2R = A0Y143;
        PaymentsFlowStep A0Y144 = DKF.A0Y("EDIT_EMAIL", "edit_email", ActionId.PREV_ACTIVITY_PAUSE);
        A0l = A0Y144;
        PaymentsFlowStep A0Y145 = DKF.A0Y("EDIT_PHONE", "edit_phone", ActionId.ACTIVITY_RESUME);
        A0o = A0Y145;
        PaymentsFlowStep A0Y146 = DKF.A0Y("EDIT_NAME", "edit_name", ActionId.ACTIVITY_START);
        A0m = A0Y146;
        PaymentsFlowStep A0Y147 = DKF.A0Y("EDIT_SHIPPING_ADDRESS", "edit_shipping_address", ActionId.BEGIN_START_ACTIVITY);
        A0p = A0Y147;
        PaymentsFlowStep A0Y148 = DKF.A0Y("UPFRONT_SHIPPING_ADDRESS", "upfront_shipping_address", ActionId.END_START_ACTIVITY);
        A2W = A0Y148;
        PaymentsFlowStep A0Y149 = DKF.A0Y("UPDATE_SIMPLE_CONTACT", "update_simple_contact", ActionId.FILE_SYSTEM_FAIL);
        A2U = A0Y149;
        PaymentsFlowStep A0Y150 = DKF.A0Y("USER_FACING_ERROR", "user_facing_error", ActionId.FORMAT_ERROR);
        A2X = A0Y150;
        PaymentsFlowStep A0Y151 = DKF.A0Y("VIEW_CART", "view_cart", ActionId.PRIVACY_VIOLATION);
        A2d = A0Y151;
        PaymentsFlowStep A0Y152 = DKF.A0Y("DISABLE_PIN", "disable_pin", 150);
        A0i = A0Y152;
        PaymentsFlowStep A0Y153 = DKF.A0Y("ENABLE_PIN", "enable_pin", ActionId.POPULATE_CONSISTENCY_MEMORY_CACHE);
        A0r = A0Y153;
        PaymentsFlowStep A0Y154 = DKF.A0Y("BACKLOAD_PIN", "backloaded_pin", ActionId.APPLY_OPTIMISTICS);
        A0E = A0Y154;
        PaymentsFlowStep A0Y155 = DKF.A0Y("FORGOT_PIN", "forgot_pin", ActionId.APPLY_FINISHED_LIST);
        A0v = A0Y155;
        PaymentsFlowStep A0Y156 = DKF.A0Y("FORGOT_PASSWORD", "forgot_password", ActionId.APPLY_FINISHED_LIST_AGAIN);
        A0u = A0Y156;
        PaymentsFlowStep A0Y157 = DKF.A0Y("LEAVE_RESET_PIN", "leave_reset_pin", ActionId.FUTURE_LISTENERS_COMPLETE);
        A1H = A0Y157;
        PaymentsFlowStep A0Y158 = DKF.A0Y("FETCH_AUTH_CONTENT", "fetch_auth_content", ActionId.SERVICE_ON_START_COMMAND);
        A0t = A0Y158;
        PaymentsFlowStep A0Y159 = DKF.A0Y("AUTH_CONTENT_DISPLAY", "auth_content_display", ActionId.WAIT_FOR_BLOCKERS);
        A0D = A0Y159;
        PaymentsFlowStep A0Y160 = DKF.A0Y("UPDATE_USER_CURRENCY", "update_user_currency", ActionId.NOTIFY_SUBSCRIBERS);
        A2V = A0Y160;
        PaymentsFlowStep A0Y161 = DKF.A0Y("MCOM_PAYOUT_METHOD", "mcom_payout_method", ActionId.FAIL_FILE_TOO_LARGE);
        A1N = A0Y161;
        PaymentsFlowStep A0Y162 = DKF.A0Y("MCOM_DISABLE_PAYMENTS", "mcom_disable_payments", ActionId.OFFLINE);
        A1M = A0Y162;
        PaymentsFlowStep A0Y163 = DKF.A0Y("PTT_BASED_AUTHENTICATION", "ptt_based_authentication", ActionId.ASNYC_FAILED);
        A1j = A0Y163;
        PaymentsFlowStep A0Y164 = DKF.A0Y("UNDEFINED", "undefined", ActionId.ASYNC_FAIL);
        A2Q = A0Y164;
        PaymentsFlowStep[] paymentsFlowStepArr = new PaymentsFlowStep[ActionId.ON_ATTACH_FRAGMENT];
        System.arraycopy(new PaymentsFlowStep[]{A0Y2, A0Y3, A0Y4, A0Y5, A0Y6, A0Y7, A0Y8, A0Y9, A0Y10, A0Y11, A0Y12, A0Y13, A0Y14, A0Y15, A0Y16, A0Y17, A0Y18, A0Y19, A0Y20, A0Y21, A0Y22, A0Y23, A0Y24, A0Y25, A0Y26, A0Y27, A0Y28}, 0, paymentsFlowStepArr, 0, 27);
        System.arraycopy(new PaymentsFlowStep[]{A0Y29, A0Y30, A0Y31, A0Y32, A0Y33, A0Y34, A0Y35, A0Y36, A0Y37, A0Y38, A0Y39, A0Y40, A0Y41, A0Y42, A0Y43, A0Y44, A0Y45, A0Y46, A0Y47, A0Y48, A0Y49, A0Y50, A0Y51, A0Y52, A0Y53, A0Y54, A0Y55}, 0, paymentsFlowStepArr, 27, 27);
        System.arraycopy(new PaymentsFlowStep[]{A0Y56, A0Y57, A0Y58, A0Y59, A0Y60, A0Y61, A0Y62, A0Y63, A0Y64, A0Y65, A0Y66, A0Y67, A0Y68, A0Y69, A0Y70, A0Y71, A0Y72, A0Y73, A0Y74, A0Y75, A0Y76, A0Y77, A0Y78, A0Y79, A0Y80, A0Y81, A0Y82}, 0, paymentsFlowStepArr, 54, 27);
        System.arraycopy(new PaymentsFlowStep[]{A0Y83, A0Y84, A0Y85, A0Y86, A0Y87, A0Y88, A0Y89, A0Y90, A0Y91, A0Y92, A0Y93, A0Y94, A0Y95, A0Y96, A0Y97, A0Y98, A0Y99, A0Y100, A0Y101, A0Y102, A0Y103, A0Y104, A0Y105, A0Y106, A0Y107, A0Y108, A0Y109}, 0, paymentsFlowStepArr, 81, 27);
        System.arraycopy(new PaymentsFlowStep[]{A0Y110, A0Y111, A0Y112, A0Y113, A0Y114, A0Y115, A0Y116, A0Y117, A0Y118, A0Y119, A0Y120, A0Y121, A0Y122, A0Y123, A0Y124, A0Y125, A0Y126, A0Y127, A0Y128, A0Y129, A0Y130, A0Y131, A0Y132, A0Y133, A0Y134, A0Y135, A0Y136}, 0, paymentsFlowStepArr, 108, 27);
        System.arraycopy(new PaymentsFlowStep[]{A0Y137, A0Y138, A0Y139, A0Y140, A0Y141, A0Y142, A0Y143, A0Y144, A0Y145, A0Y146, A0Y147, A0Y148, A0Y149, A0Y150, A0Y151, A0Y152, A0Y153, A0Y154, A0Y155, A0Y156, A0Y157, A0Y158, A0Y159, A0Y160, A0Y161, A0Y162, A0Y163}, 0, paymentsFlowStepArr, ActionId.MQTT_CONNECTING, 27);
        System.arraycopy(new PaymentsFlowStep[]{A0Y164}, 0, paymentsFlowStepArr, ActionId.ASYNC_FAIL, 1);
        A00 = paymentsFlowStepArr;
    }

    public PaymentsFlowStep(String str, int i, String str2) {
        this.mValue = str2;
    }

    public static PaymentsFlowStep forValue(String str) {
        Object obj = A0I;
        Object A002 = C0e1.A00(PaymentsFlowStep.class, str);
        if (A002 != null) {
            obj = A002;
        }
        return (PaymentsFlowStep) obj;
    }

    public static PaymentsFlowStep valueOf(String str) {
        return (PaymentsFlowStep) Enum.valueOf(PaymentsFlowStep.class, str);
    }

    public static PaymentsFlowStep[] values() {
        return (PaymentsFlowStep[]) A00.clone();
    }

    public /* bridge */ /* synthetic */ Object getValue() {
        return this.mValue;
    }
}
