package com.facebook.quickpromotion.debug;

import X.1BK;
import X.1Bi;
import X.1Bq;
import X.1Br;
import X.C3o5;
import X.F5B;
import X.FWh;
import X.GDE;
import android.os.Bundle;
import android.preference.Preference;
import android.preference.PreferenceCategory;
import android.preference.PreferenceScreen;
import com.facebook.base.activity.FbPreferenceActivity;
import com.facebook.quickpromotion.model.QuickPromotionDefinition;

/* loaded from: QuickPromotionFiltersActivity.class */
public final class QuickPromotionFiltersActivity extends FbPreferenceActivity implements GDE {
    public final 1Br A00 = 1Bq.A00(33013);

    public static final void A01(QuickPromotionFiltersActivity quickPromotionFiltersActivity) {
        F5B f5b = (F5B) 1Bi.A03(98796);
        PreferenceScreen createPreferenceScreen = quickPromotionFiltersActivity.getPreferenceManager().createPreferenceScreen(quickPromotionFiltersActivity);
        Preference preference = new Preference(quickPromotionFiltersActivity);
        preference.setTitle("Reset All Overrides to Default");
        preference.setOnPreferenceClickListener(new FWh(quickPromotionFiltersActivity, 12));
        createPreferenceScreen.addPreference(preference);
        PreferenceCategory preferenceCategory = new PreferenceCategory(quickPromotionFiltersActivity);
        createPreferenceScreen.addPreference(preferenceCategory);
        preferenceCategory.setTitle("Filters");
        if (f5b == null) {
            throw 1BK.A0h();
        }
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A38);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2U);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2S);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0a);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0c);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0f);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A12);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1H);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1I);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1f);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1j);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1n);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1x);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1y);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1l);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1m);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A22);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1t);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2D);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1k);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2G);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A25);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2E);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2I);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2J);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2X);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2R);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2T);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2V);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3P);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3S);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3T);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3U);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3V);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3W);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3X);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3Y);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3Q);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A03);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A04);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A05);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A07);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A08);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A09);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0A);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1d);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0C);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0B);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0D);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1e);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0E);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0F);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0L);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0M);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0H);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1Y);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0I);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0J);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0K);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A34);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3F);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0v);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0u);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2Z);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0P);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1Z);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0R);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0S);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0T);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0U);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0V);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0W);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0e);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0j);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0k);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1a);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0m);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0t);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0w);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1D);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0n);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1E);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0x);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1F);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0y);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0z);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A10);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A11);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A13);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A15);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A17);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1J);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0G);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A19);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1A);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2Y);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2x);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1B);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1b);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1L);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1M);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1R);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1N);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1S);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1U);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1T);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2l);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1c);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2K);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A06);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1i);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0b);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1o);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1C);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1Q);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1s);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1z);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0l);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1G);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A20);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2n);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A24);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A23);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3C);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A26);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A27);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A28);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1g);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A29);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2B);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2A);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2C);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2F);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2H);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1u);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1v);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2L);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2M);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2N);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2O);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2m);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2W);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2b);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2h);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2c);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2d);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2g);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2f);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2i);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2k);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2o);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2q);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2s);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2t);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2z);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A30);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A31);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A32);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A36);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A35);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3H);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2j);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3M);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3N);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3O);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A0d);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1V);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2u);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3D);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3B);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3G);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3I);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A16);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1O);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1P);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3Z);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3a);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3K);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3J);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3L);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3b);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1w);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2w);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3h);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A3i);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1q);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A1r);
        C3o5.A0X(quickPromotionFiltersActivity, createPreferenceScreen, f5b, QuickPromotionDefinition.ContextualFilter.Type.A2P);
        quickPromotionFiltersActivity.setPreferenceScreen(createPreferenceScreen);
    }

    @Override // com.facebook.base.activity.FbPreferenceActivity
    public void A0A(Bundle bundle) {
        A01(this);
    }
}
