package com.facebook.video.heroplayer.setting;

import X.C7hy;
import com.facebook.acra.constants.ActionId;
import java.io.Serializable;

/* loaded from: FbAutogeneratedSettings.class */
public class FbAutogeneratedSettings implements Serializable {
    public static final long serialVersionUID = 968006291006349357L;
    public final int autoAddIntParams;
    public final boolean enableSloHttpHeaderLogging;
    public final String grootPrefetchSuboriginBlocklist;
    public final int maxAllowed503RetryCount;

    public FbAutogeneratedSettings(int i, String str, boolean z) {
        this.autoAddIntParams = i;
        this.maxAllowed503RetryCount = -1;
        this.enableSloHttpHeaderLogging = z;
        this.grootPrefetchSuboriginBlocklist = str;
    }

    public FbAutogeneratedSettings(C7hy c7hy) {
        this.autoAddIntParams = ActionId.ON_VIEW_CREATED_END;
        this.maxAllowed503RetryCount = -1;
        this.enableSloHttpHeaderLogging = false;
        this.grootPrefetchSuboriginBlocklist = "";
    }
}
