package com.facebook.notifications.constants.push;

import X.11T;
import X.82M;
import X.C00t;
import android.os.Parcel;
import android.os.Parcelable;
import com.facebook.acra.constants.ActionId;
import com.facebook.forker.Process;
import com.facebookpay.offsite.models.message.OffsiteInitAvailabilityRequestKt;
import com.google.common.collect.ImmutableSet;
import kotlin.enums.EnumEntries;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: NotificationType.class */
public final class NotificationType implements Parcelable {
    public static final ImmutableSet A00;
    public static final /* synthetic */ EnumEntries A01;
    public static final /* synthetic */ NotificationType[] A02;
    public static final NotificationType A03;
    public static final NotificationType A04;
    public static final NotificationType A05;
    public static final NotificationType A06;
    public static final NotificationType A07;
    public static final NotificationType A08;
    public static final NotificationType A09;
    public static final NotificationType A0A;
    public static final NotificationType A0B;
    public static final NotificationType A0C;
    public static final NotificationType A0D;
    public static final NotificationType A0E;
    public static final NotificationType A0F;
    public static final NotificationType A0G;
    public static final NotificationType A0H;
    public static final NotificationType A0I;
    public static final NotificationType A0J;
    public static final NotificationType A0K;
    public static final NotificationType A0L;
    public static final NotificationType A0M;
    public static final NotificationType A0N;
    public static final NotificationType A0O;
    public static final NotificationType A0P;
    public static final NotificationType A0Q;
    public static final NotificationType A0R;
    public static final NotificationType A0S;
    public static final NotificationType A0T;
    public static final NotificationType A0U;
    public static final NotificationType A0V;
    public static final NotificationType A0W;
    public static final NotificationType A0X;
    public static final NotificationType A0Y;
    public static final NotificationType A0Z;
    public static final NotificationType A0a;
    public static final NotificationType A0b;
    public static final NotificationType A0c;
    public static final NotificationType A0d;
    public static final NotificationType A0e;
    public static final NotificationType A0f;
    public static final NotificationType A0g;
    public static final NotificationType A0h;
    public static final NotificationType A0i;
    public static final NotificationType A0j;
    public static final NotificationType A0k;
    public static final NotificationType A0l;
    public static final NotificationType A0m;
    public static final NotificationType A0n;
    public static final NotificationType A0o;
    public static final NotificationType A0p;
    public static final NotificationType A0q;
    public static final NotificationType A0r;
    public static final NotificationType A0s;
    public static final NotificationType A0t;
    public static final NotificationType A0u;
    public static final NotificationType A0v;
    public static final NotificationType A0w;
    public static final NotificationType A0x;
    public static final NotificationType A0y;
    public static final NotificationType A0z;
    public static final NotificationType A10;
    public static final NotificationType A11;
    public static final NotificationType A12;
    public static final NotificationType A13;
    public static final NotificationType A14;
    public static final NotificationType A15;
    public static final NotificationType A16;
    public static final NotificationType A17;
    public static final NotificationType A18;
    public static final NotificationType A19;
    public static final NotificationType A1A;
    public static final NotificationType A1B;
    public static final NotificationType A1C;
    public static final NotificationType A1D;
    public static final NotificationType A1E;
    public static final NotificationType A1F;
    public static final NotificationType A1G;
    public static final NotificationType A1H;
    public static final NotificationType A1I;
    public static final NotificationType A1J;
    public static final NotificationType A1K;
    public static final NotificationType A1L;
    public static final NotificationType A1M;
    public static final NotificationType A1N;
    public static final NotificationType A1O;
    public static final NotificationType A1P;
    public static final NotificationType A1Q;
    public static final NotificationType A1R;
    public static final NotificationType A1S;
    public static final NotificationType A1T;
    public static final NotificationType A1U;
    public static final NotificationType A1V;
    public static final NotificationType A1W;
    public static final NotificationType A1X;
    public static final NotificationType A1Y;
    public static final NotificationType A1Z;
    public static final NotificationType A1a;
    public static final NotificationType A1b;
    public static final NotificationType A1c;
    public static final NotificationType A1d;
    public static final NotificationType A1e;
    public static final NotificationType A1f;
    public static final NotificationType A1g;
    public static final NotificationType A1h;
    public static final NotificationType A1i;
    public static final NotificationType A1j;
    public static final NotificationType A1k;
    public static final NotificationType A1l;
    public static final NotificationType A1m;
    public static final NotificationType A1n;
    public static final NotificationType A1o;
    public static final NotificationType A1p;
    public static final NotificationType A1q;
    public static final NotificationType A1r;
    public static final NotificationType A1s;
    public static final NotificationType A1t;
    public static final NotificationType A1u;
    public static final NotificationType A1v;
    public static final NotificationType A1w;
    public static final NotificationType A1x;
    public static final NotificationType A1y;
    public static final NotificationType A1z;
    public static final NotificationType A20;
    public static final NotificationType A21;
    public static final NotificationType A22;
    public static final NotificationType A23;
    public static final NotificationType A24;
    public static final NotificationType A25;
    public static final NotificationType A26;
    public static final NotificationType A27;
    public static final NotificationType A28;
    public static final NotificationType A29;
    public static final NotificationType A2A;
    public static final NotificationType A2B;
    public static final NotificationType A2C;
    public static final NotificationType A2D;
    public static final NotificationType A2E;
    public static final NotificationType A2F;
    public static final NotificationType A2G;
    public static final NotificationType A2H;
    public static final NotificationType A2I;
    public static final NotificationType A2J;
    public static final NotificationType A2K;
    public static final NotificationType A2L;
    public static final NotificationType A2M;
    public static final NotificationType A2N;
    public static final NotificationType A2O;
    public static final NotificationType A2P;
    public static final NotificationType A2Q;
    public static final NotificationType A2R;
    public static final NotificationType A2S;
    public static final NotificationType A2T;
    public static final NotificationType A2U;
    public static final NotificationType A2V;
    public static final NotificationType A2W;
    public static final NotificationType A2X;
    public static final NotificationType A2Y;
    public static final NotificationType A2Z;
    public static final NotificationType A2a;
    public static final NotificationType A2b;
    public static final NotificationType A2c;
    public static final NotificationType A2d;
    public static final NotificationType A2e;
    public static final NotificationType A2f;
    public static final NotificationType A2g;
    public static final NotificationType A2h;
    public static final NotificationType A2i;
    public static final NotificationType A2j;
    public static final NotificationType A2k;
    public static final NotificationType A2l;
    public static final NotificationType A2m;
    public static final NotificationType A2n;
    public static final NotificationType A2o;
    public static final NotificationType A2p;
    public static final NotificationType A2q;
    public static final NotificationType A2r;
    public static final NotificationType A2s;
    public static final NotificationType A2t;
    public static final NotificationType A2u;
    public static final NotificationType A2v;
    public static final NotificationType A2w;
    public static final NotificationType A2x;
    public static final NotificationType A2y;
    public static final NotificationType A2z;
    public static final NotificationType A30;
    public static final NotificationType A31;
    public static final NotificationType A32;
    public static final NotificationType A33;
    public static final NotificationType A34;
    public static final NotificationType A35;
    public static final NotificationType A36;
    public static final NotificationType A37;
    public static final NotificationType A38;
    public static final NotificationType A39;
    public static final NotificationType A3A;
    public static final NotificationType A3B;
    public static final NotificationType A3C;
    public static final NotificationType A3D;
    public static final NotificationType A3E;
    public static final NotificationType A3F;
    public static final NotificationType A3G;
    public static final NotificationType A3H;
    public static final NotificationType A3I;
    public static final NotificationType A3J;
    public static final NotificationType A3K;
    public static final NotificationType A3L;
    public static final NotificationType A3M;
    public static final NotificationType A3N;
    public static final NotificationType A3O;
    public static final NotificationType A3P;
    public static final NotificationType A3Q;
    public static final NotificationType A3R;
    public static final NotificationType A3S;
    public static final NotificationType A3T;
    public static final NotificationType A3U;
    public static final NotificationType A3V;
    public static final NotificationType A3W;
    public static final NotificationType A3X;
    public static final NotificationType A3Y;
    public static final NotificationType A3Z;
    public static final NotificationType A3a;
    public static final NotificationType A3b;
    public static final NotificationType A3c;
    public static final NotificationType A3d;
    public static final NotificationType A3e;
    public static final NotificationType A3f;
    public static final NotificationType A3g;
    public static final NotificationType A3h;
    public static final NotificationType A3i;
    public static final NotificationType A3j;
    public static final NotificationType A3k;
    public static final NotificationType A3l;
    public static final NotificationType A3m;
    public static final NotificationType A3n;
    public static final NotificationType A3o;
    public static final NotificationType A3p;
    public static final NotificationType A3q;
    public static final NotificationType A3r;
    public static final NotificationType A3s;
    public static final NotificationType A3t;
    public static final NotificationType A3u;
    public static final NotificationType A3v;
    public static final NotificationType A3w;
    public static final NotificationType A3x;
    public static final NotificationType A3y;
    public static final NotificationType A3z;
    public static final NotificationType A40;
    public static final NotificationType A41;
    public static final NotificationType A42;
    public static final NotificationType A43;
    public static final NotificationType A44;
    public static final NotificationType A45;
    public static final NotificationType A46;
    public static final NotificationType A47;
    public static final NotificationType A48;
    public static final NotificationType A49;
    public static final NotificationType A4A;
    public static final NotificationType A4B;
    public static final NotificationType A4C;
    public static final NotificationType A4D;
    public static final NotificationType A4E;
    public static final NotificationType A4F;
    public static final NotificationType A4G;
    public static final NotificationType A4H;
    public static final NotificationType A4I;
    public static final NotificationType A4J;
    public static final NotificationType A4K;
    public static final NotificationType A4L;
    public static final NotificationType A4M;
    public static final NotificationType A4N;
    public static final NotificationType A4O;
    public static final NotificationType A4P;
    public static final NotificationType A4Q;
    public static final NotificationType A4R;
    public static final NotificationType A4S;
    public static final NotificationType A4T;
    public static final NotificationType A4U;
    public static final NotificationType A4V;
    public static final NotificationType A4W;
    public static final NotificationType A4X;
    public static final NotificationType A4Y;
    public static final NotificationType A4Z;
    public static final NotificationType A4a;
    public static final NotificationType A4b;
    public static final NotificationType A4c;
    public static final NotificationType A4d;
    public static final NotificationType A4e;
    public static final NotificationType A4f;
    public static final NotificationType A4g;
    public static final NotificationType A4h;
    public static final NotificationType A4i;
    public static final NotificationType A4j;
    public static final NotificationType A4k;
    public static final NotificationType A4l;
    public static final NotificationType A4m;
    public static final NotificationType A4n;
    public static final NotificationType A4o;
    public static final NotificationType A4p;
    public static final NotificationType A4q;
    public static final NotificationType A4r;
    public static final NotificationType A4s;
    public static final NotificationType A4t;
    public static final NotificationType A4u;
    public static final NotificationType A4v;
    public static final NotificationType A4w;
    public static final NotificationType A4x;
    public static final NotificationType A4y;
    public static final NotificationType A4z;
    public static final NotificationType A50;
    public static final NotificationType A51;
    public static final NotificationType A52;
    public static final NotificationType A53;
    public static final NotificationType A54;
    public static final NotificationType A55;
    public static final NotificationType A56;
    public static final NotificationType A57;
    public static final NotificationType A58;
    public static final NotificationType A59;
    public static final NotificationType A5A;
    public static final NotificationType A5B;
    public static final NotificationType A5C;
    public static final NotificationType A5D;
    public static final NotificationType A5E;
    public static final NotificationType A5F;
    public static final NotificationType A5G;
    public static final NotificationType A5H;
    public static final NotificationType A5I;
    public static final NotificationType A5J;
    public static final NotificationType A5K;
    public static final NotificationType A5L;
    public static final NotificationType A5M;
    public static final NotificationType A5N;
    public static final NotificationType A5O;
    public static final NotificationType A5P;
    public static final NotificationType A5Q;
    public static final NotificationType A5R;
    public static final NotificationType A5S;
    public static final NotificationType A5T;
    public static final NotificationType A5U;
    public static final NotificationType A5V;
    public static final NotificationType A5W;
    public static final Parcelable.Creator CREATOR;

    static {
        NotificationType notificationType = new NotificationType("MESSENGER_BACKGROUND_ACCOUNT_GENERIC", 0);
        A2i = notificationType;
        NotificationType notificationType2 = new NotificationType("MESSENGER_AP_E2EE_BACKGROUND_GENERIC", 1);
        A2h = notificationType2;
        NotificationType notificationType3 = new NotificationType("MSGR_JEWEL_UPDATE", 2);
        A3s = notificationType3;
        NotificationType notificationType4 = new NotificationType("APP_DIRECT_INSTALL_OPEN_REMIND", 3);
        A04 = notificationType4;
        NotificationType notificationType5 = new NotificationType("APPMANAGER_ACTION", 4);
        A03 = notificationType5;
        NotificationType notificationType6 = new NotificationType("AUTHENTICATION_FAILED", 5);
        A05 = notificationType6;
        NotificationType notificationType7 = new NotificationType("AUTO_UPDATE_AVAILABLE", 6);
        A06 = notificationType7;
        NotificationType notificationType8 = new NotificationType("AYMT_MAKE_PAGE_POST_TIP", 7);
        A0A = notificationType8;
        NotificationType notificationType9 = new NotificationType("AYMT_PAGE_RESPOND_MESSAGES_REMINDER_TIP_NOTIF", 8);
        A0B = notificationType9;
        NotificationType notificationType10 = new NotificationType("AYMT_LWI_YESTERDAY_SUMMARY_TIP_NOTIF", 9);
        A09 = notificationType10;
        NotificationType notificationType11 = new NotificationType("MBS_BIZAPP_PHASE_1_FTA_COUPON", 10);
        A2Z = notificationType11;
        NotificationType notificationType12 = new NotificationType("AYMT_LWI_YESTERDAY_SUMMARY_BIZAPP_NOTIF", 11);
        A08 = notificationType12;
        NotificationType notificationType13 = new NotificationType("BIZSUITE_POST_CTX_BOOST_RECOMMENDATION", 12);
        A0Q = notificationType13;
        NotificationType notificationType14 = new NotificationType("BIZSUITE_POST_BOOST_RECOMMENDATION", 13);
        A0P = notificationType14;
        NotificationType notificationType15 = new NotificationType("BADGE_UPDATE", 14);
        A0C = notificationType15;
        NotificationType notificationType16 = new NotificationType("BIRTHDAY_REMINDER", 15);
        A0D = notificationType16;
        NotificationType notificationType17 = new NotificationType("BIZ_COMPOSER_POST_CREATE", 16);
        A0U = notificationType17;
        NotificationType notificationType18 = new NotificationType("BIZ_INBOX_WHATSAPP_MESSAGE", 17);
        A0V = notificationType18;
        NotificationType notificationType19 = new NotificationType("BIZSUITE_MESSAGE_REMINDER", 18);
        A0J = notificationType19;
        NotificationType notificationType20 = new NotificationType("BROADCAST_CHANNELS_BATCHED_REACTIONS", 19);
        A0Y = notificationType20;
        NotificationType notificationType21 = new NotificationType("BOOTSTRAP_UPDATED", 20);
        A0W = notificationType21;
        NotificationType notificationType22 = new NotificationType("BROADCAST_CHANNELS_BATCHED_POLL_VOTES", 21);
        A0X = notificationType22;
        NotificationType notificationType23 = new NotificationType("C4G_INVITE", 22);
        A0Z = notificationType23;
        NotificationType notificationType24 = new NotificationType("CAMPAIGN_CLOSE_FRIEND_ACTIVITY", 23);
        A0a = notificationType24;
        NotificationType notificationType25 = new NotificationType("CAMPAIGN_COMMENT_MENTION", 24);
        A0b = notificationType25;
        NotificationType notificationType26 = new NotificationType("CAMPAIGN_FEED_COMMENT", 25);
        A0c = notificationType26;
        NotificationType notificationType27 = new NotificationType("CAMPAIGN_FEED_COMMENT_REPLY", 26);
        A0d = notificationType27;
        NotificationType notificationType28 = new NotificationType("CAMPAIGN_FRIEND", 27);
        A0e = notificationType28;
        NotificationType notificationType29 = new NotificationType("CAMPAIGN_FRIEND_CONFIRMED", 28);
        A0f = notificationType29;
        NotificationType notificationType30 = new NotificationType("CAMPAIGN_GROUP_COMMENT_REPLY", 29);
        A0g = notificationType30;
        NotificationType notificationType31 = new NotificationType("CAMPAIGN_MENTIONS_COMMENT", 30);
        A0h = notificationType31;
        NotificationType notificationType32 = new NotificationType("CAMPAIGN_STORY_HIGHLIGHT", 31);
        A0i = notificationType32;
        NotificationType notificationType33 = new NotificationType("CBI_IG_PUSH", 32);
        A0j = notificationType33;
        NotificationType notificationType34 = new NotificationType("CMB_DIRECT_INVITE", 33);
        A0m = notificationType34;
        NotificationType notificationType35 = new NotificationType("CREATOR_HIGHLIGHTS", 34);
        A0q = notificationType35;
        NotificationType notificationType36 = new NotificationType("COMMUNITY_MESSAGING_IN_BLUE_CHAT_SUMMARY", 35);
        A0p = notificationType36;
        NotificationType notificationType37 = new NotificationType("BIZSUITE_ONBOARD_TEMPLATE", 36);
        A0M = notificationType37;
        NotificationType notificationType38 = new NotificationType("BIZSUITE_FEED_COMMENT", 37);
        A0F = notificationType38;
        NotificationType notificationType39 = new NotificationType("BIZSUITE_PHOTO_COMMENT", 38);
        A0O = notificationType39;
        NotificationType notificationType40 = new NotificationType("BIZSUITE_VIDEO_COMMENT", 39);
        A0R = notificationType40;
        NotificationType notificationType41 = new NotificationType("BIZSUITE_PHOTO_ALBUM_COMMENT", 40);
        A0N = notificationType41;
        NotificationType notificationType42 = new NotificationType("BIZSUITE_IG_PLATFORM", 41);
        A0I = notificationType42;
        NotificationType notificationType43 = new NotificationType("BIZSUITE_IG_DIRECT", 42);
        A0G = notificationType43;
        NotificationType notificationType44 = new NotificationType("BIZSUITE_IG_DIRECT_EXPERIMENT", 43);
        A0H = notificationType44;
        NotificationType notificationType45 = new NotificationType("BIZSUITE_MSGR_MESSAGE", 44);
        A0K = notificationType45;
        NotificationType notificationType46 = new NotificationType("BIZSUITE_MSGR_MESSAGE_EXPERIMENT", 45);
        A0L = notificationType46;
        NotificationType notificationType47 = new NotificationType("BIZSUITE_ACTION_NEEDED_JEWEL_REMINDER", 46);
        A0E = notificationType47;
        NotificationType notificationType48 = new NotificationType("BIZSUITE_WHATSAPP_MESSAGE", 47);
        A0S = notificationType48;
        NotificationType notificationType49 = new NotificationType("BIZSUITE_WHATSAPP_MESSAGE_REMINDER", 48);
        A0T = notificationType49;
        NotificationType notificationType50 = new NotificationType("CLOSE_FRIEND_ACTIVITY", 49);
        A0k = notificationType50;
        NotificationType notificationType51 = new NotificationType("CLOSE_FRIEND_COMMENT", 50);
        A0l = notificationType51;
        NotificationType notificationType52 = new NotificationType("COMMENT_FAILED", 51);
        A0n = notificationType52;
        NotificationType notificationType53 = new NotificationType("COMMENT_MENTION", 52);
        A0o = notificationType53;
        NotificationType notificationType54 = new NotificationType("DECRYPTION_FAIL_FALLBACK", 53);
        A0r = notificationType54;
        NotificationType notificationType55 = new NotificationType("DEFAULT_PUSH_OF_JEWEL_NOTIF", 54);
        A0s = notificationType55;
        NotificationType notificationType56 = new NotificationType("DEFCON_LEVEL_UPDATED_SILENT_PUSH", 55);
        A0t = notificationType56;
        NotificationType notificationType57 = new NotificationType("DEVICE_REQUEST", 56);
        A0u = notificationType57;
        NotificationType notificationType58 = new NotificationType("DIRECT_MESSAGE_STORY_SEEN", 57);
        A0w = notificationType58;
        NotificationType notificationType59 = new NotificationType("DIRECT_MESSAGE_STORY_POSTED", 58);
        A0v = notificationType59;
        NotificationType notificationType60 = new NotificationType("DIRECT_MESSAGE_STORY_SEEN_MILESTONE", 59);
        A0x = notificationType60;
        NotificationType notificationType61 = new NotificationType("EDIT_MESSAGE", 60);
        A0y = notificationType61;
        NotificationType notificationType62 = new NotificationType("ERROR_CLIENT_NOTIFICATION", 61);
        A0z = notificationType62;
        NotificationType notificationType63 = new NotificationType("EVENT_INVITE", 62);
        A10 = notificationType63;
        NotificationType notificationType64 = new NotificationType("FBNS_MESSAGES_SYNC", 63);
        A16 = notificationType64;
        NotificationType notificationType65 = new NotificationType("FBNS_MOBILE_REQUESTS_COUNT", 64);
        A17 = notificationType65;
        NotificationType notificationType66 = new NotificationType("FBNS_NOTIFICATIONS_READ", 65);
        A18 = notificationType66;
        NotificationType notificationType67 = new NotificationType("FBNS_NOTIFICATIONS_SEEN", 66);
        A19 = notificationType67;
        NotificationType notificationType68 = new NotificationType("FBNS_NOTIFICATIONS_SYNC", 67);
        A1A = notificationType68;
        NotificationType notificationType69 = new NotificationType("FB_GROUP_CHAT_NEW_CHAT_CREATED", 68);
        A1B = notificationType69;
        NotificationType notificationType70 = new NotificationType("FB_SHORTS_FOLLOWER_POSTED", 69);
        A1C = notificationType70;
        NotificationType notificationType71 = new NotificationType("FB_SHORTS_VIDEO_PROCESSED", 70);
        A1D = notificationType71;
        NotificationType notificationType72 = new NotificationType("FBM_PUSH_RETRACT", 71);
        A11 = notificationType72;
        NotificationType notificationType73 = new NotificationType("FBM_PUSH_RETRACT_V2", 72);
        A12 = notificationType73;
        NotificationType notificationType74 = new NotificationType("FBM_PUSH_RETRACT_V3", 73);
        A13 = notificationType74;
        NotificationType notificationType75 = new NotificationType("FBM_PUSH_RETRACT_V4", 74);
        A14 = notificationType75;
        NotificationType notificationType76 = new NotificationType("FBM_PUSH_RETRACT_V5", 75);
        A15 = notificationType76;
        NotificationType notificationType77 = new NotificationType("FB_STORIES_FALLBACK_REPLY", 76);
        A1E = notificationType77;
        NotificationType notificationType78 = new NotificationType("FC_MESSENGER_FETA_ACCOUNT_LIFECYCLE_SELECTED_GUARDIAN_NOTIFICATION", 77);
        A1J = notificationType78;
        NotificationType notificationType79 = new NotificationType("FC_MESSENGER_FETA_AGE_OUT_NOTIFICATION", 78);
        A1K = notificationType79;
        NotificationType notificationType80 = new NotificationType("FC_MESSENGER_FETA_INVITE_UPDATE_GUARDIAN_NOTIFICATION", 79);
        A1L = notificationType80;
        NotificationType notificationType81 = new NotificationType("FC_MESSENGER_FETA_INVITE_UPDATE_TEEN_NOTIFICATION", 80);
        A1M = notificationType81;
        NotificationType notificationType82 = new NotificationType("FC_MESSENGER_FETA_LINK_INVITE_EXPIRED_NOTIFICATION", 81);
        A1N = notificationType82;
        NotificationType notificationType83 = new NotificationType("FC_MESSENGER_FETA_ONGOING_VERIFICATION_FAILURE_NOTIFICATION", 82);
        A1O = notificationType83;
        NotificationType notificationType84 = new NotificationType("FC_MESSENGER_FETA_REMOVE_SUPERVISION_GUARDIAN_NOTIFICATION", 83);
        A1P = notificationType84;
        NotificationType notificationType85 = new NotificationType("FC_MESSENGER_FETA_REMOVE_SUPERVISION_TEEN_NOTIFICATION", 84);
        A1Q = notificationType85;
        NotificationType notificationType86 = new NotificationType("FC_MESSENGER_FETA_RETAIN_SUPERVISION_GUARDIAN_NOTIFICATION", 85);
        A1R = notificationType86;
        NotificationType notificationType87 = new NotificationType("FC_MESSENGER_FETA_TARGETED_INVITE_GUARDIAN_NOTIFICATION", 86);
        A1S = notificationType87;
        NotificationType notificationType88 = new NotificationType("FC_MESSENGER_FETA_TARGETED_INVITE_REMINDER_GUARDIAN_NOTIFICATION", 87);
        A1T = notificationType88;
        NotificationType notificationType89 = new NotificationType("FC_MESSENGER_FETA_TARGETED_INVITE_REMINDER_TEEN_NOTIFICATION", 88);
        A1U = notificationType89;
        NotificationType notificationType90 = new NotificationType("FC_MESSENGER_FETA_TARGETED_INVITE_TEEN_NOTIFICATION", 89);
        A1V = notificationType90;
        NotificationType notificationType91 = new NotificationType("FC_MESSENGER_FETA_VERIFICATION_FAILURE_GUARDIAN_NOTIFICATION", 90);
        A1W = notificationType91;
        NotificationType notificationType92 = new NotificationType("FC_MESSENGER_FETA_VERIFICATION_FAILURE_TEEN_NOTIFICATION", 91);
        A1X = notificationType92;
        NotificationType notificationType93 = new NotificationType("FC_MESSENGER_TEEN_BLOCKED_GUARDIAN_TEEN_NOTIFICATION", 92);
        A1v = notificationType93;
        NotificationType notificationType94 = new NotificationType("FC_MESSENGER_SUPERVISION_INVITE_UPDATED_TEEN_NOTIFICATION", 93);
        A1r = notificationType94;
        NotificationType notificationType95 = new NotificationType("FC_MESSENGER_SUPERVISION_INVITE_UPDATED_GUARDIAN_NOTIFICATION", 94);
        A1q = notificationType95;
        NotificationType notificationType96 = new NotificationType("FC_MESSENGER_INVITE_EXPIRED_GUARDIAN_NOTIFICATION", 95);
        A1b = notificationType96;
        NotificationType notificationType97 = new NotificationType("FC_MESSENGER_INVITE_EXPIRED_TEEN_NOTIFICATION", 96);
        A1c = notificationType97;
        NotificationType notificationType98 = new NotificationType("FC_MESSENGER_VERIFICATION_FAILED_TEEN_NOTIFICATION", 97);
        A21 = notificationType98;
        NotificationType notificationType99 = new NotificationType("FC_MESSENGER_VERIFICATION_FAILED_GUARDIAN_NOTIFICATION", 98);
        A20 = notificationType99;
        NotificationType notificationType100 = new NotificationType("FC_MESSENGER_NEW_CONTACT_GUARDIAN_NOTIFICATION", 99);
        A1d = notificationType100;
        NotificationType notificationType101 = new NotificationType("FC_MESSENGER_TEEN_CHANGED_SETTING_GUARDIAN_NOTIFICATION", 100);
        A1w = notificationType101;
        NotificationType notificationType102 = new NotificationType("FC_MESSENGER_TEEN_REPORT_DETAILS_GUARDIAN_NOTIFICATION", ActionId.ON_VIEW_CREATED_END);
        A1z = notificationType102;
        NotificationType notificationType103 = new NotificationType("FC_MESSENGER_TEEN_REMOVED_SUPERVISION_GUARDIAN_NOTIFICATION", ActionId.DATA_LOAD_START);
        A1y = notificationType103;
        NotificationType notificationType104 = new NotificationType("FC_MESSENGER_GUARDIAN_REMOVED_SUPERVISION_TEEN_NOTIFICATION", ActionId.LEGACY_MARKER);
        A1a = notificationType104;
        NotificationType notificationType105 = new NotificationType("FC_MESSENGER_ASYNC_VERIFICATION_FAILED_TEEN_NOTIFICATION", ActionId.ACTION_BAR_COMPLETE);
        A1G = notificationType105;
        NotificationType notificationType106 = new NotificationType("FC_MESSENGER_ASYNC_VERIFICATION_FAILED_GUARDIAN_NOTIFICATION", ActionId.ABORTED);
        A1F = notificationType106;
        NotificationType notificationType107 = new NotificationType("FC_MESSENGER_PRE_AGE_UP_TEEN_NOTIFICATION", ActionId.QUERY_READY);
        A1g = notificationType107;
        NotificationType notificationType108 = new NotificationType("FC_MESSENGER_PRE_AGE_UP_GUARDIAN_NOTIFICATION", ActionId.RTMP_PACKET_RECEIVED);
        A1f = notificationType108;
        NotificationType notificationType109 = new NotificationType("FC_MESSENGER_SUPERVISION_COOLDOWN_ENDED_TEEN_NOTIFICATION", 108);
        A1p = notificationType109;
        NotificationType notificationType110 = new NotificationType("FC_MESSENGER_SUPERVISION_REINSTATED_GUARDIAN_NOTIFICATION", ActionId.RTMP_CONNECTION_REQUESTED);
        A1s = notificationType110;
        NotificationType notificationType111 = new NotificationType("FC_MESSENGER_TEEN_AGE_UP_REMINDER_TEEN_NOTIFICATION", ActionId.RTMP_CONNECTION_RELEASE);
        A1u = notificationType111;
        NotificationType notificationType112 = new NotificationType("FC_MESSENGER_TEEN_AGE_UP_REMINDER_GUARDIAN_NOTIFICATION", ActionId.NEW_START_FOUND);
        A1t = notificationType112;
        NotificationType notificationType113 = new NotificationType("FC_MESSENGER_GEN_AI_NOTICE_TEEN_NOTIFICATION", ActionId.MISSED_EVENT);
        A1Y = notificationType113;
        NotificationType notificationType114 = new NotificationType("FC_MESSENGER_TEEN_FIRST_GEN_AI_USE_GUARDIAN_NOTIFICATION", ActionId.TIMEOUT);
        A1x = notificationType114;
        NotificationType notificationType115 = new NotificationType("FC_MESSENGER_RECONSENT_GUARDIAN_NOTIFICATION", ActionId.CONTROLLER_INITIATED);
        A1l = notificationType115;
        NotificationType notificationType116 = new NotificationType("FC_MESSENGER_RECONSENT_TEEN_NOTIFICATION", ActionId.RTMP_STREAM_PREPARED);
        A1m = notificationType116;
        NotificationType notificationType117 = new NotificationType("FC_MESSENGER_QUIET_TIME_CHANGED_TEEN_NOTIFICATION", ActionId.VIDEO_PLAYING);
        A1k = notificationType117;
        NotificationType notificationType118 = new NotificationType("FC_MESSENGER_DAILY_TIME_LIMIT_CHANGED_TEEN_NOTIFICATION", ActionId.RTMP_CONNECTION_CONNECTED);
        A1I = notificationType118;
        NotificationType notificationType119 = new NotificationType("FC_MESSENGER_PARENT_MODIFY_SETTING_TEEN_NOTIFICATION", ActionId.RTMP_CONNECTION_FAILED);
        A1e = notificationType119;
        NotificationType notificationType120 = new NotificationType("FC_MESSENGER_SETTINGS_CHANGE_REQUEST_DECISION_TEEN_NOTIFICATION", ActionId.RTMP_CONNECTION_INTERCEPTED);
        A1n = notificationType120;
        NotificationType notificationType121 = new NotificationType("FC_MESSENGER_SETTINGS_CHANGE_REQUEST_GUARDIAN_NOTIFICATION", ActionId.VIDEO_SET_RENDERER_CONTEXT);
        A1o = notificationType121;
        NotificationType notificationType122 = new NotificationType("FC_MESSENGER_CHOOSE_GUARDIAN_TEEN_NOTIFICATION", ActionId.HEADER_DATA_LOADED);
        A1H = notificationType122;
        NotificationType notificationType123 = new NotificationType("FC_MESSENGER_GUARDIAN_NOT_CHOSEN_GUARDIAN_NOTIFICATION", ActionId.CARD_DATA_LOADED);
        A1Z = notificationType123;
        NotificationType notificationType124 = new NotificationType("FC_MESSENGER_PROFILE_WILL_NOT_BE_SUPERVISED_TEEN_NOTIFICATION", ActionId.VIEW_WILL_APPEAR_BEGIN);
        A1j = notificationType124;
        NotificationType notificationType125 = new NotificationType("FC_MESSENGER_PROFILE_IS_NO_LONGER_SUPERVISED_TEEN_NOTIFICATION", ActionId.VIEW_DID_LOAD_BEGIN);
        A1i = notificationType125;
        NotificationType notificationType126 = new NotificationType("FC_MESSENGER_PROFILE_IS_NO_LONGER_SUPERVISED_GUARDIAN_NOTIFICATION", 125);
        A1h = notificationType126;
        NotificationType notificationType127 = new NotificationType("FEEDBACK_REACTION_GENERIC", ActionId.COMPONENTS_DATA_SOURCE_DID_END_UPDATES);
        A22 = notificationType127;
        NotificationType notificationType128 = new NotificationType("FEED_COMMENT", 127);
        A23 = notificationType128;
        NotificationType notificationType129 = new NotificationType("FLASH_INVITE", 128);
        A24 = notificationType129;
        NotificationType notificationType130 = new NotificationType("FOLLOW_PROFILE", ActionId.MESSENGER_QUEUE_CREATION);
        A25 = notificationType130;
        NotificationType notificationType131 = new NotificationType("FRIEND", ActionId.APP_DID_FINISH_LAUNCHING);
        A26 = notificationType131;
        NotificationType notificationType132 = new NotificationType("FRIEND_CONFIRMED", ActionId.APP_DID_BECOME_ACTIVE);
        A27 = notificationType132;
        NotificationType notificationType133 = new NotificationType("FRIEND_REQUEST_REMOVER", ActionId.APP_WILL_ENTER_FOREGROUND);
        A28 = notificationType133;
        NotificationType notificationType134 = new NotificationType("GIFT_RECIPIENT", ActionId.APP_DID_ENTER_BACKGROUND);
        A2C = notificationType134;
        NotificationType notificationType135 = new NotificationType("GEMSTONE_MESSAGE", ActionId.APP_MAIN);
        A29 = notificationType135;
        NotificationType notificationType136 = new NotificationType("GEMSTONE_VIDEO_CALL", ActionId.MQTT_CONNECTING);
        A2A = notificationType136;
        NotificationType notificationType137 = new NotificationType("GENERIC_TINCAN_MESSAGE", ActionId.MQTT_CONNECTED);
        A2B = notificationType137;
        NotificationType notificationType138 = new NotificationType("GROUP_ACTIVITY", ActionId.MQTT_DISCONNECTED);
        A2D = notificationType138;
        NotificationType notificationType139 = new NotificationType("GROUP_COMMENT", ActionId.MESSENGER_DELTA_REQUEST);
        A2E = notificationType139;
        NotificationType notificationType140 = new NotificationType("GROUP_COMMENT_REPLY", ActionId.APP_FIRST_VIEW_CONTROLLER);
        A2G = notificationType140;
        NotificationType notificationType141 = new NotificationType("GROUP_COMMUNITY_AWARD_NOTIFICATION", ActionId.MESSENGER_THREAD_LIST_LOADED);
        A2H = notificationType141;
        NotificationType notificationType142 = new NotificationType("GROUP_HIGHLIGHTS", ActionId.MESSENGER_THREAD_LIST_DISPLAYED);
        A2I = notificationType142;
        NotificationType notificationType143 = new NotificationType("GROUP_NF_HIGHLIGHTS", ActionId.PREV_ACTIVITY_PAUSE);
        A2J = notificationType143;
        NotificationType notificationType144 = new NotificationType("GROUP_POST_AWARD", ActionId.ACTIVITY_RESUME);
        A2K = notificationType144;
        NotificationType notificationType145 = new NotificationType("GROUP_POST_MENTION", ActionId.ACTIVITY_START);
        A2L = notificationType145;
        NotificationType notificationType146 = new NotificationType("HOTP_LOGIN_APPROVALS", ActionId.BEGIN_START_ACTIVITY);
        A2M = notificationType146;
        NotificationType notificationType147 = new NotificationType("INTERNAL", ActionId.END_START_ACTIVITY);
        A2N = notificationType147;
        NotificationType notificationType148 = new NotificationType("IXC_MESSENGER_SUPPORT_INBOX", ActionId.FILE_SYSTEM_FAIL);
        A2O = notificationType148;
        NotificationType notificationType149 = new NotificationType("LA_PUSH_AUTHENTICATE", ActionId.FORMAT_ERROR);
        A2P = notificationType149;
        NotificationType notificationType150 = new NotificationType("LIKE", ActionId.PRIVACY_VIOLATION);
        A2Q = notificationType150;
        NotificationType notificationType151 = new NotificationType("LIVE_VIDEO", 150);
        A2R = notificationType151;
        NotificationType notificationType152 = new NotificationType("LIVE_VIDEO_EXPLICIT", ActionId.POPULATE_CONSISTENCY_MEMORY_CACHE);
        A2S = notificationType152;
        NotificationType notificationType153 = new NotificationType("WATCH_FOLLOWER_VIDEO", ActionId.APPLY_OPTIMISTICS);
        A5F = notificationType153;
        NotificationType notificationType154 = new NotificationType("WATCH_FOLLOWER_VIDEO_EXPLICIT", ActionId.APPLY_FINISHED_LIST);
        A5G = notificationType154;
        NotificationType notificationType155 = new NotificationType("LOCATION_SHARING_SILENT_PUSH", ActionId.APPLY_FINISHED_LIST_AGAIN);
        A2T = notificationType155;
        NotificationType notificationType156 = new NotificationType("LOGGED_OUT_BADGE", ActionId.FUTURE_LISTENERS_COMPLETE);
        A2U = notificationType156;
        NotificationType notificationType157 = new NotificationType("LOGGED_OUT_PUSH", ActionId.SERVICE_ON_START_COMMAND);
        A2V = notificationType157;
        NotificationType notificationType158 = new NotificationType("LOGGED_OUT_PUSH_TRIGGER", ActionId.WAIT_FOR_BLOCKERS);
        A2W = notificationType158;
        NotificationType notificationType159 = new NotificationType("LOGIN_APPROVALS_PUSH_AUTH", ActionId.NOTIFY_SUBSCRIBERS);
        A2X = notificationType159;
        NotificationType notificationType160 = new NotificationType("MARKETING_MESSAGES_UNREAD_OPTIN_REMINDER", ActionId.FAIL_FILE_TOO_LARGE);
        A2Y = notificationType160;
        NotificationType notificationType161 = new NotificationType("MENTION", ActionId.OFFLINE);
        A2a = notificationType161;
        NotificationType notificationType162 = new NotificationType("MENTIONS_COMMENT", ActionId.ASNYC_FAILED);
        A2b = notificationType162;
        NotificationType notificationType163 = new NotificationType("MESSAGE_COUNTS", ActionId.ASYNC_FAIL);
        A2c = notificationType163;
        NotificationType notificationType164 = new NotificationType("MESSAGE_REQUEST", ActionId.ON_ATTACH_FRAGMENT);
        A2d = notificationType164;
        NotificationType notificationType165 = new NotificationType("MESSAGING_IN_BLUE_DIRECT_MESSAGE", ActionId.VIEW_DID_APPEAR_BEGIN);
        A2e = notificationType165;
        NotificationType notificationType166 = new NotificationType("MESSAGING_IN_BLUE_EDIT_MESSAGE", ActionId.DISPLAYED);
        A2f = notificationType166;
        NotificationType notificationType167 = new NotificationType("MESSENGER_MONTAGE_REPLY", ActionId.DISPLAYED_ON_SCREEN);
        A3V = notificationType167;
        NotificationType notificationType168 = new NotificationType("MESSAGING_IN_BLUE_SUBSEQUENT_MESSAGE", ActionId.ASYNC_ACTION_SUCCESS);
        A2g = notificationType168;
        NotificationType notificationType169 = new NotificationType("MESSENGER_DIRECT_INVITE_MEMBERSHIP_REQUEST_APPROVAL_STATUS", ActionId.ASYNC_ACTION_FAIL);
        A3F = notificationType169;
        NotificationType notificationType170 = new NotificationType("MESSENGER_ENCRYPTED_BACKUPS_ONE_TIME_CODE", ActionId.CONNECTIVITY_CHANGED);
        A3H = notificationType170;
        NotificationType notificationType171 = new NotificationType("MESSENGER_ENCRYPTED_BACKUPS_NETWORK_VERIFICATION_RESTORE", ActionId.VIDEO_DISPLAYED);
        A3G = notificationType171;
        NotificationType notificationType172 = new NotificationType("MESSENGER_ENCRYPTED_BACKUPS_WEB2MOBILE_ONBOARDING", ActionId.VIDEO_REQUESTED_PLAYING);
        A3I = notificationType172;
        NotificationType notificationType173 = new NotificationType("MESSENGER_EVENT_REMINDER", 172);
        A3J = notificationType173;
        NotificationType notificationType174 = new NotificationType("MESSENGER_REFERRAL_EXPIRY_REMINDER", 173);
        A3Z = notificationType174;
        NotificationType notificationType175 = new NotificationType("MESSENGER_REMOVE_MESSAGE", 174);
        A3b = notificationType175;
        NotificationType notificationType176 = new NotificationType("MESSENGER_GROUP_JOIN_REQUEST", 175);
        A3L = notificationType176;
        NotificationType notificationType177 = new NotificationType("MESSENGER_GROUP_CALL_UPDATES", 176);
        A3K = notificationType177;
        NotificationType notificationType178 = new NotificationType("MESSENGER_KIDS_REMINDER", 177);
        A3M = notificationType178;
        NotificationType notificationType179 = new NotificationType("MESSENGER_LIVING_ROOM_CREATE", 178);
        A3N = notificationType179;
        NotificationType notificationType180 = new NotificationType("MESSENGER_MESSAGE_REMINDER", 179);
        A3P = notificationType180;
        NotificationType notificationType181 = new NotificationType("MESSENGER_MONTAGE_DAILY_DIGEST", 180);
        A3Q = notificationType181;
        NotificationType notificationType182 = new NotificationType("MESSENGER_MONTAGE_FIRST_MESSAGE", 181);
        A3R = notificationType182;
        NotificationType notificationType183 = new NotificationType("MESSENGER_MONTAGE_FIRST_POST", 182);
        A3S = notificationType183;
        NotificationType notificationType184 = new NotificationType("MESSENGER_MONTAGE_MESSAGE_EXPIRING", 183);
        A3T = notificationType184;
        NotificationType notificationType185 = new NotificationType("MESSENGER_MONTAGE_MESSAGE_VIEWING_STATUS", 184);
        A3U = notificationType185;
        NotificationType notificationType186 = new NotificationType("MESSENGER_CHAT_ENCOURAGEMENT", 185);
        A2k = notificationType186;
        NotificationType notificationType187 = new NotificationType("MESSENGER_REACTIONS", 186);
        A3Y = notificationType187;
        NotificationType notificationType188 = new NotificationType("MESSENGER_NOTE_UPDATE", 187);
        A3X = notificationType188;
        NotificationType notificationType189 = new NotificationType("MESSENGER_NOTE_MENTION", 188);
        A3W = notificationType189;
        NotificationType notificationType190 = new NotificationType("MESSENGER_BIC_CONSENT_REQUEST", 189);
        A2j = notificationType190;
        NotificationType notificationType191 = new NotificationType("MESSENGER_MEMORIES", 190);
        A3O = notificationType191;
        NotificationType notificationType192 = new NotificationType("MESSENGER_REMINDER", 191);
        A3a = notificationType192;
        NotificationType notificationType193 = new NotificationType("MESSENGER_ROOM_FRIEND_JOIN", 192);
        A3d = notificationType193;
        NotificationType notificationType194 = new NotificationType("MESSENGER_ROOM_INVITE", 193);
        A3e = notificationType194;
        NotificationType notificationType195 = new NotificationType("MESSENGER_STALE_PUSH", 194);
        A3f = notificationType195;
        NotificationType notificationType196 = new NotificationType("MESSENGER_STATUS_CHANGE", 195);
        A3g = notificationType196;
        NotificationType notificationType197 = new NotificationType("MESSENGER_TRY_AR_EFFECT", 196);
        A3h = notificationType197;
        NotificationType notificationType198 = new NotificationType("MESSENGER_COMMUNITY_CHAT", 197);
        A2o = notificationType198;
        NotificationType notificationType199 = new NotificationType("MESSENGER_COMMUNITY_CHAT_MENTIONS_AND_REPLIES", 198);
        A2v = notificationType199;
        NotificationType notificationType200 = new NotificationType("MESSENGER_COMMUNITY_CHAT_LEVEL_PARTICIPATION_CONTROL_APPROVAL", 199);
        A2u = notificationType200;
        NotificationType notificationType201 = new NotificationType("MESSENGER_COMMUNITY_LEVEL_PARTICIPATION_CONTROL_APPROVAL", 200);
        A36 = notificationType201;
        NotificationType notificationType202 = new NotificationType("MESSENGER_COMMUNITY_LEVEL_JOIN_REQUEST_APPROVAL_STATUS", 201);
        A35 = notificationType202;
        NotificationType notificationType203 = new NotificationType("MESSENGER_COMMUNITY_REACTION", 202);
        A3A = notificationType203;
        NotificationType notificationType204 = new NotificationType("MESSENGER_COMMUNITY_ADMIN_DIRECT_INVITE_GENERIC", 203);
        A2l = notificationType204;
        NotificationType notificationType205 = new NotificationType("MESSENGER_COMMUNITY_CHANNEL_CREATION", 204);
        A2n = notificationType205;
        NotificationType notificationType206 = new NotificationType("MESSENGER_COMMUNITY_TRENDING", 205);
        A3C = notificationType206;
        NotificationType notificationType207 = new NotificationType("MESSENGER_COMMUNITY_DEFAULT_GENERAL_CHAT", 206);
        A2w = notificationType207;
        NotificationType notificationType208 = new NotificationType("MESSENGER_COMMUNITY_DEFAULT_NOTIFICATION", 207);
        A2x = notificationType208;
        NotificationType notificationType209 = new NotificationType("MESSENGER_COMMUNITY_LEVEL_DIRECT_INVITE", 208);
        A32 = notificationType209;
        NotificationType notificationType210 = new NotificationType("MESSENGER_COMMUNITY_LEVEL_DIRECT_INVITE_V2", 209);
        A33 = notificationType210;
        NotificationType notificationType211 = new NotificationType("MESSENGER_COMMUNITY_LEVEL_ENGAGEMENT", 210);
        A34 = notificationType211;
        NotificationType notificationType212 = new NotificationType("MESSENGER_COMMUNITY_MEMBER_CHAT_APPROVED", 211);
        A37 = notificationType212;
        NotificationType notificationType213 = new NotificationType("MESSENGER_COMMUNITY_BROADCAST_CHAT_FIRST_MESSAGE", 212);
        A2m = notificationType213;
        NotificationType notificationType214 = new NotificationType("MESSENGER_COMMUNITY_EPHEMERAL_STATUS_BADGE_EARNED", 213);
        A30 = notificationType214;
        NotificationType notificationType215 = new NotificationType("MESSENGER_COMMUNITY_MEMBER_REQUEST", 214);
        A38 = notificationType215;
        NotificationType notificationType216 = new NotificationType("MESSENGER_COMMUNITY_INCOMPLETE_ADMOD_SUGGESTED_ACTIONS", 215);
        A31 = notificationType216;
        NotificationType notificationType217 = new NotificationType("MESSENGER_COMMUNITY_CHAT_HOST_INVITE", 216);
        A2p = notificationType217;
        NotificationType notificationType218 = new NotificationType("MESSENGER_COMMUNITY_DIGEST", 217);
        A2y = notificationType218;
        NotificationType notificationType219 = new NotificationType("MESSENGER_COMMUNITY_PAGE_CHAT", 218);
        A39 = notificationType219;
        NotificationType notificationType220 = new NotificationType("MESSENGER_COMMUNITY_RECALL_MESSAGE", 219);
        A3B = notificationType220;
        NotificationType notificationType221 = new NotificationType("MESSENGER_COMMUNITY_CHAT_JOIN_REQUEST_ADDED", 220);
        A2q = notificationType221;
        NotificationType notificationType222 = new NotificationType("MESSENGER_COMMUNITY_CHAT_JOIN_REQUEST_APPROVED", 221);
        A2t = notificationType222;
        NotificationType notificationType223 = new NotificationType("MESSENGER_COMMUNITY_CHAT_JOIN_REQUEST_ADDED_SINGLE", 222);
        A2s = notificationType223;
        NotificationType notificationType224 = new NotificationType("MESSENGER_COMMUNITY_CHAT_JOIN_REQUEST_ADDED_BATCHED", 223);
        A2r = notificationType224;
        NotificationType notificationType225 = new NotificationType("MESSENGER_COMMUNITY_EDIT_MESSAGE", 224);
        A2z = notificationType225;
        NotificationType notificationType226 = new NotificationType("MESSENGER_COWATCH_VIDEO_STARTED", 225);
        A3D = notificationType226;
        NotificationType notificationType227 = new NotificationType("MESSENGER_DEEP_SLEEP_MODE", 226);
        A3E = notificationType227;
        NotificationType notificationType228 = new NotificationType("PUBLIC_DISCOVERABLE_BROADCAST_CHAT_NOTIFICATION", 227);
        A4p = notificationType228;
        NotificationType notificationType229 = new NotificationType("MK_BACKGROUND_ACTION_TRIGGER", 228);
        A3i = notificationType229;
        NotificationType notificationType230 = new NotificationType("MOBILE_ZERO_FREE_FACEBOOK_LAUNCH", 229);
        A3j = notificationType230;
        NotificationType notificationType231 = new NotificationType("MONTAGE_MESSAGE_REACTION", 230);
        A3k = notificationType231;
        NotificationType notificationType232 = new NotificationType("MSG", 231);
        A3l = notificationType232;
        NotificationType notificationType233 = new NotificationType("MSGR_AI_AGENTS_USER_OFF_WAITLIST", 232);
        A3m = notificationType233;
        NotificationType notificationType234 = new NotificationType("MSGR_SHARED_ALBUM_CREATION", 233);
        A3v = notificationType234;
        NotificationType notificationType235 = new NotificationType("MSGR_SHARED_ALBUM_ADDITION", 234);
        A3u = notificationType235;
        NotificationType notificationType236 = new NotificationType("MSGR_SHARED_ALBUM_DELETION", 235);
        A3w = notificationType236;
        NotificationType notificationType237 = new NotificationType("MSGR_SHARED_ALBUM_REMOVAL", 236);
        A3y = notificationType237;
        NotificationType notificationType238 = new NotificationType("MSGR_SHARED_ALBUM_REACTION", 237);
        A3x = notificationType238;
        NotificationType notificationType239 = new NotificationType("MSGR_BC_FIRST_MESSAGE_REMINDER", 238);
        A3n = notificationType239;
        NotificationType notificationType240 = new NotificationType("MSGR_BROADCAST_CHANNELS_MESSAGE_RECALL_NOTIFICATION", 239);
        A3o = notificationType240;
        NotificationType notificationType241 = new NotificationType("MSGR_CM_AND_CHANNEL_INVITE_LINK_JOIN", 240);
        A3p = notificationType241;
        NotificationType notificationType242 = new NotificationType("MSGR_COMMUNITY_MEMBER_CHAT_SUGGESTIONS_NOTIF", 241);
        A3q = notificationType242;
        NotificationType notificationType243 = new NotificationType("MSGR_PUBLIC_CHATS_DIRECT_INVITE", 242);
        A3t = notificationType243;
        NotificationType notificationType244 = new NotificationType("MSNGR_AFS_SUBSCRIPTION_CANCELED_DEVICE_SETTINGS", 243);
        A45 = notificationType244;
        NotificationType notificationType245 = new NotificationType("MSNGR_AFS_LINKING_BOTH_SUBSCRIBED", 244);
        A40 = notificationType245;
        NotificationType notificationType246 = new NotificationType("MSNGR_AFS_CANCELATION_INCOMPLETE", 245);
        A3z = notificationType246;
        NotificationType notificationType247 = new NotificationType("MSNGR_AFS_YOUTH_SHOULD_CANCEL_SUBSCRIPTION", 246);
        A48 = notificationType247;
        NotificationType notificationType248 = new NotificationType("MSNGR_AFS_UNLINKING_DEFERRED_DOWNGRADE_NEXT_BILLING_CYCLE", 247);
        A46 = notificationType248;
        NotificationType notificationType249 = new NotificationType("MSNGR_AFS_LINKING_MULTIPLE_SUBSCRIPTION_DEFERRED_DOWNGRADE_NEXT_BILLING_CYCLE", 248);
        A42 = notificationType249;
        NotificationType notificationType250 = new NotificationType("MSNGR_AFS_LINKING_MULTIPLE_SUBSCRIPTION_DEFERRED_DOWNGRADE", 249);
        A41 = notificationType250;
        NotificationType notificationType251 = new NotificationType("MSNGR_AFS_STANDARD_UNLINKING", 250);
        A44 = notificationType251;
        NotificationType notificationType252 = new NotificationType("MSNGR_AFS_MULTIPLE_SUBSCRIPTION_VARIABLE_PRICING", Process.SD_STDOUT);
        A43 = notificationType252;
        NotificationType notificationType253 = new NotificationType("MSNGR_AFS_UPGRADE_DEVICE_SETTING", Process.SD_PIPE);
        A47 = notificationType253;
        NotificationType notificationType254 = new NotificationType("NEAR_SAVED_PLACE", Process.SD_BLACK_HOLE);
        A4B = notificationType254;
        NotificationType notificationType255 = new NotificationType("NEKO_INSTALL_REMINDER", 254);
        A4C = notificationType255;
        NotificationType notificationType256 = new NotificationType("NF_CHECKIN_STORY", 255);
        A4D = notificationType256;
        NotificationType notificationType257 = new NotificationType("NF_COMMENT_STORY", 256);
        A4E = notificationType257;
        NotificationType notificationType258 = new NotificationType("NF_NOTE_STORY", 257);
        A4F = notificationType258;
        NotificationType notificationType259 = new NotificationType("NF_PHOTO_ALBUM_STORY", 258);
        A4G = notificationType259;
        NotificationType notificationType260 = new NotificationType("NF_PHOTO_STORY", 259);
        A4H = notificationType260;
        NotificationType notificationType261 = new NotificationType("NF_SHARE_STORY", 260);
        A4I = notificationType261;
        NotificationType notificationType262 = new NotificationType("NF_STATUS_STORY", 261);
        A4J = notificationType262;
        NotificationType notificationType263 = new NotificationType("NF_VIDEO_STORY", 262);
        A4K = notificationType263;
        NotificationType notificationType264 = new NotificationType("NOW_UPDATE", 263);
        A4L = notificationType264;
        NotificationType notificationType265 = new NotificationType("N4M_TXN_P2P_UPDATE", 264);
        A4A = notificationType265;
        NotificationType notificationType266 = new NotificationType("ONTHISDAY", 265);
        A4M = notificationType266;
        NotificationType notificationType267 = new NotificationType("ORCA_FRIEND_MSG", 266);
        A4N = notificationType267;
        NotificationType notificationType268 = new NotificationType("ORCA_MESSAGE", 267);
        A4O = notificationType268;
        NotificationType notificationType269 = new NotificationType("ORCA_THREAD_READ", 268);
        A4P = notificationType269;
        NotificationType notificationType270 = new NotificationType("P2P_PAYMENT", 269);
        A4Q = notificationType270;
        NotificationType notificationType271 = new NotificationType("PAGE_ADMIN_INCOMING_CALL", 270);
        A4S = notificationType271;
        NotificationType notificationType272 = new NotificationType("PAGE_FEED_COMMENT", 271);
        A4T = notificationType272;
        NotificationType notificationType273 = new NotificationType("PAGE_HIGHLIGHTS", 272);
        A4U = notificationType273;
        NotificationType notificationType274 = new NotificationType("PAGES_INSTAGRAM_DIRECT_MESSAGE_ADMIN_ASSIGNMENT", 273);
        A4R = notificationType274;
        NotificationType notificationType275 = new NotificationType("PAGE_INSTAGRAM_DIRECT_MESSAGE", 274);
        A4V = notificationType275;
        NotificationType notificationType276 = new NotificationType("PAGE_MESSAGE", 275);
        A4W = notificationType276;
        NotificationType notificationType277 = new NotificationType("PAGE_MESSAGE_ADMIN_ASSIGNMENT", 276);
        A4X = notificationType277;
        NotificationType notificationType278 = new NotificationType("PAGE_MESSAGE_REMINDER", 277);
        A4Z = notificationType278;
        NotificationType notificationType279 = new NotificationType("PAGE_MESSAGE_AGGREGATED_REMINDER", 278);
        A4Y = notificationType279;
        NotificationType notificationType280 = new NotificationType("PAGE_MISSED_CALL", 279);
        A4a = notificationType280;
        NotificationType notificationType281 = new NotificationType("PAGE_USER_ACTIVITY", 280);
        A4b = notificationType281;
        NotificationType notificationType282 = new NotificationType("PAGE_WALL", 281);
        A4c = notificationType282;
        NotificationType notificationType283 = new NotificationType("PAGE_WHATS_APP_MESSAGE", 282);
        A4d = notificationType283;
        NotificationType notificationType284 = new NotificationType("PAYMENTS_BANNER", 283);
        A4e = notificationType284;
        NotificationType notificationType285 = new NotificationType("PERSONALIZED_REELS", 284);
        A4f = notificationType285;
        NotificationType notificationType286 = new NotificationType("PHOTO_COMMENT", 285);
        A4h = notificationType286;
        NotificationType notificationType287 = new NotificationType("PHOTO_ALBUM_COMMENT", 286);
        A4g = notificationType287;
        NotificationType notificationType288 = new NotificationType("PLACE_FEED_NEARBY", 287);
        A4i = notificationType288;
        NotificationType notificationType289 = new NotificationType("PLAN_USER_INVITED", 288);
        A4j = notificationType289;
        NotificationType notificationType290 = new NotificationType("PLATFORM_LOGIN_APPROVAL", 289);
        A4k = notificationType290;
        NotificationType notificationType291 = new NotificationType("POST_FAILED", 290);
        A4l = notificationType291;
        NotificationType notificationType292 = new NotificationType("PRE_REG_PUSH", 291);
        A4m = notificationType292;
        NotificationType notificationType293 = new NotificationType("PROFILE_PLUS_MESSAGE", 292);
        A4n = notificationType293;
        NotificationType notificationType294 = new NotificationType("PUBLIC_CHANNELS_NEW_CHANNEL_NOTIF", 293);
        A4o = notificationType294;
        NotificationType notificationType295 = new NotificationType("PUSH_REACHABILITY_CHECK", 294);
        A4q = notificationType295;
        NotificationType notificationType296 = new NotificationType("PUSH_TO_SESSION_MESSENGER_LOGIN", 295);
        A4r = notificationType296;
        NotificationType notificationType297 = new NotificationType("PYMK_EMAIL", 296);
        A4s = notificationType297;
        NotificationType notificationType298 = new NotificationType("REQUEST_LOCATION_UPDATE", 297);
        A4t = notificationType298;
        NotificationType notificationType299 = new NotificationType("MESSENGER_ROOMS_GENERIC", 298);
        A3c = notificationType299;
        NotificationType notificationType300 = new NotificationType("RETRACT_INVALID", 299);
        A4u = notificationType300;
        NotificationType notificationType301 = new NotificationType("RISING_FAN_NOTIF", 300);
        A4v = notificationType301;
        NotificationType notificationType302 = new NotificationType("RTC_VCWA_ATTEMPTED_JOIN", 301);
        A4w = notificationType302;
        NotificationType notificationType303 = new NotificationType("RTC_VCWA_CREATOR_JOINED", 302);
        A4x = notificationType303;
        NotificationType notificationType304 = new NotificationType("SECURE_MESSAGE_OVER_WA", 303);
        A4y = notificationType304;
        NotificationType notificationType305 = new NotificationType("SESSION_LEVEL_SURVEY", 304);
        A4z = notificationType305;
        NotificationType notificationType306 = new NotificationType("SHOWS_FOLLOWER_NEW_EPISODE", 305);
        A50 = notificationType306;
        NotificationType notificationType307 = new NotificationType("STALE_CONTACT_IMPORT", 306);
        A52 = notificationType307;
        NotificationType notificationType308 = new NotificationType("STALE_EMAIL", 307);
        A53 = notificationType308;
        NotificationType notificationType309 = new NotificationType("STALE_FRIEND_CONFIRM", 308);
        A54 = notificationType309;
        NotificationType notificationType310 = new NotificationType("STALE_NOTIFICATIONS", 309);
        A55 = notificationType310;
        NotificationType notificationType311 = new NotificationType("STORY_RESHARE", 310);
        A56 = notificationType311;
        NotificationType notificationType312 = new NotificationType("TINCAN_MESSAGE_RECEIVED", 311);
        A57 = notificationType312;
        NotificationType notificationType313 = new NotificationType("TOP_TRENDING_VIDEO", 312);
        A58 = notificationType313;
        NotificationType notificationType314 = new NotificationType("TOR_STATUS", 313);
        A59 = notificationType314;
        NotificationType notificationType315 = new NotificationType(OffsiteInitAvailabilityRequestKt.DEFAULT_PARTNER_ID, 314);
        A5A = notificationType315;
        NotificationType notificationType316 = new NotificationType("VIDEO_COMMENT", 315);
        A5B = notificationType316;
        NotificationType notificationType317 = new NotificationType("VOIP", 316);
        A5C = notificationType317;
        NotificationType notificationType318 = new NotificationType("WAKEUP_MQTT", 317);
        A5D = notificationType318;
        NotificationType notificationType319 = new NotificationType("WALL", 318);
        A5E = notificationType319;
        NotificationType notificationType320 = new NotificationType("WEATHER_NOWCAST", 319);
        A5H = notificationType320;
        NotificationType notificationType321 = new NotificationType("WEBRTC_VOIP_CALL", 320);
        A5I = notificationType321;
        NotificationType notificationType322 = new NotificationType("WORK_STALE", 321);
        A5J = notificationType322;
        NotificationType notificationType323 = new NotificationType("YOUTH_RS_MESSENGER_TEEN_MESSAGING_DATA_REQUEST_TEEN_NOTIFICATION", 322);
        A5S = notificationType323;
        NotificationType notificationType324 = new NotificationType("YOUTH_RS_MESSENGER_APPEAL_SUCCESS_OLD_PARENT_NOTIFICATION", 323);
        A5K = notificationType324;
        NotificationType notificationType325 = new NotificationType("YOUTH_RS_MESSENGER_APPEAL_SUCCESS_TEEN_NOTIFICATION", 324);
        A5L = notificationType325;
        NotificationType notificationType326 = new NotificationType("YOUTH_RS_MESSENGER_GS_INVITE_ACCEPT_NOTIFICATION", 325);
        A5M = notificationType326;
        NotificationType notificationType327 = new NotificationType("YOUTH_RS_MESSENGER_GS_INVITE_CREATE_NOTIFICATION", 326);
        A5N = notificationType327;
        NotificationType notificationType328 = new NotificationType("YOUTH_RS_MESSENGER_GS_INVITE_DECLINE_NOTIFICATION", 327);
        A5O = notificationType328;
        NotificationType notificationType329 = new NotificationType("YOUTH_RS_MESSENGER_GS_OPT_OUT_NOTIFICATION", 328);
        A5P = notificationType329;
        NotificationType notificationType330 = new NotificationType("YOUTH_RS_MESSENGER_INVITE_CREATE_TEEN_NOTIFICATION", 329);
        A5Q = notificationType330;
        NotificationType notificationType331 = new NotificationType("YOUTH_RS_MESSENGER_OFFBOARDING_NOTIFICATION", 330);
        A5R = notificationType331;
        NotificationType notificationType332 = new NotificationType("YOUTH_RS_MESSENGER_TRANSITION_NOTIFICATION", 331);
        A5T = notificationType332;
        NotificationType notificationType333 = new NotificationType("ZB_NOTIF", 332);
        A5U = notificationType333;
        NotificationType notificationType334 = new NotificationType("ZERO", 333);
        A5V = notificationType334;
        NotificationType notificationType335 = new NotificationType("MUSIC_RELEASE_RECOMMENDATION", 334);
        A49 = notificationType335;
        NotificationType notificationType336 = new NotificationType("ZP", 335);
        A5W = notificationType336;
        NotificationType notificationType337 = new NotificationType("GROUP_COMMENT_MENTION", 336);
        A2F = notificationType337;
        NotificationType notificationType338 = new NotificationType("AYMT_LWI_ASYNC_CREATION_FAILURE", 337);
        A07 = notificationType338;
        NotificationType notificationType339 = new NotificationType("SILENT_MPW_TRUSTED_DEVICE_FB", 338);
        A51 = notificationType339;
        NotificationType notificationType340 = new NotificationType("MSGR_E2EE_MESSAGE_REMINDER", 339);
        A3r = notificationType340;
        NotificationType[] notificationTypeArr = new NotificationType[340];
        System.arraycopy(new NotificationType[]{notificationType, notificationType2, notificationType3, notificationType4, notificationType5, notificationType6, notificationType7, notificationType8, notificationType9, notificationType10, notificationType11, notificationType12, notificationType13, notificationType14, notificationType15, notificationType16, notificationType17, notificationType18, notificationType19, notificationType20, notificationType21, notificationType22, notificationType23, notificationType24, notificationType25, notificationType26, notificationType27}, 0, notificationTypeArr, 0, 27);
        System.arraycopy(new NotificationType[]{notificationType28, notificationType29, notificationType30, notificationType31, notificationType32, notificationType33, notificationType34, notificationType35, notificationType36, notificationType37, notificationType38, notificationType39, notificationType40, notificationType41, notificationType42, notificationType43, notificationType44, notificationType45, notificationType46, notificationType47, notificationType48, notificationType49, notificationType50, notificationType51, notificationType52, notificationType53, notificationType54}, 0, notificationTypeArr, 27, 27);
        System.arraycopy(new NotificationType[]{notificationType55, notificationType56, notificationType57, notificationType58, notificationType59, notificationType60, notificationType61, notificationType62, notificationType63, notificationType64, notificationType65, notificationType66, notificationType67, notificationType68, notificationType69, notificationType70, notificationType71, notificationType72, notificationType73, notificationType74, notificationType75, notificationType76, notificationType77, notificationType78, notificationType79, notificationType80, notificationType81}, 0, notificationTypeArr, 54, 27);
        System.arraycopy(new NotificationType[]{notificationType82, notificationType83, notificationType84, notificationType85, notificationType86, notificationType87, notificationType88, notificationType89, notificationType90, notificationType91, notificationType92, notificationType93, notificationType94, notificationType95, notificationType96, notificationType97, notificationType98, notificationType99, notificationType100, notificationType101, notificationType102, notificationType103, notificationType104, notificationType105, notificationType106, notificationType107, notificationType108}, 0, notificationTypeArr, 81, 27);
        System.arraycopy(new NotificationType[]{notificationType109, notificationType110, notificationType111, notificationType112, notificationType113, notificationType114, notificationType115, notificationType116, notificationType117, notificationType118, notificationType119, notificationType120, notificationType121, notificationType122, notificationType123, notificationType124, notificationType125, notificationType126, notificationType127, notificationType128, notificationType129, notificationType130, notificationType131, notificationType132, notificationType133, notificationType134, notificationType135}, 0, notificationTypeArr, 108, 27);
        System.arraycopy(new NotificationType[]{notificationType136, notificationType137, notificationType138, notificationType139, notificationType140, notificationType141, notificationType142, notificationType143, notificationType144, notificationType145, notificationType146, notificationType147, notificationType148, notificationType149, notificationType150, notificationType151, notificationType152, notificationType153, notificationType154, notificationType155, notificationType156, notificationType157, notificationType158, notificationType159, notificationType160, notificationType161, notificationType162}, 0, notificationTypeArr, ActionId.MQTT_CONNECTING, 27);
        System.arraycopy(new NotificationType[]{notificationType163, notificationType164, notificationType165, notificationType166, notificationType167, notificationType168, notificationType169, notificationType170, notificationType171, notificationType172, notificationType173, notificationType174, notificationType175, notificationType176, notificationType177, notificationType178, notificationType179, notificationType180, notificationType181, notificationType182, notificationType183, notificationType184, notificationType185, notificationType186, notificationType187, notificationType188, notificationType189}, 0, notificationTypeArr, ActionId.ASYNC_FAIL, 27);
        System.arraycopy(new NotificationType[]{notificationType190, notificationType191, notificationType192, notificationType193, notificationType194, notificationType195, notificationType196, notificationType197, notificationType198, notificationType199, notificationType200, notificationType201, notificationType202, notificationType203, notificationType204, notificationType205, notificationType206, notificationType207, notificationType208, notificationType209, notificationType210, notificationType211, notificationType212, notificationType213, notificationType214, notificationType215, notificationType216}, 0, notificationTypeArr, 189, 27);
        System.arraycopy(new NotificationType[]{notificationType217, notificationType218, notificationType219, notificationType220, notificationType221, notificationType222, notificationType223, notificationType224, notificationType225, notificationType226, notificationType227, notificationType228, notificationType229, notificationType230, notificationType231, notificationType232, notificationType233, notificationType234, notificationType235, notificationType236, notificationType237, notificationType238, notificationType239, notificationType240, notificationType241, notificationType242, notificationType243}, 0, notificationTypeArr, 216, 27);
        System.arraycopy(new NotificationType[]{notificationType244, notificationType245, notificationType246, notificationType247, notificationType248, notificationType249, notificationType250, notificationType251, notificationType252, notificationType253, notificationType254, notificationType255, notificationType256, notificationType257, notificationType258, notificationType259, notificationType260, notificationType261, notificationType262, notificationType263, notificationType264, notificationType265, notificationType266, notificationType267, notificationType268, notificationType269, notificationType270}, 0, notificationTypeArr, 243, 27);
        System.arraycopy(new NotificationType[]{notificationType271, notificationType272, notificationType273, notificationType274, notificationType275, notificationType276, notificationType277, notificationType278, notificationType279, notificationType280, notificationType281, notificationType282, notificationType283, notificationType284, notificationType285, notificationType286, notificationType287, notificationType288, notificationType289, notificationType290, notificationType291, notificationType292, notificationType293, notificationType294, notificationType295, notificationType296, notificationType297}, 0, notificationTypeArr, 270, 27);
        System.arraycopy(new NotificationType[]{notificationType298, notificationType299, notificationType300, notificationType301, notificationType302, notificationType303, notificationType304, notificationType305, notificationType306, notificationType307, notificationType308, notificationType309, notificationType310, notificationType311, notificationType312, notificationType313, notificationType314, notificationType315, notificationType316, notificationType317, notificationType318, notificationType319, notificationType320, notificationType321, notificationType322, notificationType323, notificationType324}, 0, notificationTypeArr, 297, 27);
        System.arraycopy(new NotificationType[]{notificationType325, notificationType326, notificationType327, notificationType328, notificationType329, notificationType330, notificationType331, notificationType332, notificationType333, notificationType334, notificationType335, notificationType336, notificationType337, notificationType338, notificationType339, notificationType340}, 0, notificationTypeArr, 324, 16);
        A02 = notificationTypeArr;
        A01 = C00t.A00(notificationTypeArr);
        A00 = ImmutableSet.A04(notificationType284, notificationType155, notificationType300, notificationType339);
        CREATOR = new 82M(98);
    }

    public NotificationType(String str, int i) {
    }

    public static NotificationType valueOf(String str) {
        return (NotificationType) Enum.valueOf(NotificationType.class, str);
    }

    public static NotificationType[] values() {
        return (NotificationType[]) A02.clone();
    }

    public final boolean A00(String str) {
        boolean z = false;
        if (str != null && str.length() != 0) {
            z = str.equalsIgnoreCase(toString());
        }
        return z;
    }

    @Override // android.os.Parcelable
    public int describeContents() {
        return 0;
    }

    @Override // android.os.Parcelable
    public void writeToParcel(Parcel parcel, int i) {
        11T.A0F(parcel, 0);
        parcel.writeInt(ordinal());
    }
}
