package X;

import com.facebookpay.offsite.models.message.OffsiteInitAvailabilityRequestKt;

/* renamed from: X.Mrn, reason: case insensitive filesystem */
/* loaded from: Mrn.class */
public abstract class AbstractC3835Mrn {
    public static final String[] A00;

    static {
        String[] strArr = new String[81];
        System.arraycopy(new String[]{"ADD_PREDICTION_MID_CARD", "ADD_TO_STORY", "ADD_TO_STORY_MID_CARD", "ADMINED_ADDITIONAL_PROFILE_STORY", "AGGREGATED_STORY", "ARCHIVED_STORY", "BIRTHDAY_GENERATED_STORY", "BIRTHDAY_STORY", "BIRTHDAY_WALLPOST_GENERATED_STORY", "BUCKET_FEEDBACK_STORY", "CHANNEL_BUCKET", "CHANNEL_GENERATED_STORY", "CHANNEL_STORY", "CHRONOLOGICALLY_AGGREGATED_STORY", "COVID_SUPPORT", "COVID_SUPPORT_GENERATED_STORY", "CREW_STORY", "DEPTH_PLAYGROUND_GENERATED_STORY", "DIRECT", "DIRECT_NUX", "DUMMY_SELF_BUCKET", "EVENT_STORY", "FEATURED_HIGHLIGHTS_STORY", "FRIEND_GROUP_STORY", "FX_FB_STORIES_CROSS_POSTING_AFTER_SELFVIEW_QP", "GEMSTONE_STORY", "GOODWILL_GENERATED_STORY"}, 0, strArr, 0, 27);
        System.arraycopy(new String[]{"GOODWILL_STORY", "GROUP_DIRECT", "GROUP_STORY", "HASHTAG_GENERATED_STORY", "HASHTAG_STORY", "HIGHLIGHTED_STORY", "IMBE_STORY", "LAST_CHANCE_STORY", "LIVE_STORY", "LOCKED_PROFILE_COMPREHENSION_MID_CARD", "LOL_DAILY_DROP_STORY", "MESSENGER_THREAD_STORY", "MULTI_AUTHOR_GENERATED_STORY", "MULTI_AUTHOR_STORY", "MUSIC_STORY_MID_CARD", "M_GROUP_STORY", "NATIVE_TEMPLATES_GENERATED_STORY", "NULL_HEADS", "NULL_STATE_STORY", "ONE_BY_ONE_MID_CARD", "OPTIMISTIC_STORY", "PAGE_GENERATED_STORY", "PAGE_INSIGHTS_STORY", "PAGE_STORY", "PREDICTION_STORY_RESULTS", "PROFILE_PLUS_STORY", "PROMOTION_GENERATED_STORY"}, 0, strArr, 27, 27);
        System.arraycopy(new String[]{"PROMOTION_STORY", "PYMK_GENERATED_STORY", "QUICK_PROMOTION_STORY_VIEWER_ONLY_STORY", "REPLY_STORY", "SCHOOL_COMMUNITY_STORY", "SC_INDIA_FRIENDING_CTA_STORY", "SELF_BIRTHDAY_STORY", "SHARED_ADMINED_ADDITIONAL_PROFILE_STORY", "SHARED_CHANNEL_STORY", "SHARED_PAGE_STORY", "SHARED_PROFILE_PLUS_STORY", "SHARED_REPLY_STORY", "SHARED_USER_STORY", "STICKER_AGGREGATED_GENERATED_STORY", "STICKER_AGGREGATED_STORY", "STORIES_END_CARD", "STORIES_IG_XPOSTING_MID_CARD", "STORIES_READER_MID_CARD_UPSELL", "STORIES_READER_POG_UPSELL", "STORY", "STORY_NUX", "STORY_VIEWER_ONLY_GENERATED_STORY", "SUGGESTED_AGGREGATED_STORY", "TOPIC_STORY", OffsiteInitAvailabilityRequestKt.DEFAULT_PARTNER_ID, "UNPUBLISHED_STORY", "WAS_LIVE"}, 0, strArr, 54, 27);
        A00 = strArr;
    }
}
