package X;

/* loaded from: Bz8.class */
public final class Bz8 {
    public final int A00;
    public final int A01;
    public final Boolean A02;
    public final Boolean A03;
    public final Double A04;
    public final Integer A05;
    public final Integer A06;
    public final Integer A07;
    public final Integer A08;
    public final Integer A09;
    public final Long A0A;
    public final Long A0B;
    public final Long A0C;
    public final Long A0D;
    public final Long A0E;
    public final Long A0F;
    public final Long A0G;
    public final Long A0H;
    public final Long A0I;
    public final String A0J;
    public final String A0K;
    public final String A0L;
    public final String A0M;
    public final String A0N;
    public final String A0O;
    public final String A0P;
    public final String A0Q;
    public final String A0R;
    public final String A0S;
    public final String A0T;
    public final String A0U;
    public final String A0V;
    public final String A0W;
    public final String A0X;
    public final String A0Y;
    public final String A0Z;
    public final String A0a;
    public final String A0b;
    public final String A0c;
    public final String A0d;
    public final String A0e;
    public final boolean A0f;

    public Bz8(Boolean bool, Boolean bool2, Double d, Integer num, Integer num2, Integer num3, Integer num4, Integer num5, Long l, Long l2, Long l3, Long l4, Long l5, Long l6, Long l7, Long l8, Long l9, String str, String str2, String str3, String str4, String str5, String str6, String str7, String str8, String str9, String str10, String str11, String str12, String str13, String str14, String str15, String str16, String str17, String str18, String str19, String str20, String str21, String str22, int i, int i2, boolean z) {
        this.A0c = str;
        this.A0A = l;
        this.A0d = str2;
        this.A0b = str3;
        this.A0X = str4;
        this.A0U = str5;
        this.A0T = str6;
        this.A0G = l2;
        this.A0W = str7;
        this.A0C = l3;
        this.A0D = l4;
        this.A0I = l5;
        this.A09 = num;
        this.A00 = i;
        this.A0a = str8;
        this.A04 = d;
        this.A0V = str9;
        this.A01 = i2;
        this.A0f = z;
        this.A0Z = str10;
        this.A0S = str11;
        this.A0F = l6;
        this.A0R = str12;
        this.A0E = l7;
        this.A02 = bool;
        this.A0Y = str13;
        this.A0J = str14;
        this.A0O = str15;
        this.A0Q = str16;
        this.A0P = str17;
        this.A0L = str18;
        this.A0M = str19;
        this.A0N = str20;
        this.A0B = l8;
        this.A0H = l9;
        this.A03 = bool2;
        this.A06 = num2;
        this.A0e = str21;
        this.A07 = num3;
        this.A05 = num4;
        this.A0K = str22;
        this.A08 = num5;
    }
}
