package X;

import com.facebook.messaging.cowatch.intent.model.CowatchShareModel;
import com.facebook.messaging.memories.share.MemoryShareMetadata;
import com.facebook.messaging.model.threadkey.ThreadKey;
import com.facebook.messaging.sharing.broadcastflow.model.BatchOperationState;
import com.facebook.messaging.sharing.broadcastflow.model.BroadcastFlowRealTimeFetchParam;
import com.facebook.messaging.sharing.broadcastflow.model.ContactShareModel;
import com.facebook.messaging.sharing.broadcastflow.model.LoadMoreState;
import com.facebook.messaging.sharing.broadcastflow.model.SendButtonStates;
import com.facebook.messaging.wellbeing.harmfulcontent.forward.ratelimit.common.data.ForwardRateLimitInfo;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableSet;

/* loaded from: Bz9.class */
public final class Bz9 {
    public int A00;
    public int A01;
    public CowatchShareModel A02;
    public MemoryShareMetadata A03;
    public ThreadKey A04;
    public ThreadKey A05;
    public ThreadKey A06;
    public ThreadKey A07;
    public DFr A09;
    public BroadcastFlowRealTimeFetchParam A0A;
    public C84 A0B;
    public ContactShareModel A0C;
    public LoadMoreState A0D;
    public Bn0 A0E;
    public CCK A0F;
    public BLQ A0H;
    public SendButtonStates A0I;
    public BMK A0J;
    public ForwardRateLimitInfo A0K;
    public ImmutableList A0L;
    public ImmutableList A0M;
    public ImmutableList A0N;
    public ImmutableList A0O;
    public ImmutableList A0P;
    public ImmutableMap A0Q;
    public ImmutableSet A0R;
    public Integer A0S;
    public String A0T;
    public String A0U;
    public String A0V;
    public String A0W;
    public String A0X;
    public String A0Y;
    public String A0Z;
    public String A0a;
    public String A0b;
    public String A0c;
    public String A0d;
    public String A0e;
    public boolean A0f;
    public boolean A0g;
    public boolean A0h;
    public boolean A0i;
    public boolean A0j;
    public boolean A0k;
    public boolean A0l;
    public boolean A0m;
    public boolean A0n;
    public boolean A0o;
    public boolean A0p;
    public boolean A0q;
    public boolean A0r;
    public boolean A0s;
    public boolean A0t;
    public boolean A0u;
    public boolean A0v;
    public BatchOperationState A08 = BatchOperationState.NONE;
    public CNc A0G = new CNc(new Byy());
}
