package X;

/* renamed from: X.0od, reason: invalid class name */
/* loaded from: 0od.class */
public abstract class C0od {
    public static String A00(int i) {
        return i != 6977 ? i != 7610 ? i != 10247 ? i != 11466 ? i != 11866 ? i != 14485 ? "UNDEFINED_QPL_EVENT" : "BUSINESS_INBOX_IN_MESSENGER_INBOX_LOAD_COMPLETE" : "BUSINESS_INBOX_IN_MESSENGER_NOTIFICATION_CLICK" : "BUSINESS_INBOX_IN_MESSENGER_ACCOUNT_SWITCH_START" : "BUSINESS_INBOX_IN_MESSENGER_THREAD_LOAD_COMPLETE" : "BUSINESS_INBOX_IN_MESSENGER_INBOX_LOAD_TTRC" : "BUSINESS_INBOX_IN_MESSENGER_ACCOUNT_SWITCH_LOGIN_START";
    }
}
