package X;

/* renamed from: X.0u1, reason: invalid class name */
/* loaded from: 0u1.class */
public abstract class C0u1 {
    public static String A00(int i) {
        return i != 1 ? i != 2 ? i != 3 ? i != 4 ? i != 7 ? i != 5967 ? i != 7659 ? i != 12634 ? "UNDEFINED_QPL_EVENT" : "IG_FEED_SHARING_PROFILE_AVATAR_CHANGE" : "IG_FEED_SHARING_PROFILE_SUGGESTED_USERS_IN_HIGHLIGHTS" : "IG_FEED_SHARING_PROFILE_HEADER_LOAD" : "IG_FEED_SHARING_PROFILE_HIGHLIGHTS_TRAY_LOAD" : "IG_FEED_SHARING_PROFILE_PROFILE_PAGE_LOAD_TTI" : "IG_FEED_SHARING_PROFILE_CAMERA_INIT" : "IG_FEED_SHARING_PROFILE_GALLERY_PREVIEW_TTI" : "IG_FEED_SHARING_PROFILE_GALLERY_LAUNCH";
    }
}
