package X;

/* renamed from: X.0uc, reason: invalid class name */
/* loaded from: 0uc.class */
public abstract class C0uc {
    public static String A00(int i) {
        return i != 1495 ? i != 1953 ? i != 2308 ? i != 5406 ? i != 7313 ? i != 8955 ? i != 13562 ? i != 13841 ? i != 14241 ? "UNDEFINED_QPL_EVENT" : "IG_SHOPS_QUESTIONS_AND_ANSWERS_LIKE_AN_ANSWER" : "IG_SHOPS_QUESTIONS_AND_ANSWERS_ASK_A_QUESTION" : "IG_SHOPS_QUESTIONS_AND_ANSWERS_ANSWER_A_QUESTION" : "IG_SHOPS_QUESTIONS_AND_ANSWERS_LAZY_LOAD_PDP_MODULE" : "IG_SHOPS_QUESTIONS_AND_ANSWERS_UNLIKE_A_QUESTION" : "IG_SHOPS_QUESTIONS_AND_ANSWERS_LIKE_A_QUESTION" : "IG_SHOPS_QUESTIONS_AND_ANSWERS_DELETE_A_QUESTION" : "IG_SHOPS_QUESTIONS_AND_ANSWERS_UNLIKE_AN_ANSWER" : "IG_SHOPS_QUESTIONS_AND_ANSWERS_ALL_QNA_PAGINATION";
    }
}
