package X;

/* renamed from: X.0y5, reason: invalid class name */
/* loaded from: 0y5.class */
public abstract class C0y5 {
    public static String A00(int i) {
        return i != 2039 ? i != 4094 ? i != 8262 ? i != 9108 ? i != 10687 ? i != 13376 ? "UNDEFINED_QPL_EVENT" : "MTV_MANAGED_MOBILE_ERRORS_LAUNCH_AS_FRAGMENT_UNEXPECTED_EVENT" : "MTV_MANAGED_MOBILE_ERRORS_RENDER_UNSUPPORTED_THREAD_TYPE" : "MTV_MANAGED_MOBILE_ERRORS_CONTACT_TYPE_EXACT_MISSING_MAPPING_EVENT" : "MTV_MANAGED_MOBILE_ERRORS_GENAI_TYPING_INDICATOR_ERROR" : "MTV_MANAGED_MOBILE_ERRORS_EARLY_EXIT" : "MTV_MANAGED_MOBILE_ERRORS_RENDER_DIFFERENT_THREAD_KEY_UNEXPECTED_EVENT";
    }
}
