package X;

/* renamed from: X.12h, reason: invalid class name */
/* loaded from: 12h.class */
public abstract class C12h {
    public static String A00(int i) {
        return i != 4003 ? i != 5221 ? i != 6473 ? i != 7559 ? i != 10246 ? i != 11662 ? i != 11940 ? i != 14212 ? "UNDEFINED_QPL_EVENT" : "WEARABLE_ACTIVITIES_LEADERBOARD_UPSERT" : "WEARABLE_ACTIVITIES_SEND_GOAL_REACHED_NOTIFICATION" : "WEARABLE_ACTIVITIES_LEADERBOARD_QUERY" : "WEARABLE_ACTIVITIES_VIEW_ACTIVITY_METRIC_DETAILS" : "WEARABLE_ACTIVITIES_LEADERBOARD_DELETE" : "WEARABLE_ACTIVITIES_APP_START" : "WEARABLE_ACTIVITIES_QUERY_ACTIVITY_METRICS_TODAY" : "WEARABLE_ACTIVITIES_SET_ACTIVITY_METRIC_GOAL";
    }
}
