package X;

/* renamed from: X.13y, reason: invalid class name */
/* loaded from: 13y.class */
public abstract class C13y {
    public static String A00(int i) {
        return i != 2635 ? i != 4732 ? i != 5917 ? i != 6738 ? i != 8091 ? i != 8495 ? i != 12998 ? "UNDEFINED_QPL_EVENT" : "WHATSAPP_MUSIC_WHATSAPP_MUSIC_RECEIVER_ALBUM_ARTWORK_DOWNLOAD" : "WHATSAPP_MUSIC_WHATSAPP_MUSIC_ACS_TOKEN_FETCH" : "WHATSAPP_MUSIC_WHATSAPP_OHAI_CALL" : "WHATSAPP_MUSIC_WHATSAPP_MUSIC_METADATA_INSERT_TO_DB" : "WHATSAPP_MUSIC_WHATSAPP_MUSIC_PRODUCER_CATALOG_API_CALL" : "WHATSAPP_MUSIC_WHATSAPP_MUSIC_PRODUCER_ALBUM_ARTWORK_DOWNLOAD" : "WHATSAPP_MUSIC_WHATSAPP_MUSIC_METADATA_READ_FROM_DB";
    }
}
