package X;

import com.facebook.acra.constants.ActionId;
import kotlin.enums.EnumEntries;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* renamed from: X.1fe, reason: invalid class name */
/* loaded from: 1fe.class */
public final class C1fe {
    public static final /* synthetic */ EnumEntries A00;
    public static final /* synthetic */ C1fe[] A01;
    public static final C1fe A02;
    public static final C1fe A03;
    public static final C1fe A04;
    public static final C1fe A05;
    public static final C1fe A06;
    public static final C1fe A07;
    public static final C1fe A08;
    public static final C1fe A09;
    public static final C1fe A0A;
    public static final C1fe A0B;
    public static final C1fe A0C;
    public static final C1fe A0D;
    public static final C1fe A0E;
    public static final C1fe A0F;
    public static final C1fe A0G;
    public static final C1fe A0H;
    public static final C1fe A0I;
    public static final C1fe A0J;
    public static final C1fe A0K;
    public static final C1fe A0L;
    public static final C1fe A0M;
    public static final C1fe A0N;
    public static final C1fe A0O;
    public static final C1fe A0P;
    public static final C1fe A0Q;
    public static final C1fe A0R;
    public static final C1fe A0S;
    public static final C1fe A0T;
    public static final C1fe A0U;
    public static final C1fe A0V;
    public static final C1fe A0W;
    public static final C1fe A0X;
    public static final C1fe A0Y;
    public static final C1fe A0Z;
    public static final C1fe A0a;
    public static final C1fe A0b;
    public static final C1fe A0c;
    public static final C1fe A0d;
    public static final C1fe A0e;
    public static final C1fe A0f;
    public static final C1fe A0g;
    public static final C1fe A0h;
    public static final C1fe A0i;
    public static final C1fe A0j;
    public static final C1fe A0k;
    public static final C1fe A0l;
    public static final C1fe A0m;
    public static final C1fe A0n;
    public static final C1fe A0o;
    public static final C1fe A0p;
    public static final C1fe A0q;
    public static final C1fe A0r;
    public static final C1fe A0s;
    public static final C1fe A0t;
    public static final C1fe A0u;
    public static final C1fe A0v;
    public static final C1fe A0w;
    public static final C1fe A0x;
    public static final C1fe A0y;
    public static final C1fe A0z;
    public static final C1fe A10;
    public static final C1fe A11;
    public static final C1fe A12;
    public static final C1fe A13;
    public static final C1fe A14;
    public static final C1fe A15;
    public static final C1fe A16;
    public static final C1fe A17;
    public static final C1fe A18;
    public static final C1fe A19;
    public static final C1fe A1A;
    public static final C1fe A1B;
    public static final C1fe A1C;
    public static final C1fe A1D;
    public static final C1fe A1E;
    public static final C1fe A1F;
    public static final C1fe A1G;
    public static final C1fe A1H;
    public static final C1fe A1I;
    public static final C1fe A1J;
    public static final C1fe A1K;
    public static final C1fe A1L;
    public static final C1fe A1M;
    public static final C1fe A1N;
    public static final C1fe A1O;
    public static final C1fe A1P;
    public static final C1fe A1Q;
    public static final C1fe A1R;
    public static final C1fe A1S;
    public static final C1fe A1T;
    public static final C1fe A1U;
    public static final C1fe A1V;
    public static final C1fe A1W;
    public static final C1fe A1X;
    public static final C1fe A1Y;
    public static final C1fe A1Z;
    public static final C1fe A1a;
    public static final C1fe A1b;
    public static final C1fe A1c;
    public static final C1fe A1d;
    public static final C1fe A1e;
    public static final C1fe A1f;
    public static final C1fe A1g;
    public static final C1fe A1h;
    public static final C1fe A1i;
    public static final C1fe A1j;
    public static final C1fe A1k;
    public static final C1fe A1l;
    public static final C1fe A1m;
    public static final C1fe A1n;
    public static final C1fe A1o;
    public static final C1fe A1p;
    public static final C1fe A1q;
    public static final C1fe A1r;
    public static final C1fe A1s;
    public static final C1fe A1t;
    public static final C1fe A1u;
    public static final C1fe A1v;
    public static final C1fe A1w;
    public static final C1fe A1x;
    public static final C1fe A1y;
    public static final C1fe A1z;
    public static final C1fe A20;
    public static final C1fe A21;
    public static final C1fe A22;
    public static final C1fe A23;
    public static final C1fe A24;
    public static final C1fe A25;
    public static final C1fe A26;
    public static final C1fe A27;
    public static final C1fe A28;
    public static final C1fe A29;
    public static final C1fe A2A;
    public static final C1fe A2B;
    public static final C1fe A2C;
    public static final C1fe A2D;
    public static final C1fe A2E;
    public static final C1fe A2F;
    public static final C1fe A2G;
    public static final C1fe A2H;
    public static final C1fe A2I;
    public static final C1fe A2J;
    public static final C1fe A2K;
    public static final C1fe A2L;
    public static final C1fe A2M;
    public static final C1fe A2N;
    public static final C1fe A2O;
    public static final C1fe A2P;
    public static final C1fe A2Q;
    public static final C1fe A2R;
    public static final C1fe A2S;
    public static final C1fe A2T;
    public static final C1fe A2U;
    public static final C1fe A2V;
    public static final C1fe A2W;
    public static final C1fe A2X;
    public static final C1fe A2Y;
    public static final C1fe A2Z;
    public static final C1fe A2a;
    public static final C1fe A2b;
    public static final C1fe A2c;
    public static final C1fe A2d;
    public static final C1fe A2e;
    public static final C1fe A2f;
    public static final C1fe A2g;
    public static final C1fe A2h;
    public final C1fh holdouttype;
    public final String oncall;
    public final boolean shouldholdout;
    public final String usecasename;

    static {
        C1fh c1fh = C1fh.A03;
        C1fe c1fe = new C1fe(c1fh, "FDID_SYNC", "FDID_SYNC", "pdp_signals_contactpoint_and_device", 0, false);
        A13 = c1fe;
        C1fe c1fe2 = new C1fe(c1fh, "FDID_DEBUG", "FDID_DEBUG", "pdp_signals_contactpoint_and_device", 1, false);
        A12 = c1fe2;
        C1fh c1fh2 = C1fh.A02;
        C1fe c1fe3 = new C1fe(c1fh2, "CCU", "CcuDefaultModule", "pdp_signals_mobile", 2, false);
        A08 = c1fe3;
        C1fe c1fe4 = new C1fe(c1fh, "FB4A_REGISTER_ACCOUNT_METHOD", "RegisterAccountMethod", "caa_acquisition", 3, true);
        A0t = c1fe4;
        C1fe c1fe5 = new C1fe(c1fh, "FB4A_ACCOUNT_COMMON_UTIL", "AccountCommonUtil", "caa_acquisition", 4, true);
        A0C = c1fe5;
        C1fe c1fe6 = new C1fe(c1fh, "FB4A_ACCOUNT_RECOVERY_SEND_CONFIRMATION_CODE_METHOD", Fhn.__redex_internal_original_name, "caa_growth_authentication", 5, true);
        A0D = c1fe6;
        C1fe c1fe7 = new C1fe(c1fh, "FB4A_ACCOUNT_RECOVERY_VALIDATE_CODE_METHOD", "AccountRecoveryValidateCodeMethod", "caa_growth_authentication", 6, true);
        A0E = c1fe7;
        C1fe c1fe8 = new C1fe(c1fh, "FB4A_PUSH_TOKEN_HOLDER", "PushTokenHolder", "unknown", 7, false);
        A0q = c1fe8;
        C1fe c1fe9 = new C1fe(c1fh, "FB4A_BLOCK_STORE_HELPER", "BlockStoreHelper", "mp_verticals", 8, false);
        A0S = c1fe9;
        C1fe c1fe10 = new C1fe(c1fh, "FB4A_DBL_CHECK_IF_USERS_ARE_ELIGIBLE_FOR_RES_METHOD", "DBLCheckIfUsersAreEligibleForResMethod", "caa_growth_authentication", 9, true);
        A0W = c1fe10;
        C1fe c1fe11 = new C1fe(c1fh, "FB4A_DEVICE_INFO_PERIODIC_REPORTER", "DeviceInfoPeriodicReporter", "pdp_signals_contactpoint_and_device", 10, false);
        A0Y = c1fe11;
        C1fe c1fe12 = new C1fe(c1fh, "FB4A_ALOHA_AUTHENTICATE_METHOD", Fhr.__redex_internal_original_name, "caa_growth_authentication", 11, true);
        A0G = c1fe12;
        C1fe c1fe13 = new C1fe(c1fh, "FB4A_AUTH_IDENTIFY_USER_METHOD", Cgc.__redex_internal_original_name, "caa_growth_authentication", 12, true);
        A0Q = c1fe13;
        C1fe c1fe14 = new C1fe(c1fh, "FB4A_AUTHENTICATE_BYPASS_LOGIN_URI_METHOD", "AuthenticateByPassLoginUriMethod", "caa_growth_authentication", 13, true);
        A0J = c1fe14;
        C1fe c1fe15 = new C1fe(c1fh, "FB4A_AUTHENTICATE_CREDENTIAL_CHECK_METHOD", Cgd.__redex_internal_original_name, "caa_growth_authentication", 14, true);
        A0K = c1fe15;
        C1fe c1fe16 = new C1fe(c1fh, "FB4A_AUTHENTICATE_DBL_METHOD", Fhu.__redex_internal_original_name, "caa_growth_authentication", 15, true);
        A0L = c1fe16;
        C1fe c1fe17 = new C1fe(c1fh, "FB4A_AUTHENTICATE_METHOD", Fhw.__redex_internal_original_name, "caa_growth_authentication", 16, true);
        A0M = c1fe17;
        C1fe c1fe18 = new C1fe(c1fh, "FB4A_AUTHENTICATE_NONCE_METHOD", Fhs.__redex_internal_original_name, "caa_growth_authentication", 17, true);
        A0N = c1fe18;
        C1fe c1fe19 = new C1fe(c1fh, "FB4A_AUTHENTICATE_OPEN_ID_METHOD", Fht.__redex_internal_original_name, "caa_growth_authentication", 18, true);
        A0O = c1fe19;
        C1fe c1fe20 = new C1fe(c1fh, "FB4A_AUTHENTICATE_SSO_METHOD", Fhv.__redex_internal_original_name, "caa_growth_authentication", 19, true);
        A0P = c1fe20;
        C1fe c1fe21 = new C1fe(c1fh, "FB4A_LOGIN_BYPASS_WITH_SOFTMATCHED_MESSENGER_ONLY_USER_METHOD", Cgu.__redex_internal_original_name, "caa_growth_authentication", 20, true);
        A0j = c1fe21;
        C1fe c1fe22 = new C1fe(c1fh, "M4A_DEVICE_SHARING_FILTER_METHOD", Cgf.__redex_internal_original_name, "caa_growth_identification", 21, true);
        A2Q = c1fe22;
        C1fe c1fe23 = new C1fe(c1fh, "ROOM_GUEST_USER_AUTHENTICATE_METHOD", Fhk.__redex_internal_original_name, "caa_growth_authentication", 22, true);
        A2g = c1fe23;
        C1fe c1fe24 = new C1fe(c1fh, "FB4A_CONF_CODE_INPUT_FRAGMENT", "ConfCodeInputFragment", "caa_acquisition", 23, true);
        A0U = c1fe24;
        C1fe c1fe25 = new C1fe(c1fh, "FB4A_DEVICE_UTIL", "DeviceUtil", "pdp_signals_addressbook_and_location", 24, false);
        A0Z = c1fe25;
        C1fe c1fe26 = new C1fe(c1fh, "FB4A_NDX", "NDX", "pdp_signals_contactpoint_and_device", 25, false);
        A0m = c1fe26;
        C1fe c1fe27 = new C1fe(c1fh, "FB4A_OBA_STATUS_HELPER", "ObaStatusHelper", "unknown", 26, false);
        A0n = c1fe27;
        C1fe c1fe28 = new C1fe(c1fh, "FB4A_DEFAULT_LOCATION_PERMISSION_STATE_REPOSITORY", "DefaultLocationPermissionStateRepository", "pdp_signals_addressbook_and_location", 27, false);
        A0X = c1fe28;
        C1fe c1fe29 = new C1fe(c1fh, "FB4A_FACEBOOK_LOCATION_SETTING_REPOSITORY", "FacebookLocationSettingsRepository", "pdp_signals_addressbook_and_location", 28, false);
        A0b = c1fe29;
        C1fe c1fe30 = new C1fe(c1fh, "FB4A_BUG_REPORT_UPLOAD_METHOD", "BugReportUploader", "datainfra_turbine_backend", 29, false);
        A0T = c1fe30;
        C1fe c1fe31 = new C1fe(c1fh, "M4A_ACCOUNT_LOGIN_CREDENTIALS_FRAGMENT", B2q.__redex_internal_original_name, "caa_acquisition", 30, true);
        A2L = c1fe31;
        C1fe c1fe32 = new C1fe(c1fh, "M4A_ACCOUNT_LOGIN_REC_BASE_FRAGMENT", B2y.__redex_internal_original_name, "caa_acquisition", 31, true);
        A2M = c1fe32;
        C1fe c1fe33 = new C1fe(c1fh, "M4A_ACCOUNT_LOGIN_SPLASH_FRAGMENT", B2c.__redex_internal_original_name, "caa_acquisition", 32, true);
        A2N = c1fe33;
        C1fe c1fe34 = new C1fe(c1fh, "M4A_MESSENGER_FAMILY_DEVICE_ID", "MessengerFamilyDeviceId", "messenger_dolphin_orca_infra", 33, false);
        A2V = c1fe34;
        C1fe c1fe35 = new C1fe(c1fh, "M4A_FX_CAL_DETAILS_X_POST_PROFILES_FRAGMENT", "FXCALDetailsXPostProfilesFragment", "fx_accounts_center_settings", 34, false);
        A2T = c1fe35;
        C1fe c1fe36 = new C1fe(c1fh, "M4A_FX_CAL_DETAILS_SETTINGS_FRAGMENT", E1T.__redex_internal_original_name, "fx_accounts_center_settings", 35, false);
        A2S = c1fe36;
        C1fe c1fe37 = new C1fe(c1fh, "FX_CAL_AUTH_UTILS", "FxCalAuthUtils", "fx_product_foundation_client", 36, false);
        A15 = c1fe37;
        C1fe c1fe38 = new C1fe(c1fh, "M4A_CHECK_CONFIRMATION_CODE_METHOD", Fhh.__redex_internal_original_name, "caa_growth_identification", 37, true);
        A2O = c1fe38;
        C1fe c1fe39 = new C1fe(c1fh, "M4A_MESSENGER_ONLY_REQUEST_METHOD", "MessengerOnlyRequestMethod", "caa_growth_identification", 38, true);
        A2X = c1fe39;
        C1fe c1fe40 = new C1fe(c1fh, "M4A_RESGISTER_MESSENGER_ONLY_USER_METHOD", Cgw.__redex_internal_original_name, "caa_growth_identification", 39, true);
        A2a = c1fe40;
        C1fe c1fe41 = new C1fe(c1fh, "M4A_MESSENGER_ACCOUNT_RECOVERY_ID_HOLDER", "MessengerAccountRecoveryIdHolder", "caa_growth_identification", 40, true);
        A2U = c1fe41;
        C1fe c1fe42 = new C1fe(c1fh, "FB4A_PRIVACY_FLOW_TRIGGER_CLIENT_DATA", "PrivacyFlowTriggerClientData", "unknown", 41, false);
        A0p = c1fe42;
        C1fe c1fe43 = new C1fe(c1fh, "FB4A_LOCATION_MUTATION_MODEL_CREATOR", "LocationMutationModelCreator", "pdp_signals_addressbook_and_location", 42, false);
        A0i = c1fe43;
        C1fe c1fe44 = new C1fe(c1fh, "M4A_NEUE_NUX_CONTACT_IMPORT_FRAGMENT", "NeueNuxContactImportFragment", "caa_growth_identification", 43, true);
        A2Z = c1fe44;
        C1fe c1fe45 = new C1fe(c1fh, "M4A_TINCAN_NOTIFICATIONS_SYNC_LOGGER", "TincanNotificationsSyncLogger", "messaging_client_e2ee", 44, false);
        A2b = c1fe45;
        C1fe c1fe46 = new C1fe(c1fh, "M4A_MSYS_ACCOUNTs_HELPER", "MsysAccountsHelper", "messenger_dolphin_orca_infra", 45, false);
        A2Y = c1fe46;
        C1fe c1fe47 = new C1fe(c1fh, "M4A_MESSENGER_MSYS_MQTT_APP_SPECIFICI_INFO_PROVIDER", "MessengerMsysMqttAppSpecificInfoProvider", "messenger_dolphin_orca_infra", 46, false);
        A2W = c1fe47;
        C1fe c1fe48 = new C1fe(c1fh, "FB4A_ON_DEVICE_APP_HISTORY_MANAGER", "OnDeviceAppHistoryManager", "app_aem_and_platform_api", 47, false);
        A0o = c1fe48;
        C1fe c1fe49 = new C1fe(c1fh, "FB4A_SEARCH_RESULTS_GRAPHQL_QUERY_CREATOR", "SearchResultsGraphQLQueryCreator", "search_product", 48, true);
        A0v = c1fe49;
        C1fe c1fe50 = new C1fe(c1fh, "FB4A_FACEBOOK_ATTRIBUTION_DEVICE_PROPERTIES", "FacebookAttributionDeviceProperties", "paid_ads_platform_tlv", 49, false);
        A0a = c1fe50;
        C1fe c1fe51 = new C1fe(c1fh, "FB4A_MOBILE_CONFIG_MANAGER_UTIL", "MobileConfigManagerUtil", "mobileconfig", 50, false);
        A0k = c1fe51;
        C1fe c1fe52 = new C1fe(c1fh, "M4A_FBMSYS_MAIL_BOX_INFRA_CONFIG", "FbMsysMailBoxInfraConfig", "pc_foundation_android", 51, false);
        A2R = c1fe52;
        C1fe c1fe53 = new C1fe(c1fh, "FB4A_FB_PAYMENT_METHODS_API", "FbPaymentMethodsApi", "fbpay_foundation", 52, true);
        A0f = c1fe53;
        C1fe c1fe54 = new C1fe(c1fh, "FB4A_RMS_SUGGESTION_FETCHER", "RmsSuggestionFetcher", "creation_inspiration_android_oncall", 53, true);
        A0u = c1fe54;
        C1fe c1fe55 = new C1fe(c1fh, "FB4A_CREATE_META_DATA_MUTATION_HELPER", "CreateMetaDataMutationHelper", "inspiration_sharing_inventory", 54, false);
        A0V = c1fe55;
        C1fe c1fe56 = new C1fe(c1fh, "FB4A_FB_DEVICE_INFO", "FbDeviceInfo", "mft_checkout_products_client", 55, false);
        A0d = c1fe56;
        C1fe c1fe57 = new C1fe(c1fh, "FX_SSO_BUSINESS_OR_SHARED_ACCOUNTS_NUX_FRAGMENT", "FXSsoBusinessOrSharedAccountsNuxFragment", "fx-linking-access", 56, false);
        A18 = c1fe57;
        C1fe c1fe58 = new C1fe(c1fh, "FX_BLOKS_AUTH_UTILS", Fcj.__redex_internal_original_name, "fx_android_access", 57, true);
        A14 = c1fe58;
        C1fe c1fe59 = new C1fe(c1fh, "FB4A_MQTT_BYPASS_CLIENT_PROVIDER", "MqttBypassClientProvider", "mqtt", 58, false);
        A0l = c1fe59;
        C1fe c1fe60 = new C1fe(c1fh, "FX_FB_MASTER_ACCOUNT_NETWORK_MANAGER", "FxFBMasterAccountNetworkManager", "fx_product_foundation_client", 59, false);
        A16 = c1fe60;
        C1fe c1fe61 = new C1fe(c1fh, "FX_FB_SERVICE_CACHE_GRAPHQL_HELPER", "FxFBServiceCacheGraphQLHelper", "fx_product_foundation_client", 60, false);
        A17 = c1fe61;
        C1fe c1fe62 = new C1fe(c1fh, "FB4A_TRUSTED_DEVICE_PUSH_HANDLER", "TrustedDevicePushHandler", "offsite_and_offline_payments_client", 61, false);
        A0x = c1fe62;
        C1fe c1fe63 = new C1fe(c1fh, "FB4A_TRY_IT_SURFACE_REPOSITORY", "TryItRepository", "inspiration_sharing_surface", 62, false);
        A0z = c1fe63;
        C1fe c1fe64 = new C1fe(c1fh, "FB4A_ADVANCED_PRO_MAX", "AdvancedProMax", "inspiration_sharing_foundation_fb4a", 63, false);
        A0F = c1fe64;
        C1fe c1fe65 = new C1fe(c1fh, "FB4A_AUTOFILL_KEY_MIGRATION_JOB", "FbAutofillKeyMigrationJob", "wallet_engagement", 64, true);
        A0R = c1fe65;
        C1fe c1fe66 = new C1fe(c1fh, "M4A_COMPANY_IDENTITY_SWITCHER_LOGGER", "CompanyIdentitySwitcherLogger", "fx_accounts_center_settings", 65, false);
        A2P = c1fe66;
        C1fe c1fe67 = new C1fe(c1fh, "FB4A_SERACH_NULL_STATE_FETCH_HELPER", "SearchNullStateFetchHelper", "search_product", 66, true);
        A0w = c1fe67;
        C1fe c1fe68 = new C1fe(c1fh, "FB4A_APP_FOREGROUND_MUTATION", "AppForegroundMutation", "pdp_signals_contactpoint_and_device", 67, false);
        A0I = c1fe68;
        C1fe c1fe69 = new C1fe(c1fh, "FB4A_FB_MSYS_MQTT_APP_SEPCIFIC_INFO_PROVIDER", "FBMsysMqttAppSpecificInfoProvider", "pc_foundation_android", 68, false);
        A0e = c1fe69;
        C1fe c1fe70 = new C1fe(c1fh, "FB4A_ULS_INTERFACE_STATE_LOCALE_API", "ULSInterfaceStateLocaleAPI", "gxp_content", 69, true);
        A10 = c1fe70;
        C1fe c1fe71 = new C1fe(c1fh, "FB4A_FAMILY_DEVICE_ID_INTERCEPTOR", "FamilyDeviceIdInterceptor", "mobile_networking_services", 70, false);
        A0c = c1fe71;
        C1fe c1fe72 = new C1fe(c1fh, "COMPANY_IDENTITY_SWITCHER_HELPER", "CompanyIdentitySwitcherHelper", "fx_identity", 71, false);
        A0A = c1fe72;
        C1fe c1fe73 = new C1fe(c1fh, "FB4A_ANALYTICS2_LOGGER_MODULE", "Analytics2LoggerModule", "falco", 72, false);
        A0H = c1fe73;
        C1fe c1fe74 = new C1fe(c1fh, "FB4A_QP_IXT_TRIGGER_MQTT_HANDLER", "QPIXTTriggerMqttHandler", "quick_promotion", 73, false);
        A0s = c1fe74;
        C1fe c1fe75 = new C1fe(c1fh, "FB4A_INTERSTITIAL_UTILS", "InterstitialUtils", "quick_promotion", 74, false);
        A0h = c1fe75;
        C1fe c1fe76 = new C1fe(c1fh, "FB4A_FETCHER", "Fetcher", "quick_promotion", 75, false);
        A0g = c1fe76;
        C1fe c1fe77 = new C1fe(c1fh, "FB4A_QPIXT_BROADCASTER", "QPIXTBroadcaster", "quick_promotion", 76, false);
        A0r = c1fe77;
        C1fe c1fe78 = new C1fe(c1fh, "REACT_FAMILY_DEVICE_ID", "ReactFamilyDeviceID", "react_native", 77, false);
        A2f = c1fe78;
        C1fe c1fe79 = new C1fe(c1fh, "FB4A_A2_STREAM_LOGGER_MODULE_FB4A", "A2StreamingLoggerModuleFb4a", "falco", 78, false);
        A0B = c1fe79;
        C1fe c1fe80 = new C1fe(c1fh, "IG4A_LOGGING_UTILS", "LoggingUtils", "ig_android_growth", 79, false);
        A1r = c1fe80;
        C1fe c1fe81 = new C1fe(c1fh, "IG4A_LOGIN_WATERFALL", "LoginWaterfall", "ig_android_growth", 80, false);
        A1v = c1fe81;
        C1fe c1fe82 = new C1fe(c1fh, "IG4A_PROFILE_WIZARD_WATERFALL", "ProfileWizardWaterfall", "igx_search_client", 81, true);
        A29 = c1fe82;
        C1fe c1fe83 = new C1fe(c1fh, "IG4A_DEVICE_INFORMATION_HELPER", "DeviceInformationHelper", "ig_android_dev_craft", 82, false);
        A1Y = c1fe83;
        C1fe c1fe84 = new C1fe(c1fh, "IG4A_FOREGROUND_LOCATION", "ForegroundLocation", "ig_maps_and_locations", 83, false);
        A1d = c1fe84;
        C1fe c1fe85 = new C1fe(c1fh, "IG4A_LOCATION_PLACE_SIGNATURE", "LocationPlaceSignature", "ig_maps_and_locations", 84, false);
        A1q = c1fe85;
        C1fe c1fe86 = new C1fe(c1fh, "IG4A_GDPR_API", "GDPRApi", "instagram_growth_common_services", 85, false);
        A1e = c1fe86;
        C1fe c1fe87 = new C1fe(c1fh, "IG4A_USER_LIST_API", "UserListApi", "ig_android_growth", 86, true);
        A2I = c1fe87;
        C1fe c1fe88 = new C1fe(c1fh, "IG4A_LANDING_API", "LandingApi", "ig_android_growth", 87, true);
        A1o = c1fe88;
        C1fe c1fe89 = new C1fe(c1fh, "IG4A_NUX_COMPLETION_API", "NuxCompletionApi", "ig_android_growth", 88, true);
        A23 = c1fe89;
        C1fe c1fe90 = new C1fe(c1fh, "IG4A_ACCOUNT_SECURITY_API", "AccountSecurityApi", "ig_android_growth", 89, true);
        A1A = c1fe90;
        C1fe c1fe91 = new C1fe(c1fh, "IG4A_LOGIN_API", "LoginApi", "ig_android_growth", 90, true);
        A1s = c1fe91;
        C1fe c1fe92 = new C1fe(c1fh, "IG4A_USER_PROFILE_API", "UserProfileApi", "ig_profile_oncall", 91, true);
        A2J = c1fe92;
        C1fe c1fe93 = new C1fe(c1fh, "IG4A_RECOMMENDED_USER_API", "RecommendedUserApi", "ig_android_growth", 92, true);
        A2C = c1fe93;
        C1fe c1fe94 = new C1fe(c1fh, "IG4A_REEL_API_UTIL", "ReelApiUtil", "ig_stories_android", 93, true);
        A2D = c1fe94;
        C1fe c1fe95 = new C1fe(c1fh, "IG4A_AUTH_DATA_MODULE", "AuthDataModule", "igd_client_data", 94, false);
        A1G = c1fe95;
        C1fe c1fe96 = new C1fe(c1fh, "IG4A_LOGIN_CALLBACKS", "LoginCallbacks", "ig_android_growth", 95, true);
        A1t = c1fe96;
        C1fe c1fe97 = new C1fe(c1fh, "IG4A_PUSH_REGISTRATION_CALLABLE", "PushRegistrationCallable", "instagram_notifications", 96, false);
        A2B = c1fe97;
        C1fe c1fe98 = new C1fe(c1fh, "IG4A_CACHE_HELPER", "CacheHelper", "ig_android_growth", 97, true);
        A1N = c1fe98;
        C1fe c1fe99 = new C1fe(c1fh, "IG4A_MAA_LOGIN_HELPER", "MAALoginHelper", "ig_android_growth", 98, true);
        A1x = c1fe99;
        C1fe c1fe100 = new C1fe(c1fh, "IG4A_ADDITIONAL_CONTACt_UTIL", "AdditionalContactUtil", "ig_android_growth", 99, true);
        A1B = c1fe100;
        C1fe c1fe101 = new C1fe(c1fh, "IG4A_NDX_LAUNCHER", "NDXLauncher", "pdp_signals_contactpoint_and_device", 100, false);
        A22 = c1fe101;
        C1fe c1fe102 = new C1fe(c1fh, "IG4A_STARTUP_MANAGER", "StartupManager", "instagram_app_speed", ActionId.ON_VIEW_CREATED_END, false);
        A2H = c1fe102;
        C1fe c1fe103 = new C1fe(c1fh, "IG4A_PUBLIC_DEVELOPER_OPTIONS", "PublicDeveloperOptions", "ig_android_dev_craft", ActionId.DATA_LOAD_START, false);
        A2A = c1fe103;
        C1fe c1fe104 = new C1fe(c1fh, "IG4A_CONTACT_CONNECT_HELPER", "ContactConnectHelper", "ig_android_growth", ActionId.LEGACY_MARKER, true);
        A1S = c1fe104;
        C1fe c1fe105 = new C1fe(c1fh, "IG4A_COMPANY_IDENTITY_SWITCHER_HELPER", "CompanyIdentitySwitcherHelper", "fx_accounts_center_settings", ActionId.ACTION_BAR_COMPLETE, false);
        A1R = c1fe105;
        C1fe c1fe106 = new C1fe(c1fh, "IG4A_ENCRYPTED_BACKUPS_PIN_RESTORE_VIEW_MODEL", "EncryptedBackupsPinRestoreViewModel", "ig_message_history_experiences", ActionId.ABORTED, false);
        A1b = c1fe106;
        C1fe c1fe107 = new C1fe(c1fh, "IG4A_FACEBOOK_LANDING_FRAGMENT", "FacebookLandingFragment", "ig_android_growth", ActionId.QUERY_READY, true);
        A1c = c1fe107;
        C1fe c1fe108 = new C1fe(c1fh, "IG4A_IG_API_REQUEST", "IgApiRequest", "instagram_app_speed", ActionId.RTMP_PACKET_RECEIVED, false);
        A1i = c1fe108;
        C1fe c1fe109 = new C1fe(c1fh, "IG4A_IGW3C_AUTOFILL_API", "IGW3CAutofillApi", "offsite_and_offline_payments_client", 108, false);
        A1h = c1fe109;
        C1fe c1fe110 = new C1fe(c1fh, "IG4A_CONTACT_POINT_TRIAGE_FRAGMENT", "ContactPointTriageFragment", "ig_android_growth", ActionId.RTMP_CONNECTION_REQUESTED, true);
        A1U = c1fe110;
        C1fe c1fe111 = new C1fe(c1fh, "IG4A_IGFDID_OFFLINE_EXPERIMENT_UNIT_PROVIDER", "IGFdidOfflineExperimentUnitProvider", "pdp_signals_contactpoint_and_device", ActionId.RTMP_CONNECTION_RELEASE, false);
        A1g = c1fe111;
        C1fe c1fe112 = new C1fe(c1fh, "IG4A_ONE_PAGE_REGISTRATION_FRAGMENT", "OnePageRegistrationFragment", "ig_android_growth", ActionId.NEW_START_FOUND, true);
        A24 = c1fe112;
        C1fe c1fe113 = new C1fe(c1fh, "IG4A_ANALYTICS_CONFIGURATION_FACTORY", "AnalyticsConfigurationFactory", "instagram_app_speed", ActionId.MISSED_EVENT, false);
        A1E = c1fe113;
        C1fe c1fe114 = new C1fe(c1fh, "IG4A_ANALYTICS_CONFIGURATION_FACTORY_INIT", "AnalyticsConfigurationFactoryInit", "falco", ActionId.TIMEOUT, false);
        A1F = c1fe114;
        C1fe c1fe115 = new C1fe(c1fh, "IG4A_ON_DEVICE_APP_HISTORY_MANAGER", "OnDeviceAppHistoryManager", "on_device_tech", ActionId.CONTROLLER_INITIATED, false);
        A26 = c1fe115;
        C1fe c1fe116 = new C1fe(c1fh, "IG4A_BUSINESS_ACCOUNT_CREATION_UTIL", "BusinessAccountCreationUtil", "ig_smb_growth", ActionId.RTMP_STREAM_PREPARED, false);
        A1K = c1fe116;
        C1fe c1fe117 = new C1fe(c1fh, "IG4A_CHANGE_EMAIL_FRAGMENT", "ChangeEmailFragment", "igx_search_client", ActionId.VIDEO_PLAYING, true);
        A1P = c1fe117;
        C1fe c1fe118 = new C1fe(c1fh, "IG4A_DYNAMIC_ONBOARDING_API", "DynamicOnboardingApi", "ig_android_growth", ActionId.RTMP_CONNECTION_CONNECTED, true);
        A1Z = c1fe118;
        C1fe c1fe119 = new C1fe(c1fh, "IG4A_MAIN_FEED_QP_USE_CASE", "MainFeedQpUseCase", "ig_feed_product_android", ActionId.RTMP_CONNECTION_FAILED, true);
        A1y = c1fe119;
        C1fe c1fe120 = new C1fe(c1fh, "IG4A_LOGIN_INTERSTITIAL_QP_USE_CASE", "Ig4aLoginInterstitialQPUseCase", "quick_promotion", ActionId.RTMP_CONNECTION_INTERCEPTED, false);
        A1u = c1fe120;
        C1fe c1fe121 = new C1fe(c1fh, "IG4A_MOBILE_CONFIG_ROLLOUT_DIAG_FRAGMENT", "MobileConfigRolloutDiagFragment", "config_products", ActionId.VIDEO_SET_RENDERER_CONTEXT, false);
        A20 = c1fe121;
        C1fe c1fe122 = new C1fe(c1fh, "IG4A_GRAPHQL_DEBUG_FRAGMENT", "GraphqlDebugFragment", "ig_android_dev_craft", ActionId.HEADER_DATA_LOADED, false);
        A1f = c1fe122;
        C1fe c1fe123 = new C1fe(c1fh, "IG4A_DEVELOPER_FAMILY_DEVICE_ID_FRAGMENT", "DeveloperFamilyDeviceIdFragment", "ig_android_dev_craft", ActionId.CARD_DATA_LOADED, false);
        A1X = c1fe123;
        C1fe c1fe124 = new C1fe(c1fh, "IG4A_LAUNCHER_BADGES_MANAGER_IMPL", "LauncherBadgesManagerImpl", "instagram_notifications", ActionId.VIEW_WILL_APPEAR_BEGIN, false);
        A1p = c1fe124;
        C1fe c1fe125 = new C1fe(c1fh2, "IG4A_CHECKPOINT_MANAGER_IMPL", "CheckpointManagerImpl", "igwb_experiences", ActionId.VIEW_DID_LOAD_BEGIN, true);
        A1Q = c1fe125;
        C1fe c1fe126 = new C1fe(c1fh, "IG4A_AUTOFILL_TRUSTED_DEVICE_SILENT_PUSH_SIDE_EFFECT", "AutofillTrustedDeviceSilentPushSideEffect", "instagram_notifications_mobile", 125, false);
        A1H = c1fe126;
        C1fe c1fe127 = new C1fe(c1fh, "IG4A_IG_AUTOFILL_KEY_MIGRATION_JOB", "IgAutofillKeyMigrationJob", "offsite_and_offline_payments_client", ActionId.COMPONENTS_DATA_SOURCE_DID_END_UPDATES, false);
        A1j = c1fe127;
        C1fe c1fe128 = new C1fe(c1fh, "IG4A_REQUEST_ARBITRARY_API_USER_ACTION_HANDLER", "RequestArbitraryApiUserActionHandler", "quick_promotion", 127, false);
        A2E = c1fe128;
        C1fe c1fe129 = new C1fe(c1fh, "IG4A_AD_DEVICE_CREATION_LOGGER", "AdDeviceCreationLogger", "app_ads_supply", 128, false);
        A1C = c1fe129;
        C1fe c1fe130 = new C1fe(c1fh, "IG4A_CAA_REG_TRANSITION_SCREEN_ACTIVITY", "CaaRegTransitionScreenActivity", "caa_acquisition", ActionId.MESSENGER_QUEUE_CREATION, true);
        A1M = c1fe130;
        C1fe c1fe131 = new C1fe(c1fh, "IG4A_CONTACT_POINTS_UPLOADER", "ContactPointsUploader", "ig_android_growth", ActionId.APP_DID_FINISH_LAUNCHING, true);
        A1T = c1fe131;
        C1fe c1fe132 = new C1fe(c1fh, "IG4A_CCU_JOB_SCHEDULER", "CCUJobScheduler", "pdp_signals_addressbook_and_location", ActionId.APP_DID_BECOME_ACTIVE, false);
        A1O = c1fe132;
        C1fe c1fe133 = new C1fe(c1fh, "IG4A_CAA_ACCOUNT_RECOVERY_BLOKS_IG_NAV_HELPER", "CAAAccountRecoveryBloksIgNavHelper", "caa_growth_authentication", ActionId.APP_WILL_ENTER_FOREGROUND, true);
        A1L = c1fe133;
        C1fe c1fe134 = new C1fe(c1fh, "IG4A_AD_REQUEST_UTIL", "AdRequestUtil", "instagram_core_ads_android", ActionId.APP_DID_ENTER_BACKGROUND, false);
        A1D = c1fe134;
        C1fe c1fe135 = new C1fe(c1fh, "IG4A_IG_DEVICE_INFO", "IGDeviceInfo", "mft_checkout_products_client", ActionId.APP_MAIN, false);
        A1k = c1fe135;
        C1fe c1fe136 = new C1fe(c1fh, "IG4A_PREFILL_API", "PrefillApi", "ig_android_growth", ActionId.MQTT_CONNECTING, true);
        A28 = c1fe136;
        C1fe c1fe137 = new C1fe(c1fh, "IG4A_IG_PAYMENT_METHODS_API", "IGPaymentMethodsAPI", "mft_checkout_products_client", ActionId.MQTT_CONNECTED, true);
        A1l = c1fe137;
        C1fe c1fe138 = new C1fe(c1fh, "IG4A_PHONE_ID_PREFILL_HELPER", "PhoneIdPrefillHelper", "ig_android_growth", ActionId.MQTT_DISCONNECTED, true);
        A27 = c1fe138;
        C1fe c1fe139 = new C1fe(c1fh, "IG4A_LOGOUT_API", "LogoutApi", "ig_android_growth", ActionId.MESSENGER_DELTA_REQUEST, true);
        A1w = c1fe139;
        C1fe c1fe140 = new C1fe(c1fh, "IG4A_BADGE_API", "BadgeApi", "ig_android_growth", ActionId.APP_FIRST_VIEW_CONTROLLER, true);
        A1I = c1fe140;
        C1fe c1fe141 = new C1fe(c1fh, "IG4A_CONTINUOUS_CONTACT_UPLOAD_API", "ContinuousContactUploadApi", "pdp_signals_addressbook_and_location", ActionId.MESSENGER_THREAD_LIST_LOADED, false);
        A1V = c1fe141;
        C1fe c1fe142 = new C1fe(c1fh, "IG4A_ONE_TAP_LOGIN_API", "OneTapLoginApi", "ig_android_growth", ActionId.MESSENGER_THREAD_LIST_DISPLAYED, true);
        A25 = c1fe142;
        C1fe c1fe143 = new C1fe(c1fh, "IG4A_BK_BLOKS_FX_ACTION_GET_FAMILY_DEVICE_ID_IMPL", "BKBloksFxActionGetFamilyDeviceIdImpl", "fx_linking", ActionId.PREV_ACTIVITY_PAUSE, true);
        A1J = c1fe143;
        C1fe c1fe144 = new C1fe(c1fh, "IG4A_CREATE_ACCOUNT_API", "CreateAccountApi", "ig_android_growth", ActionId.ACTIVITY_RESUME, true);
        A1W = c1fe144;
        C1fe c1fe145 = new C1fe(c1fh, "IG4A_ENCRYPTED_BACKUPS_DEVICE_ID_UTIL", "EncryptedBackupsDeviceIdUtil", "ig_message_history_experiences", ActionId.ACTIVITY_START, false);
        A1a = c1fe145;
        C1fe c1fe146 = new C1fe(c1fh, "IG4A_SECONDARY_ACCOUNT_API", "SecondaryAccountApi", "ig_android_growth", ActionId.BEGIN_START_ACTIVITY, true);
        A2F = c1fe146;
        C1fe c1fe147 = new C1fe(c1fh, "IG4A_MOBILE_CONFIG_IG_UTILS", "MobileConfigIGUtils", "mobileconfig", ActionId.END_START_ACTIVITY, false);
        A1z = c1fe147;
        C1fe c1fe148 = new C1fe(c1fh, "IG4A_INSTAGRAM_DEVICE_IDS_LOGGER", "InstagramDeviceIdsLogger", "ig_android_growth", ActionId.FILE_SYSTEM_FAIL, true);
        A1m = c1fe148;
        C1fe c1fe149 = new C1fe(c1fh, "IG4A_SHARED_EMAIL_VERIFY_FRAGMENT", "SharedEmailVerifyFragment", "ig_profile_oncall", ActionId.FORMAT_ERROR, true);
        A2G = c1fe149;
        C1fe c1fe150 = new C1fe(c1fh, "IG4A_MQTT_BYPASS_CLIENT_PROVIDER", "MqttBypassClientProvider", "mqtt", ActionId.PRIVACY_VIOLATION, false);
        A21 = c1fe150;
        C1fe c1fe151 = new C1fe(c1fh, "IG4A_INSTALL_CAMPAIGN", "InstagramInstallCampaign", "ig_android_growth", 150, false);
        A1n = c1fe151;
        C1fe c1fe152 = new C1fe(c1fh, "B4A_INSTALL_CAMPAIGN", "BarcelonaInstallCampaign", "barcelona_android_oncall", ActionId.POPULATE_CONSISTENCY_MEMORY_CACHE, false);
        A02 = c1fe152;
        C1fe c1fe153 = new C1fe(c1fh, "MAA_LOGIN_CAMPAIGN", "MAALoginCampaign", "ig_android_growth", ActionId.APPLY_OPTIMISTICS, false);
        A2c = c1fe153;
        C1fe c1fe154 = new C1fe(c1fh, "BIZ_APP_MSYS_MAIL_BOX_CONFIG", "BizAppMsysMailBoxConfig", "mbs_inbox_android", ActionId.APPLY_FINISHED_LIST, false);
        A07 = c1fe154;
        C1fe c1fe155 = new C1fe(c1fh, "MOBILE_APP_MANAGEMENT_FALCO_LOGGER", "MobileAppManagementFalcoLogger", "facebook_at_work_android", ActionId.APPLY_FINISHED_LIST_AGAIN, false);
        A2d = c1fe155;
        C1fe c1fe156 = new C1fe(c1fh, "BIZ_APP_AUTH_ANALYTICS_LOGGER_PLUGIN", "BizAppAuthAnalyticsLoggerPlugin", "oncall+fbs_foundations_android@xmail.facebook.com", ActionId.FUTURE_LISTENERS_COMPLETE, false);
        A03 = c1fe156;
        C1fe c1fe157 = new C1fe(c1fh, "CLAIM_ACCOUNT_METHOD", "ClaimAccountMethod", "facebook_at_work_android", ActionId.SERVICE_ON_START_COMMAND, false);
        A09 = c1fe157;
        C1fe c1fe158 = new C1fe(c1fh, "FB_W3C_GRAPH_API", "FbW3CGraphApi", "offsite_and_offline_payments_client", ActionId.WAIT_FOR_BLOCKERS, false);
        A11 = c1fe158;
        C1fe c1fe159 = new C1fe(c1fh, "BIZ_APP_LOGIN_LOGGER", "BizAppLoginLogger", "fbs_foundations_android", ActionId.NOTIFY_SUBSCRIBERS, true);
        A06 = c1fe159;
        C1fe c1fe160 = new C1fe(c1fh, "PAGES_USER_AGENT", "UserAgent", "fbs_foundations_android", ActionId.FAIL_FILE_TOO_LARGE, false);
        A2e = c1fe160;
        C1fe c1fe161 = new C1fe(c1fh, "WORK_CHAT_MSYS_INFRA_CONFIG", "WorkChatMsysInfraConfig", "work_chat_android", ActionId.OFFLINE, false);
        A2h = c1fe161;
        C1fe c1fe162 = new C1fe(c1fh, "BIZ_APP_LOGIN_BASE_FRAGMENT", "BizAppLoginBaseFragment", "fbs_foundations_android", ActionId.ASNYC_FAILED, false);
        A05 = c1fe162;
        C1fe c1fe163 = new C1fe(c1fh, "BIZ_APP_CALL_CONTROLLER", "BizAppCallController", "messenger_business_rtc", ActionId.ASYNC_FAIL, false);
        A04 = c1fe163;
        C1fe c1fe164 = new C1fe(c1fh, "LOCATION_PERMISSION_LOGGING", "LocationPermissionLogging", "pdp_signals_mobile", ActionId.ON_ATTACH_FRAGMENT, false);
        A2K = c1fe164;
        C1fe c1fe165 = new C1fe(c1fh, "FB4A_TRUSTED_DEVICE_REGISTRATION_JOB", "TrustedDeviceRegistrationJob", "meta_pay_wallet", ActionId.VIEW_DID_APPEAR_BEGIN, false);
        A0y = c1fe165;
        C1fe c1fe166 = new C1fe(c1fh, "HEADERS_CONFIG_FETCH", "HeadersConfigFetch", "fos_ig", ActionId.DISPLAYED, false);
        A19 = c1fe166;
        C1fe c1fe167 = new C1fe(c1fh, "HEADERS_SIDE_EFFECTS", "HeadersSideEffects", "fos_ig", ActionId.DISPLAYED_ON_SCREEN, false);
        C1fe[] c1feArr = new C1fe[ActionId.ASYNC_ACTION_SUCCESS];
        System.arraycopy(new C1fe[]{c1fe, c1fe2, c1fe3, c1fe4, c1fe5, c1fe6, c1fe7, c1fe8, c1fe9, c1fe10, c1fe11, c1fe12, c1fe13, c1fe14, c1fe15, c1fe16, c1fe17, c1fe18, c1fe19, c1fe20, c1fe21, c1fe22, c1fe23, c1fe24, c1fe25, c1fe26, c1fe27}, 0, c1feArr, 0, 27);
        System.arraycopy(new C1fe[]{c1fe28, c1fe29, c1fe30, c1fe31, c1fe32, c1fe33, c1fe34, c1fe35, c1fe36, c1fe37, c1fe38, c1fe39, c1fe40, c1fe41, c1fe42, c1fe43, c1fe44, c1fe45, c1fe46, c1fe47, c1fe48, c1fe49, c1fe50, c1fe51, c1fe52, c1fe53, c1fe54}, 0, c1feArr, 27, 27);
        System.arraycopy(new C1fe[]{c1fe55, c1fe56, c1fe57, c1fe58, c1fe59, c1fe60, c1fe61, c1fe62, c1fe63, c1fe64, c1fe65, c1fe66, c1fe67, c1fe68, c1fe69, c1fe70, c1fe71, c1fe72, c1fe73, c1fe74, c1fe75, c1fe76, c1fe77, c1fe78, c1fe79, c1fe80, c1fe81}, 0, c1feArr, 54, 27);
        System.arraycopy(new C1fe[]{c1fe82, c1fe83, c1fe84, c1fe85, c1fe86, c1fe87, c1fe88, c1fe89, c1fe90, c1fe91, c1fe92, c1fe93, c1fe94, c1fe95, c1fe96, c1fe97, c1fe98, c1fe99, c1fe100, c1fe101, c1fe102, c1fe103, c1fe104, c1fe105, c1fe106, c1fe107, c1fe108}, 0, c1feArr, 81, 27);
        System.arraycopy(new C1fe[]{c1fe109, c1fe110, c1fe111, c1fe112, c1fe113, c1fe114, c1fe115, c1fe116, c1fe117, c1fe118, c1fe119, c1fe120, c1fe121, c1fe122, c1fe123, c1fe124, c1fe125, c1fe126, c1fe127, c1fe128, c1fe129, c1fe130, c1fe131, c1fe132, c1fe133, c1fe134, c1fe135}, 0, c1feArr, 108, 27);
        System.arraycopy(new C1fe[]{c1fe136, c1fe137, c1fe138, c1fe139, c1fe140, c1fe141, c1fe142, c1fe143, c1fe144, c1fe145, c1fe146, c1fe147, c1fe148, c1fe149, c1fe150, c1fe151, c1fe152, c1fe153, c1fe154, c1fe155, c1fe156, c1fe157, c1fe158, c1fe159, c1fe160, c1fe161, c1fe162}, 0, c1feArr, ActionId.MQTT_CONNECTING, 27);
        System.arraycopy(new C1fe[]{c1fe163, c1fe164, c1fe165, c1fe166, c1fe167}, 0, c1feArr, ActionId.ASYNC_FAIL, 5);
        A01 = c1feArr;
        A00 = C00t.A00(c1feArr);
    }

    public C1fe(C1fh c1fh, String str, String str2, String str3, int i, boolean z) {
        this.usecasename = str2;
        this.oncall = str3;
        this.shouldholdout = z;
        this.holdouttype = c1fh;
    }

    public static C1fe valueOf(String str) {
        return (C1fe) Enum.valueOf(C1fe.class, str);
    }

    public static C1fe[] values() {
        return (C1fe[]) A01.clone();
    }
}
