package X;

/* renamed from: X.1ic, reason: invalid class name */
/* loaded from: 1ic.class */
public final class C1ic {
    public static final String A00;
    public static final String A01;
    public static final String A02;
    public static final String A03;
    public static final String A04;
    public static final String A05;
    public static final String A06;
    public static final String A07;
    public static final String A08;
    public static final String A09;
    public static final String A0A;
    public static final String A0B;
    public static final String A0C;
    public static final String A0D;
    public static final String A0E;
    public static final String A0F;
    public static final String A0G;
    public static final String A0H;
    public static final String A0I;
    public static final String A0J;
    public static final String A0K;
    public static final String A0L;
    public static final String A0M;
    public static final String A0N;
    public static final String A0O;
    public static final String A0P;
    public static final String A0Q;
    public static final String A0R;
    public static final String A0S;
    public static final String A0T;
    public static final String A0U;
    public static final String A0V;
    public static final String A0W;
    public static final String A0X;
    public static final String A0Y;
    public static final String A0Z;
    public static final String A0a;
    public static final String A0b;
    public static final String A0c;
    public static final String A0d;
    public static final String A0e;
    public static final String A0f;
    public static final String A0g;
    public static final String A0h;
    public static final String A0i;
    public static final String A0j;
    public static final String A0k;
    public static final String A0l;
    public static final String A0m;
    public static final String A0n;
    public static final String A0o;
    public static final String A0p;
    public static final String A0q;
    public static final String A0r;
    public static final String A0s;
    public static final String A0t;
    public static final String A0u;
    public static final String A0v;
    public static final String A0w;
    public static final String A0x;
    public static final String A0y;
    public static final String A0z;
    public static final String A10;
    public static final String A11;
    public static final String A12;
    public static final String A13;
    public static final String A14;
    public static final String A15;
    public static final String A16;
    public static final String A17;
    public static final String A18;
    public static final String A19;

    static {
        String A0W2 = 0Pz.A0W("fb", "://");
        A18 = A0W2;
        String A0W3 = 0Pz.A0W(A0W2, "group/%s");
        A0K = A0W3;
        A0L = 0Pz.A0W(A0W3, "?group_view_referrer=%s");
        A0M = 0Pz.A0W(A0W3, "?content_view_type=%s");
        A0u = 0Pz.A0W(A0W2, "registration");
        A01 = 0Pz.A0W(A0W2, "account/recovery");
        A0B = 0Pz.A0W(A0W2, "event/%s");
        A09 = 0Pz.A0W(A0W2, "event/%s?hoist_wall_post_id=%s");
        A08 = 0Pz.A0W(A0W2, "events?hoist_event_ids=%s&hoist_story_id=%s");
        A0n = 0Pz.A0W(A0W2, "page/%s");
        A0Y = 0Pz.A0W(A0W2, "messaging");
        A0Z = 0Pz.A0W(A0W2, "messaging/");
        A0m = 0Pz.A0W(A0W2, "booking_request/create_appointment?booking_request_id=%s&customer_id=%s&default_start_time=%s&referrer=%s");
        0Pz.A0W(A0W2, "booking_request/create_appointment?customer_id=%s&default_start_time=%s&referrer=%s&customer_name=%s&interaction_id=%s");
        A0C = 0Pz.A0W(A0W2, "pages/%s/upsell_calendar_export?booking_request_id=%s&calendar_status=%s&ref=%s");
        A0l = 0Pz.A0W(A0W2, "page/appointment_detail?appointment_id=%s&referrer=%s&is_appointment_request=%s");
        A0a = 0Pz.A0W(A0W2, "native_album/%s");
        A0b = 0Pz.A0W(A0W2, "faceweb/f?href=/media/set/?set=ft.%s");
        A0c = 0Pz.A0W(A0W2, "native_post/%s?content_discovery_session_id=%s");
        A0d = 0Pz.A0W(A0W2, "native_post/%s?comment_id=%s&default_comment_ordering=toplevel&entry_point=TAP_FROM_EXTERNAL_URL_HANDLER");
        A10 = 0Pz.A0W(A0W2, "story/%s/%s");
        A0i = 0Pz.A0W(A0W2, "note/%s");
        A0r = 0Pz.A0W(A0W2, "profile/%s");
        A0q = 0Pz.A0W(A0W2, "profile/%s/friends/%s?source_ref=%s");
        A0o = 0Pz.A0W(A0W2, "photo/%s");
        A0A = 0Pz.A0W(A0W2, "event/%s?event_ref_mechanism=%s&event_ref_surface=%s");
        A07 = 0Pz.A0W(A0W2, "event_creation");
        A0F = 0Pz.A0W(A0W2, "feed");
        A0j = 0Pz.A0W(A0W2, "notifications");
        A0p = 0Pz.A0W(A0W2, "profile");
        A0E = 0Pz.A0W(A0W2, "faceweb/f?href=");
        A0D = 0Pz.A0W(A0W2, "faceweb/f?href=%s");
        A15 = 0Pz.A0W(A0W2, "www_link?url=%s");
        A0G = 0Pz.A0W(A0W2, "faceweb/f?href=%s&force_faceweb=true");
        A0H = 0Pz.A0W(A0W2, "friendlist/%s");
        A0N = 0Pz.A0W(A0W2, "hashtag/%s?name=%s&id=%s");
        A0O = 0Pz.A0W(A0W2, "faceweb/f?href=/help/android-app");
        A0v = 0Pz.A0W(A0W2, "payment_settings_rn");
        A17 = 0Pz.A0W(A0W2, "payments/close");
        11T.A0A(0Pz.A0W(A0W2, "fbpay_incentive_details?entity_id=%s&entry_point=%s&is_terms_open=%b"));
        A05 = 0Pz.A0W(A0W2, "device_location_optin");
        A00 = 0Pz.A0W(A0W2, "account_location_optin");
        A02 = 0Pz.A0W(A0W2, "appcenter/detail?app_id=%s");
        A0s = 0Pz.A0W(A0W2, "qp/%s");
        A0t = 0Pz.A0W(A0W2, "qp/%s?data=%s");
        A12 = 0Pz.A0W(A0W2, "video/?id={%s}");
        11T.A0A(0Pz.A0W(A0W2, "shared/?url=%s&iab_session_id=%s"));
        A0e = 0Pz.A0W(A0W2, "nt_screen/FB-SCREEN-FB");
        A0z = 0Pz.A0W(A0W2, "story_privacy?source={source}");
        A0y = 0Pz.A0W(A0W2, "snacks_sharesheet/");
        A0T = 0Pz.A0W(A0W2, "maps");
        A06 = 0Pz.A0W(A0W2, "dialtone_info_screen");
        A03 = 0Pz.A0W(A0W2, "autoflex_info_screen");
        A0I = 0Pz.A0W(A0W2, "donate/?fundraiser_campaign_id=%1$s&post_id=0");
        A16 = 0Pz.A0W(A0W2, "native_article?article={%s}&canonical={%s}");
        A0h = 0Pz.A0W(0Pz.A0W(A0W2, "neo/fallback"), "?target=profile");
        String A0W4 = 0Pz.A0W(A0W2, "neo_hub");
        A0g = 0Pz.A0W(0Pz.A0W(A0W2, "neo_profile"), "?fbid=%s&referrer=%s");
        A0f = 0Pz.A0W(A0W4, "?referrer=%s");
        A0k = 0Pz.A0W(A0W2, "sales_promo_details/?sales_promo_id=%s&referrer=%s&marketplace_client_session_id=%s");
        A11 = 0Pz.A0W(A0W2, "video_home/");
        String A0W5 = 0Pz.A0W(A0W2, "watch");
        A13 = A0W5;
        A14 = 0Pz.A0W(A0W5, "/discover");
        A0V = 0Pz.A0W(A0W2, "marketplace_product_details");
        A0W = 0Pz.A0W(A0W2, "marketplace_product_details?id=%s&referralCode=%s");
        A0U = 0Pz.A0W(A0W2, "marketplace_message/?threadID=%s&referralSurface=%s");
        A0X = 0Pz.A0W(A0W2, "marketplace_search?query=%s&referralSurface=%s");
        A0J = 0Pz.A0W(A0W2, "gaming");
        A0P = 0Pz.A0W(A0W2, "instantgames");
        A0Q = 0Pz.A0W(A0W2, "jobApplicationDetails?job_application_id=%s&source=%s&is_viewer_admin=%b");
        A0S = 0Pz.A0W(A0W2, "jobsPageManagerRoute?job_opening_id=%s&source=%s");
        A0R = 0Pz.A0W(A0W2, "jobsPageManagerRoute?job_opening_id=%s&source=%s&page_id=%s");
        A04 = 0Pz.A0W(A0W2, "cityguides?pageID=%s&pageName=%s&entryPoint=%s");
        A0x = 0Pz.A0W(A0W2, "fb_shorts/viewer?video_id=%s&source=%s");
        A0w = 0Pz.A0W(A0W2, "shorts_aggregation_profile?agg_id=%s&entry_point=%s&profile_type=%s");
        A19 = 0Pz.A0W(A0W2, "storycomposerforchannelshare?channel_name=%s&channel_desc=%s&member_count=%s&channel_image_uri=%s&thread_id=%s&target_user_id=%s&channel_sticker_style=%s&message_text=%s&message_author=%s&message_author_profile_pic_url=%s&message_id=%s&message_type=%s");
    }
}
