package X;

/* renamed from: X.1yg, reason: invalid class name */
/* loaded from: 1yg.class */
public enum C1yg {
    ONE_TO_ONE,
    GROUP,
    FOLDER,
    TINCAN,
    TINCAN_MULTI_ENDPOINT,
    PENDING_THREAD,
    PENDING_GENERAL_THREAD,
    SMS,
    OPTIMISTIC_GROUP_THREAD,
    MONTAGE,
    ENCRYPTED_ONE_TO_ONE_DISAPPEARING,
    CARRIER_MESSAGING_ONE_TO_ONE,
    CARRIER_MESSAGING_GROUP,
    ADVANCED_CRYPTO_ONE_TO_ONE,
    ADVANCED_CRYPTO_GROUP,
    OCCAMADILLO_ONE_TO_ONE,
    OCCAMADILLO_GROUP,
    COMMUNITY_CHANNEL,
    SOCIAL_CHANNEL,
    BROADCAST_CHANNEL,
    COMMUNITY_SUB_THREAD,
    AI_BOT,
    INTEROP_ONE_TO_ONE,
    MARKETPLACE
}
