package X;

import com.facebook.acra.constants.ActionId;
import com.facebookpay.offsite.models.message.OffsiteInitAvailabilityRequestKt;
import com.google.common.base.Objects;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* renamed from: X.5ap, reason: invalid class name */
/* loaded from: 5ap.class */
public final class C5ap {
    public static final /* synthetic */ C5ap[] A00;
    public static final C5ap A01;
    public static final C5ap A02;
    public static final C5ap A03;
    public static final C5ap A04;
    public static final C5ap A05;
    public static final C5ap A06;
    public static final C5ap A07;
    public static final C5ap A08;
    public static final C5ap A09;
    public static final C5ap A0A;
    public static final C5ap A0B;
    public static final C5ap A0C;
    public static final C5ap A0D;
    public static final C5ap A0E;
    public static final C5ap A0F;
    public static final C5ap A0G;
    public static final C5ap A0H;
    public static final C5ap A0I;
    public static final C5ap A0J;
    public static final C5ap A0K;
    public static final C5ap A0L;
    public static final C5ap A0M;
    public static final C5ap A0N;
    public static final C5ap A0O;
    public static final C5ap A0P;
    public static final C5ap A0Q;
    public static final C5ap A0R;
    public static final C5ap A0S;
    public static final C5ap A0T;
    public static final C5ap A0U;
    public static final C5ap A0V;
    public static final C5ap A0W;
    public static final C5ap A0X;
    public static final C5ap A0Y;
    public static final C5ap A0Z;
    public static final C5ap A0a;
    public static final C5ap A0b;
    public static final C5ap A0c;
    public static final C5ap A0d;
    public static final C5ap A0e;
    public static final C5ap A0f;
    public static final C5ap A0g;
    public static final C5ap A0h;
    public static final C5ap A0i;
    public static final C5ap A0j;
    public static final C5ap A0k;
    public static final C5ap A0l;
    public static final C5ap A0m;
    public static final C5ap A0n;
    public static final C5ap A0o;
    public static final C5ap A0p;
    public static final C5ap A0q;
    public static final C5ap A0r;
    public static final C5ap A0s;
    public static final C5ap A0t;
    public static final C5ap A0u;
    public static final C5ap A0v;
    public static final C5ap A0w;
    public static final C5ap A0x;
    public static final C5ap A0y;
    public static final C5ap A0z;
    public static final C5ap A10;
    public static final C5ap A11;
    public static final C5ap A12;
    public static final C5ap A13;
    public static final C5ap A14;
    public static final C5ap A15;
    public static final C5ap A16;
    public static final C5ap A17;
    public static final C5ap A18;
    public static final C5ap A19;
    public static final C5ap A1A;
    public static final C5ap A1B;
    public static final C5ap A1C;
    public static final C5ap A1D;
    public static final C5ap A1E;
    public static final C5ap A1F;
    public static final C5ap A1G;
    public static final C5ap A1H;
    public static final C5ap A1I;
    public static final C5ap A1J;
    public static final C5ap A1K;
    public static final C5ap A1L;
    public static final C5ap A1M;
    public static final C5ap A1N;
    public static final C5ap A1O;
    public static final C5ap A1P;
    public static final C5ap A1Q;
    public static final C5ap A1R;
    public static final C5ap A1S;
    public static final C5ap A1T;
    public static final C5ap A1U;
    public static final C5ap A1V;
    public static final C5ap A1W;
    public static final C5ap A1X;
    public static final C5ap A1Y;
    public static final C5ap A1Z;
    public static final C5ap A1a;
    public static final C5ap A1b;
    public static final C5ap A1c;
    public static final C5ap A1d;
    public static final C5ap A1e;
    public static final C5ap A1f;
    public static final C5ap A1g;
    public static final C5ap A1h;
    public static final C5ap A1i;
    public static final C5ap A1j;
    public static final C5ap A1k;
    public static final C5ap A1l;
    public static final C5ap A1m;
    public static final C5ap A1n;
    public static final C5ap A1o;
    public static final C5ap A1p;
    public static final C5ap A1q;
    public static final C5ap A1r;
    public static final C5ap A1s;
    public static final C5ap A1t;
    public static final C5ap A1u;
    public static final C5ap A1v;
    public static final C5ap A1w;
    public static final C5ap A1x;
    public static final C5ap A1y;
    public static final C5ap A1z;
    public static final C5ap A20;
    public static final C5ap A21;
    public static final C5ap A22;
    public static final C5ap A23;
    public static final C5ap A24;
    public static final C5ap A25;
    public static final C5ap A26;
    public static final C5ap A27;
    public static final C5ap A28;
    public static final C5ap A29;
    public static final C5ap A2A;
    public static final C5ap A2B;
    public static final C5ap A2C;
    public static final C5ap A2D;
    public static final C5ap A2E;
    public static final C5ap A2F;
    public static final C5ap A2G;
    public static final C5ap A2H;
    public static final C5ap A2I;
    public static final C5ap A2J;
    public static final C5ap A2K;
    public static final C5ap A2L;
    public static final C5ap A2M;
    public static final C5ap A2N;
    public static final C5ap A2O;
    public static final C5ap A2P;
    public static final C5ap A2Q;
    public static final C5ap A2R;
    public static final C5ap A2S;
    public static final C5ap A2T;
    public static final C5ap A2U;
    public static final C5ap A2V;
    public static final C5ap A2W;
    public static final C5ap A2X;
    public static final C5ap A2Y;
    public static final C5ap A2Z;
    public static final C5ap A2a;
    public static final C5ap A2b;
    public static final C5ap A2c;
    public static final C5ap A2d;
    public static final C5ap A2e;
    public static final C5ap A2f;
    public static final C5ap A2g;
    public static final C5ap A2h;
    public static final C5ap A2i;
    public static final C5ap A2j;
    public static final C5ap A2k;
    public static final C5ap A2l;
    public static final C5ap A2m;
    public static final C5ap A2n;
    public static final C5ap A2o;
    public static final C5ap A2p;
    public static final C5ap A2q;
    public static final C5ap A2r;
    public static final C5ap A2s;
    public static final C5ap A2t;
    public static final C5ap A2u;
    public final String stringValue;

    static {
        C5ap c5ap = new C5ap("NEW_MESSAGE", 0, "NEW_MESSAGE");
        A2R = c5ap;
        C5ap c5ap2 = new C5ap("BACKGROUND_ACCOUNT_MESSAGE", 1, "BACKGROUND_ACCOUNT_MESSAGE");
        A01 = c5ap2;
        C5ap c5ap3 = new C5ap("MESSENGER_JEWEL_UPDATE", 2, "MSGR_JEWEL_UPDATE");
        A1o = c5ap3;
        C5ap c5ap4 = new C5ap("MENTION", 3, "NEW_MESSAGE_MENTION");
        A13 = c5ap4;
        C5ap c5ap5 = new C5ap("LOGGED_OUT_MESSAGE", 4, "LOGGED_OUT_MESSAGE");
        A11 = c5ap5;
        C5ap c5ap6 = new C5ap("USER_LOGGED_OUT", 5, "USER_LOGGED_OUT");
        A2j = c5ap6;
        C5ap c5ap7 = new C5ap("FRIEND_INSTALL", 6, "FRIEND_INSTALL");
        A0w = c5ap7;
        C5ap c5ap8 = new C5ap("FAILED_TO_SEND", 7, "FAILED_TO_SEND");
        A07 = c5ap8;
        C5ap c5ap9 = new C5ap("P2P_PAYMENT", 8, "P2P_PAYMENT");
        A2T = c5ap9;
        C5ap c5ap10 = new C5ap("URI", 9, "URI");
        A2i = c5ap10;
        C5ap c5ap11 = new C5ap("STALE", 10, "STALE");
        A2c = c5ap11;
        C5ap c5ap12 = new C5ap("INTERNAL", 11, "INTERNAL");
        A0y = c5ap12;
        C5ap c5ap13 = new C5ap("MISSED_CALL", 12, "MISSED_CALL");
        A2C = c5ap13;
        C5ap c5ap14 = new C5ap("MESSAGE_REQUEST", 13, "MESSAGE_REQUEST");
        A16 = c5ap14;
        C5ap c5ap15 = new C5ap("PRE_REG_PUSH", 14, "PRE_REG_PUSH");
        A2Y = c5ap15;
        C5ap c5ap16 = new C5ap("MULTIPLE_ACCOUNTS_NEW_MESSAGES", 15, "MULTIPLE_ACCOUNTS_NEW_MESSAGES");
        A2Q = c5ap16;
        C5ap c5ap17 = new C5ap("MESSAGE_REACTION", 16, "MESSAGE_REACTION");
        A15 = c5ap17;
        C5ap c5ap18 = new C5ap("MESSAGE_NOTES", 17, "MESSAGE_NOTES");
        A14 = c5ap18;
        C5ap c5ap19 = new C5ap("BIC_CONSENT_REQUEST", 18, "BIC_CONSENT_REQUEST");
        A02 = c5ap19;
        C5ap c5ap20 = new C5ap("MESSENGER_MEMORIES", 19, "MESSENGER_MEMORIES");
        A1q = c5ap20;
        C5ap c5ap21 = new C5ap("JOIN_REQUEST", 20, "JOIN_REQUEST");
        A10 = c5ap21;
        C5ap c5ap22 = new C5ap("ROOM_REMINDER", 21, "ROOM_REMINDER");
        A2b = c5ap22;
        C5ap c5ap23 = new C5ap("SWITCH_TO_FB_ACCOUNT", 22, "SWITCH_TO_FB_ACCOUNT");
        A2d = c5ap23;
        C5ap c5ap24 = new C5ap("EVENT_REMINDER", 23, "EVENT_REMINDER");
        A06 = c5ap24;
        C5ap c5ap25 = new C5ap("FAILED_TO_SET_PROFILE_PICTURE", 24, "FAILED_TO_SET_PROFILE_PICTURE");
        A08 = c5ap25;
        C5ap c5ap26 = new C5ap("MESSENGER_LIVING_ROOM_CREATE", 25, "MESSENGER_LIVING_ROOM_CREATE");
        A1p = c5ap26;
        C5ap c5ap27 = new C5ap("MESSENGER_MONTAGE_FIRST_POST", 26, "MESSENGER_MONTAGE_FIRST_POST");
        A1u = c5ap27;
        C5ap c5ap28 = new C5ap("MESSENGER_MONTAGE_FIRST_MESSAGE", 27, "MESSENGER_MONTAGE_FIRST_MESSAGE");
        A1t = c5ap28;
        C5ap c5ap29 = new C5ap("MESSENGER_MONTAGE_MESSAGE_EXPIRING", 28, "MESSENGER_MONTAGE_MESSAGE_EXPIRING");
        A1v = c5ap29;
        C5ap c5ap30 = new C5ap("MESSENGER_MONTAGE_MESSAGE_VIEWING_STATUS", 29, "MESSENGER_MONTAGE_MESSAGE_VIEWING_STATUS");
        A1w = c5ap30;
        C5ap c5ap31 = new C5ap("MESSENGER_MONTAGE_DAILY_DIGEST", 30, "MESSENGER_MONTAGE_DAILY_DIGEST");
        A1s = c5ap31;
        C5ap c5ap32 = new C5ap("MESSENGER_CHAT_ENCOURAGEMENT", 31, "MESSENGER_CHAT_ENCOURAGEMENT");
        A1B = c5ap32;
        C5ap c5ap33 = new C5ap("MONTAGE_MESSAGE_REACTION", 32, "MONTAGE_MESSAGE_REACTION");
        A2D = c5ap33;
        C5ap c5ap34 = new C5ap("TINCAN_DEVICES_CHANGED", 33, "TINCAN_DEVICE_CHANGED");
        A2f = c5ap34;
        C5ap c5ap35 = new C5ap("PAGE_MESSAGE", 34, "PAGE_MESSAGE");
        A2W = c5ap35;
        C5ap c5ap36 = new C5ap("TALK", 35, "TALK");
        A2e = c5ap36;
        C5ap c5ap37 = new C5ap("DIRECT_MESSAGE_STORY_SEEN_MILESTONE", 36, "DIRECT_MESSAGE_STORY_SEEN_MILESTONE");
        A05 = c5ap37;
        C5ap c5ap38 = new C5ap("DIRECT_MESSAGE_STORY_SEEN", 37, "DIRECT_MESSAGE_STORY_SEEN");
        A04 = c5ap38;
        C5ap c5ap39 = new C5ap("VIDEO_CHAT_LINK_JOIN_ATTEMPT", 38, "VIDEO_CHAT_LINK_JOIN_ATTEMPT");
        A2k = c5ap39;
        C5ap c5ap40 = new C5ap("UNREAD_MESSAGE_REMINDER", 39, "UNREAD_MESSAGE_REMINDER");
        A2h = c5ap40;
        C5ap c5ap41 = new C5ap("ROOMS_SPEAKEASY_GENERIC", 40, "ROOMS_SPEAKEASY_GENERIC");
        A2a = c5ap41;
        C5ap c5ap42 = new C5ap("PAGE_ADMIN_INCOMING_CALL", 41, "PAGE_ADMIN_INCOMING_CALL");
        A2U = c5ap42;
        C5ap c5ap43 = new C5ap("MESSENGER_TRY_AR_EFFECT", 42, "MESSENGER_TRY_AR_EFFECT");
        A2A = c5ap43;
        C5ap c5ap44 = new C5ap("IXC_MESSENGER_SUPPORT_INBOX", 43, "IXC_MESSENGER_SUPPORT_INBOX");
        A0z = c5ap44;
        C5ap c5ap45 = new C5ap("PAGE_INCOMING_CALL", 44, "PAGE_INCOMING_CALL");
        A2V = c5ap45;
        C5ap c5ap46 = new C5ap("MESSENGER_MESSAGE_REMINDER", 45, "MESSENGER_MESSAGE_REMINDER");
        A1r = c5ap46;
        C5ap c5ap47 = new C5ap("MESSENGER_CHANNELS_NEW_CHANNEL", 46, "PUBLIC_CHANNELS_NEW_CHANNEL_NOTIF");
        A1A = c5ap47;
        C5ap c5ap48 = new C5ap("MESSENGER_CHANNELS_DIRECT_INVITE", 47, "MSGR_PUBLIC_CHATS_DIRECT_INVITE");
        A19 = c5ap48;
        C5ap c5ap49 = new C5ap("MESSENGER_COMMUNITY_CHAT", 48, "MESSENGER_COMMUNITY_CHAT");
        A1G = c5ap49;
        C5ap c5ap50 = new C5ap("MESSENGER_COMMUNITY_CHAT_MENTIONS_AND_REPLIES", 49, "MESSENGER_COMMUNITY_CHAT_MENTIONS_AND_REPLIES");
        A1O = c5ap50;
        C5ap c5ap51 = new C5ap("MESSENGER_COMMUNITY_CHAT_LEVEL_PARTICIPATION_CONTROL_APPROVAL", 50, "MESSENGER_COMMUNITY_CHAT_LEVEL_PARTICIPATION_CONTROL_APPROVAL");
        A1N = c5ap51;
        C5ap c5ap52 = new C5ap("COMMUNITY_MESSAGING_IN_BLUE_CHAT_SUMMARY", 51, "COMMUNITY_MESSAGING_IN_BLUE_CHAT_SUMMARY");
        A03 = c5ap52;
        C5ap c5ap53 = new C5ap("MESSENGER_COMMUNITY_LEVEL_PARTICIPATION_CONTROL_APPROVAL", 52, "MESSENGER_COMMUNITY_LEVEL_PARTICIPATION_CONTROL_APPROVAL");
        A1Y = c5ap53;
        C5ap c5ap54 = new C5ap("MESSENGER_COMMUNITY_LEVEL_JOIN_REQUEST_APPROVAL_STATUS", 53, "MESSENGER_COMMUNITY_LEVEL_JOIN_REQUEST_APPROVAL_STATUS");
        A1X = c5ap54;
        C5ap c5ap55 = new C5ap("MESSENGER_COMMUNITY_REACTION", 54, "MESSENGER_COMMUNITY_REACTION");
        A1d = c5ap55;
        C5ap c5ap56 = new C5ap("MESSENGER_COMMUNITY_ADMIN_DIRECT_INVITE_GENERIC", 55, "MESSENGER_COMMUNITY_ADMIN_DIRECT_INVITE_GENERIC");
        A1C = c5ap56;
        C5ap c5ap57 = new C5ap("MESSENGER_COMMUNITY_CHAT_FRIEND_JOINED_COMMUNITY_CHAT", 56, "MESSENGER_COMMUNITY_CHAT_FRIEND_JOINED_COMMUNITY_CHAT");
        A1H = c5ap57;
        C5ap c5ap58 = new C5ap("MESSENGER_COMMUNITY_CHANNEL_CREATION", 57, "MESSENGER_COMMUNITY_CHANNEL_CREATION");
        A1F = c5ap58;
        C5ap c5ap59 = new C5ap("MESSENGER_COMMUNITY_TRENDING", 58, "MESSENGER_COMMUNITY_TRENDING");
        A1f = c5ap59;
        C5ap c5ap60 = new C5ap("MESSENGER_COMMUNITY_DEFAULT_NOTIFICATION", 59, "MESSENGER_COMMUNITY_DEFAULT_NOTIFICATION");
        A1Q = c5ap60;
        C5ap c5ap61 = new C5ap("MESSENGER_COMMUNITY_LEVEL_DIRECT_INVITE", 60, "MESSENGER_COMMUNITY_LEVEL_DIRECT_INVITE");
        A1U = c5ap61;
        C5ap c5ap62 = new C5ap("MESSENGER_COMMUNITY_LEVEL_DIRECT_INVITE_V2", 61, "MESSENGER_COMMUNITY_LEVEL_DIRECT_INVITE_V2");
        A1V = c5ap62;
        C5ap c5ap63 = new C5ap("MESSENGER_COMMUNITY_DEFAULT_GENERAL_CHAT", 62, "MESSENGER_COMMUNITY_DEFAULT_GENERAL_CHAT");
        A1P = c5ap63;
        C5ap c5ap64 = new C5ap("MESSENGER_COMMUNITY_LEVEL_ENGAGEMENT", 63, "MESSENGER_COMMUNITY_LEVEL_ENGAGEMENT");
        A1W = c5ap64;
        C5ap c5ap65 = new C5ap("MESSENGER_DIRECT_INVITE_MEMBERSHIP_REQUEST_APPROVAL_STATUS", 64, "MESSENGER_DIRECT_INVITE_MEMBERSHIP_REQUEST_APPROVAL_STATUS");
        A1i = c5ap65;
        C5ap c5ap66 = new C5ap("MESSENGER_COMMUNITY_MEMBER_CHAT_APPROVED", 65, "MESSENGER_COMMUNITY_MEMBER_CHAT_APPROVED");
        A1Z = c5ap66;
        C5ap c5ap67 = new C5ap("MESSENGER_COMMUNITY_MEMBER_CHAT_SUGGESTED", 66, "MESSENGER_COMMUNITY_MEMBER_CHAT_SUGGESTED");
        A1a = c5ap67;
        C5ap c5ap68 = new C5ap("MESSENGER_COMMUNITY_BROADCAST_CHAT_FIRST_MESSAGE", 67, "MESSENGER_COMMUNITY_BROADCAST_CHAT_FIRST_MESSAGE");
        A1E = c5ap68;
        C5ap c5ap69 = new C5ap("MESSENGER_COMMUNITY_EPHEMERAL_STATUS_BADGE_EARNED", 68, "MESSENGER_COMMUNITY_EPHEMERAL_STATUS_BADGE_EARNED");
        A1S = c5ap69;
        C5ap c5ap70 = new C5ap("MESSENGER_COMMUNITY_MEMBER_REQUEST", 69, "MESSENGER_COMMUNITY_MEMBER_REQUEST");
        A1b = c5ap70;
        C5ap c5ap71 = new C5ap("MESSENGER_COMMUNITY_INCOMPLETE_ADMOD_SUGGESTED_ACTIONS", 70, "MESSENGER_COMMUNITY_INCOMPLETE_ADMOD_SUGGESTED_ACTIONS");
        A1T = c5ap71;
        C5ap c5ap72 = new C5ap("MESSENGER_COMMUNITY_CHAT_HOST_INVITE", 71, "MESSENGER_COMMUNITY_CHAT_HOST_INVITE");
        A1I = c5ap72;
        C5ap c5ap73 = new C5ap("MESSENGER_COMMUNITY_DIGEST", 72, "MESSENGER_COMMUNITY_DIGEST");
        A1R = c5ap73;
        C5ap c5ap74 = new C5ap("MESSENGER_COMMUNITY_PAGE_CHAT", 73, "MESSENGER_COMMUNITY_PAGE_CHAT");
        A1c = c5ap74;
        C5ap c5ap75 = new C5ap("MESSENGER_COMMUNITY_RECALL_MESSAGE", 74, "MESSENGER_COMMUNITY_RECALL_MESSAGE");
        A1e = c5ap75;
        C5ap c5ap76 = new C5ap("MESSENGER_COMMUNITY_CHAT_JOIN_REQUEST_ADDED", 75, "MESSENGER_COMMUNITY_CHAT_JOIN_REQUEST_ADDED");
        A1J = c5ap76;
        C5ap c5ap77 = new C5ap("MESSENGER_COMMUNITY_CHAT_JOIN_REQUEST_APPROVED", 76, "MESSENGER_COMMUNITY_CHAT_JOIN_REQUEST_APPROVED");
        A1M = c5ap77;
        C5ap c5ap78 = new C5ap("MESSENGER_COMMUNITY_CHAT_JOIN_REQUEST_ADDED_SINGLE", 77, "MESSENGER_COMMUNITY_CHAT_JOIN_REQUEST_ADDED_SINGLE_REQUESTER");
        A1L = c5ap78;
        C5ap c5ap79 = new C5ap("MESSENGER_COMMUNITY_CHAT_JOIN_REQUEST_ADDED_BATCHED", 78, "MESSENGER_COMMUNITY_CHAT_JOIN_REQUEST_ADDED_BATCHED");
        A1K = c5ap79;
        C5ap c5ap80 = new C5ap("MESSENGER_COMMUNITY_ADMOD_INVITE", 79, "MESSENGER_COMMUNITY_ADMOD_INVITE");
        A1D = c5ap80;
        C5ap c5ap81 = new C5ap("MESSENGER_DEEP_SLEEP_MODE", 80, "MESSENGER_DEEP_SLEEP_MODE");
        A1h = c5ap81;
        C5ap c5ap82 = new C5ap("MESSENGER_REFERRAL_EXPIRY_REMINDER", 81, "MESSENGER_REFERRAL_EXPIRY_REMINDER");
        A24 = c5ap82;
        C5ap c5ap83 = new C5ap("MESSENGER_N4M_P2P_UPDATE", 82, "N4M_TXN_P2P_UPDATE");
        A1x = c5ap83;
        C5ap c5ap84 = new C5ap("MESSENGER_USER_INITIATED_REMINDER", 83, "MESSENGER_USER_INITIATED_REMINDER");
        A2B = c5ap84;
        C5ap c5ap85 = new C5ap("MESSENGER_PAGE_USER_INITIATED_REMINDER", 84, "MESSENGER_PAGE_USER_INITIATED_REMINDER");
        A1z = c5ap85;
        C5ap c5ap86 = new C5ap("MESSENGER_COWATCH_VIDEO_STARTED", 85, "MESSENGER_COWATCH_VIDEO_STARTED");
        A1g = c5ap86;
        C5ap c5ap87 = new C5ap("MESSENGER_GROUP_CALL_UPDATES", 86, "MESSENGER_GROUP_CALL_UPDATES");
        A1n = c5ap87;
        C5ap c5ap88 = new C5ap("MESSENGER_PUBLIC_BROADCAST_CHANNEL", 87, "PUBLIC_DISCOVERABLE_BROADCAST_CHAT_NOTIFICATION");
        A20 = c5ap88;
        C5ap c5ap89 = new C5ap("MESSENGER_PUBLIC_BROADCAST_CHANNELS_BATCHED_REACTIONS", 88, "BROADCAST_CHANNELS_BATCHED_REACTIONS");
        A22 = c5ap89;
        C5ap c5ap90 = new C5ap("MESSENGER_PUBLIC_BROADCAST_CHANNELS_FIRST_MESSAGE_REMINDER", 89, "MSGR_BC_FIRST_MESSAGE_REMINDER");
        A23 = c5ap90;
        C5ap c5ap91 = new C5ap("MESSENGER_PUBLIC_BROADCAST_CHANNELS_BATCHED_POLL_VOTES", 90, "BROADCAST_CHANNELS_BATCHED_POLL_VOTES");
        A21 = c5ap91;
        C5ap c5ap92 = new C5ap("MESSENGER_BROADCAST_CHANNELS_MESSAGE_RECALL_NOTIFICATION", 91, "MSGR_BROADCAST_CHANNELS_MESSAGE_RECALL_NOTIFICATION");
        A18 = c5ap92;
        C5ap c5ap93 = new C5ap("PAGE_MESSAGE_AGGREGRATED_REMINDER_NOTIFICATION", 92, "PAGE_MESSAGE_AGGREGRATED_REMINDER_NOTIFICATION");
        A2X = c5ap93;
        C5ap c5ap94 = new C5ap("MSGR_CM_AND_CHANNEL_INVITE_LINK_JOIN", 93, "MSGR_CM_AND_CHANNEL_INVITE_LINK_JOIN");
        A2E = c5ap94;
        C5ap c5ap95 = new C5ap("MSGR_COMMUNITY_MEMBER_CHAT_SUGGESTIONS_NOTIF", 94, "MSGR_COMMUNITY_MEMBER_CHAT_SUGGESTIONS_NOTIF");
        A2F = c5ap95;
        C5ap c5ap96 = new C5ap("ORCA_IN_VR_ARMADILLO_PLACEHOLDER_NOTIFICATION", 95, "ORCA_IN_VR_ARMADILLO_PLACEHOLDER_NOTIFICATION");
        A2S = c5ap96;
        C5ap c5ap97 = new C5ap("FC_MESSENGER_FETA_ACCOUNT_LIFECYCLE_SELECTED_GUARDIAN_NOTIFICATION", 96, "FC_MESSENGER_FETA_ACCOUNT_LIFECYCLE_SELECTED_GUARDIAN_NOTIFICATION");
        A0D = c5ap97;
        C5ap c5ap98 = new C5ap("FC_MESSENGER_FETA_AGE_OUT_NOTIFICATION", 97, "FC_MESSENGER_FETA_AGE_OUT_NOTIFICATION");
        A0E = c5ap98;
        C5ap c5ap99 = new C5ap("FC_MESSENGER_FETA_INVITE_UPDATE_GUARDIAN_NOTIFICATION", 98, "FC_MESSENGER_FETA_INVITE_UPDATE_GUARDIAN_NOTIFICATION");
        A0F = c5ap99;
        C5ap c5ap100 = new C5ap("FC_MESSENGER_FETA_INVITE_UPDATE_TEEN_NOTIFICATION", 99, "FC_MESSENGER_FETA_INVITE_UPDATE_TEEN_NOTIFICATION");
        A0G = c5ap100;
        C5ap c5ap101 = new C5ap("FC_MESSENGER_FETA_LINK_INVITE_EXPIRED_NOTIFICATION", 100, "FC_MESSENGER_FETA_LINK_INVITE_EXPIRED_NOTIFICATION");
        A0H = c5ap101;
        C5ap c5ap102 = new C5ap("FC_MESSENGER_FETA_ONGOING_VERIFICATION_FAILURE_NOTIFICATION", ActionId.ON_VIEW_CREATED_END, "FC_MESSENGER_FETA_ONGOING_VERIFICATION_FAILURE_NOTIFICATION");
        A0I = c5ap102;
        C5ap c5ap103 = new C5ap("FC_MESSENGER_FETA_REMOVE_SUPERVISION_GUARDIAN_NOTIFICATION", ActionId.DATA_LOAD_START, "FC_MESSENGER_FETA_REMOVE_SUPERVISION_GUARDIAN_NOTIFICATION");
        A0J = c5ap103;
        C5ap c5ap104 = new C5ap("FC_MESSENGER_FETA_REMOVE_SUPERVISION_TEEN_NOTIFICATION", ActionId.LEGACY_MARKER, "FC_MESSENGER_FETA_REMOVE_SUPERVISION_TEEN_NOTIFICATION");
        A0K = c5ap104;
        C5ap c5ap105 = new C5ap("FC_MESSENGER_FETA_RETAIN_SUPERVISION_GUARDIAN_NOTIFICATION", ActionId.ACTION_BAR_COMPLETE, "FC_MESSENGER_FETA_RETAIN_SUPERVISION_GUARDIAN_NOTIFICATION");
        A0L = c5ap105;
        C5ap c5ap106 = new C5ap("FC_MESSENGER_FETA_TARGETED_INVITE_GUARDIAN_NOTIFICATION", ActionId.ABORTED, "FC_MESSENGER_FETA_TARGETED_INVITE_GUARDIAN_NOTIFICATION");
        A0M = c5ap106;
        C5ap c5ap107 = new C5ap("FC_MESSENGER_FETA_TARGETED_INVITE_REMINDER_GUARDIAN_NOTIFICATION", ActionId.QUERY_READY, "FC_MESSENGER_FETA_TARGETED_INVITE_REMINDER_GUARDIAN_NOTIFICATION");
        A0N = c5ap107;
        C5ap c5ap108 = new C5ap("FC_MESSENGER_FETA_TARGETED_INVITE_REMINDER_TEEN_NOTIFICATION", ActionId.RTMP_PACKET_RECEIVED, "FC_MESSENGER_FETA_TARGETED_INVITE_REMINDER_TEEN_NOTIFICATION");
        A0O = c5ap108;
        C5ap c5ap109 = new C5ap("FC_MESSENGER_FETA_TARGETED_INVITE_TEEN_NOTIFICATION", 108, "FC_MESSENGER_FETA_TARGETED_INVITE_TEEN_NOTIFICATION");
        A0P = c5ap109;
        C5ap c5ap110 = new C5ap("FC_MESSENGER_FETA_VERIFICATION_FAILURE_GUARDIAN_NOTIFICATION", ActionId.RTMP_CONNECTION_REQUESTED, "FC_MESSENGER_FETA_VERIFICATION_FAILURE_GUARDIAN_NOTIFICATION");
        A0Q = c5ap110;
        C5ap c5ap111 = new C5ap("FC_MESSENGER_FETA_VERIFICATION_FAILURE_TEEN_NOTIFICATION", ActionId.RTMP_CONNECTION_RELEASE, "FC_MESSENGER_FETA_VERIFICATION_FAILURE_TEEN_NOTIFICATION");
        A0R = c5ap111;
        C5ap c5ap112 = new C5ap("FC_MESSENGER_TEEN_BLOCKED_GUARDIAN_TEEN_NOTIFICATION", ActionId.NEW_START_FOUND, "FC_MESSENGER_TEEN_BLOCKED_GUARDIAN_TEEN_NOTIFICATION");
        A0p = c5ap112;
        C5ap c5ap113 = new C5ap("FC_MESSENGER_SUPERVISION_INVITE_UPDATED_TEEN_NOTIFICATION", ActionId.MISSED_EVENT, "FC_MESSENGER_SUPERVISION_INVITE_UPDATED_TEEN_NOTIFICATION");
        A0l = c5ap113;
        C5ap c5ap114 = new C5ap("FC_MESSENGER_SUPERVISION_INVITE_UPDATED_GUARDIAN_NOTIFICATION", ActionId.TIMEOUT, "FC_MESSENGER_SUPERVISION_INVITE_UPDATED_GUARDIAN_NOTIFICATION");
        A0k = c5ap114;
        C5ap c5ap115 = new C5ap("FC_MESSENGER_INVITE_EXPIRED_GUARDIAN_NOTIFICATION", ActionId.CONTROLLER_INITIATED, "FC_MESSENGER_INVITE_EXPIRED_GUARDIAN_NOTIFICATION");
        A0V = c5ap115;
        C5ap c5ap116 = new C5ap("FC_MESSENGER_INVITE_EXPIRED_TEEN_NOTIFICATION", ActionId.RTMP_STREAM_PREPARED, "FC_MESSENGER_INVITE_EXPIRED_TEEN_NOTIFICATION");
        A0W = c5ap116;
        C5ap c5ap117 = new C5ap("FC_MESSENGER_VERIFICATION_FAILED_TEEN_NOTIFICATION", ActionId.VIDEO_PLAYING, "FC_MESSENGER_VERIFICATION_FAILED_TEEN_NOTIFICATION");
        A0v = c5ap117;
        C5ap c5ap118 = new C5ap("FC_MESSENGER_VERIFICATION_FAILED_GUARDIAN_NOTIFICATION", ActionId.RTMP_CONNECTION_CONNECTED, "FC_MESSENGER_VERIFICATION_FAILED_GUARDIAN_NOTIFICATION");
        A0u = c5ap118;
        C5ap c5ap119 = new C5ap("FC_MESSENGER_NEW_CONTACT_GUARDIAN_NOTIFICATION", ActionId.RTMP_CONNECTION_FAILED, "FC_MESSENGER_NEW_CONTACT_GUARDIAN_NOTIFICATION");
        A0X = c5ap119;
        C5ap c5ap120 = new C5ap("FC_MESSENGER_TEEN_CHANGED_SETTING_GUARDIAN_NOTIFICATION", ActionId.RTMP_CONNECTION_INTERCEPTED, "FC_MESSENGER_TEEN_CHANGED_SETTING_GUARDIAN_NOTIFICATION");
        A0q = c5ap120;
        C5ap c5ap121 = new C5ap("FC_MESSENGER_TEEN_REPORT_DETAILS_GUARDIAN_NOTIFICATION", ActionId.VIDEO_SET_RENDERER_CONTEXT, "FC_MESSENGER_TEEN_REPORT_DETAILS_GUARDIAN_NOTIFICATION");
        A0t = c5ap121;
        C5ap c5ap122 = new C5ap("FC_MESSENGER_TEEN_REMOVED_SUPERVISION_GUARDIAN_NOTIFICATION", ActionId.HEADER_DATA_LOADED, "FC_MESSENGER_TEEN_REMOVED_SUPERVISION_GUARDIAN_NOTIFICATION");
        A0s = c5ap122;
        C5ap c5ap123 = new C5ap("FC_MESSENGER_GUARDIAN_REMOVED_SUPERVISION_TEEN_NOTIFICATION", ActionId.CARD_DATA_LOADED, "FC_MESSENGER_GUARDIAN_REMOVED_SUPERVISION_TEEN_NOTIFICATION");
        A0U = c5ap123;
        C5ap c5ap124 = new C5ap("FC_MESSENGER_ASYNC_VERIFICATION_FAILED_TEEN_NOTIFICATION", ActionId.VIEW_WILL_APPEAR_BEGIN, "FC_MESSENGER_ASYNC_VERIFICATION_FAILED_TEEN_NOTIFICATION");
        A0A = c5ap124;
        C5ap c5ap125 = new C5ap("FC_MESSENGER_ASYNC_VERIFICATION_FAILED_GUARDIAN_NOTIFICATION", ActionId.VIEW_DID_LOAD_BEGIN, "FC_MESSENGER_ASYNC_VERIFICATION_FAILED_GUARDIAN_NOTIFICATION");
        A09 = c5ap125;
        C5ap c5ap126 = new C5ap("FC_MESSENGER_PRE_AGE_UP_TEEN_NOTIFICATION", 125, "FC_MESSENGER_PRE_AGE_UP_TEEN_NOTIFICATION");
        A0a = c5ap126;
        C5ap c5ap127 = new C5ap("FC_MESSENGER_PRE_AGE_UP_GUARDIAN_NOTIFICATION", ActionId.COMPONENTS_DATA_SOURCE_DID_END_UPDATES, "FC_MESSENGER_PRE_AGE_UP_GUARDIAN_NOTIFICATION");
        A0Z = c5ap127;
        C5ap c5ap128 = new C5ap("FC_MESSENGER_SUPERVISION_COOLDOWN_ENDED_TEEN_NOTIFICATION", 127, "FC_MESSENGER_SUPERVISION_COOLDOWN_ENDED_TEEN_NOTIFICATION");
        A0j = c5ap128;
        C5ap c5ap129 = new C5ap("FC_MESSENGER_SUPERVISION_REINSTATED_GUARDIAN_NOTIFICATION", 128, "FC_MESSENGER_SUPERVISION_REINSTATED_GUARDIAN_NOTIFICATION");
        A0m = c5ap129;
        C5ap c5ap130 = new C5ap("FC_MESSENGER_TEEN_AGE_UP_REMINDER_TEEN_NOTIFICATION", ActionId.MESSENGER_QUEUE_CREATION, "FC_MESSENGER_TEEN_AGE_UP_REMINDER_TEEN_NOTIFICATION");
        A0o = c5ap130;
        C5ap c5ap131 = new C5ap("FC_MESSENGER_TEEN_AGE_UP_REMINDER_GUARDIAN_NOTIFICATION", ActionId.APP_DID_FINISH_LAUNCHING, "FC_MESSENGER_TEEN_AGE_UP_REMINDER_GUARDIAN_NOTIFICATION");
        A0n = c5ap131;
        C5ap c5ap132 = new C5ap("FC_MESSENGER_GEN_AI_NOTICE_TEEN_NOTIFICATION", ActionId.APP_DID_BECOME_ACTIVE, "FC_MESSENGER_GEN_AI_NOTICE_TEEN_NOTIFICATION");
        A0S = c5ap132;
        C5ap c5ap133 = new C5ap("FC_MESSENGER_TEEN_FIRST_GEN_AI_USE_GUARDIAN_NOTIFICATION", ActionId.APP_WILL_ENTER_FOREGROUND, "FC_MESSENGER_TEEN_FIRST_GEN_AI_USE_GUARDIAN_NOTIFICATION");
        A0r = c5ap133;
        C5ap c5ap134 = new C5ap("FC_MESSENGER_RECONSENT_GUARDIAN_NOTIFICATION", ActionId.APP_DID_ENTER_BACKGROUND, "FC_MESSENGER_RECONSENT_GUARDIAN_NOTIFICATION");
        A0f = c5ap134;
        C5ap c5ap135 = new C5ap("FC_MESSENGER_RECONSENT_TEEN_NOTIFICATION", ActionId.APP_MAIN, "FC_MESSENGER_RECONSENT_TEEN_NOTIFICATION");
        A0g = c5ap135;
        C5ap c5ap136 = new C5ap("FC_MESSENGER_QUIET_TIME_CHANGED_TEEN_NOTIFICATION", ActionId.MQTT_CONNECTING, "FC_MESSENGER_QUIET_TIME_CHANGED_TEEN_NOTIFICATION");
        A0e = c5ap136;
        C5ap c5ap137 = new C5ap("FC_MESSENGER_DAILY_TIME_LIMIT_CHANGED_TEEN_NOTIFICATION", ActionId.MQTT_CONNECTED, "FC_MESSENGER_DAILY_TIME_LIMIT_CHANGED_TEEN_NOTIFICATION");
        A0C = c5ap137;
        C5ap c5ap138 = new C5ap("FC_MESSENGER_PARENT_MODIFY_SETTING_TEEN_NOTIFICATION", ActionId.MQTT_DISCONNECTED, "FC_MESSENGER_PARENT_MODIFY_SETTING_TEEN_NOTIFICATION");
        A0Y = c5ap138;
        C5ap c5ap139 = new C5ap("FC_MESSENGER_SETTINGS_CHANGE_REQUEST_DECISION_TEEN_NOTIFICATION", ActionId.MESSENGER_DELTA_REQUEST, "FC_MESSENGER_SETTINGS_CHANGE_REQUEST_DECISION_TEEN_NOTIFICATION");
        A0h = c5ap139;
        C5ap c5ap140 = new C5ap("FC_MESSENGER_SETTINGS_CHANGE_REQUEST_GUARDIAN_NOTIFICATION", ActionId.APP_FIRST_VIEW_CONTROLLER, "FC_MESSENGER_SETTINGS_CHANGE_REQUEST_GUARDIAN_NOTIFICATION");
        A0i = c5ap140;
        C5ap c5ap141 = new C5ap("FC_MESSENGER_CHOOSE_GUARDIAN_TEEN_NOTIFICATION", ActionId.MESSENGER_THREAD_LIST_LOADED, "FC_MESSENGER_CHOOSE_GUARDIAN_TEEN_NOTIFICATION");
        A0B = c5ap141;
        C5ap c5ap142 = new C5ap("FC_MESSENGER_GUARDIAN_NOT_CHOSEN_GUARDIAN_NOTIFICATION", ActionId.MESSENGER_THREAD_LIST_DISPLAYED, "FC_MESSENGER_GUARDIAN_NOT_CHOSEN_GUARDIAN_NOTIFICATION");
        A0T = c5ap142;
        C5ap c5ap143 = new C5ap("FC_MESSENGER_PROFILE_WILL_NOT_BE_SUPERVISED_TEEN_NOTIFICATION", ActionId.PREV_ACTIVITY_PAUSE, "FC_MESSENGER_PROFILE_WILL_NOT_BE_SUPERVISED_TEEN_NOTIFICATION");
        A0d = c5ap143;
        C5ap c5ap144 = new C5ap("FC_MESSENGER_PROFILE_IS_NO_LONGER_SUPERVISED_TEEN_NOTIFICATION", ActionId.ACTIVITY_RESUME, "FC_MESSENGER_PROFILE_IS_NO_LONGER_SUPERVISED_TEEN_NOTIFICATION");
        A0c = c5ap144;
        C5ap c5ap145 = new C5ap("FC_MESSENGER_PROFILE_IS_NO_LONGER_SUPERVISED_GUARDIAN_NOTIFICATION", ActionId.ACTIVITY_START, "FC_MESSENGER_PROFILE_IS_NO_LONGER_SUPERVISED_GUARDIAN_NOTIFICATION");
        A0b = c5ap145;
        C5ap c5ap146 = new C5ap("YOUTH_RS_MESSENGER_TEEN_MESSAGING_DATA_REQUEST_TEEN_NOTIFICATION", ActionId.BEGIN_START_ACTIVITY, "YOUTH_RS_MESSENGER_TEEN_MESSAGING_DATA_REQUEST_TEEN_NOTIFICATION");
        A2t = c5ap146;
        C5ap c5ap147 = new C5ap("YOUTH_RS_MESSENGER_APPEAL_SUCCESS_OLD_PARENT_NOTIFICATION", ActionId.END_START_ACTIVITY, "YOUTH_RS_MESSENGER_APPEAL_SUCCESS_OLD_PARENT_NOTIFICATION");
        A2l = c5ap147;
        C5ap c5ap148 = new C5ap("YOUTH_RS_MESSENGER_APPEAL_SUCCESS_TEEN_NOTIFICATION", ActionId.FILE_SYSTEM_FAIL, "YOUTH_RS_MESSENGER_APPEAL_SUCCESS_TEEN_NOTIFICATION");
        A2m = c5ap148;
        C5ap c5ap149 = new C5ap("YOUTH_RS_MESSENGER_GS_INVITE_ACCEPT_NOTIFICATION", ActionId.FORMAT_ERROR, "YOUTH_RS_MESSENGER_GS_INVITE_ACCEPT_NOTIFICATION");
        A2n = c5ap149;
        C5ap c5ap150 = new C5ap("YOUTH_RS_MESSENGER_GS_INVITE_CREATE_NOTIFICATION", ActionId.PRIVACY_VIOLATION, "YOUTH_RS_MESSENGER_GS_INVITE_CREATE_NOTIFICATION");
        A2o = c5ap150;
        C5ap c5ap151 = new C5ap("YOUTH_RS_MESSENGER_GS_INVITE_DECLINE_NOTIFICATION", 150, "YOUTH_RS_MESSENGER_GS_INVITE_DECLINE_NOTIFICATION");
        A2p = c5ap151;
        C5ap c5ap152 = new C5ap("YOUTH_RS_MESSENGER_GS_OPT_OUT_NOTIFICATION", ActionId.POPULATE_CONSISTENCY_MEMORY_CACHE, "YOUTH_RS_MESSENGER_GS_OPT_OUT_NOTIFICATION");
        A2q = c5ap152;
        C5ap c5ap153 = new C5ap("YOUTH_RS_MESSENGER_INVITE_CREATE_TEEN_NOTIFICATION", ActionId.APPLY_OPTIMISTICS, "YOUTH_RS_MESSENGER_INVITE_CREATE_TEEN_NOTIFICATION");
        A2r = c5ap153;
        C5ap c5ap154 = new C5ap("YOUTH_RS_MESSENGER_OFFBOARDING_NOTIFICATION", ActionId.APPLY_FINISHED_LIST, "YOUTH_RS_MESSENGER_OFFBOARDING_NOTIFICATION");
        A2s = c5ap154;
        C5ap c5ap155 = new C5ap("YOUTH_RS_MESSENGER_TRANSITION_NOTIFICATION", ActionId.APPLY_FINISHED_LIST_AGAIN, "YOUTH_RS_MESSENGER_TRANSITION_NOTIFICATION");
        A2u = c5ap155;
        C5ap c5ap156 = new C5ap("PUSH_TO_SESSION_MESSENGER_LOGIN", ActionId.FUTURE_LISTENERS_COMPLETE, "PUSH_TO_SESSION_MESSENGER_LOGIN");
        A2Z = c5ap156;
        C5ap c5ap157 = new C5ap("MESSENGER_ENCRYPTED_BACKUPS_ONE_TIME_CODE", ActionId.SERVICE_ON_START_COMMAND, "MESSENGER_ENCRYPTED_BACKUPS_ONE_TIME_CODE");
        A1k = c5ap157;
        C5ap c5ap158 = new C5ap("MESSENGER_ENCRYPTED_BACKUPS_WEB2MOBILE_ONBOARDING_NOTIFICATION", ActionId.WAIT_FOR_BLOCKERS, "messenger_encrypted_backups_web2mobile_onboarding");
        A1l = c5ap158;
        C5ap c5ap159 = new C5ap("MARKETING_MESSAGES_UNREAD_OPTIN_REMINDER", ActionId.NOTIFY_SUBSCRIBERS, "MARKETING_MESSAGES_UNREAD_OPTIN_REMINDER");
        A12 = c5ap159;
        C5ap c5ap160 = new C5ap("MSNGR_AFS_SUBSCRIPTION_CANCELED_DEVICE_SETTINGS", ActionId.FAIL_FILE_TOO_LARGE, "MSNGR_AFS_SUBSCRIPTION_CANCELED_DEVICE_SETTINGS");
        A2M = c5ap160;
        C5ap c5ap161 = new C5ap("MSNGR_AFS_LINKING_BOTH_SUBSCRIBED", ActionId.OFFLINE, "MSNGR_AFS_LINKING_BOTH_SUBSCRIBED");
        A2H = c5ap161;
        C5ap c5ap162 = new C5ap("MSNGR_AFS_CANCELATION_INCOMPLETE", ActionId.ASNYC_FAILED, "MSNGR_AFS_CANCELATION_INCOMPLETE");
        A2G = c5ap162;
        C5ap c5ap163 = new C5ap("MSNGR_AFS_YOUTH_SHOULD_CANCEL_SUBSCRIPTION", ActionId.ASYNC_FAIL, "MSNGR_AFS_YOUTH_SHOULD_CANCEL_SUBSCRIPTION");
        A2P = c5ap163;
        C5ap c5ap164 = new C5ap("MSNGR_AFS_UNLINKING_DEFERRED_DOWNGRADE_NEXT_BILLING_CYCLE", ActionId.ON_ATTACH_FRAGMENT, "MSNGR_AFS_UNLINKING_DEFERRED_DOWNGRADE_NEXT_BILLING_CYCLE");
        A2N = c5ap164;
        C5ap c5ap165 = new C5ap("MSNGR_AFS_STANDARD_UNLINKING", ActionId.VIEW_DID_APPEAR_BEGIN, "MSNGR_AFS_STANDARD_UNLINKING");
        A2L = c5ap165;
        C5ap c5ap166 = new C5ap("MSNGR_AFS_MULTIPLE_SUBSCRIPTION_VARIABLE_PRICING", ActionId.DISPLAYED, "MSNGR_AFS_MULTIPLE_SUBSCRIPTION_VARIABLE_PRICING");
        A2K = c5ap166;
        C5ap c5ap167 = new C5ap("MSNGR_AFS_UPGRADE_DEVICE_SETTING", ActionId.DISPLAYED_ON_SCREEN, "MSNGR_AFS_UPGRADE_DEVICE_SETTING");
        A2O = c5ap167;
        C5ap c5ap168 = new C5ap("MSNGR_AFS_LINKING_MULTIPLE_SUBSCRIPTION_DEFERRED_DOWNGRADE_NEXT_BILLING_CYCLE", ActionId.ASYNC_ACTION_SUCCESS, "MSNGR_AFS_LINKING_MULTIPLE_SUBSCRIPTION_DEFERRED_DOWNGRADE_NEXT_BILLING_CYCLE");
        A2J = c5ap168;
        C5ap c5ap169 = new C5ap("MSNGR_AFS_LINKING_MULTIPLE_SUBSCRIPTION_DEFERRED_DOWNGRADE", ActionId.ASYNC_ACTION_FAIL, "MSNGR_AFS_LINKING_MULTIPLE_SUBSCRIPTION_DEFERRED_DOWNGRADE");
        A2I = c5ap169;
        C5ap c5ap170 = new C5ap("MESSENGER_AI_AGENTS_USER_OFF_WAITLIST", ActionId.CONNECTIVITY_CHANGED, "MSGR_AI_AGENTS_USER_OFF_WAITLIST");
        A17 = c5ap170;
        C5ap c5ap171 = new C5ap("MESSENGER_GENERIC_TINCAN_MESSAGE", ActionId.VIDEO_DISPLAYED, "MESSENGER_GENERIC_TINCAN_MESSAGE");
        A1m = c5ap171;
        C5ap c5ap172 = new C5ap("MESSENGER_SHARED_ALBUM_CREATION", ActionId.VIDEO_REQUESTED_PLAYING, "MSGR_SHARED_ALBUM_CREATION");
        A26 = c5ap172;
        C5ap c5ap173 = new C5ap("MESSENGER_SHARED_ALBUM_ADDITION", 172, "MSGR_SHARED_ALBUM_ADDITION");
        A25 = c5ap173;
        C5ap c5ap174 = new C5ap("MESSENGER_SHARED_ALBUM_DELETION", 173, "MSGR_SHARED_ALBUM_DELETION");
        A27 = c5ap174;
        C5ap c5ap175 = new C5ap("MESSENGER_SHARED_ALBUM_REMOVAL", 174, "MSGR_SHARED_ALBUM_REMOVAL");
        A29 = c5ap175;
        C5ap c5ap176 = new C5ap("MESSENGER_SHARED_ALBUM_REACTION", 175, "MSGR_SHARED_ALBUM_REACTION");
        A28 = c5ap176;
        C5ap c5ap177 = new C5ap("MESSENGER_NOTE_MENTION", 176, "MESSENGER_NOTE_MENTION");
        A1y = c5ap177;
        C5ap c5ap178 = new C5ap("FRIEND_REQUEST", 177, "FRIEND_REQUEST");
        A0x = c5ap178;
        C5ap c5ap179 = new C5ap("MESSENGER_ENCRYPTED_BACKUPS_NETWORK_VERIFICATION_RESTORE", 178, "MESSENGER_ENCRYPTED_BACKUPS_NETWORK_VERIFICATION_RESTORE");
        A1j = c5ap179;
        C5ap c5ap180 = new C5ap(OffsiteInitAvailabilityRequestKt.DEFAULT_PARTNER_ID, 179, OffsiteInitAvailabilityRequestKt.DEFAULT_PARTNER_ID);
        A2g = c5ap180;
        C5ap[] c5apArr = new C5ap[180];
        System.arraycopy(new C5ap[]{c5ap, c5ap2, c5ap3, c5ap4, c5ap5, c5ap6, c5ap7, c5ap8, c5ap9, c5ap10, c5ap11, c5ap12, c5ap13, c5ap14, c5ap15, c5ap16, c5ap17, c5ap18, c5ap19, c5ap20, c5ap21, c5ap22, c5ap23, c5ap24, c5ap25, c5ap26, c5ap27}, 0, c5apArr, 0, 27);
        System.arraycopy(new C5ap[]{c5ap28, c5ap29, c5ap30, c5ap31, c5ap32, c5ap33, c5ap34, c5ap35, c5ap36, c5ap37, c5ap38, c5ap39, c5ap40, c5ap41, c5ap42, c5ap43, c5ap44, c5ap45, c5ap46, c5ap47, c5ap48, c5ap49, c5ap50, c5ap51, c5ap52, c5ap53, c5ap54}, 0, c5apArr, 27, 27);
        System.arraycopy(new C5ap[]{c5ap55, c5ap56, c5ap57, c5ap58, c5ap59, c5ap60, c5ap61, c5ap62, c5ap63, c5ap64, c5ap65, c5ap66, c5ap67, c5ap68, c5ap69, c5ap70, c5ap71, c5ap72, c5ap73, c5ap74, c5ap75, c5ap76, c5ap77, c5ap78, c5ap79, c5ap80, c5ap81}, 0, c5apArr, 54, 27);
        System.arraycopy(new C5ap[]{c5ap82, c5ap83, c5ap84, c5ap85, c5ap86, c5ap87, c5ap88, c5ap89, c5ap90, c5ap91, c5ap92, c5ap93, c5ap94, c5ap95, c5ap96, c5ap97, c5ap98, c5ap99, c5ap100, c5ap101, c5ap102, c5ap103, c5ap104, c5ap105, c5ap106, c5ap107, c5ap108}, 0, c5apArr, 81, 27);
        System.arraycopy(new C5ap[]{c5ap109, c5ap110, c5ap111, c5ap112, c5ap113, c5ap114, c5ap115, c5ap116, c5ap117, c5ap118, c5ap119, c5ap120, c5ap121, c5ap122, c5ap123, c5ap124, c5ap125, c5ap126, c5ap127, c5ap128, c5ap129, c5ap130, c5ap131, c5ap132, c5ap133, c5ap134, c5ap135}, 0, c5apArr, 108, 27);
        System.arraycopy(new C5ap[]{c5ap136, c5ap137, c5ap138, c5ap139, c5ap140, c5ap141, c5ap142, c5ap143, c5ap144, c5ap145, c5ap146, c5ap147, c5ap148, c5ap149, c5ap150, c5ap151, c5ap152, c5ap153, c5ap154, c5ap155, c5ap156, c5ap157, c5ap158, c5ap159, c5ap160, c5ap161, c5ap162}, 0, c5apArr, ActionId.MQTT_CONNECTING, 27);
        System.arraycopy(new C5ap[]{c5ap163, c5ap164, c5ap165, c5ap166, c5ap167, c5ap168, c5ap169, c5ap170, c5ap171, c5ap172, c5ap173, c5ap174, c5ap175, c5ap176, c5ap177, c5ap178, c5ap179, c5ap180}, 0, c5apArr, ActionId.ASYNC_FAIL, 18);
        A00 = c5apArr;
    }

    public C5ap(String str, int i, String str2) {
        this.stringValue = str2;
    }

    public static C5ap A00(String str) {
        C5ap c5ap;
        C5ap[] values = values();
        int length = values.length;
        int i = 0;
        while (true) {
            int i2 = i;
            if (i2 >= length) {
                c5ap = A2g;
                break;
            }
            c5ap = values[i2];
            if (Objects.equal(c5ap.stringValue, str)) {
                break;
            }
            i = i2 + 1;
        }
        return c5ap;
    }

    public static C5ap valueOf(String str) {
        return (C5ap) Enum.valueOf(C5ap.class, str);
    }

    public static C5ap[] values() {
        return (C5ap[]) A00.clone();
    }

    @Override // java.lang.Enum
    public String toString() {
        return this.stringValue;
    }
}
