package X;

/* renamed from: X.7gi, reason: invalid class name */
/* loaded from: 7gi.class */
public final class C7gi extends 6Cy {
    public static final long serialVersionUID = 1014987236950835638L;
    public final String appNetSessionId;
    public final long avgBitrate;
    public final int bufferedDurationMs;
    public final int bufferedDurationMsAtDataSpecCreation;
    public final 6DD cacheType;
    public final long cdnResponseTime;
    public final Long clientWallClockOffsetMs;
    public final String codec;
    public final long confidenceBasedBitrateEstimate;
    public final int confidencePctForBitrateEstimate;
    public final String connectionQuality;
    public final Long contentLength;
    public final String contentType;
    public final String dataSourceFactory;
    public final long dataSpecCreationTimeMs;
    public final String edgeHit;
    public final String exceptionMessage;
    public final int expectedPredictedNumber;
    public final int firstChunkSize;
    public final boolean inRewoundState;
    public final boolean isChunkedTransfer;
    public final boolean isFBMS;
    public final boolean isFbPredictiveDASH;
    public final boolean isFirstTimePlay;
    public final boolean isInWarmup;
    public final boolean isLowestBitrate;
    public final boolean isManifestDynamic;
    public final boolean isPredictedURL;
    public final boolean isPrefetch;
    public final boolean isSkipAheadChunk;
    public final boolean isSpherical;
    public final boolean isSponsored;
    public final boolean isTemplatedManifest;
    public final int latestSegmentId;
    public final long manifestFirstSegmentStartTs;
    public final long manifestLastSegmentEndTs;
    public final long manifestNumSegments;
    public final int minimumLoadPositionMs;
    public final int networkPriority;
    public final long numSegmentsToEndOfManifest;
    public final String oneObserved;
    public final String oneReqWave;
    public final String oneResWave;
    public final String oneVariant;
    public final String originHit;
    public final String playOrigin;
    public final String playSubOrigin;
    public final long playerId;
    public final String playerType;
    public final int positionInUnit;
    public final int predictedNumberMapping;
    public final String prefetchSource;
    public final String qualityLabel;
    public final long requestQueueDurationMs;
    public final long requestedLength;
    public final int segmentDurationMs;
    public final long segmentStartMs;
    public final long startVideoBandwidth;
    public final long startVideoTTFB;
    public final long startingByteOffset;
    public final int streamType;
    public final String tigonSessionId;
    public final String tigonTransactionId;
    public final long timeMs;
    public final int transferSeqNum;
    public final long transferStartDurationMs;
    public final long upstreamTTFB;
    public final String url;
    public final String videoBandwidthEstimateStr;
    public final String videoId;
    public final String vpSessionId;

    public C7gi(6DD r302, Long l, Long l2, String str, String str2, String str3, String str4, String str5, String str6, String str7, String str8, String str9, String str10, String str11, String str12, String str13, String str14, String str15, String str16, String str17, String str18, String str19, String str20, String str21, int i, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10, int i11, int i12, int i13, long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10, boolean z11, boolean z12, boolean z13, boolean z14) {
        super(6Cz.A0H);
        this.timeMs = j;
        this.videoId = str;
        this.playerId = j2;
        this.url = str2;
        this.exceptionMessage = str3;
        this.isPrefetch = z;
        this.prefetchSource = str4;
        this.requestQueueDurationMs = j3;
        this.transferStartDurationMs = j4;
        this.transferSeqNum = i;
        this.cacheType = r302;
        this.isFirstTimePlay = z2;
        this.isInWarmup = z3;
        this.playOrigin = str5;
        this.playSubOrigin = str11;
        this.startingByteOffset = j5;
        this.requestedLength = j6;
        this.streamType = i2;
        this.segmentStartMs = j7;
        this.segmentDurationMs = i3;
        this.dataSourceFactory = str6;
        this.qualityLabel = str7;
        this.connectionQuality = str8;
        this.networkPriority = i4;
        this.avgBitrate = j8;
        this.isLowestBitrate = z4;
        this.bufferedDurationMs = i5;
        this.startVideoBandwidth = j9;
        this.startVideoTTFB = j10;
        this.isSpherical = z5;
        this.isSponsored = z6;
        this.isTemplatedManifest = z7;
        this.videoBandwidthEstimateStr = str9;
        this.upstreamTTFB = j11;
        this.tigonSessionId = null;
        this.tigonTransactionId = null;
        this.appNetSessionId = str10;
        this.manifestFirstSegmentStartTs = j12;
        this.manifestLastSegmentEndTs = j13;
        this.manifestNumSegments = j14;
        this.bufferedDurationMsAtDataSpecCreation = i6;
        this.dataSpecCreationTimeMs = j15;
        this.isFBMS = z8;
        this.isFbPredictiveDASH = z9;
        this.isSkipAheadChunk = z10;
        this.inRewoundState = z11;
        this.isManifestDynamic = z12;
        this.isChunkedTransfer = z13;
        this.isPredictedURL = z14;
        this.expectedPredictedNumber = i8;
        this.predictedNumberMapping = i7;
        this.numSegmentsToEndOfManifest = j16;
        this.edgeHit = str12;
        this.originHit = str13;
        this.codec = str14;
        this.cdnResponseTime = j17;
        this.contentType = str15;
        this.latestSegmentId = i9;
        this.confidenceBasedBitrateEstimate = j18;
        this.confidencePctForBitrateEstimate = i10;
        this.minimumLoadPositionMs = i11;
        this.oneReqWave = str16;
        this.oneResWave = str17;
        this.oneObserved = str18;
        this.oneVariant = str19;
        this.playerType = str20;
        this.positionInUnit = i12;
        this.vpSessionId = str21;
        this.firstChunkSize = i13;
        this.clientWallClockOffsetMs = l;
        this.contentLength = l2;
    }

    public String toString() {
        StringBuilder A0k = AnonymousClass001.A0k();
        4YV.A1O("timeMs=", A0k, this.timeMs);
        4YU.A1S(", videoId=", this.videoId, A0k);
        4YV.A1O(", playerId=", A0k, this.playerId);
        4YU.A1S(", url=", this.url, A0k);
        4YU.A1S(", exception=", this.exceptionMessage, A0k);
        4YV.A1P(", isPrefetch=", A0k, this.isPrefetch);
        4YU.A1S(", prefetchSource=", this.prefetchSource, A0k);
        4YV.A1O(", queueDuration=", A0k, this.requestQueueDurationMs);
        4YV.A1O(", startDuration=", A0k, this.transferStartDurationMs);
        6Cy.A00(", seqNum=", A0k, this.transferSeqNum);
        4YU.A1S(", cacheType=", this.cacheType.mName, A0k);
        4YV.A1P(", isFirstPlay=", A0k, this.isFirstTimePlay);
        4YU.A1S(", playOrigin=", this.playOrigin, A0k);
        4YV.A1O(", startingByteOffset=", A0k, this.startingByteOffset);
        4YV.A1O(", requestedLength=", A0k, this.requestedLength);
        6Cy.A00(", streamType=", A0k, this.streamType);
        4YV.A1O(", segmentStart=", A0k, this.segmentStartMs);
        6Cy.A00(", segmentDuration=", A0k, this.segmentDurationMs);
        4YU.A1S(", dataSourceFactory=", this.dataSourceFactory, A0k);
        4YU.A1S(", qualityLabel=", this.qualityLabel, A0k);
        4YU.A1S(", connQual=", this.connectionQuality, A0k);
        6Cy.A00(", networkPriority=", A0k, this.networkPriority);
        6Cy.A00(", bufferedDurationMs=", A0k, this.bufferedDurationMs);
        4YV.A1O(", startVideoBandwidth=", A0k, this.startVideoBandwidth);
        4YV.A1O(", startVideoTTFB=", A0k, this.startVideoTTFB);
        4YU.A1S(", videoBandwidthEstimateStr=", this.videoBandwidthEstimateStr, A0k);
        4YV.A1O(", upstreamTTFB=", A0k, this.upstreamTTFB);
        4YU.A1S(", tigonSessionId=", this.tigonSessionId, A0k);
        4YU.A1S(", tigonTransactionId=", this.tigonTransactionId, A0k);
        4YU.A1S(", appNetSesssionId=", this.appNetSessionId, A0k);
        4YV.A1O(", manifestFirstSegmentStartTs=", A0k, this.manifestFirstSegmentStartTs);
        4YV.A1O(", manifestLastSegmentEndTs=", A0k, this.manifestLastSegmentEndTs);
        4YV.A1O(", manifestNumSegments=", A0k, this.manifestNumSegments);
        6Cy.A00(", bufferedDurationMsAtDataSpecCreation=", A0k, this.bufferedDurationMsAtDataSpecCreation);
        4YV.A1O(", dataSpecCreationTimeMs=", A0k, this.dataSpecCreationTimeMs);
        4YU.A1S(", playSubOrigin=", this.playSubOrigin, A0k);
        4YV.A1P(", isFBMS=", A0k, this.isFBMS);
        4YV.A1P(", isFbPredictiveDASH=", A0k, this.isFbPredictiveDASH);
        4YV.A1P(", isSkipAheadChunk=", A0k, this.isSkipAheadChunk);
        4YV.A1P(", inRewoundState=", A0k, this.inRewoundState);
        4YV.A1P(", isManifestDynamic=", A0k, this.isManifestDynamic);
        4YV.A1P(", isChunkedTransfer=", A0k, this.isChunkedTransfer);
        4YV.A1P(", isPredictedURL=", A0k, this.isPredictedURL);
        6Cy.A00(", expectedPredictedNumber=", A0k, this.expectedPredictedNumber);
        6Cy.A00(", predictedNumberMapping=", A0k, this.predictedNumberMapping);
        4YV.A1O(", numSegmentsToEndOfManifest= ", A0k, this.numSegmentsToEndOfManifest);
        4YU.A1S(", edgeHit= ", this.edgeHit, A0k);
        4YU.A1S(", originHit= ", this.originHit, A0k);
        4YU.A1S(", codec= ", this.codec, A0k);
        4YV.A1O(", cdnResponseTime= ", A0k, this.cdnResponseTime);
        4YU.A1S(", contentType= ", this.contentType, A0k);
        6Cy.A00(", latestSegmentId= ", A0k, this.latestSegmentId);
        4YV.A1O(", confidenceBasedBitrateEstimate=", A0k, this.confidenceBasedBitrateEstimate);
        6Cy.A00(", confidencePctForBitrateEstimate=", A0k, this.confidencePctForBitrateEstimate);
        6Cy.A00(", minimumLoadPositionMs=", A0k, this.minimumLoadPositionMs);
        4YU.A1S(", oneReqWave=", this.oneReqWave, A0k);
        4YU.A1S(", oneResWave=", this.oneResWave, A0k);
        4YU.A1S(", oneObserved=", this.oneObserved, A0k);
        4YU.A1S(", oneVariant=", this.oneVariant, A0k);
        4YU.A1S(", playerType=", this.playerType, A0k);
        6Cy.A00(", positionInUnit=", A0k, this.positionInUnit);
        4YU.A1S(", vpSessionId=", this.vpSessionId, A0k);
        6Cy.A00(", firstChunkSize=", A0k, this.firstChunkSize);
        StringBuilder A0k2 = AnonymousClass001.A0k();
        A0k2.append(", clientWallClockOffsetMs=");
        A0k2.append(this.clientWallClockOffsetMs);
        1BK.A1R(A0k, A0k2);
        StringBuilder A0k3 = AnonymousClass001.A0k();
        A0k3.append(", contentLength=");
        A0k3.append(this.contentLength);
        1BK.A1R(A0k, A0k3);
        return A0k.toString();
    }
}
