package X;

import com.facebook.acra.constants.ActionId;
import com.facebook.forker.Process;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* renamed from: X.7hh, reason: invalid class name */
/* loaded from: 7hh.class */
public final class C7hh implements C07n {
    public static final /* synthetic */ C7hh[] A00;
    public final String mValue;

    static {
        C7hh[] c7hhArr = new C7hh[297];
        System.arraycopy(new C7hh[]{A00("FALLBACK", "fallback", 0), A00("PAGE_FEEDBACK_DO_NOT_USE", "page_feedback", 1), A00("XMA_PAGE_SHARE", "xma_page_share", 2), A00("XMA_ELEMENT_SHARE", "xma_element_share", 3), A00("XMA_PAYMENT", "xma_payment", 4), A00("XMA_GAME_PLAY", "xma_game_play", 5), A00("XMA_WEB_URL", "xma_web_url", 6), A00("XMA_EXTENSION", "xma_extension", 7), A00("XMA_POSTBACK", "xma_postback", 8), A00("XMA_OPEN_NATIVE", "xma_open_native", 9), A00("XMA_OPEN_DIALOG", "xma_open_dialog", 10), A00("XMA_FBPAY_OFFER_DETAIL", "xma_fbpay_offer_detail", 11), A00("XMA_REFERRAL_ACCEPT", "xma_referral_accept", 12), A00("XMA_REFERRAL_SEE_TERMS", "xma_referral_see_terms", 13), A00("XMA_REFERRAL_SEND_MONEY", "xma_referral_send_money", 14), A00("XMA_REFERRAL_SEE_DETAILS", "xma_referral_see_details", 15), A00("XMA_REFERRAL_INVITE_FRIENDS", "xma_referral_invite_friends", 16), A00("XMA_BRANDED_CAMERA", "xma_branded_camera", 17), A00("XMA_ACCOUNT_LINK", "xma_account_link", 18), A00("XMA_ACCOUNT_UNLINK", "xma_account_unlink", 19), A00("XMA_DIRECT_SEND", "xma_direct_send", 20), A00("XMA_FEEDBACK_SEND", "xma_feedback_send", 21), A00("XMA_LIVE_LOCATION_SHARING", "xma_live_location_sharing", 22), A00("XMA_STATIC_LOCATION_SHARING", "xma_static_location_sharing", 23), A00("XMA_SPONSORED_MESSAGE_WEB_URL", "xma_sponsored_message_web_url", 24), A00("XMA_SPONSORED_MESSAGE_POSTBACK", "xma_sponsored_message_postback", 25), A00("XMA_BIZ_INBOX_FORM_SEND", "xma_biz_inbox_form_send", 26)}, 0, c7hhArr, 0, 27);
        System.arraycopy(new C7hh[]{A00("XMA_RTC_AUDIO", "xma_rtc_audio", 27), A00("XMA_RTC_VIDEO", "xma_rtc_video", 28), A00("XMA_RTC_MISSED_AUDIO", "xma_rtc_missed_audio", 29), A00("XMA_RTC_MISSED_VIDEO", "xma_rtc_missed_video", 30), A00("XMA_RTC_MISSED_GROUP_AUDIO", "xma_rtc_missed_group_audio", 31), A00("XMA_RTC_MISSED_GROUP_VIDEO", "xma_rtc_missed_group_video", 32), A00("XMA_RTC_ENDED_AUDIO", "xma_rtc_ended_audio", 33), A00("XMA_RTC_ENDED_VIDEO", "xma_rtc_ended_video", 34), A00("XMA_RTC_NEW_AUDIO_DEFAULT", "xma_rtc_new_audio_default", 35), A00("XMA_RTC_NEW_VIDEO_DEFAULT", "xma_rtc_new_video_default", 36), A00("XMA_RTC_NEW_AUDIO_FROM_FB_SHARE", "xma_rtc_new_audio_from_fb_share", 37), A00("XMA_RTC_NEW_VIDEO_FROM_FB_SHARE", "xma_rtc_new_video_from_fb_share", 38), A00("XMA_RTC_NEW_AUDIO_FROM_FB_VIDEO_SHARE", "xma_rtc_new_audio_from_fb_video_share", 39), A00("XMA_RTC_NEW_VIDEO_FROM_FB_VIDEO_SHARE", "xma_rtc_new_video_from_fb_video_share", 40), A00("XMA_RTC_NEW_AUDIO_FROM_COWATCH_SHARE", "xma_rtc_new_audio_from_cowatch_share", 41), A00("XMA_RTC_NEW_VIDEO_FROM_COWATCH_SHARE", "xma_rtc_new_video_from_cowatch_share", 42), A00("XMA_RTC_COWATCH_START_VIDEO", "xma_rtc_cowatch_start_video", 43), A00("XMA_RTC_APPLY_EFFECT", "xma_rtc_apply_effect", 44), A00("XMA_FILE_URL", "xma_file_url", 45), A00("XMA_MONTAGE_SHARE", "xma_montage_share", 46), A00("XMA_RATE_SELLER", "xma_rate_seller", 47), A00("XMA_OPEN_RICH_WIDGET", "xma_open_rich_widget", 48), A00("XMA_POLL_DETAILS_CARD", "xma_poll_details_card", 49), A00("XMA_POLL_DETAILS_BUTTON", "xma_poll_details_button", 50), A00("XMA_JOIN_FROM_PORTAL", "xma_join_from_portal", 51), A00("XMA_JOIN_WITHOUT_VIDEO", "xma_join_without_video", 52), A00("XMA_IG_COMMENT_ACTION_URL", "xma_ig_comment_action_url", 53)}, 0, c7hhArr, 27, 27);
        System.arraycopy(new C7hh[]{A00("XMA_IG_PROMPT_ACTION_URL", "xma_ig_prompt_action_url", 54), A00("XMA_IG_COMMENT_MEDIA_ACTION_URL", "xma_ig_comment_media_action_url", 55), A00("XMA_CONSUMER_INBOX_ORDER_HISTORY", "xma_consumer_inbox_order_history", 56), A00("XMA_IG_VIEW_PROFILE", "xma_ig_view_profile", 57), A00("IGD_WEB_POST_SHARE", "igd_web_post_share", 58), A00("XMA_WORK_MEETINGS_ACCEPT", "xma_work_meetings_accept", 59), A00("XMA_WORK_MEETINGS_ALREADY_ACCEPTED", "xma_work_meetings_already_accepted", 60), A00("XMA_WORK_MEETINGS_DECLINE", "xma_work_meetings_decline", 61), A00("XMA_WORK_MEETINGS_ALREADY_DECLINED", "xma_work_meetings_already_declined", 62), A00("XMA_WORK_MEETINGS_MAYBE", "xma_work_meeting_maybe", 63), A00("XMA_WORK_MEETINGS_ALREADY_MAYBE", "xma_wokr_meeting_already_maybe", 64), A00("XMA_WORK_SHIFTS_VIEW_SHIFT_DETAILS", "xma_work_shifts_view_shift_details", 65), A00("XMA_WORK_SHIFTS_VIEW_POST", "xma_work_shifts_view_post", 66), A00("XMA_CTM_IN_THREAD_MULTIPHOTO_REPLY_IMAGE", "xma_ctm_in_thread_multiphoto_reply_image", 67), A00("XMA_SHOPS_PDP", "xma_shops_pdp", 68), A00("XMA_SHOPS_PRODUCT_VARIANT_PICKER", "xma_shops_product_variant_picker", 69), A00("MN_SHOPS_REQUEST_ORDER", "mn_shops_request_order", 70), A00("XMA_MERCHANT_CONFIRM_ORDER", "xma_merchant_confirm_order", 71), A00("XMA_VIEW_MESSENGER_CATALOG", "xma_view_messenger_catalog", 72), A00("XMA_OFFERS_VIEW_DETAILS", "xma_offers_view_details", 73), A00("XMA_OFFERS_BUY_NOW", "xma_offers_buy_now", 74), A00("XMAT_OFFERS_REMINDER_SUBSCRIBE", "xmat_offers_reminder_subscribe", 75), A00("XMAT_OFFERS_REMINDER_UNSUBSCRIBE", "xmat_offers_reminder_unsubscribe", 76), A00("XMAT_OFFERS_VIEW_OFFER", "xmat_offers_view_offer", 77), A00("XMA_OPEN_JOINTABLE_CALL_INVITE_URL", "xma_open_joinable_call_invite_url", 78), A00("XMA_ROOMS_SPEAKEASY_INVITE", "xma_rooms_speakeasy_invite", 79), A00("XMA_ROOMS_SPEAKEASY_INTERESTED", "xma_rooms_speakeasy_interested", 80)}, 0, c7hhArr, 54, 27);
        System.arraycopy(new C7hh[]{A00("XMA_ROOMS_SPEAKEASY_EDIT", "xma_rooms_speakeasy_edit", 81), A00("XMA_ROOMS_SPEAKEASY_EXPIRED", "xma_rooms_speakeasy_expired", 82), A00("XMA_ROOMS_SPEAKEASY_UNDO", "xma_rooms_speakeasy_undo", 83), A00("XMA_ROOMS_SPEAKEASY_CALLBACK", "xma_rooms_speakeasy_callback", 84), A00("XMA_SERVICES_CONFIRM_BOOKING", "xma_services_confirm_booking", 85), A00("XMA_SERVICES_RESCHEDULE_BOOKING", "xma_services_reschedule_booking", 86), A00("XMA_SERVICES_DECLINE_BOOKING", "xma_services_decline_booking", 87), A00("XMA_SERVICES_ADD_TO_CALENDAR", "xma_services_add_to_calendar", 88), A00("XMA_SERVICES_VIEW_APPOINTMENT_DETAILS", "xma_services_view_appointment_details", 89), A00("BOOKING_IG_USER_ADD_DETAILS", "booking_ig_user_add_details", 90), A00("BOOKING_IG_USER_VIEW_DETAILS", "booking_ig_user_view_details", 91), A00("BOOKING_IG_USER_VIEW_DETAILS_APPOINTMENT_CANCELLED", "booking_ig_user_view_details_appointment_cancelled", 92), A00("BOOKING_IG_BUSINESS_VIEW_APPOINTMENT_DETAILS", "booking_ig_business_view_appointment_details", 93), A00("BOOKING_IG_BUSINESS_VIEW_DETAILS_APPOINTMENT_CANCELLED", "booking_ig_business_view_details_appointment_cancelled", 94), A00("BOOKING_IG_VIEW_CALENDAR", "booking_ig_view_calendar", 95), A00("XMA_P2P_PAYMENT_DETAILS", "xma_p2p_payment_details", 96), A00("XMA_P2P_SHARED_PAYMENT_DETAILS", "xma_p2p_shared_payment_details", 97), A00("XMA_P2P_REQUEST_PAY", "xma_p2p_request_pay", 98), A00("XMA_P2P_PAYMENT_DETAILS_RECEIVE_MONEY", "xma_p2p_payment_details_receive_money", 99), A00("XMA_P2P_VERIFY_INFO", "xma_p2p_verify_info", 100), A00("XMA_P2M_CHECKOUT", "xma_p2m_checkout", ActionId.ON_VIEW_CREATED_END), A00("XMA_P2M_MARK_AS_PAID", "xma_p2m_mark_as_paid", ActionId.DATA_LOAD_START), A00("XMA_P2M_PAYMENT_DETAILS", "xma_p2m_payment_details", ActionId.LEGACY_MARKER), A00("XMA_P2M_PAYMENT_EDIT", "xma_p2m_payment_edit", ActionId.ACTION_BAR_COMPLETE), A00("XMA_P2M_ATTACH_RECEIPT", "xma_p2m_attach_receipt", ActionId.ABORTED), A00("XMA_P2M_OFFSITE_BANK_TRANSFER", "xma_p2m_offsite_bank_transfer", ActionId.QUERY_READY), A00("XMA_P2M_BUYER_SHIPPING", "xma_p2m_buyer_shipping", ActionId.RTMP_PACKET_RECEIVED)}, 0, c7hhArr, 81, 27);
        System.arraycopy(new C7hh[]{A00("XMA_P2M_INFORMATIONAL_MESSAGE_BOTTOM_SHEET", "xma_p2m_informational_message_bottom_sheet", 108), A00("XMA_P2M_PAYMENT_CONFIRMATION", "xma_p2m_payment_confirmation", ActionId.RTMP_CONNECTION_REQUESTED), A00("XMA_P2M_CREATE_ORDER", "xma_p2m_create_order", ActionId.RTMP_CONNECTION_RELEASE), A00("BANNER_P2M_CHECKOUT", "banner_p2m_checkout", ActionId.NEW_START_FOUND), A00("BANNER_P2M_LEARN_MORE", "banner_p2m_learn_more", ActionId.MISSED_EVENT), A00("BANNER_P2M_INFORMATIONAL_MESSAGE_BOTTOM_SHEET", "banner_p2m_informational_message_bottom_sheet", ActionId.TIMEOUT), A00("BANNER_P2M_BUYER_INITIATED_PAYMENT", "banner_p2m_buyer_initiated_payment", ActionId.CONTROLLER_INITIATED), A00("BANNER_P2M_CREATE_ORDER", "banner_p2m_create_order", ActionId.RTMP_STREAM_PREPARED), A00("BANNER_P2M_OFFSITE_BANK_TRANSFER", "banner_p2m_offsite_bank_transfer", ActionId.VIDEO_PLAYING), A00("BANNER_P2M_ATTACH_RECEIPT", "banner_p2m_attach_receipt", ActionId.RTMP_CONNECTION_CONNECTED), A00("BANNER_P2M_PAYMENT_DETECTION_CONFIRMATION", "banner_p2m_payment_detection_confirmation", ActionId.RTMP_CONNECTION_FAILED), A00("PAYMENT_TRANSACTION_DETAIL_ACCEPT_TO_PAY", "payment_txn_detail_accept_to_pay", ActionId.RTMP_CONNECTION_INTERCEPTED), A00("PAYMENT_TRANSACTION_DETAIL_DECLINE_TO_PAY", "payment_txn_detail_decline_to_pay", ActionId.VIDEO_SET_RENDERER_CONTEXT), A00("PAYMENT_TRANSACTION_DETAIL_CANCEL_REQUEST_TO_BE_PAID", "payment_txn_detail_cancel_request_to_be_paid", ActionId.HEADER_DATA_LOADED), A00("PAYMENT_TRANSACTION_DETAIL_ACCEPT_TO_RECEIVE", "payment_txn_detail_accept_to_receive", ActionId.CARD_DATA_LOADED), A00("PAYMENT_TRANSACTION_DETAIL_DECLINE_TO_RECEIVE", "payment_txn_detail_decline_to_receive", ActionId.VIEW_WILL_APPEAR_BEGIN), A00("PAYMENT_TRANSACTION_DETAIL_VIEW_GROUP_PAYMENT", "payment_txn_detail_view_group_payment", ActionId.VIEW_DID_LOAD_BEGIN), A00("QUICK_REPLY_TEXT", "quick_reply_text", 125), A00("QUICK_REPLY_LOCATION", "quick_reply_location", ActionId.COMPONENTS_DATA_SOURCE_DID_END_UPDATES), A00("QUICK_REPLY_AD", "quick_reply_ad", 127), A00("QUICK_REPLY_PHONE", "quick_reply_phone", 128), A00("QUICK_REPLY_EMAIL", "quick_reply_email", ActionId.MESSENGER_QUEUE_CREATION), A00("QUICK_REPLY_BIRTHDAY", "quick_reply_birthday", ActionId.APP_DID_FINISH_LAUNCHING), A00("QUICK_REPLY_STATE", "quick_reply_state", ActionId.APP_DID_BECOME_ACTIVE), A00("QUICK_REPLY_ZIP_CODE", "quick_reply_zip_code", ActionId.APP_WILL_ENTER_FOREGROUND), A00("FOCUS_MODE_EXIT", "focus_mode_exit", ActionId.APP_DID_ENTER_BACKGROUND), A00("MENU_NESTED", "menu_nested", ActionId.APP_MAIN)}, 0, c7hhArr, 108, 27);
        System.arraycopy(new C7hh[]{A00("MENU_PAGE_SHARE", "menu_page_share", ActionId.MQTT_CONNECTING), A00("MENU_ELEMENT_SHARE", "menu_element_share", ActionId.MQTT_CONNECTED), A00("MENU_PAYMENT", "menu_payment", ActionId.MQTT_DISCONNECTED), A00("MENU_GAME_PLAY", "menu_game_play", ActionId.MESSENGER_DELTA_REQUEST), A00("MENU_WEB_URL", "menu_web_url", ActionId.APP_FIRST_VIEW_CONTROLLER), A00("MENU_EXTENSION", "menu_extension", ActionId.MESSENGER_THREAD_LIST_LOADED), A00("MENU_POSTBACK", "menu_postback", ActionId.MESSENGER_THREAD_LIST_DISPLAYED), A00("MENU_PHONE_NUMBER", "menu_phone_number", ActionId.PREV_ACTIVITY_PAUSE), A00("MENU_OPEN_NATIVE", "menu_open_native", ActionId.ACTIVITY_RESUME), A00("MENU_BRANDED_CAMERA", "menu_branded_camera", ActionId.ACTIVITY_START), A00("NULLSTATE_POSTBACK", "nullstate_postback", ActionId.BEGIN_START_ACTIVITY), A00("NULLSTATE_ICEBREAKER", "nullstate_icebreaker", ActionId.END_START_ACTIVITY), A00("NULLSTATE_GAME", "nullstate_game", ActionId.FILE_SYSTEM_FAIL), A00("COMMUNITY_MESSAGING_ICEBREAKER", "community_messaging_ice_breaker", ActionId.FORMAT_ERROR), A00("MARKETPLACE_ICE_BREAKERS", "marketplace_ice_breakers", ActionId.PRIVACY_VIOLATION), A00("MARKETPLACE_SERVER_MUTATION", "marketplace_server_mutation", 150), A00("MARKETPLACE_BANNER_OPEN_NATIVE", "marketplace_banner_open_native", ActionId.POPULATE_CONSISTENCY_MEMORY_CACHE), A00("MARKETPLACE_MARK_AS_SOLD", "marketplace_mark_as_sold", ActionId.APPLY_OPTIMISTICS), A00("MARKETPLACE_MARK_AS_SOLD_SCALED", "marketplace_mark_as_sold_scaled", ActionId.APPLY_FINISHED_LIST), A00("MARKETPLACE_MARK_AS_SOLD_WITH_TXN_SURVEY", "marketplace_mark_as_sold_with_txn_survey", ActionId.APPLY_FINISHED_LIST_AGAIN), A00("MARKETPLACE_MARK_AS_SOLD_WITH_TXN_SURVEY_SCALED", "marketplace_mark_as_sold_with_txn_survey_scaled", ActionId.FUTURE_LISTENERS_COMPLETE), A00("MARKETPLACE_MARK_AS_SOLD_WITH_SELECT_BUYER", "marketplace_mark_as_sold_with_select_buyer", ActionId.SERVICE_ON_START_COMMAND), A00("MARKETPLACE_MARK_AS_SOLD_WITH_SELECT_BUYER_SCALED", "marketplace_mark_as_sold_with_select_buyer_scaled", ActionId.WAIT_FOR_BLOCKERS), A00("MARKETPLACE_MARK_AS_PENDING", "marketplace_mark_as_pending", ActionId.NOTIFY_SUBSCRIBERS), A00("MARKETPLACE_MARK_AS_AVAILABLE", "marketplace_mark_as_available", ActionId.FAIL_FILE_TOO_LARGE), A00("MARKETPLACE_MARK_AS_PAID", "marketplace_mark_as_paid", ActionId.OFFLINE), A00("MARKETPLACE_RATE_BUYER", "marketplace_rate_buyer", ActionId.ASNYC_FAILED)}, 0, c7hhArr, ActionId.MQTT_CONNECTING, 27);
        System.arraycopy(new C7hh[]{A00("MARKETPLACE_SCALED_RATE_BUYER", "marketplace_scaled_rate_buyer", ActionId.ASYNC_FAIL), A00("MARKETPLACE_RATE_SELLER", "marketplace_rate_seller", ActionId.ON_ATTACH_FRAGMENT), A00("MARKETPLACE_SCALED_RATE_SELLER", "marketplace_scaled_rate_seller", ActionId.VIEW_DID_APPEAR_BEGIN), A00("MARKETPLACE_REPORT_BUYER", "marketplace_report_buyer", ActionId.DISPLAYED), A00("MARKETPLACE_REPORT_SELLER", "marketplace_report_seller", ActionId.DISPLAYED_ON_SCREEN), A00("MARKETPLACE_SEE_DETAILS", "marketplace_see_details", ActionId.ASYNC_ACTION_SUCCESS), A00("MARKETPLACE_REQUEST_PAYMENT", "marketplace_request_payment", ActionId.ASYNC_ACTION_FAIL), A00("MARKETPLACE_SEND_PAYMENT", "marketplace_send_payment", ActionId.CONNECTIVITY_CHANGED), A00("MARKETPLACE_FIND_SIMILAR", "marketplace_find_similar", ActionId.VIDEO_DISPLAYED), A00("MARKETPLACE_MORE_OPTIONS", "marketplace_more_options", ActionId.VIDEO_REQUESTED_PLAYING), A00("MARKETPLACE_P2M_REQUEST_PAYMENT", "marketplace_p2m_request_payment", 172), A00("MARKETPLACE_CREATE_DOOR_EXCHANGE_PLAN", "marketplace_create_door_exchange_plan", 173), A00("MARKETPLACE_C2C_VIEW_ORDER", "marketplace_c2c_view_order", 174), A00("MARKETPLACE_RESERVE", "marketplace_reserve", 175), A00("MARKETPLACE_RESERVE_VIEW_DETAILS", "marketplace_reserve_view_details", 176), A00("MARKETPLACE_RESERVE_ACCEPT", "marketplace_reserve_accept", 177), A00("MARKETPLACE_RESERVE_MARK_AS_RECEIVED", "marketplace_reserve_mark_as_received", 178), A00("MARKETPLACE_RESERVE_MARK_AS_SOLD", "marketplace_reserve_mark_as_sold", 179), A00("MARKETPLACE_RESERVE_CANCEL_HOLD_REQUEST", "marketplace_reserve_cancel_hold_request", 180), A00("MARKETPLACE_RESERVE_CANCEL_HOLD", "marketplace_reserve_cancel_hold", 181), A00("MARKETPLACE_RESERVE_REQUEST_PAYMENT", "marketplace_reserve_request_payment", 182), A00("MARKETPLACE_RESERVE_FULFILL_PAYMENT", "marketplace_reserve_fulfill_payment", 183), A00("MARKETPLACE_RESERVE_NOTIFY_BUYERS", "marketplace_reserve_notify_buyers", 184), A00("MARKETPLACE_MESSAGE_SETTINGS", "marketplace_message_settings", 185), A00("MARKETPLACE_LABEL_CHAT", "marketplace_label_chat", 186), A00("MARKETPLACE_CREATE_TEST_DRIVE", "marketplace_create_test_drive", 187), A00("MARKETPLACE_CREATE_HOME_TOUR", "marketplace_create_home_tour", 188)}, 0, c7hhArr, ActionId.ASYNC_FAIL, 27);
        System.arraycopy(new C7hh[]{A00("MARKETPLACE_REQUEST_RATING", "marketplace_request_rating", 189), A00("MARKETPLACE_VIEW_PROFILE", "marketplace_view_profile", 190), A00("MARKETPLACE_CREATE_DISCOUNT", "marketplace_create_discount", 191), A00("LEAD_GEN_PAUSE_QUESTIONS", "lead_gen_pause_questions", 192), A00("MARKETPLACE_XMA_CALL_FUNCTION", "marketplace_xma_call_function", 193), A00("MARKETPLACE_XMA_OPEN_DIALOG", "marketplace_xma_open_dialog", 194), A00("ADMIN_MSG_MANAGE_AD", "admin_msg_manage_ad", 195), A00("ADMIN_MSG_WEB_URL", "admin_msg_web_url", 196), A00("ADMIN_MSG_P2B_USER_CONTROLS", "admin_msg_p2b_user_controls", 197), A00("ADMIN_MSG_EDIT_NICKNAME", "admin_msg_edit_nickname", 198), A00("ADMIN_MSG_NAME_GROUP", "admin_msg_name_group", 199), A00("ADMIN_MSG_POLL_CREATION", "admin_msg_poll_creation", 200), A00("ADMIN_MSG_POLL_DETAILS", "admin_msg_poll_details", 201), A00("ADMIN_MSG_WORKCHAT_REMINDER", "admin_msg_workchat_reminder", 202), A00("ADMIN_MSG_CHANGE_THEME", "admin_msg_change_theme", 203), A00("ADMIN_MSG_MAGIC_WORDS", "admin_msg_magic_words", 204), A00("ADMIN_MSG_RPC", "admin_msg_rpc", 205), A00("ADMIN_NOTIFICATION_MESSAGES_OPT_IN", "admin_notification_messages_opt_in", 206), A00("ADMIN_NOTIFICATION_MESSAGES_OPT_OUT", "admin_notification_messages_opt_out", 207), A00("ADMIN_MSG_VIEW_GROUP_LINK", "admin_msg_view_group_link", 208), A00("ADMIN_MSG_VIEW_PINNED_MESSAGES_V2", "admin_msg_view_pin_msgs_v2", 209), A00("ADMIN_MSG_ARMADILLO_EPHEMERAL_CHANGE_DURATION", "admin_msg_armadillo_ephemeral_change_duration", 210), A00("ADMIN_MSG_P2B_PRIVACY_DISCLOSURE", "admin_msg_p2b_privacy_disclosure", 211), A00("ADMIN_MSG_CHANGE_THEME_LOCATION", "admin_msg_change_theme_location", 212), A00("ADMIN_MSG_THREAD_LEVEL_CUTOVER", "admin_msg_thread_level_cutover", 213), A00("ADMIN_MSG_E2EE_THREAD", "admin_msg_e2ee_thread", 214), A00("ADMIN_MSG_CUTOVER_ROLLBACK", "admin_msg_cutover_rollback", 215)}, 0, c7hhArr, 189, 27);
        System.arraycopy(new C7hh[]{A00("ADMIN_MSG_SERVICE_BOOKING_LEGAL_DISCLAIMER", "admin_message_service_booking_legal_disclaimer", 216), A00("ADMIN_MSG_P2B_EDIT_BMO_SELLER_REVIEW", "admin_message_p2b_edit_bmo_seller_review", 217), A00("ADMIN_MSG_VIEW_CART", "admin_message_view_cart", 218), A00("SERVICES_BOOK_NOW", "services_book_now", 219), A00("SERVICES_REMIND_ME_LATER", "services_remind_me_later", 220), A00("SERVICES_VIEW_DETAILS", "services_view_details", 221), A00("SERVICES_PAYMENT_VIEW_DETAILS", "services_payment_view_details", 222), A00("INBOX_ADS_WEB_URL", "inbox_ads_web_url", 223), A00("INBOX_ADS_CTM", "inbox_ads_ctm", 224), A00("INBOX_ADS_OPEN_APP", "inbox_ads_open_app", 225), A00("INBOX_ADS_MEDIA_VIEWER", "inbox_ads_media_viewer", 226), A00("STORY_ADS_WEB_URL", "story_ads_web_url", 227), A00("ADS_NO_CTA", "ads_no_cta", 228), A00("STORY_ADS_OPEN_APP", "story_ads_open_app", 229), A00("STORY_ADS_CTM", "story_ads_ctm", 230), A00("GEMSTONE_THREAD_CREATION", "gemstone_thread_creation", 231), A00("GEMSTONE_CONTACT_SHARE_UPSELL", "gemstone_contact_share_upsell", 232), A00("GEMSTONE_MUTUAL_READY_TO_MEET", "gemstone_mutual_ready_to_meet", 233), A00("GEMSTONE_ADD_READY_TO_MEET_SINGLE_SIDED", "gemstone_add_ready_to_meet_single_sided", 234), A00("GEMSTONE_RECEIVED_COMPLIMENTS", "gemstone_received_compliments", 235), A00("GEMSTONE_REMOVE_READY_TO_MEET_SINGLE_SIDED", "gemstone_remove_ready_to_meet_single_sided", 236), new C7hh("GEMSTONE_SEND_COMPLIMENTS_PM_TRIGGER", 237, "GEMSTONE_SEND_COMPLIMENTS_PM_TRIGGER"), new C7hh("GEMSTONE_SOCIAL_BADGE_PM_TRIGGER", 238, "GEMSTONE_SOCIAL_BADGE_PM_TRIGGER"), A00("GEMSTONE_STALE_THREAD", "gemstone_stale_thread", 239), A00("GEMSTONE_WE_MET_PROMPT", "gemstone_we_met_prompt", 240), A00("GEMSTONE_WAVE_INITIATED", "gemstone_wave_initiated", 241), A00("GEMSTONE_WAVE_INITIATED_RECIPROCATED", "gemstone_wave_initiated_reciprocated", 242)}, 0, c7hhArr, 216, 27);
        System.arraycopy(new C7hh[]{A00("GEMSTONE_WAVE_RECIPROCATED", "gemstone_wave_reciprocated", 243), A00("GEMSTONE_MESSENGER_CONTACT_SHARE", "gemstone_messenger_contact_share", 244), A00("GEMSTONE_FACEBOOK_CONTACT_SHARE", "gemstone_facebook_contact_share", 245), A00("GEMSTONE_INSTAGRAM_CONTACT_SHARE", "gemstone_instagram_contact_share", 246), A00("GEMSTONE_CONVERSATION_STARTER_QUESTION", "gemstone_conversation_starter_question", 247), A00("GEMSTONE_CONVERSATION_STARTER_IMAGE", "gemstone_conversation_starter_image", 248), A00("GEMSTONE_AUDIO_CALL", "gemstone_audio_call", 249), A00("GEMSTONE_VIDEO_CALL", "gemstone_video_call", 250), A00("JOB_SEARCH_APPLY_NOW", "job_search_apply_now", Process.SD_STDOUT), A00("JOB_SEARCH_VIEW_APPLICATION", "job_search_view_application", Process.SD_PIPE), A00("JOB_SEARCH_VIEW_JOB_OPENING", "job_search_view_job_opening", Process.SD_BLACK_HOLE), A00("JOB_SEARCH_VIEW_PAGE", "job_search_view_page", 254), A00("JOB_SEARCH_GIVE_FEEDBACK", "job_search_give_feedback", 255), A00("MESSENGER_KIDS_PROFILE", "messenger_kids_account_profile", 256), A00("NEO_APPROVED_CONNECTION_ADDED", "neo_approved_connection_added", 257), A00("MESSENGER_KIDS_FOF_SETTING", "messenger_kids_fof_setting", 258), A00("GLOBAL_DELETE_MITIGATION_DISMISS", "global_delete_mitigation_dismiss", 259), A00("GLOBAL_DELETE_MITIGATION_LEARN_MORE", "global_delete_mitigation_learn_more", 260), A00("MESSENGER_PAYMENTS_ACCEPT_PENDING_PAYMENT", "messenger_payments_accept_pending_payments", 261), A00("MESSENGER_PAYMENTS_SEE_DETAIL", "messenger_payments_see_detail", 262), A00("PROACTIVE_WARNING_AFFIRMATIVE", "proactive_warning_affirmative", 263), A00("PROACTIVE_WARNING_NEGATIVE", "proactive_warning_negative", 264), A00("PROACTIVE_WARNING_DISMISS", "proactive_warning_dismiss", 265), A00("CTM_AD_CONTEXT", "ads_context", 266), A00("CTM_AD_CONTEXT_REINSTATED_DISMISS", "ads_context_reinstated_dismiss", 267), A00("CTM_AD_CONTEXT_CALL_CTA", "ctm_ad_context_call_cta", 268), A00("CTM_AD_CONTEXT_ORDERS_CTA", "ctm_ad_context_orders_cta", 269)}, 0, c7hhArr, 243, 27);
        System.arraycopy(new C7hh[]{A00("OCULUS_JOIN_PARTY", "oculus_join_party", 270), A00("IN_THREAD_BANNER_DISMISS", "in_thread_banner_dismiss", 271), A00("IN_THREAD_BANNER_CHEVRON", "in_thread_banner_chevron", 272), A00("NOVI_P2P_TXN_SEE_DETAILS", "novi_p2p_txn_see_details", 273), A00("NOVI_P2P_ACCEPT_INVITE", "novi_p2p_accept_invite", 274), A00("CONTACT_SHARING_MESSAGE", "contact_sharing_message", 275), A00("CONTACT_SHARING_PROFILE", "contact_sharing_profile", 276), A00("PORTAL_REFERRAL_SEE_DETAILS", "portal_referral_see_details", 277), A00("XMA_DISABLED_CTA", "xma_disabled_cta", 278), A00("XMA_CUSTOMER_INFORMATION", "xma_customer_information", 279), A00("XMA_FB_SHOPS_REFERRAL_DETAIL", "xma_fb_shops_referral_detail", 280), A00("XMA_BCP_PROJECT_DETAIL", "xma_bcp_project_detail", 281), A00("XMA_VIEW_EVENT", "xma_view_event", 282), A00("XMA_EVENT_RSVP", "xma_event_rsvp", 283), A00("XMAT_INSTANT_GAME_BOT_MESSAGE_SUBSCRIBE", "xmat_instant_game_bot_message_subscribe", 284), A00("XMAT_INSTANT_GAME_BOT_MESSAGE_UNSUBSCRIBE", "xmat_instant_game_bot_message_unsubscribe", 285), A00("XMA_VIEW_ACTIVITY_LOG", "xma_view_activity_log", 286), A00("XMA_AR_VIRTUAL_OBJECT", "xma_ar_virtual_object", 287), A00("XMAT_INSTANT_GAME_CUSTOM_UPDATE_MESSAGE_MUTE", "xmat_instant_game_custom_update_message_mute", 288), A00("XMAT_INSTANT_GAME_CUSTOM_UPDATE_MESSAGE_UNMUTE", "xmat_instant_game_custom_update_message_unmute", 289), A00("MEMBER_REQUEST", "member_requests_view", 290), A00("XMA_ADMOD_CHAT_MEMBER_REQUEST", "xma_admod_chat_member_request", 291), A00("XMA_ADMOD_CHAT_PENDING_POST", "xma_admod_chat_pending_post", 292), A00("XMA_IG_SUBS_REFERRAL_DETAIL", "xma_ig_subs_referral_detail", 293), A00("BIIM_AD_EXTENTER_BANNER", "biim_ad_extender_banner", 294), A00("BIIM_AD_EXTENDER_BANNER_VIEW_AD", "biim_ad_extender_banner_view_ad", 295), A00("BIIM_AD_EXTENDER_BANNER_EXTEND_AD", "biim_ad_extender_banner_extend_ad", 296)}, 0, c7hhArr, 270, 27);
        A00 = c7hhArr;
    }

    public C7hh(String str, int i, String str2) {
        this.mValue = str2;
    }

    public static C7hh A00(String str, String str2, int i) {
        return new C7hh(str, i, str2);
    }

    public static C7hh valueOf(String str) {
        return (C7hh) Enum.valueOf(C7hh.class, str);
    }

    public static C7hh[] values() {
        return (C7hh[]) A00.clone();
    }

    @Override // X.C07n
    public /* bridge */ /* synthetic */ Object getValue() {
        return this.mValue;
    }
}
