package X;

import com.facebook.acra.constants.ActionId;
import com.facebookpay.offsite.models.message.OffsiteInitAvailabilityRequestKt;
import com.facebookpay.offsite.models.message.PaymentDetailChangeTypes$Companion;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* renamed from: X.7hi, reason: invalid class name */
/* loaded from: 7hi.class */
public final class C7hi implements C07n {
    public static final /* synthetic */ C7hi[] A00;
    public static final C7hi A01;
    public final String mValue;

    static {
        C7hi[] c7hiArr = new C7hi[ActionId.ASYNC_ACTION_FAIL];
        C7hi A002 = A00(OffsiteInitAvailabilityRequestKt.DEFAULT_PARTNER_ID, "unknown", 0);
        A01 = A002;
        System.arraycopy(new C7hi[]{A002, A00("NEWSFEED", "newsfeed", 1), A00("USER_TIMELINE", "user_timeline", 2), A00("PAGE_TIMELINE", "page_timeline", 3), A00("PARENT_PAGE_TIMELINE", "parent_page_timeline", 4), A00("PERMALINK", "permalink", 5), A00("GROUP", "group", 6), A00("CONNECTED_TV", "connected_tv", 7), A00("CONNECTED_TV_DISCOVERY", "connected_tv_discovery", 8), A00("CONNECTED_TV_PLAYER", "connected_tv_player", 9), A00("CONNECTED_TV_PROFILE", "connected_tv_profile", 10), A00("CONNECTED_TV_CATALOG", "connected_tv_catalog", 11), A00("CONNECTED_TV_SAMSUNG_EDEN_TILE", "connected_tv_samsung_eden_tile", 12), A00("CONNECTED_TV_SAMSUNG_LC", "connected_tv_samsung_lc", 13), A00("CONNECTED_TV_SERIES", "connected_tv_series", 14), A00("SOCIAL_PLAYER", "social_player", 15), A00("VIDEO_DIRECT_APP", "video_direct_app", 16), A00("VIDEO_HOME", "video_home", 17), A00("VIDEO_HOME_FEED", "video_home_feed", 18), A00("VIDEO_HOME_REACTION", "video_home_reaction", 19), A00("VIDEO_HOME_MAIN", "video_home_main", 20), A00("VIDEO_HOME_GUIDE", "video_home_guide", 21), A00("VIDEO_TAB", "video_tab", 22), A00("EXTERNAL", "external", 23), A00("EXTERNAL_DEEPLINK", "external_deeplink", 24), A00("INSTANT_ARTICLES", "instant_articles", 25), A00("INTERN", "intern", 26)}, 0, c7hiArr, 0, 27);
        System.arraycopy(new C7hi[]{A00("INTEREST_SUBTOPIC_AGGREGATION", "interests_subtopic_aggregation", 27), A00("BACKSTAGE", "backstage", 28), A00("INSTANT_SHOPPING", "instant_shopping", 29), A00("REDSPACE", "redspace", 30), A00("SAVED", "saved", 31), A00("SEARCH", "search", 32), A00("NOTIFICATIONS", "notifications", 33), A00("LIVE_CONTROL_PANEL", "live_control_panel", 34), A00("LIVE_DISCOVERY", "live_discovery", 35), A00("LIVE_MAP", "live_map", 36), A00("LIVE_SHOPPING", "live_shopping", 37), A00("LIVE_REDIRECT", "live_redirect", 38), A00("LIVE_EMBED_REDIRECT", "live_embed_redirect", 39), A00("LOCAL_NEWS", "local_news", 40), A00("MOVIE_CHECKOUT_FLOW", "movie_checkout_flow", 41), A00("PAGES_MODULE", "pages_module", 42), A00("PAGES_VIDEO_TAB", "pages_video_tab", 43), A00("PAGES_LIVE_TAB", "pages_live_tab", 44), A00("BUSINESS_PAGE_VIDEO_EDUCATION_UNIT", "business_page_video_education_unit", 45), A00("BUSINESS_PAGE_VIDEO_EDUCATION_DIALOG", "business_page_video_education_dialog", 46), A00("PROMOTIONS_MANAGER_INSPIRATION_GALLERY", "promotions_manager_inspiration_gallery", 47), A00("BACKGROUND_PLAY", "background_play", 48), A00("QUICK_PROMOTION", "quick_promotion", 49), A00("CULTURAL_MOMENTS_SHARE", "cultural_moments_share", 50), A00("CULTURAL_MOMENTS_PROMOTION", "cm_promotion", 51), A00("DAILY_DIALOGUE_PINNED_UNIT", "dd_pinned", 52), A00("SPHERIAL_VIDEO_EDITING", "spherial_video_editing", 53)}, 0, c7hiArr, 27, 27);
        System.arraycopy(new C7hi[]{A00("EXPLORE_FEED", "explorefeed", 54), A00("RHC", "rhc", 55), A00("ADS", "ads", 56), A00("CANVAS", "canvas", 57), A00("COMMERCE", "commerce", 58), A00("COMPOSER", "composer", 59), A00("DASH", "dash", 60), A00("FACEWEB", "faceweb", 61), A00("FEEDBACK", "feedback", 62), A00("FRIENDS", "friends", 63), A00("EVENTS", "events", 64), A00("HELP", "help", 65), A00("INFRASTRUCTURE", "infrastructure", 66), A00("LOGIN", "login", 67), A00("MARKETING", "marketing", 68), A00("MESSAGING", "messaging", 69), A00("NAVIGATION", "navigation", 70), A00("PHOTOS", "photos", 71), A00("PRIVACY", "privacy", 72), A00("SETTINGS", "settings", 73), A00("SHOPPING", "shopping", 74), A00("STORY_VIEW", "story_view", 75), A00("WEBVIEW", "webview", 76), A00("TRENDING", "trending", 77), A00("FACECAST_NUX", "facecast_nux", 78), A00("PIXELCLOUD", "pixelcloud", 79), A00("PROTON", "proton", 80)}, 0, c7hiArr, 54, 27);
        System.arraycopy(new C7hi[]{A00("TAROT", "tarot", 81), A00("GAMEROOM", "gameroom", 82), A00("GAMES_VIDEO_CHANNEL", "games_video_channel", 83), A00("GAMES_VIDEO_HUB", "games_video_hub", 84), A00("LEARN", "learn", 85), A00("BEEPER", "beeper", 86), A00("FACECAST_BEEPER", "facecast_beeper", 87), A00("JOB_SEARCH", "job_search", 88), A00("TOP_LIVE_BOOKMARK", "top_live_bookmark", 89), A00("AUTODOWNLOAD", "autodownload", 90), A00("FB_STORIES", "fb_stories", 91), A00("DIRECT_INBOX", "direct_inbox", 92), A00("COMMENT", "comment", 93), A00("LIVE_VIDEO_END_SCREEN", "live_video_end_screen", 94), A00("MEDIA_GALLERY", "media_gallery", 95), A00("MEDIA_VIEWER", "media_viewer", 96), A00("MOMENTS", "moments", 97), A00("PHOTOSFEED", "photosfeed", 98), A00("SIMPLE_PICKER", "simple_picker", 99), A00("VIDEO_EDITING_GALLERY", "video_editing_gallery", 100), A00("ALBUM", "album", ActionId.ON_VIEW_CREATED_END), A00(PaymentDetailChangeTypes$Companion.OFFERS, "offers", ActionId.DATA_LOAD_START), A00("MESSENGER_THREAD", "messenger_thread", ActionId.LEGACY_MARKER), A00("MESSENGER_MONTAGE", "messenger_montage", ActionId.ACTION_BAR_COMPLETE), A00("MESSENGER_GIF", "messenger_gif", ActionId.ABORTED), A00("SHARED_VIDEO", "shared_video", ActionId.QUERY_READY), A00("VISUAL_POLL_GIF", "visual_poll_gif", ActionId.RTMP_PACKET_RECEIVED)}, 0, c7hiArr, 81, 27);
        System.arraycopy(new C7hi[]{A00("LIVING_ROOM", "living_room", 108), A00("LIVE_CHAINING", "live_chaining", ActionId.RTMP_CONNECTION_REQUESTED), A00("BRANDED_CONTENT", "branded_content", ActionId.RTMP_CONNECTION_RELEASE), A00("LIVING_ROOM_RECAP", "living_room_recap", ActionId.NEW_START_FOUND), A00("LIVING_ROOM_ADD_VIDEO", "living_room_add_video", ActionId.MISSED_EVENT), A00("POLITICAL_AD_ARCHIVE", "political_ad_archive", ActionId.TIMEOUT), A00("MESSENGER_ADS", "messenger_ads", ActionId.CONTROLLER_INITIATED), A00("VIDEO_PAGE_VIDEO_LIST", "video_page_video_list", ActionId.RTMP_STREAM_PREPARED), A00("HASHTAG_DISCOVERY", "hashtag_discovery", ActionId.VIDEO_PLAYING), A00("VIEW_ADS", "view_ads", ActionId.RTMP_CONNECTION_CONNECTED), A00("GAME_GROUP_RHC", "game_group_rhc", ActionId.RTMP_CONNECTION_FAILED), A00("GAME_PAGE_RHC", "game_page_rhc", ActionId.RTMP_CONNECTION_INTERCEPTED), A00("INTERN_CURATION", "intern_curation", ActionId.VIDEO_SET_RENDERER_CONTEXT), A00("SEARCH_VOYAGER", "search_voyager", ActionId.HEADER_DATA_LOADED), A00("KOTOTORO", "kototoro", ActionId.CARD_DATA_LOADED), A00("CMS", "cms", ActionId.VIEW_WILL_APPEAR_BEGIN), A00("PAGE_SPOTLIGHT", "page_spotlight", ActionId.VIEW_DID_LOAD_BEGIN), A00("PAGE_VIDEOS_TAB", "page_videos_tab", 125), A00("PAGE_VIDEOS_CARD", "page_videos_card", ActionId.COMPONENTS_DATA_SOURCE_DID_END_UPDATES), A00("PLAYLIST_PAGE", "playlist_page", 127), A00("PLAYLISTS_CARD", "playlists_card", 128), A00("PLAYLISTS_TAB", "playlists_tab", ActionId.MESSENGER_QUEUE_CREATION), A00("MESSENGER_STORY", "messenger_story", ActionId.APP_DID_FINISH_LAUNCHING), A00("GAMES_FEED", "games_feed", ActionId.APP_DID_BECOME_ACTIVE), A00("GAMES_TAB", "games_tab", ActionId.APP_WILL_ENTER_FOREGROUND), A00("GAMES_APP", "games_app", ActionId.APP_DID_ENTER_BACKGROUND), A00("GAMES_BOOKMARK", "games_bookmark", ActionId.APP_MAIN)}, 0, c7hiArr, 108, 27);
        System.arraycopy(new C7hi[]{A00("GAMES_ACTION_LINK", "games_action_links", ActionId.MQTT_CONNECTING), A00("GAMES_VIDEO_STREAMER_DASHBOARD", "games_video_streamer_dashboard", ActionId.MQTT_CONNECTED), A00("GAMES_VIDEO_CLIPS_HOME", "games_video_clips_home", ActionId.MQTT_DISCONNECTED), A00("GAMES_VIDEO_CLIPS_HOME_TOP_CLIPS", "games_video_clips_home_top_clips", ActionId.MESSENGER_DELTA_REQUEST), A00("GAMES_VIDEO_CLIPS_HOME_YOUR_CLIPS", "games_video_clips_home_your_clips", ActionId.APP_FIRST_VIEW_CONTROLLER), A00("GAMES_VIDEO_EXPLORE_HOME", "games_video_explore_home", ActionId.MESSENGER_THREAD_LIST_LOADED), A00("GAMEHUB", "gamehub", ActionId.MESSENGER_THREAD_LIST_DISPLAYED), A00("GAMES_STREAMER_HUB", "games_streamer_hub", ActionId.PREV_ACTIVITY_PAUSE), A00("WATCH_SUGGESTED_PAGES_QP", "watch_suggested_pages_qp", ActionId.ACTIVITY_RESUME), A00("WATCH_ORIGINALS_QP", "watch_originals_qp", ActionId.ACTIVITY_START), A00("VIDEO_CATALOG", "video_catalog", ActionId.BEGIN_START_ACTIVITY), A00("INTERACTIVE_POLL_CREATION_KIT", "interactive_poll_creation_kit", ActionId.END_START_ACTIVITY), A00("SERIES_CARD", "series_card", ActionId.FILE_SYSTEM_FAIL), A00("WAGER_SURFACE", "wager_surface", ActionId.FORMAT_ERROR), A00("PAGE_MUSIC_VIDEOS_SPOTLIGHT", "page_music_videos_spotlight", ActionId.PRIVACY_VIOLATION), A00("MUSIC_VIDEOS_TAB", "music_videos_tab", 150), new C7hi("LIVE_RHC", ActionId.POPULATE_CONSISTENCY_MEMORY_CACHE, "LIVE_RHC"), A00("THREAD", "thread", ActionId.APPLY_OPTIMISTICS), A00("LIVE_VIDEO_CUE", "live_video_cue", ActionId.APPLY_FINISHED_LIST), A00("RECOMMENDED_SHARE_TARGET_ANNOUNCEMENT", "recommended_share_target_announcement", ActionId.APPLY_FINISHED_LIST_AGAIN), A00("LIVE_MSITE", "live_msite", ActionId.FUTURE_LISTENERS_COMPLETE), A00("NATIVE_TEMPLATES", "native_templates", ActionId.SERVICE_ON_START_COMMAND), A00("LIVING_ROOM_DASHBOARD", "living_room_dashboard", ActionId.WAIT_FOR_BLOCKERS), A00("MUSIC_HOME", "music_home", ActionId.NOTIFY_SUBSCRIBERS), A00("NEWS_TAB", "news_tab", ActionId.FAIL_FILE_TOO_LARGE), A00("SHORT_FORM_VIDEO", "short_form_video", ActionId.OFFLINE), A00("PAGE_TIMELINE_LIVE_CARD", "page_timeline_live_card", ActionId.ASNYC_FAILED)}, 0, c7hiArr, ActionId.MQTT_CONNECTING, 27);
        System.arraycopy(new C7hi[]{A00("COWATCH", "cowatch", ActionId.ASYNC_FAIL), A00("DISCOVERY_HUBS", "discovery_hubs", ActionId.ON_ATTACH_FRAGMENT), A00("NOTIFICATIONS_SHOWS_FOLLOWER_NEW_EPISODE", "notifications_shows_follower_new_episode", ActionId.VIEW_DID_APPEAR_BEGIN), A00("NOTIFICATIONS_HEAVY_SAVE_REMINDER", "notifications_heavy_save_reminder", ActionId.DISPLAYED), A00("NOTIFICATIONS_WATCH_FOLLOWER_CAMPAIGN", "notifications_watch_follower_campaign", ActionId.DISPLAYED_ON_SCREEN), A00("SEARCH_VIDEO_HOME", "search_video_home", ActionId.ASYNC_ACTION_SUCCESS)}, 0, c7hiArr, ActionId.ASYNC_FAIL, 6);
        A00 = c7hiArr;
    }

    public C7hi(String str, int i, String str2) {
        this.mValue = str2;
    }

    public static C7hi A00(String str, String str2, int i) {
        return new C7hi(str, i, str2);
    }

    public static C7hi valueOf(String str) {
        return (C7hi) Enum.valueOf(C7hi.class, str);
    }

    public static C7hi[] values() {
        return (C7hi[]) A00.clone();
    }

    @Override // X.C07n
    public /* bridge */ /* synthetic */ Object getValue() {
        return this.mValue;
    }
}
