package X;

import com.facebook.bugreporter.core.model.BugReportExtraData;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import com.meta.flytrap.attachment.model.AttachmentCounter;
import com.meta.flytrap.attachment.model.BugReportAttachment;

/* loaded from: Er5.class */
public final class Er5 {
    public int A00;
    public int A01;
    public int A02;
    public EPO A03;
    public ImmutableList A04;
    public ImmutableList A05;
    public ImmutableList A06;
    public ImmutableMap A07;
    public ImmutableMap A08;
    public ImmutableMap A09;
    public ImmutableMap A0A;
    public BugReportAttachment A0B;
    public Boolean A0C;
    public String A0D;
    public String A0E;
    public String A0F;
    public String A0G;
    public String A0H;
    public String A0I;
    public String A0J;
    public String A0K;
    public String A0L;
    public String A0M;
    public String A0N;
    public String A0O;
    public String A0P;
    public String A0Q;
    public String A0R;
    public String A0S;
    public String A0T;
    public String A0U;
    public String A0V;
    public String A0W;
    public String A0X;
    public String A0Y;
    public String A0Z;
    public String A0a;
    public String A0b;
    public String A0c;
    public boolean A0d;
    public boolean A0e;
    public final BugReportExtraData A0f;
    public final AttachmentCounter A0g;
    public final AttachmentCounter A0h;
    public final AttachmentCounter A0i;
    public final AttachmentCounter A0j;
    public final String A0k;
    public final String A0l;
    public final boolean A0m;

    public Er5(BugReportExtraData bugReportExtraData, EPO epo, ImmutableList immutableList, ImmutableList immutableList2, ImmutableList immutableList3, ImmutableMap immutableMap, ImmutableMap immutableMap2, ImmutableMap immutableMap3, ImmutableMap immutableMap4, AttachmentCounter attachmentCounter, AttachmentCounter attachmentCounter2, AttachmentCounter attachmentCounter3, AttachmentCounter attachmentCounter4, BugReportAttachment bugReportAttachment, Boolean bool, String str, String str2, String str3, String str4, String str5, String str6, String str7, String str8, String str9, String str10, String str11, String str12, String str13, String str14, String str15, String str16, String str17, String str18, String str19, String str20, String str21, String str22, String str23, String str24, String str25, String str26, String str27, String str28, int i, int i2, int i3, boolean z, boolean z2, boolean z3) {
        this.A0W = str;
        this.A0H = str2;
        this.A0L = str3;
        this.A04 = immutableList;
        this.A06 = immutableList2;
        this.A0B = bugReportAttachment;
        this.A08 = immutableMap;
        this.A07 = immutableMap2;
        this.A05 = immutableList3;
        this.A0N = str4;
        this.A0I = str5;
        this.A0G = str6;
        this.A0M = str7;
        this.A0Q = str8;
        this.A0E = str9;
        this.A0F = str10;
        this.A0P = str11;
        this.A0U = str12;
        this.A0T = str13;
        this.A03 = epo;
        this.A09 = immutableMap3;
        this.A0e = z;
        this.A0J = str14;
        this.A0b = str15;
        this.A0D = str16;
        this.A0R = str17;
        this.A0V = str18;
        this.A0f = bugReportExtraData;
        this.A02 = i;
        this.A01 = i2;
        this.A00 = i3;
        this.A0S = str19;
        this.A0O = str20;
        this.A0K = str21;
        this.A0X = str22;
        this.A0Y = str23;
        this.A0a = str24;
        this.A0Z = str25;
        this.A0C = bool;
        this.A0A = immutableMap4;
        this.A0l = str26;
        this.A0d = z2;
        this.A0c = str27;
        this.A0k = str28;
        this.A0m = z3;
        this.A0g = attachmentCounter;
        this.A0h = attachmentCounter2;
        this.A0i = attachmentCounter3;
        this.A0j = attachmentCounter4;
    }
}
