package X;

import android.net.Uri;
import com.facebook.cameracore.ardelivery.model.ARRequestAsset;
import com.facebook.expression.effect.interactive.metadata.InteractiveEffectMetadata;
import com.facebook.messaging.montage.model.art.BaseItem;
import com.facebook.messaging.montage.model.art.EffectItem;
import com.facebook.messaging.montage.model.art.EffectMetaData;
import com.facebook.messaging.montage.model.montageattribution.MontageAttributionData;
import com.facebook.messaging.montage.model.previewvideo.EffectVideoPreviewData;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import com.google.common.collect.RegularImmutableMap;

/* loaded from: I0h.class */
public final class I0h {
    public double A00;
    public int A01;
    public int A02;
    public int A03;
    public long A04;
    public long A05;
    public long A06;
    public long A07;
    public Uri A08;
    public Uri A09;
    public Uri A0A;
    public Uri A0B;
    public Uri A0C;
    public Uri A0D;
    public Uri A0E;
    public Hpi A0F;
    public ARRequestAsset.CompressionMethod A0G;
    public InteractiveEffectMetadata A0H;
    public HC2 A0I;
    public H9C A0J;
    public EffectMetaData A0K;
    public HCR A0L;
    public MontageAttributionData A0M;
    public EffectVideoPreviewData A0N;
    public ImmutableList A0O;
    public ImmutableList A0P;
    public ImmutableList A0Q;
    public ImmutableList A0R;
    public ImmutableMap A0S;
    public ImmutableMap A0T;
    public String A0U;
    public String A0V;
    public String A0W;
    public String A0X;
    public String A0Y;
    public String A0Z;
    public String A0a;
    public String A0b;
    public String A0c;
    public String A0d;
    public String A0e;
    public String A0f;
    public String A0g;
    public String A0h;
    public String A0i;
    public String A0j;
    public String A0k;
    public String A0l;
    public String A0m;
    public String A0n;
    public String A0o;
    public String A0p;
    public String A0q;
    public String A0r;
    public boolean A0s;
    public boolean A0t;
    public boolean A0u;
    public boolean A0v;
    public boolean A0w;
    public boolean A0x;
    public boolean A0y;
    public boolean A0z;
    public boolean A10;
    public boolean A11;
    public boolean A12;
    public boolean A13;
    public boolean A14;
    public boolean A15;
    public boolean A16;
    public boolean A17;
    public boolean A18;
    public boolean A19;
    public boolean A1A;
    public boolean A1B;
    public boolean A1C;
    public boolean A1D;
    public boolean A1E;

    public I0h() {
        this.A0L = HCR.A0N;
        this.A0S = RegularImmutableMap.A03;
        long j = -1;
        this.A06 = j;
        this.A07 = j;
        this.A01 = 0;
    }

    public I0h(EffectItem effectItem) {
        this.A0L = HCR.A0N;
        this.A0S = RegularImmutableMap.A03;
        long j = -1;
        this.A06 = j;
        this.A07 = j;
        this.A01 = 0;
        this.A0r = ((BaseItem) effectItem).A09;
        this.A0b = effectItem.A0W;
        this.A0i = effectItem.A0d;
        this.A0I = ((BaseItem) effectItem).A03;
        this.A0D = ((BaseItem) effectItem).A02;
        this.A0A = ((BaseItem) effectItem).A01;
        this.A0E = effectItem.A0C;
        this.A08 = effectItem.A09;
        this.A0n = ((BaseItem) effectItem).A05;
        this.A0o = ((BaseItem) effectItem).A06;
        this.A0L = ((BaseItem) effectItem).A04;
        this.A0q = ((BaseItem) effectItem).A08;
        this.A0p = ((BaseItem) effectItem).A07;
        this.A0z = effectItem.A0p;
        this.A0y = effectItem.A0o;
        this.A0J = effectItem.A0G;
        this.A0c = effectItem.A0X;
        this.A0Y = effectItem.A0T;
        this.A0Z = effectItem.A0U;
        this.A0f = effectItem.A0a;
        this.A0l = effectItem.A0g;
        this.A0F = effectItem.A0D;
        this.A0Q = effectItem.A0M;
        this.A0S = effectItem.A0O;
        this.A0T = effectItem.A00;
        this.A14 = effectItem.A0u;
        this.A0H = effectItem.A0F;
        this.A0k = effectItem.A0f;
        this.A0j = effectItem.A0e;
        this.A0m = effectItem.A0h;
        this.A0h = effectItem.A0c;
        this.A06 = effectItem.A07;
        this.A07 = effectItem.A08;
        this.A0G = effectItem.A0E;
        this.A0R = effectItem.A0N;
        this.A0O = effectItem.A0K;
        this.A0K = effectItem.A0H;
        this.A0d = effectItem.A0Y;
        this.A0W = effectItem.A0R;
        this.A0v = effectItem.A0l;
        this.A1E = effectItem.A14;
        this.A1B = effectItem.A11;
        this.A1C = effectItem.A12;
        this.A1D = effectItem.A13;
        this.A19 = effectItem.A0z;
        this.A18 = effectItem.A0y;
        this.A17 = effectItem.A0x;
        this.A15 = effectItem.A0v;
        this.A1A = effectItem.A10;
        this.A16 = effectItem.A0w;
        this.A0X = effectItem.A0S;
        this.A0w = effectItem.A0m;
        this.A00 = effectItem.A01;
        this.A01 = effectItem.A02;
        this.A0g = effectItem.A0b;
        this.A0P = effectItem.A0L;
        this.A0M = effectItem.A0I;
        this.A0N = effectItem.A0J;
        this.A0s = effectItem.A0i;
        this.A12 = effectItem.A0s;
        this.A11 = effectItem.A0r;
        this.A10 = effectItem.A0q;
        this.A0u = effectItem.A0k;
        this.A0t = effectItem.A0j;
        this.A13 = effectItem.A0t;
        this.A0e = effectItem.A0Z;
        this.A0a = effectItem.A0V;
        this.A05 = effectItem.A06;
        this.A09 = ((BaseItem) effectItem).A00;
        this.A0x = effectItem.A0n;
        this.A0U = effectItem.A0P;
        this.A0B = effectItem.A0A;
        this.A0V = effectItem.A0Q;
        this.A04 = effectItem.A05;
        this.A03 = effectItem.A04;
        this.A02 = effectItem.A03;
        this.A0C = effectItem.A0B;
    }
}
