package X;

import com.facebook.proxygen.TraceFieldType;

/* renamed from: X.4wv, reason: invalid class name and case insensitive filesystem */
/* loaded from: 4wv.class */
public interface InterfaceC11574wv {
    public static final 4vP[] A00 = {new 4vP("_id", "INTEGER", (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, false, true, true, false, false), new 4vP(TraceFieldType.MsgId, "TEXT", (String) null, (String) null, (String) null, (String) null, "messages", TraceFieldType.MsgId, "NO ACTION", "CASCADE", true, false, false, false, false), new 4vP("poll_id", "TEXT", (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, true, false, false, false, false), new 4vP("style", "TEXT", (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, true, false, false, false, false), new 4vP("question_text", "TEXT", (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, true, false, false, false, false), new 4vP("url", "TEXT", (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, true, false, false, false, false), new 4vP("can_viewer_vote", "INTEGER", (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, true, false, false, false, false), new 4vP("bound_x", "REAL", (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, true, false, false, false, false), new 4vP("bound_y", "REAL", (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, true, false, false, false, false), new 4vP("bound_width", "REAL", (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, true, false, false, false, false), new 4vP("bound_height", "REAL", (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, true, false, false, false, false), new 4vP("bound_rotation", "REAL", (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, true, false, false, false, false), new 4vP("viewer_vote_index", "INTEGER", (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, true, false, false, false, false)};
    public static final 4vQ[] A01 = {new 4vQ(new String[]{"poll_id"}, new String[]{""}, true)};
}
