package X;

/* loaded from: KNP.class */
public enum KNP {
    CALL_ACTION,
    ANSWER_CALL_ACTION,
    END_CALL_ACTION,
    DECLINE_CALL_ACTION,
    GET_CALL_STATE_ACTION,
    CHECK_STATE_FOR_ENABLE_STELLA_ACTION,
    STELLA_OPT_IN_OUT_ACTION,
    CALL_ENGINE_DISPATCH_ACTION,
    SEND_MESSAGE_ACTION,
    MARK_THREAD_READ_ACTION,
    FETCH_UNREAD_MESSAGES_ACTION,
    FETCH_MESSAGE_AUDIO_ACTION,
    FETCH_MESSAGE_IMAGE_ACTION,
    FETCH_CONTACTS,
    FETCH_GROUPS,
    LOAD_THREADS,
    LOAD_MESSAGES,
    GET_CALL_HISTORY_ACTION,
    OPT_OUT_ACTION,
    FETCH_LOGS_ACTION,
    CONNECTED_USER_ACTIVE
}
