package X;

import com.facebook.composer.stories.camerarollinspiration.suggestions.model.SuggestionModel;
import com.facebook.composer.stories.camerarollinspiration.tryit.models.TryItSurfaceContext;
import com.facebook.events.story.ipc.EventsInspirationConfiguration;
import com.facebook.goodwill.ipc.GoodwillInspirationComposerLoggingParams;
import com.facebook.graphql.enums.GraphQLXFBCameraRollDataAccess;
import com.facebook.graphql.model.GraphQLTextWithEntities;
import com.facebook.groups.share.api.config.GroupInspirationConfiguration;
import com.facebook.inspiration.capture.multicapture.remix.model.InspirationRemixData;
import com.facebook.inspiration.model.InspirationMultiCaptureState;
import com.facebook.inspiration.model.InspirationPostAction;
import com.facebook.inspiration.model.InspirationVideoEditingData;
import com.facebook.inspiration.model.InspirationVideoTemplate;
import com.facebook.inspiration.model.SuggestionComponentModel;
import com.facebook.inspiration.model.movableoverlay.InspirationInitialTextToolTextParams;
import com.facebook.inspiration.model.movableoverlay.InspirationStickerParams;
import com.facebook.inspiration.reshare.ipc.ReshareToStoryMetadata;
import com.facebook.ipc.composer.model.RMSRecommendationData;
import com.facebook.ipc.facecast.config.FacecastConfiguration;
import com.facebook.ipc.inspiration.config.InspirationArAdsConfiguration;
import com.facebook.ipc.inspiration.config.InspirationCameraConfiguration;
import com.facebook.ipc.inspiration.config.InspirationConfiguration;
import com.facebook.ipc.inspiration.config.InspirationDraftTrackingInfo;
import com.facebook.ipc.inspiration.config.InspirationMultiCaptureReshootConfiguration;
import com.facebook.ipc.inspiration.config.InspirationNUXConfiguration;
import com.facebook.ipc.inspiration.config.InspirationStartReason;
import com.facebook.ipc.inspiration.config.InspirationStorySourceMetadata;
import com.facebook.ipc.inspiration.config.memories.InspirationThenAndNowModel;
import com.facebook.ipc.inspiration.config.platform.PlatformCameraShareConfiguration;
import com.facebook.ipc.inspiration.config.rms.InspirationRMSPlaceholderModel;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import com.google.common.collect.RegularImmutableMap;
import java.util.HashSet;
import java.util.Set;

/* loaded from: N4j.class */
public final class N4j {
    public int A00;
    public int A01;
    public int A02;
    public int A03;
    public int A04;
    public int A05;
    public long A06;
    public long A07;
    public long A08;
    public long A09;
    public SuggestionModel A0A;
    public TryItSurfaceContext A0B;
    public EventsInspirationConfiguration A0C;
    public GoodwillInspirationComposerLoggingParams A0D;
    public GraphQLXFBCameraRollDataAccess A0E;
    public GraphQLTextWithEntities A0F;
    public GraphQLTextWithEntities A0G;
    public GroupInspirationConfiguration A0H;
    public EnumC3488Mf7 A0I;
    public EnumC3488Mf7 A0J;
    public InspirationRemixData A0K;
    public ELz A0L;
    public MfV A0M;
    public InspirationMultiCaptureState A0N;
    public InspirationPostAction A0O;
    public InspirationVideoEditingData A0P;
    public InspirationVideoTemplate A0Q;
    public SuggestionComponentModel A0R;
    public InspirationInitialTextToolTextParams A0S;
    public InspirationStickerParams A0T;
    public ReshareToStoryMetadata A0U;
    public Qp5 A0V;
    public RMSRecommendationData A0W;
    public EPQ A0X;
    public FacecastConfiguration A0Y;
    public Qoc A0Z;
    public InspirationArAdsConfiguration A0a;
    public InspirationCameraConfiguration A0b;
    public EnumC3481Mez A0c;
    public EnumC3484Mf2 A0d;
    public EnumC3476Meu A0e;
    public InspirationDraftTrackingInfo A0f;
    public InspirationMultiCaptureReshootConfiguration A0g;
    public InspirationNUXConfiguration A0h;
    public InspirationStartReason A0i;
    public EnumC3482Mf0 A0j;
    public InspirationStorySourceMetadata A0k;
    public InspirationThenAndNowModel A0l;
    public PlatformCameraShareConfiguration A0m;
    public InspirationRMSPlaceholderModel A0n;
    public ImmutableList A0o;
    public ImmutableList A0p;
    public ImmutableList A0q;
    public ImmutableList A0r;
    public ImmutableList A0s;
    public ImmutableList A0t;
    public ImmutableList A0u;
    public ImmutableList A0v;
    public ImmutableList A0w;
    public ImmutableList A0x;
    public ImmutableList A0y;
    public ImmutableList A0z;
    public ImmutableList A10;
    public ImmutableMap A11;
    public Float A12;
    public Integer A13;
    public Long A14;
    public String A15;
    public String A16;
    public String A17;
    public String A18;
    public String A19;
    public String A1A;
    public String A1B;
    public String A1C;
    public String A1D;
    public String A1E;
    public String A1F;
    public String A1G;
    public String A1H;
    public String A1I;
    public String A1J;
    public String A1K;
    public String A1L;
    public String A1M;
    public String A1N;
    public String A1O;
    public String A1P;
    public String A1Q;
    public String A1R;
    public String A1S;
    public String A1T;
    public String A1U;
    public String A1V;
    public String A1W;
    public String A1X;
    public String A1Y;
    public String A1Z;
    public String A1a;
    public String A1b;
    public String A1c;
    public String A1d;
    public String A1e;
    public String A1f;
    public String A1g;
    public String A1h;
    public String A1i;
    public String A1j;
    public String A1k;
    public Set A1l;
    public boolean A1m;
    public boolean A1n;
    public boolean A1o;
    public boolean A1p;
    public boolean A1q;
    public boolean A1r;
    public boolean A1s;
    public boolean A1t;
    public boolean A1u;
    public boolean A1v;
    public boolean A1w;
    public boolean A1x;
    public boolean A1y;
    public boolean A1z;
    public boolean A20;
    public boolean A21;
    public boolean A22;
    public boolean A23;
    public boolean A24;
    public boolean A25;
    public boolean A26;
    public boolean A27;
    public boolean A28;
    public boolean A29;
    public boolean A2A;
    public boolean A2B;
    public boolean A2C;
    public boolean A2D;
    public boolean A2E;
    public boolean A2F;
    public boolean A2G;
    public boolean A2H;
    public boolean A2I;
    public boolean A2J;
    public boolean A2K;
    public boolean A2L;
    public boolean A2M;
    public boolean A2N;
    public boolean A2O;
    public boolean A2P;
    public boolean A2Q;
    public boolean A2R;
    public boolean A2S;
    public boolean A2T;
    public boolean A2U;
    public boolean A2V;
    public boolean A2W;
    public boolean A2X;
    public boolean A2Y;
    public boolean A2Z;
    public boolean A2a;
    public boolean A2b;
    public boolean A2c;
    public boolean A2d;
    public boolean A2e;
    public boolean A2f;
    public boolean A2g;
    public boolean A2h;
    public boolean A2i;
    public boolean A2j;
    public boolean A2k;
    public boolean A2l;
    public boolean A2m;
    public boolean A2n;
    public boolean A2o;
    public boolean A2p;
    public boolean A2q;
    public boolean A2r;
    public boolean A2s;
    public boolean A2t;
    public boolean A2u;
    public boolean A2v;
    public boolean A2w;
    public boolean A2x;
    public boolean A2y;
    public boolean A2z;
    public boolean A30;
    public boolean A31;
    public boolean A32;
    public boolean A33;
    public boolean A34;
    public boolean A35;
    public boolean A36;
    public boolean A37;
    public boolean A38;
    public boolean A39;
    public boolean A3A;
    public boolean A3B;
    public boolean A3C;
    public boolean A3D;
    public boolean A3E;
    public boolean A3F;
    public boolean A3G;
    public boolean A3H;
    public boolean A3I;
    public boolean A3J;
    public boolean A3K;
    public boolean A3L;
    public boolean A3M;
    public boolean A3N;
    public boolean A3O;
    public boolean A3P;
    public boolean A3Q;
    public boolean A3R;
    public boolean A3S;
    public boolean A3T;
    public boolean A3U;
    public boolean A3V;
    public boolean A3W;
    public boolean A3X;
    public boolean A3Y;
    public boolean A3Z;
    public boolean A3a;
    public boolean A3b;
    public boolean A3c;
    public boolean A3d;
    public boolean A3e;
    public boolean A3f;
    public boolean A3g;
    public boolean A3h;
    public boolean A3i;
    public boolean A3j;
    public boolean A3k;
    public boolean A3l;
    public boolean A3m;
    public boolean A3n;
    public boolean A3o;
    public boolean A3p;
    public boolean A3q;
    public boolean A3r;
    public boolean A3s;
    public boolean A3t;
    public boolean A3u;
    public boolean A3v;
    public boolean A3w;
    public boolean A3x;
    public boolean A3y;
    public boolean A3z;
    public boolean A40;
    public boolean A41;
    public boolean A42;
    public boolean A43;
    public boolean A44;
    public boolean A45;
    public boolean A46;
    public boolean A47;
    public boolean A48;
    public boolean A49;
    public boolean A4A;
    public boolean A4B;
    public boolean A4C;
    public boolean A4D;
    public boolean A4E;

    public N4j() {
        this.A1l = AnonymousClass001.A0v();
        this.A00 = -16777216;
        this.A1E = "CAMERA_SYSTEM";
        this.A0o = ImmutableList.of();
        this.A01 = 0;
        this.A1r = true;
        this.A1J = "slide_bottom_in";
        this.A1L = "";
        this.A0p = ImmutableList.of();
        this.A1P = "";
        this.A0r = ImmutableList.of();
        this.A0s = ImmutableList.of();
        this.A03 = -1;
        this.A0t = ImmutableList.of();
        this.A26 = true;
        this.A2B = true;
        this.A2C = true;
        this.A2E = true;
        this.A2G = true;
        this.A2H = true;
        this.A2Q = true;
        this.A2R = true;
        this.A2V = true;
        this.A2f = true;
        this.A2h = true;
        this.A2k = true;
        this.A2o = true;
        this.A2r = true;
        this.A2u = true;
        this.A30 = true;
        this.A31 = true;
        this.A35 = true;
        this.A39 = true;
        this.A3C = true;
        this.A3E = true;
        this.A3I = true;
        this.A06 = -1;
        this.A07 = 1000L;
        this.A09 = 3000L;
        this.A0x = ImmutableList.of();
        this.A11 = RegularImmutableMap.A03;
        this.A04 = 0;
        this.A3O = false;
        this.A3X = true;
        this.A3g = true;
        this.A3h = true;
        this.A3i = true;
        this.A3q = true;
        this.A3r = true;
        this.A3t = true;
        this.A46 = false;
    }

    public N4j(NAs nAs) {
        this.A1l = AnonymousClass001.A0v();
        nAs.getClass();
        if (nAs instanceof InspirationConfiguration) {
            InspirationConfiguration inspirationConfiguration = (InspirationConfiguration) nAs;
            A00(this, inspirationConfiguration);
            this.A1E = inspirationConfiguration.A1E;
            this.A0E = inspirationConfiguration.A0E;
            this.A0o = inspirationConfiguration.A0o;
            this.A1F = inspirationConfiguration.A1F;
            this.A1G = inspirationConfiguration.A1G;
            this.A0Z = inspirationConfiguration.A0Z;
            this.A0X = inspirationConfiguration.A0X;
            this.A1H = inspirationConfiguration.A1H;
            this.A1I = inspirationConfiguration.A1I;
            this.A01 = inspirationConfiguration.A01;
            this.A0I = inspirationConfiguration.A0I;
            this.A0J = inspirationConfiguration.A0J;
            this.A1q = inspirationConfiguration.A1q;
            this.A1r = inspirationConfiguration.A1r;
            this.A0f = inspirationConfiguration.A0f;
            this.A1s = inspirationConfiguration.A1s;
            this.A1t = inspirationConfiguration.A1t;
            this.A1J = inspirationConfiguration.A1J;
            this.A0C = inspirationConfiguration.A0C;
            this.A0Y = inspirationConfiguration.A0Y;
            this.A1K = inspirationConfiguration.A1K;
            this.A0D = inspirationConfiguration.A0D;
            this.A0H = inspirationConfiguration.A0H;
            this.A1L = inspirationConfiguration.A1L;
            this.A1M = inspirationConfiguration.A1M;
            this.A1u = inspirationConfiguration.A1u;
            this.A0p = inspirationConfiguration.A0p;
            this.A0q = inspirationConfiguration.A0q;
            this.A02 = inspirationConfiguration.A02;
            this.A1N = inspirationConfiguration.A1N;
            this.A0T = inspirationConfiguration.A0T;
            this.A1O = inspirationConfiguration.A1O;
            this.A1P = inspirationConfiguration.A1P;
            this.A0r = inspirationConfiguration.A0r;
            this.A0L = inspirationConfiguration.A0L;
            this.A0M = inspirationConfiguration.A0M;
            this.A1Q = inspirationConfiguration.A1Q;
            this.A0s = inspirationConfiguration.A0s;
            this.A1R = inspirationConfiguration.A1R;
            this.A03 = inspirationConfiguration.A03;
            this.A0K = inspirationConfiguration.A0K;
            this.A0F = inspirationConfiguration.A0F;
            this.A0G = inspirationConfiguration.A0G;
            this.A0S = inspirationConfiguration.A0S;
            this.A0P = inspirationConfiguration.A0P;
            this.A0t = inspirationConfiguration.A0t;
            this.A0a = inspirationConfiguration.A0a;
            this.A0b = inspirationConfiguration.A0b;
            this.A0u = inspirationConfiguration.A0u;
            this.A0g = inspirationConfiguration.A0g;
            this.A0N = inspirationConfiguration.A0N;
            this.A13 = inspirationConfiguration.A13;
            this.A0O = inspirationConfiguration.A0O;
            this.A0k = inspirationConfiguration.A0k;
            this.A0v = inspirationConfiguration.A0v;
            this.A0Q = inspirationConfiguration.A0Q;
            this.A12 = inspirationConfiguration.A12;
            this.A0c = inspirationConfiguration.A0c;
            A01(this, inspirationConfiguration);
            A06(this, inspirationConfiguration, inspirationConfiguration.A2G);
            A03(this, inspirationConfiguration, inspirationConfiguration.A2g);
            A05(this, inspirationConfiguration, inspirationConfiguration.A36);
            this.A0V = inspirationConfiguration.A0V;
            this.A3N = inspirationConfiguration.A3N;
            this.A1U = inspirationConfiguration.A1U;
            this.A1V = inspirationConfiguration.A1V;
            this.A0m = inspirationConfiguration.A0m;
            this.A1W = inspirationConfiguration.A1W;
            this.A1X = inspirationConfiguration.A1X;
            this.A0x = inspirationConfiguration.A0x;
            this.A1Y = inspirationConfiguration.A1Y;
            this.A1Z = inspirationConfiguration.A1Z;
            this.A11 = inspirationConfiguration.A11;
            this.A04 = inspirationConfiguration.A04;
            this.A0A = inspirationConfiguration.A0A;
            this.A1a = inspirationConfiguration.A1a;
            this.A1b = inspirationConfiguration.A1b;
            this.A1c = inspirationConfiguration.A1c;
            this.A1d = inspirationConfiguration.A1d;
            this.A0y = inspirationConfiguration.A0y;
            this.A0z = inspirationConfiguration.A0z;
            this.A0U = inspirationConfiguration.A0U;
            this.A0n = inspirationConfiguration.A0n;
            this.A0W = inspirationConfiguration.A0W;
            this.A1e = inspirationConfiguration.A1e;
            this.A10 = inspirationConfiguration.A10;
            this.A05 = inspirationConfiguration.A05;
            A02(this, inspirationConfiguration, inspirationConfiguration.A1f);
            A04(this, inspirationConfiguration, inspirationConfiguration.A3n);
            this.A0i = inspirationConfiguration.A0i;
            this.A0j = inspirationConfiguration.A0j;
            this.A1g = inspirationConfiguration.A1g;
            this.A0R = inspirationConfiguration.A0R;
            this.A0d = inspirationConfiguration.A0d;
            this.A1h = inspirationConfiguration.A1h;
            this.A1i = inspirationConfiguration.A1i;
            this.A0l = inspirationConfiguration.A0l;
            this.A0e = inspirationConfiguration.A0e;
            this.A0B = inspirationConfiguration.A0B;
            this.A4D = inspirationConfiguration.A4D;
            this.A1j = inspirationConfiguration.A1j;
            this.A1k = inspirationConfiguration.A1k;
            this.A4E = inspirationConfiguration.A4E;
            this.A1l = AbF.A1E(inspirationConfiguration.A1l);
            return;
        }
        InspirationConfiguration inspirationConfiguration2 = (InspirationConfiguration) nAs;
        A00(this, inspirationConfiguration2);
        String str = inspirationConfiguration2.A1E;
        this.A1E = str;
        C1pq.A08("cameraPostContextSource", str);
        this.A0E = inspirationConfiguration2.A0E;
        A0F(inspirationConfiguration2.A0o);
        this.A1F = inspirationConfiguration2.A1F;
        this.A1G = inspirationConfiguration2.A1G;
        this.A0Z = inspirationConfiguration2.A0Z;
        this.A0X = inspirationConfiguration2.A0X;
        this.A1H = inspirationConfiguration2.A1H;
        this.A1I = inspirationConfiguration2.A1I;
        this.A01 = inspirationConfiguration2.A01;
        this.A0I = inspirationConfiguration2.A0I;
        A08(nAs.Ah2());
        this.A1q = inspirationConfiguration2.A1q;
        this.A1r = inspirationConfiguration2.A1r;
        this.A0f = inspirationConfiguration2.A0f;
        this.A1s = inspirationConfiguration2.A1s;
        this.A1t = inspirationConfiguration2.A1t;
        A0K(inspirationConfiguration2.A1J);
        this.A0C = inspirationConfiguration2.A0C;
        this.A0Y = inspirationConfiguration2.A0Y;
        this.A1K = inspirationConfiguration2.A1K;
        this.A0D = inspirationConfiguration2.A0D;
        this.A0H = inspirationConfiguration2.A0H;
        String str2 = inspirationConfiguration2.A1L;
        this.A1L = str2;
        C1pq.A08("hashtagId", str2);
        this.A1M = inspirationConfiguration2.A1M;
        this.A1u = inspirationConfiguration2.A1u;
        ImmutableList immutableList = inspirationConfiguration2.A0p;
        this.A0p = immutableList;
        C1pq.A08("initialAddYoursTemplateOverlayParams", immutableList);
        this.A0q = inspirationConfiguration2.A0q;
        this.A02 = inspirationConfiguration2.A02;
        this.A1N = inspirationConfiguration2.A1N;
        this.A0T = inspirationConfiguration2.A0T;
        this.A1O = inspirationConfiguration2.A1O;
        A0L(inspirationConfiguration2.A1P);
        A0G(inspirationConfiguration2.A0r);
        A09(nAs.Aqe());
        A0A(nAs.Aqf());
        this.A1Q = inspirationConfiguration2.A1Q;
        ImmutableList immutableList2 = inspirationConfiguration2.A0s;
        this.A0s = immutableList2;
        C1pq.A08("initialMovableOverlayParams", immutableList2);
        this.A1R = inspirationConfiguration2.A1R;
        this.A03 = inspirationConfiguration2.A03;
        this.A0K = inspirationConfiguration2.A0K;
        this.A0F = inspirationConfiguration2.A0F;
        this.A0G = inspirationConfiguration2.A0G;
        this.A0S = inspirationConfiguration2.A0S;
        A0C(nAs.Aql());
        A0H(inspirationConfiguration2.A0t);
        this.A0a = inspirationConfiguration2.A0a;
        this.A0b = inspirationConfiguration2.A0b;
        A0I(nAs.ArB());
        this.A0g = inspirationConfiguration2.A0g;
        this.A0N = inspirationConfiguration2.A0N;
        this.A13 = inspirationConfiguration2.A13;
        A0B(nAs.ArF());
        this.A0k = inspirationConfiguration2.A0k;
        this.A0v = inspirationConfiguration2.A0v;
        this.A0Q = inspirationConfiguration2.A0Q;
        this.A12 = inspirationConfiguration2.A12;
        A0D(nAs.ArP());
        A01(this, inspirationConfiguration2);
        A06(this, inspirationConfiguration2, inspirationConfiguration2.A2G);
        A03(this, inspirationConfiguration2, inspirationConfiguration2.A2g);
        A05(this, inspirationConfiguration2, inspirationConfiguration2.A36);
        Qp5 B0J = nAs.B0J();
        this.A0V = B0J;
        C1pq.A08("openSoundSyncActionType", B0J);
        A07(this, "openSoundSyncActionType");
        this.A3N = inspirationConfiguration2.A3N;
        this.A1U = inspirationConfiguration2.A1U;
        this.A1V = inspirationConfiguration2.A1V;
        this.A0m = inspirationConfiguration2.A0m;
        this.A1W = inspirationConfiguration2.A1W;
        this.A1X = inspirationConfiguration2.A1X;
        ImmutableList immutableList3 = inspirationConfiguration2.A0x;
        this.A0x = immutableList3;
        C1pq.A08("preAppliedEffects", immutableList3);
        this.A1Y = inspirationConfiguration2.A1Y;
        this.A1Z = inspirationConfiguration2.A1Z;
        ImmutableMap immutableMap = inspirationConfiguration2.A11;
        this.A11 = immutableMap;
        C1pq.A08("previouslySelectedMedia", immutableMap);
        this.A04 = inspirationConfiguration2.A04;
        this.A0A = inspirationConfiguration2.A0A;
        this.A1a = inspirationConfiguration2.A1a;
        this.A1b = inspirationConfiguration2.A1b;
        this.A1c = inspirationConfiguration2.A1c;
        this.A1d = inspirationConfiguration2.A1d;
        this.A0y = inspirationConfiguration2.A0y;
        A0J(nAs.B7d());
        this.A0U = inspirationConfiguration2.A0U;
        this.A0n = inspirationConfiguration2.A0n;
        this.A0W = inspirationConfiguration2.A0W;
        this.A1e = inspirationConfiguration2.A1e;
        this.A10 = inspirationConfiguration2.A10;
        this.A05 = inspirationConfiguration2.A05;
        A02(this, inspirationConfiguration2, inspirationConfiguration2.A1f);
        A04(this, inspirationConfiguration2, inspirationConfiguration2.A3n);
        A0E(nAs.BBz());
        EnumC3482Mf0 BC5 = nAs.BC5();
        this.A0j = BC5;
        C1pq.A08("startingMode", BC5);
        A07(this, "startingMode");
        this.A1g = inspirationConfiguration2.A1g;
        this.A0R = inspirationConfiguration2.A0R;
        this.A0d = inspirationConfiguration2.A0d;
        this.A1h = inspirationConfiguration2.A1h;
        this.A1i = inspirationConfiguration2.A1i;
        this.A0l = inspirationConfiguration2.A0l;
        EnumC3476Meu BGx = nAs.BGx();
        this.A0e = BGx;
        C1pq.A08("trashUnificationSupportEnabledEntryPoint", BGx);
        A07(this, "trashUnificationSupportEnabledEntryPoint");
        this.A0B = inspirationConfiguration2.A0B;
        this.A4D = inspirationConfiguration2.A4D;
        this.A1j = inspirationConfiguration2.A1j;
        this.A1k = inspirationConfiguration2.A1k;
        this.A4E = inspirationConfiguration2.A4E;
    }

    public static void A00(N4j n4j, InspirationConfiguration inspirationConfiguration) {
        n4j.A15 = inspirationConfiguration.A15;
        n4j.A1m = inspirationConfiguration.A1m;
        n4j.A1n = inspirationConfiguration.A1n;
        n4j.A1o = inspirationConfiguration.A1o;
        n4j.A16 = inspirationConfiguration.A16;
        n4j.A17 = inspirationConfiguration.A17;
        n4j.A18 = inspirationConfiguration.A18;
        n4j.A19 = inspirationConfiguration.A19;
        n4j.A1p = inspirationConfiguration.A1p;
        n4j.A1A = inspirationConfiguration.A1A;
        n4j.A1B = inspirationConfiguration.A1B;
        n4j.A00 = inspirationConfiguration.A00;
        n4j.A1C = inspirationConfiguration.A1C;
        n4j.A1D = inspirationConfiguration.A1D;
    }

    public static void A01(N4j n4j, InspirationConfiguration inspirationConfiguration) {
        n4j.A1v = inspirationConfiguration.A1v;
        n4j.A1w = inspirationConfiguration.A1w;
        n4j.A1x = inspirationConfiguration.A1x;
        n4j.A1y = inspirationConfiguration.A1y;
        n4j.A1z = inspirationConfiguration.A1z;
        n4j.A20 = inspirationConfiguration.A20;
        n4j.A21 = inspirationConfiguration.A21;
        n4j.A22 = inspirationConfiguration.A22;
        n4j.A23 = inspirationConfiguration.A23;
        n4j.A24 = inspirationConfiguration.A24;
        n4j.A25 = inspirationConfiguration.A25;
        n4j.A26 = inspirationConfiguration.A26;
        n4j.A27 = inspirationConfiguration.A27;
        n4j.A28 = inspirationConfiguration.A28;
        n4j.A29 = inspirationConfiguration.A29;
        n4j.A2A = inspirationConfiguration.A2A;
        n4j.A2B = inspirationConfiguration.A2B;
        n4j.A2C = inspirationConfiguration.A2C;
        n4j.A2D = inspirationConfiguration.A2D;
        n4j.A2E = inspirationConfiguration.A2E;
        n4j.A2F = inspirationConfiguration.A2F;
    }

    public static void A02(N4j n4j, InspirationConfiguration inspirationConfiguration, String str) {
        n4j.A1f = str;
        n4j.A3O = inspirationConfiguration.A3O;
        n4j.A3P = inspirationConfiguration.A3P;
        n4j.A3Q = inspirationConfiguration.A3Q;
        n4j.A3R = inspirationConfiguration.A3R;
        n4j.A3S = inspirationConfiguration.A3S;
        n4j.A3T = inspirationConfiguration.A3T;
        n4j.A3U = inspirationConfiguration.A3U;
        n4j.A3V = inspirationConfiguration.A3V;
        n4j.A3W = inspirationConfiguration.A3W;
        n4j.A3X = inspirationConfiguration.A3X;
        n4j.A3Y = inspirationConfiguration.A3Y;
        n4j.A3Z = inspirationConfiguration.A3Z;
        n4j.A3a = inspirationConfiguration.A3a;
        n4j.A3b = inspirationConfiguration.A3b;
        n4j.A3c = inspirationConfiguration.A3c;
        n4j.A3d = inspirationConfiguration.A3d;
        n4j.A3e = inspirationConfiguration.A3e;
        n4j.A3f = inspirationConfiguration.A3f;
        n4j.A3g = inspirationConfiguration.A3g;
        n4j.A3h = inspirationConfiguration.A3h;
        n4j.A3i = inspirationConfiguration.A3i;
        n4j.A3j = inspirationConfiguration.A3j;
        n4j.A3k = inspirationConfiguration.A3k;
        n4j.A3l = inspirationConfiguration.A3l;
        n4j.A3m = inspirationConfiguration.A3m;
    }

    public static void A03(N4j n4j, InspirationConfiguration inspirationConfiguration, boolean z) {
        n4j.A2g = z;
        n4j.A2h = inspirationConfiguration.A2h;
        n4j.A2i = inspirationConfiguration.A2i;
        n4j.A2j = inspirationConfiguration.A2j;
        n4j.A2k = inspirationConfiguration.A2k;
        n4j.A2l = inspirationConfiguration.A2l;
        n4j.A2m = inspirationConfiguration.A2m;
        n4j.A2n = inspirationConfiguration.A2n;
        n4j.A2o = inspirationConfiguration.A2o;
        n4j.A2p = inspirationConfiguration.A2p;
        n4j.A2q = inspirationConfiguration.A2q;
        n4j.A2r = inspirationConfiguration.A2r;
        n4j.A2s = inspirationConfiguration.A2s;
        n4j.A2t = inspirationConfiguration.A2t;
        n4j.A2u = inspirationConfiguration.A2u;
        n4j.A2v = inspirationConfiguration.A2v;
        n4j.A2w = inspirationConfiguration.A2w;
        n4j.A2x = inspirationConfiguration.A2x;
        n4j.A2y = inspirationConfiguration.A2y;
        n4j.A2z = inspirationConfiguration.A2z;
        n4j.A30 = inspirationConfiguration.A30;
        n4j.A31 = inspirationConfiguration.A31;
        n4j.A32 = inspirationConfiguration.A32;
        n4j.A33 = inspirationConfiguration.A33;
        n4j.A34 = inspirationConfiguration.A34;
        n4j.A35 = inspirationConfiguration.A35;
    }

    public static void A04(N4j n4j, InspirationConfiguration inspirationConfiguration, boolean z) {
        n4j.A3n = z;
        n4j.A3o = inspirationConfiguration.A3o;
        n4j.A3p = inspirationConfiguration.A3p;
        n4j.A3q = inspirationConfiguration.A3q;
        n4j.A3r = inspirationConfiguration.A3r;
        n4j.A3s = inspirationConfiguration.A3s;
        n4j.A3t = inspirationConfiguration.A3t;
        n4j.A3u = inspirationConfiguration.A3u;
        n4j.A3v = inspirationConfiguration.A3v;
        n4j.A3w = inspirationConfiguration.A3w;
        n4j.A3x = inspirationConfiguration.A3x;
        n4j.A3y = inspirationConfiguration.A3y;
        n4j.A3z = inspirationConfiguration.A3z;
        n4j.A40 = inspirationConfiguration.A40;
        n4j.A41 = inspirationConfiguration.A41;
        n4j.A42 = inspirationConfiguration.A42;
        n4j.A43 = inspirationConfiguration.A43;
        n4j.A44 = inspirationConfiguration.A44;
        n4j.A45 = inspirationConfiguration.A45;
        n4j.A46 = inspirationConfiguration.A46;
        n4j.A47 = inspirationConfiguration.A47;
        n4j.A48 = inspirationConfiguration.A48;
        n4j.A49 = inspirationConfiguration.A49;
        n4j.A4A = inspirationConfiguration.A4A;
        n4j.A4B = inspirationConfiguration.A4B;
        n4j.A4C = inspirationConfiguration.A4C;
    }

    public static void A05(N4j n4j, InspirationConfiguration inspirationConfiguration, boolean z) {
        n4j.A36 = z;
        n4j.A37 = inspirationConfiguration.A37;
        n4j.A38 = inspirationConfiguration.A38;
        n4j.A39 = inspirationConfiguration.A39;
        n4j.A3A = inspirationConfiguration.A3A;
        n4j.A3B = inspirationConfiguration.A3B;
        n4j.A3C = inspirationConfiguration.A3C;
        n4j.A3D = inspirationConfiguration.A3D;
        n4j.A3E = inspirationConfiguration.A3E;
        n4j.A3F = inspirationConfiguration.A3F;
        n4j.A3G = inspirationConfiguration.A3G;
        n4j.A3H = inspirationConfiguration.A3H;
        n4j.A3I = inspirationConfiguration.A3I;
        n4j.A3J = inspirationConfiguration.A3J;
        n4j.A3K = inspirationConfiguration.A3K;
        n4j.A3L = inspirationConfiguration.A3L;
        n4j.A3M = inspirationConfiguration.A3M;
        n4j.A06 = inspirationConfiguration.A06;
        n4j.A14 = inspirationConfiguration.A14;
        n4j.A1S = inspirationConfiguration.A1S;
        n4j.A07 = inspirationConfiguration.A07;
        n4j.A08 = inspirationConfiguration.A08;
        n4j.A09 = inspirationConfiguration.A09;
        n4j.A0w = inspirationConfiguration.A0w;
        n4j.A1T = inspirationConfiguration.A1T;
        n4j.A0h = inspirationConfiguration.A0h;
    }

    public static void A06(N4j n4j, InspirationConfiguration inspirationConfiguration, boolean z) {
        n4j.A2G = z;
        n4j.A2H = inspirationConfiguration.A2H;
        n4j.A2I = inspirationConfiguration.A2I;
        n4j.A2J = inspirationConfiguration.A2J;
        n4j.A2K = inspirationConfiguration.A2K;
        n4j.A2L = inspirationConfiguration.A2L;
        n4j.A2M = inspirationConfiguration.A2M;
        n4j.A2N = inspirationConfiguration.A2N;
        n4j.A2O = inspirationConfiguration.A2O;
        n4j.A2P = inspirationConfiguration.A2P;
        n4j.A2Q = inspirationConfiguration.A2Q;
        n4j.A2R = inspirationConfiguration.A2R;
        n4j.A2S = inspirationConfiguration.A2S;
        n4j.A2T = inspirationConfiguration.A2T;
        n4j.A2U = inspirationConfiguration.A2U;
        n4j.A2V = inspirationConfiguration.A2V;
        n4j.A2W = inspirationConfiguration.A2W;
        n4j.A2X = inspirationConfiguration.A2X;
        n4j.A2Y = inspirationConfiguration.A2Y;
        n4j.A2Z = inspirationConfiguration.A2Z;
        n4j.A2a = inspirationConfiguration.A2a;
        n4j.A2b = inspirationConfiguration.A2b;
        n4j.A2c = inspirationConfiguration.A2c;
        n4j.A2d = inspirationConfiguration.A2d;
        n4j.A2e = inspirationConfiguration.A2e;
        n4j.A2f = inspirationConfiguration.A2f;
    }

    public static void A07(N4j n4j, String str) {
        if (n4j.A1l.contains(str)) {
            return;
        }
        HashSet A1E = AbF.A1E(n4j.A1l);
        n4j.A1l = A1E;
        A1E.add(str);
    }

    public void A08(EnumC3488Mf7 enumC3488Mf7) {
        this.A0J = enumC3488Mf7;
        C1pq.A08("defaultOpenTrayInPostCaptureWhenOtherTraysAreDismissed", enumC3488Mf7);
        A07(this, "defaultOpenTrayInPostCaptureWhenOtherTraysAreDismissed");
    }

    public void A09(ELz eLz) {
        this.A0L = eLz;
        C1pq.A08("initialFormType", eLz);
        A07(this, "initialFormType");
    }

    public void A0A(MfV mfV) {
        this.A0M = mfV;
        C1pq.A08("initialFormatMode", mfV);
        A07(this, "initialFormatMode");
    }

    public void A0B(InspirationPostAction inspirationPostAction) {
        this.A0O = inspirationPostAction;
        C1pq.A08("inspirationPostAction", inspirationPostAction);
        A07(this, "inspirationPostAction");
    }

    public void A0C(InspirationVideoEditingData inspirationVideoEditingData) {
        this.A0P = inspirationVideoEditingData;
        C1pq.A08("initialVideoEditingData", inspirationVideoEditingData);
        A07(this, "initialVideoEditingData");
    }

    public void A0D(EnumC3481Mez enumC3481Mez) {
        this.A0c = enumC3481Mez;
        C1pq.A08("instagramCrossPostingState", enumC3481Mez);
        A07(this, "instagramCrossPostingState");
    }

    public void A0E(InspirationStartReason inspirationStartReason) {
        this.A0i = inspirationStartReason;
        C1pq.A08("startReason", inspirationStartReason);
        A07(this, "startReason");
    }

    public void A0F(ImmutableList immutableList) {
        this.A0o = immutableList;
        C1pq.A08("capturedMedia", immutableList);
    }

    public void A0G(ImmutableList immutableList) {
        this.A0r = immutableList;
        C1pq.A08("initialEffects", immutableList);
    }

    public void A0H(ImmutableList immutableList) {
        this.A0t = immutableList;
        C1pq.A08("initialVideoSegments", immutableList);
    }

    public void A0I(ImmutableList immutableList) {
        this.A0u = immutableList;
        C1pq.A08("inspirationFormTypes", immutableList);
        A07(this, "inspirationFormTypes");
    }

    public void A0J(ImmutableList immutableList) {
        this.A0z = immutableList;
        C1pq.A08("requiredStyleCategories", immutableList);
        A07(this, "requiredStyleCategories");
    }

    public void A0K(String str) {
        this.A1J = str;
        C1pq.A08("entryAnimationType", str);
    }

    public void A0L(String str) {
        this.A1P = str;
        C1pq.A08("initialComposerSessionId", str);
    }
}
