package com.facebook.video.engine.api;

import X.0Pz;
import X.0S2;
import X.11T;
import X.1BL;
import X.4YW;
import X.6A8;
import X.6Ch;
import X.6Cl;
import X.6TA;
import X.6TX;
import X.6VJ;
import X.82N;
import X.AnonymousClass001;
import X.AnonymousClass243;
import X.C03353xs;
import X.HBk;
import android.os.Parcel;
import android.os.ParcelFormatException;
import android.os.Parcelable;
import androidx.media.AudioAttributesCompat;
import androidx.versionedparcelable.ParcelImpl;
import com.facebook.graphql.enums.GraphQLVideoBroadcastInfraType;
import com.facebook.graphql.enums.GraphQLVideoBroadcastStatus;
import com.facebook.spherical.video.model.SphericalVideoParams;
import com.facebook.video.heroplayer.ipc.AudioFocusLossSettings;
import com.google.common.collect.ImmutableMap;
import java.io.IOException;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Map;

/* loaded from: VideoPlayerParams.class */
public final class VideoPlayerParams implements Parcelable, 6A8 {
    public static final Parcelable.Creator CREATOR = new 82N(17);
    public boolean A00;
    public final double A01;
    public final double A02;
    public final double A03;
    public final float A04;
    public final int A05;
    public final int A06;
    public final int A07;
    public final int A08;
    public final int A09;
    public final int A0A;
    public final int A0B;
    public final int A0C;
    public final int A0D;
    public final int A0E;
    public final int A0F;
    public final int A0G;
    public final int A0H;
    public final int A0I;
    public final int A0J;
    public final int A0K;
    public final int A0L;
    public final int A0M;
    public final int A0N;
    public final int A0O;
    public final long A0P;
    public final long A0Q;
    public final AudioAttributesCompat A0R;
    public final GraphQLVideoBroadcastInfraType A0S;
    public final GraphQLVideoBroadcastStatus A0T;
    public final SphericalVideoParams A0U;
    public final VideoDataSource A0V;
    public final 6Ch A0W;
    public final AudioFocusLossSettings A0X;
    public final C03353xs A0Y;
    public final 6Cl A0Z;
    public final ImmutableMap A0a;
    public final Boolean A0b;
    public final String A0c;
    public final String A0d;
    public final String A0e;
    public final String A0f;
    public final String A0g;
    public final String A0h;
    public final String A0i;
    public final String A0j;
    public final String A0k;
    public final List A0l;
    public final boolean A0m;
    public final boolean A0n;
    public final boolean A0o;
    public final boolean A0p;
    public final boolean A0q;
    public final boolean A0r;
    public final boolean A0s;
    public final boolean A0t;
    public final boolean A0u;
    public final boolean A0v;
    public final boolean A0w;
    public final boolean A0x;
    public final boolean A0y;
    public final boolean A0z;
    public final boolean A10;
    public final boolean A11;
    public final boolean A12;
    public final boolean A13;
    public final boolean A14;
    public final boolean A15;
    public final boolean A16;
    public final boolean A17;
    public final boolean A18;
    public final boolean A19;
    public final boolean A1A;
    public final boolean A1B;
    public final boolean A1C;
    public final boolean A1D;
    public final boolean A1E;
    public final boolean A1F;
    public final boolean A1G;
    public final boolean A1H;
    public final boolean A1I;
    public final boolean A1J;
    public final boolean A1K;
    public final boolean A1L;
    public final boolean A1M;
    public final boolean A1N;
    public final boolean A1O;
    public final boolean A1P;
    public final boolean A1Q;
    public final boolean A1R;
    public final boolean A1S;
    public final boolean A1T;
    public final boolean A1U;
    public final boolean A1V;
    public final boolean A1W;
    public final boolean A1X;
    public final boolean A1Y;
    public final boolean A1Z;
    public final boolean A1a;
    public final boolean A1b;
    public final boolean A1c;
    public final boolean A1d;
    public final boolean A1e;
    public final boolean A1f;
    public final boolean A1g;
    public final boolean A1h;
    public final boolean A1i;
    public final boolean A1j;
    public final boolean A1k;
    public final boolean A1l;
    public final boolean A1m;
    public final boolean A1n;
    public final boolean A1o;

    public VideoPlayerParams(6TA r302) {
        this.A0V = r302.A0U;
        this.A0k = r302.A0i;
        int i = r302.A0L;
        this.A0M = i;
        this.A04 = r302.A03;
        this.A0j = r302.A0h;
        this.A0Y = r302.A0X;
        this.A1N = r302.A1R;
        this.A1g = r302.A1h;
        this.A0J = r302.A0I;
        this.A0B = r302.A0A;
        this.A12 = r302.A0w;
        this.A0z = r302.A0t;
        this.A1J = r302.A1K;
        this.A0c = r302.A0a;
        this.A0b = r302.A0Z;
        this.A1F = r302.A1G;
        this.A1G = r302.A1H;
        this.A1A = r302.A1A;
        this.A16 = r302.A10;
        this.A1I = r302.A1J;
        this.A0E = r302.A0D;
        this.A1D = r302.A1D;
        this.A1P = r302.A1T;
        this.A19 = r302.A19;
        this.A0P = r302.A0O;
        this.A0Q = r302.A0P;
        this.A0T = r302.A0S;
        this.A05 = r302.A05;
        this.A0U = r302.A0T;
        this.A1C = r302.A1C;
        this.A1b = r302.A0k;
        this.A0K = r302.A0J;
        int i2 = r302.A04;
        this.A0A = i2 <= 0 ? i : i2;
        this.A09 = r302.A09;
        this.A08 = r302.A08;
        this.A0D = r302.A0C;
        this.A1f = r302.A1g;
        this.A0y = r302.A0s;
        this.A1Q = r302.A1V;
        this.A1j = r302.A1j;
        this.A1k = r302.A1k;
        this.A1B = r302.A1B;
        this.A0L = r302.A0K;
        this.A1M = r302.A1Q;
        this.A06 = r302.A06;
        this.A0W = r302.A0V;
        ImmutableMap copyOf = ImmutableMap.copyOf(r302.A1n);
        11T.A0A(copyOf);
        this.A0a = copyOf;
        this.A11 = r302.A0v;
        this.A10 = r302.A0u;
        this.A1H = r302.A1I;
        this.A13 = r302.A0x;
        this.A1T = r302.A1L;
        this.A1L = r302.A1N;
        this.A1c = r302.A0l;
        this.A1l = r302.A0n;
        this.A1o = r302.A0o;
        this.A0f = r302.A0d;
        this.A0I = r302.A0H;
        this.A0H = r302.A0G;
        this.A1Z = r302.A1d;
        this.A0d = r302.A0b;
        this.A07 = r302.A07;
        this.A0R = r302.A0Q;
        this.A00 = r302.A0p;
        this.A1R = r302.A1W;
        this.A17 = r302.A17;
        this.A0e = r302.A0c;
        this.A1K = false;
        this.A0x = r302.A0r;
        this.A1e = r302.A1f;
        this.A0S = r302.A0R;
        this.A03 = r302.A02;
        this.A0F = r302.A0E;
        this.A0G = r302.A0F;
        this.A1O = r302.A1S;
        this.A0X = r302.A0W;
        this.A1a = r302.A1O;
        this.A15 = r302.A0z;
        this.A0C = r302.A0B;
        this.A14 = r302.A0y;
        this.A1d = r302.A1e;
        this.A1i = r302.A1i;
        this.A1E = r302.A1F;
        this.A0N = r302.A0M;
        this.A0O = r302.A0N;
        this.A0h = r302.A0f;
        this.A1V = r302.A1Z;
        this.A1W = r302.A1a;
        this.A1X = r302.A1b;
        this.A1Y = r302.A1c;
        this.A1m = r302.A1l;
        this.A0w = r302.A0q;
        this.A1n = r302.A1m;
        this.A1U = r302.A1Y;
        this.A0g = r302.A0e;
        this.A0s = r302.A16;
        this.A0m = r302.A11;
        this.A0r = r302.A15;
        this.A0Z = r302.A0Y;
        this.A0u = r302.A1P;
        this.A1h = r302.A0m;
        this.A0i = r302.A0g;
        this.A01 = r302.A00;
        this.A02 = r302.A01;
        this.A0o = r302.A13;
        this.A0n = r302.A12;
        this.A0q = r302.A14;
        this.A0v = r302.A1U;
        this.A0l = r302.A0j;
        this.A0t = r302.A1M;
        this.A18 = r302.A18;
        this.A0p = r302.A1E;
        this.A1S = r302.A1X;
    }

    public VideoPlayerParams(Parcel parcel) {
        String str;
        AudioAttributesCompat audioAttributesCompat;
        try {
            C03353xs A0I = AnonymousClass243.A00().A0I(parcel.readString());
            11T.A0I(A0I, "null cannot be cast to non-null type com.fasterxml.jackson.databind.node.ArrayNode");
            this.A0Y = A0I;
            this.A0V = (VideoDataSource) 1BL.A0C(parcel, VideoDataSource.class);
            String readString = parcel.readString();
            str = "";
            this.A0k = readString == null ? str : readString;
            this.A0M = parcel.readInt();
            this.A04 = parcel.readFloat();
            String readString2 = parcel.readString();
            this.A0j = readString2 != null ? readString2 : "";
            boolean z = true;
            this.A1N = AnonymousClass001.A1N(parcel.readByte());
            this.A1F = 4YW.A0K(parcel);
            this.A1G = 4YW.A0K(parcel);
            this.A1A = 4YW.A0K(parcel);
            this.A0x = 4YW.A0K(parcel);
            this.A16 = 4YW.A0K(parcel);
            this.A1I = 4YW.A0K(parcel);
            this.A0E = parcel.readInt();
            this.A1D = 4YW.A0K(parcel);
            this.A1P = 4YW.A0K(parcel);
            this.A19 = 4YW.A0K(parcel);
            this.A0P = parcel.readLong();
            this.A0Q = parcel.readLong();
            String readString3 = parcel.readString();
            this.A0T = readString3 != null ? GraphQLVideoBroadcastStatus.valueOf(readString3) : GraphQLVideoBroadcastStatus.UNSET_OR_UNRECOGNIZED_ENUM_VALUE;
            this.A1g = 4YW.A0K(parcel);
            this.A0J = parcel.readInt();
            this.A0B = parcel.readInt();
            this.A05 = parcel.readInt();
            this.A0U = (SphericalVideoParams) 1BL.A0C(parcel, SphericalVideoParams.class);
            this.A1C = 4YW.A0K(parcel);
            this.A1b = 4YW.A0K(parcel);
            this.A11 = 4YW.A0K(parcel);
            this.A10 = 4YW.A0K(parcel);
            this.A0K = parcel.readInt();
            this.A0A = parcel.readInt();
            this.A09 = parcel.readInt();
            this.A08 = parcel.readInt();
            this.A0D = parcel.readInt();
            this.A1f = 4YW.A0K(parcel);
            this.A12 = 4YW.A0K(parcel);
            this.A0z = 4YW.A0K(parcel);
            this.A1J = 4YW.A0K(parcel);
            this.A0c = parcel.readString();
            this.A0b = AnonymousClass001.A1N(parcel.readByte()) ? Boolean.valueOf(4YW.A0K(parcel)) : null;
            this.A0y = 4YW.A0K(parcel);
            this.A1Q = 4YW.A0K(parcel);
            this.A1j = 4YW.A0K(parcel);
            this.A1k = 4YW.A0K(parcel);
            this.A1B = 4YW.A0K(parcel);
            this.A0L = parcel.readInt();
            this.A1M = 4YW.A0K(parcel);
            this.A06 = parcel.readInt();
            6Ch r0 = 6Ch.values()[parcel.readInt()];
            11T.A0A(r0);
            this.A0W = r0;
            this.A1H = 4YW.A0K(parcel);
            this.A13 = 4YW.A0K(parcel);
            this.A1T = 4YW.A0K(parcel);
            this.A1L = 4YW.A0K(parcel);
            this.A1c = 4YW.A0K(parcel);
            this.A1l = 4YW.A0K(parcel);
            this.A1o = 4YW.A0K(parcel);
            this.A0I = parcel.readInt();
            this.A0H = parcel.readInt();
            if (parcel.readByte() != 0) {
                this.A0f = parcel.readString();
            } else {
                this.A0f = null;
            }
            this.A1Z = 4YW.A0K(parcel);
            this.A0d = parcel.readString();
            this.A0a = null;
            this.A07 = parcel.readInt();
            Parcelable A0C = 1BL.A0C(parcel, AudioAttributesCompat.class);
            if (A0C == null) {
                audioAttributesCompat = null;
            } else {
                if (!(A0C instanceof ParcelImpl)) {
                    throw AnonymousClass001.A0L("Invalid parcel");
                }
                audioAttributesCompat = (AudioAttributesCompat) ((ParcelImpl) A0C).A00;
            }
            this.A0R = audioAttributesCompat;
            this.A00 = 4YW.A0K(parcel);
            this.A1R = 4YW.A0K(parcel);
            this.A17 = 4YW.A0K(parcel);
            this.A0e = parcel.readString();
            this.A1K = 4YW.A0K(parcel);
            this.A1e = 4YW.A0K(parcel);
            String readString4 = parcel.readString();
            this.A0S = readString4 != null ? GraphQLVideoBroadcastInfraType.valueOf(readString4) : GraphQLVideoBroadcastInfraType.UNSET_OR_UNRECOGNIZED_ENUM_VALUE;
            this.A03 = parcel.readDouble();
            this.A0F = parcel.readInt();
            this.A0G = parcel.readInt();
            this.A1O = 4YW.A0K(parcel);
            AudioFocusLossSettings audioFocusLossSettings = (AudioFocusLossSettings) 1BL.A0C(parcel, AudioFocusLossSettings.class);
            this.A0X = audioFocusLossSettings == null ? new AudioFocusLossSettings() : audioFocusLossSettings;
            this.A1a = 4YW.A0K(parcel);
            this.A15 = 4YW.A0K(parcel);
            this.A0C = parcel.readInt();
            this.A14 = 4YW.A0K(parcel);
            this.A1d = 4YW.A0K(parcel);
            this.A1i = 4YW.A0K(parcel);
            this.A1E = 4YW.A0K(parcel);
            this.A0O = parcel.readInt();
            this.A0N = parcel.readInt();
            this.A0h = parcel.readString();
            this.A1V = 4YW.A0K(parcel);
            this.A1W = 4YW.A0K(parcel);
            this.A1X = 4YW.A0K(parcel);
            this.A1Y = 4YW.A0K(parcel);
            this.A1U = 4YW.A0K(parcel);
            this.A0g = parcel.readString();
            this.A0s = 4YW.A0K(parcel);
            this.A0m = 4YW.A0K(parcel);
            this.A0r = 4YW.A0K(parcel);
            this.A0Z = null;
            this.A0l = Collections.emptyList();
            this.A0u = 4YW.A0K(parcel);
            this.A1h = 4YW.A0K(parcel);
            this.A1m = 4YW.A0K(parcel);
            this.A0w = 4YW.A0K(parcel);
            this.A0i = parcel.readString();
            this.A1n = 4YW.A0K(parcel);
            this.A01 = parcel.readDouble();
            this.A02 = parcel.readDouble();
            this.A0o = 4YW.A0K(parcel);
            this.A0n = 4YW.A0K(parcel);
            this.A0q = 4YW.A0K(parcel);
            this.A0v = 4YW.A0K(parcel);
            this.A0t = 4YW.A0K(parcel);
            this.A0p = 4YW.A0K(parcel);
            this.A18 = 4YW.A0K(parcel);
            this.A1S = parcel.readByte() == 0 ? false : z;
        } catch (IOException e) {
            throw new ParcelFormatException(AnonymousClass001.A0Z(e, "Failed to process event ", AnonymousClass001.A0k()));
        }
    }

    public VideoPlayerParams(GraphQLVideoBroadcastInfraType graphQLVideoBroadcastInfraType, GraphQLVideoBroadcastStatus graphQLVideoBroadcastStatus, SphericalVideoParams sphericalVideoParams, VideoDataSource videoDataSource, 6Ch r306, AudioFocusLossSettings audioFocusLossSettings, C03353xs c03353xs, String str, String str2, String str3, String str4, String str5, List list, Map map, int i, int i2, int i3, int i4, int i5, int i6, int i7, long j, long j2, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10, boolean z11, boolean z12, boolean z13, boolean z14, boolean z15, boolean z16, boolean z17, boolean z18, boolean z19) {
        this.A0V = videoDataSource;
        this.A0k = str5;
        this.A0M = i7;
        this.A04 = 1.0f;
        this.A0j = "";
        this.A0Y = c03353xs;
        this.A1N = false;
        this.A1g = false;
        this.A0J = i6;
        this.A0B = i2;
        this.A12 = z3;
        this.A0z = z2;
        this.A1J = z14;
        this.A0c = str;
        this.A0b = null;
        this.A1F = z10;
        this.A1G = z11;
        this.A1A = z7;
        this.A16 = z5;
        this.A1I = z13;
        this.A0E = i5;
        this.A1D = z8;
        this.A1P = z18;
        this.A19 = z6;
        this.A0P = j;
        this.A0Q = j2;
        this.A0T = graphQLVideoBroadcastStatus;
        this.A05 = i;
        this.A0U = sphericalVideoParams;
        this.A1C = false;
        this.A1b = false;
        this.A0K = 0;
        this.A0A = i7;
        this.A09 = -1;
        this.A08 = -1;
        this.A0D = i4;
        this.A1f = false;
        this.A0y = false;
        this.A1Q = false;
        this.A1j = z19;
        this.A1k = false;
        this.A1B = false;
        this.A0L = -1;
        this.A1M = z17;
        this.A06 = 2;
        this.A0W = r306;
        ImmutableMap copyOf = ImmutableMap.copyOf(map);
        11T.A0A(copyOf);
        this.A0a = copyOf;
        this.A11 = false;
        this.A10 = false;
        this.A1H = z12;
        this.A13 = z4;
        this.A1T = false;
        this.A1L = z16;
        this.A1c = false;
        this.A1l = false;
        this.A1o = false;
        this.A0f = str3;
        this.A0I = -1;
        this.A0H = -1;
        this.A1Z = true;
        this.A0d = str2;
        this.A07 = 0;
        this.A0R = null;
        this.A00 = false;
        this.A1R = false;
        this.A17 = false;
        this.A0e = null;
        this.A1K = z15;
        this.A0x = z;
        this.A1e = false;
        this.A0S = graphQLVideoBroadcastInfraType;
        this.A03 = 0.0d;
        this.A0F = -1;
        this.A0G = -1;
        this.A1O = false;
        this.A0X = audioFocusLossSettings;
        this.A1a = false;
        this.A15 = false;
        this.A0C = i3;
        this.A14 = false;
        this.A1d = false;
        this.A1i = false;
        this.A1E = z9;
        this.A0N = 0;
        this.A0O = 0;
        this.A0h = str4;
        this.A1V = false;
        this.A1W = false;
        this.A1X = false;
        this.A1Y = false;
        this.A1m = false;
        this.A0w = false;
        this.A1n = false;
        this.A1U = false;
        this.A0g = null;
        this.A0s = false;
        this.A0m = false;
        this.A0r = false;
        this.A0Z = null;
        this.A0u = false;
        this.A1h = false;
        this.A0i = "";
        this.A01 = 0.0d;
        this.A02 = 0.0d;
        this.A0o = false;
        this.A0n = false;
        this.A0q = false;
        this.A0v = false;
        this.A0l = list;
        this.A0t = false;
        this.A18 = false;
        this.A0p = false;
        this.A1S = false;
    }

    public VideoPlayerParams(GraphQLVideoBroadcastInfraType graphQLVideoBroadcastInfraType, GraphQLVideoBroadcastStatus graphQLVideoBroadcastStatus, VideoDataSource videoDataSource, 6Ch r305, AudioFocusLossSettings audioFocusLossSettings, C03353xs c03353xs, String str, List list, Map map) {
        long j = -1;
        this.A0V = videoDataSource;
        this.A0k = str;
        this.A0M = 0;
        this.A04 = 1.0f;
        this.A0j = "";
        this.A0Y = c03353xs;
        this.A1N = false;
        this.A1g = true;
        this.A0J = 0;
        this.A0B = 0;
        this.A12 = false;
        this.A0z = false;
        this.A1J = false;
        this.A0c = "";
        this.A0b = null;
        this.A1F = false;
        this.A1G = false;
        this.A1A = false;
        this.A16 = false;
        this.A1I = false;
        this.A0E = -1;
        this.A1D = false;
        this.A1P = false;
        this.A19 = false;
        this.A0P = j;
        this.A0Q = j;
        this.A0T = graphQLVideoBroadcastStatus;
        this.A05 = 0;
        this.A0U = null;
        this.A1C = false;
        this.A1b = true;
        this.A0K = 0;
        this.A0A = 0;
        this.A09 = -1;
        this.A08 = -1;
        this.A0D = -1;
        this.A1f = false;
        this.A0y = false;
        this.A1Q = false;
        this.A1j = false;
        this.A1k = false;
        this.A1B = false;
        this.A0L = -1;
        this.A1M = false;
        this.A06 = 2;
        this.A0W = r305;
        ImmutableMap copyOf = ImmutableMap.copyOf(map);
        11T.A0A(copyOf);
        this.A0a = copyOf;
        this.A11 = false;
        this.A10 = false;
        this.A1H = false;
        this.A13 = false;
        this.A1T = false;
        this.A1L = false;
        this.A1c = false;
        this.A1l = false;
        this.A1o = false;
        this.A0f = null;
        this.A0I = -1;
        this.A0H = -1;
        this.A1Z = true;
        this.A0d = null;
        this.A07 = 0;
        this.A0R = null;
        this.A00 = false;
        this.A1R = false;
        this.A17 = false;
        this.A0e = null;
        this.A1K = false;
        this.A0x = false;
        this.A1e = false;
        this.A0S = graphQLVideoBroadcastInfraType;
        this.A03 = 0.0d;
        this.A0F = -1;
        this.A0G = -1;
        this.A1O = false;
        this.A0X = audioFocusLossSettings;
        this.A1a = false;
        this.A15 = false;
        this.A0C = 0;
        this.A14 = false;
        this.A1d = false;
        this.A1i = false;
        this.A1E = false;
        this.A0N = 0;
        this.A0O = 0;
        this.A0h = null;
        this.A1V = false;
        this.A1W = false;
        this.A1X = false;
        this.A1Y = false;
        this.A1m = false;
        this.A0w = false;
        this.A1n = false;
        this.A1U = false;
        this.A0g = null;
        this.A0s = false;
        this.A0m = false;
        this.A0r = false;
        this.A0Z = null;
        this.A0u = false;
        this.A1h = false;
        this.A0i = "";
        this.A01 = 0.0d;
        this.A02 = 0.0d;
        this.A0o = false;
        this.A0n = false;
        this.A0q = false;
        this.A0v = false;
        this.A0l = list;
        this.A0t = false;
        this.A18 = false;
        this.A0p = false;
        this.A1S = false;
    }

    public HBk A00() {
        SphericalVideoParams sphericalVideoParams = this.A0U;
        if (sphericalVideoParams != null) {
            return sphericalVideoParams.A00;
        }
        return null;
    }

    public 6VJ A01() {
        SphericalVideoParams sphericalVideoParams = this.A0U;
        if (sphericalVideoParams != null) {
            return sphericalVideoParams.A01;
        }
        return null;
    }

    public final boolean A02(VideoPlayerParams videoPlayerParams) {
        11T.A0F(videoPlayerParams, 0);
        return 11T.A0O(this.A0k, videoPlayerParams.A0k) && this.A0M == videoPlayerParams.A0M && this.A04 == videoPlayerParams.A04 && 11T.A0O(this.A0j, videoPlayerParams.A0j) && 11T.A0O(this.A0Y, videoPlayerParams.A0Y) && this.A1N == videoPlayerParams.A1N && this.A1g == videoPlayerParams.A1g && 11T.A0O(this.A0U, videoPlayerParams.A0U) && this.A0K == videoPlayerParams.A0K && this.A0A == videoPlayerParams.A0A && this.A09 == videoPlayerParams.A09 && this.A08 == videoPlayerParams.A08 && this.A0D == videoPlayerParams.A0D && this.A1f == videoPlayerParams.A1f && this.A0y == videoPlayerParams.A0y && this.A1Q == videoPlayerParams.A1Q && this.A1j == videoPlayerParams.A1j && this.A1M == videoPlayerParams.A1M && this.A06 == videoPlayerParams.A06 && this.A0I == videoPlayerParams.A0I && this.A0H == videoPlayerParams.A0H;
    }

    public void CgE(6TX r302) {
        11T.A0F(r302, 0);
        VideoDataSource videoDataSource = this.A0V;
        if (videoDataSource == null) {
            r302.A04("VideoPlayerParams", "videoDataSourceNull", "");
            r302.A03("videoDataSourceNull", 0S2.A00);
        } else {
            videoDataSource.CgE(r302);
        }
        r302.A02(0S2.A13, String.valueOf(this.A0z));
        r302.A04("VideoPlayerParams", "videoId", this.A0k);
        r302.A04("VideoPlayerParams", "videoDurationMs", String.valueOf(this.A0M));
        r302.A04("VideoPlayerParams", "vEncode", this.A0j);
        C03353xs c03353xs = this.A0Y;
        if (c03353xs != null) {
            r302.A04("VideoPlayerParams", "trackingCodes", c03353xs.toString());
        }
        r302.A04("VideoPlayerParams", "isSponsored", String.valueOf(this.A1N));
        r302.A04("VideoPlayerParams", "isBroadcast", String.valueOf(this.A12));
        r302.A04("VideoPlayerParams", "isLiveNow", String.valueOf(this.A1F));
        r302.A04("VideoPlayerParams", "isLiveRewindEnabled", String.valueOf(this.A1G));
        r302.A04("VideoPlayerParams", "isGamingVideo", String.valueOf(this.A1A));
        r302.A04("VideoPlayerParams", "HasStreamerTray", String.valueOf(this.A0x));
        r302.A04("VideoPlayerParams", "isDarkModeSneakPeekEnabled", String.valueOf(this.A16));
        r302.A04("VideoPlayerParams", "isLowLatencyOptInEnabled", String.valueOf(this.A1I));
        r302.A04("VideoPlayerParams", "lowLatencyApplicability", String.valueOf(this.A0E));
        r302.A04("VideoPlayerParams", "isLatencySensitiveBroadcast", String.valueOf(this.A1D));
        r302.A04("VideoPlayerParams", "isUltraLowLatencyBroadcast", String.valueOf(this.A1P));
        r302.A04("VideoPlayerParams", "isGamingEsportsVideo", String.valueOf(this.A19));
        r302.A04("VideoPlayerParams", "liveLatency", String.valueOf(this.A0P));
        r302.A04("VideoPlayerParams", "liveLatencyTolerance", String.valueOf(this.A0Q));
        GraphQLVideoBroadcastStatus graphQLVideoBroadcastStatus = this.A0T;
        if (graphQLVideoBroadcastStatus != null) {
            r302.A04("VideoPlayerParams", "videoBroadcastStatus", graphQLVideoBroadcastStatus.toString());
        }
        GraphQLVideoBroadcastInfraType graphQLVideoBroadcastInfraType = this.A0S;
        if (graphQLVideoBroadcastInfraType != null) {
            r302.A04("VideoPlayerParams", "videoBroadcastInfraType", graphQLVideoBroadcastInfraType.toString());
        }
        r302.A04("VideoPlayerParams", "isAnimatedGifVideo", String.valueOf(this.A0y));
        r302.A04("VideoPlayerParams", "shouldLoopVideo", String.valueOf(this.A1g));
        r302.A04("VideoPlayerParams", "isHdUriPreferred", String.valueOf(this.A1C));
        r302.A04("VideoPlayerParams", "shouldAutoPlay", String.valueOf(this.A1b));
        r302.A04("VideoPlayerParams", "shouldShowQualitySelector", String.valueOf(this.A1j));
        r302.A04("VideoPlayerParams", "shouldUseGroot", String.valueOf(this.A1k));
        r302.A04("VideoPlayerParams", "isGrootEligible", String.valueOf(this.A1B));
        r302.A04("VideoPlayerParams", "isXMASharedVideo", String.valueOf(this.A1Q));
        r302.A04("VideoPlayerParams", "startPositionMs", String.valueOf(this.A0K));
        r302.A04("VideoPlayerParams", "endPositionMs", String.valueOf(this.A0A));
        r302.A04("VideoPlayerParams", "clippingStartPositionMs", String.valueOf(this.A09));
        r302.A04("VideoPlayerParams", "clippingEndPositionMs", String.valueOf(this.A08));
        r302.A04("VideoPlayerParams", "loopCount", String.valueOf(this.A0D));
        r302.A04("VideoPlayerParams", "storyPosition", String.valueOf(this.A0L));
        r302.A04("VideoPlayerParams", "audioFocusType", String.valueOf(this.A06));
        6Ch r0 = this.A0W;
        if (r0 != null) {
            r302.A04("VideoPlayerParams", "renderMode", r0.toString());
        }
        r302.A04("VideoPlayerParams", "isAutoAdvanced", String.valueOf(this.A11));
        r302.A04("VideoPlayerParams", "isAudioOnly", String.valueOf(this.A10));
        r302.A04("VideoPlayerParams", "preparePlayerUponPrepare", String.valueOf(this.A1T));
        r302.A04("VideoPlayerParams", "isServableViaFbms", String.valueOf(this.A1L));
        r302.A04("VideoPlayerParams", "livingRoomSessionId", String.valueOf(this.A0f));
        r302.A04("VideoPlayerParams", "fanFundingRFCreatorVertical", String.valueOf(this.A0d));
        r302.A04("VideoPlayerParams", "shouldKeepPlayerOnCompletion", String.valueOf(this.A1f));
        r302.A04("VideoPlayerParams", "sqBitrate", String.valueOf(this.A0J));
        r302.A04("VideoPlayerParams", "hqBitrate", String.valueOf(this.A0B));
        r302.A04("VideoPlayerParams", "atomSize", String.valueOf(this.A05));
        r302.A04("VideoPlayerParams", "overridingWatermarkMsBeforePlayed", String.valueOf(this.A0I));
        r302.A04("VideoPlayerParams", "overridingWarmupWatermarkMs", String.valueOf(this.A0H));
        r302.A04("VideoPlayerParams", "audioUsage", String.valueOf(this.A07));
        r302.A04("VideoPlayerParams", "audioAttributes", String.valueOf(this.A0R));
        r302.A04("VideoPlayerParams", "isBackGroundEligible", String.valueOf(this.A00));
        r302.A04("VideoPlayerParams", "shouldUseVideoEffectsPlugin", String.valueOf(this.A1l));
        r302.A04("VideoPlayerParams", "useFullGrootOutputDimensions", String.valueOf(this.A1o));
        r302.A04("VideoPlayerParams", "optinVideoProtocolUse", String.valueOf(this.A1R));
        r302.A04("VideoPlayerParams", "isFbShorts", String.valueOf(this.A17));
        r302.A04("VideoPlayerParams", "fbShortsViewerSessionId", String.valueOf(this.A0e));
        r302.A04("VideoPlayerParams", "watchTimePredictionSeconds", String.valueOf(this.A03));
        r302.A04("VideoPlayerParams", "overrideBufferWatermarkMs", String.valueOf(this.A0F));
        r302.A04("VideoPlayerParams", "overrideEndPositionMs", String.valueOf(this.A0G));
        r302.A04("VideoPlayerParams", "audioFocusLossSettings", this.A0X.toString());
        r302.A04("VideoPlayerParams", "servicePlayerReuseEnabled", String.valueOf(this.A1a));
        r302.A04("VideoPlayerParams", "isConcurrentPlaybackPermitted", String.valueOf(this.A15));
        r302.A04("VideoPlayerParams", "liveViewerCount", String.valueOf(this.A0C));
        r302.A04("VideoPlayerParams", "isClipPreview", String.valueOf(this.A14));
        r302.A04("VideoPlayerParams", "shouldDisableDownload", String.valueOf(this.A1d));
        r302.A04("VideoPlayerParams", "shouldResumePlayUponForeground", String.valueOf(this.A1i));
        r302.A04("VideoPlayerParams", "isLiveAudioRoomV2Broadcast", String.valueOf(this.A1E));
        r302.A04("VideoPlayerParams", "isClientTriggeredTraceEnabled", String.valueOf(this.A13));
        r302.A04("VideoPlayerParams", "preselectedVideoQualityLabel", this.A0h);
        r302.A04("VideoPlayerParams", "resizeGrootContainerOnAttach", String.valueOf(this.A1V));
        r302.A04("VideoPlayerParams", "resizeGrootContainerOnAttachForTextureView", String.valueOf(this.A1W));
        r302.A04("VideoPlayerParams", "restoreExoThreadPriorityOnPlayRequest", String.valueOf(this.A1X));
        r302.A04("VideoPlayerParams", "restoreLoaderThreadPriorityOnPlayRequest", String.valueOf(this.A1Y));
        r302.A04("VideoPlayerParams", "skipForeGroundPlayerCleanUp", String.valueOf(this.A1m));
        r302.A04("VideoPlayerParams", "handleForcedPlayerRelease", String.valueOf(this.A0w));
        r302.A04("VideoPlayerParams", "useCropToFitOnSurfaceView", String.valueOf(this.A1n));
        r302.A04("VideoPlayerParams", "enableResetPlayerParamsForReusedPlayer", String.valueOf(this.A0s));
        r302.A04("VideoPlayerParams", "disableBlackScreenDetectorForReusedPlayer", String.valueOf(this.A0m));
        r302.A04("VideoPlayerParams", "enableResetAspectRatioForReusedPlayer", String.valueOf(this.A0r));
        r302.A04("VideoPlayerParams", "customDataSourceFactory", String.valueOf(this.A0Z));
        r302.A04("VideoPlayerParams", "enableSoundToggleFeatureForReels", String.valueOf(this.A0u));
        r302.A04("VideoPlayerParams", "shouldPreventExcessiveLooping", String.valueOf(this.A1h));
        String str = this.A0i;
        if (str != null) {
            r302.A04("VideoPlayerParams", "qplJoinId", str);
        }
        double d = this.A01;
        if (d > 0.0d) {
            r302.A04("VideoPlayerParams", "focusX", String.valueOf(d));
        }
        double d2 = this.A02;
        if (d2 > 0.0d) {
            r302.A04("VideoPlayerParams", "focusY", String.valueOf(d2));
        }
        r302.A04("VideoPlayerParams", "enableE2EEStreamingDownload", String.valueOf(this.A0o));
        r302.A04("VideoPlayerParams", "disablePreloadDataForVod", String.valueOf(this.A0n));
        r302.A04("VideoPlayerParams", "enableMinBufferOverride", String.valueOf(this.A0q));
        r302.A04("VideoPlayerParams", "enableVitoOverride", String.valueOf(this.A0v));
        r302.A04("VideoPlayerParams", "enableResetSeekPositionOverride", String.valueOf(this.A0t));
        r302.A04("VideoPlayerParams", "enableLazyAudioOverride", String.valueOf(this.A0p));
        r302.A04("videoPlayerParams", "isForegroundCleanUpEligible", String.valueOf(this.A18));
        r302.A04("videoPlayerParams", "playLowestQuality", String.valueOf(this.A1S));
    }

    @Override // android.os.Parcelable
    public int describeContents() {
        return 0;
    }

    public boolean equals(Object obj) {
        boolean z = true;
        if (obj != this) {
            if (!(obj instanceof VideoPlayerParams)) {
                return false;
            }
            VideoPlayerParams videoPlayerParams = (VideoPlayerParams) obj;
            if (A02(videoPlayerParams) && this.A12 == videoPlayerParams.A12 && this.A1F == videoPlayerParams.A1F && this.A1G == videoPlayerParams.A1G && this.A1A == videoPlayerParams.A1A && this.A16 == videoPlayerParams.A16 && this.A1I == videoPlayerParams.A1I && this.A0E == videoPlayerParams.A0E && this.A1D == videoPlayerParams.A1D && this.A1P == videoPlayerParams.A1P && this.A19 == videoPlayerParams.A19 && this.A0P == videoPlayerParams.A0P && this.A0Q == videoPlayerParams.A0Q && this.A0T == videoPlayerParams.A0T && this.A0S == videoPlayerParams.A0S && this.A1b == videoPlayerParams.A1b && this.A11 == videoPlayerParams.A11 && this.A10 == videoPlayerParams.A10 && this.A1H == videoPlayerParams.A1H && this.A13 == videoPlayerParams.A13 && this.A1T == videoPlayerParams.A1T && 11T.A0O(this.A0V, videoPlayerParams.A0V) && this.A1k == videoPlayerParams.A1k && this.A1B == videoPlayerParams.A1B && this.A0W == videoPlayerParams.A0W && 11T.A0O(this.A0a, videoPlayerParams.A0a) && 11T.A0O(this.A0f, videoPlayerParams.A0f) && this.A1Z == videoPlayerParams.A1Z && this.A07 == videoPlayerParams.A07 && 11T.A0O(this.A0R, videoPlayerParams.A0R) && this.A0x == videoPlayerParams.A0x && 11T.A0O(this.A0X, videoPlayerParams.A0X) && this.A0F == videoPlayerParams.A0F && this.A0G == videoPlayerParams.A0G && this.A1d == videoPlayerParams.A1d && this.A1i == videoPlayerParams.A1i && this.A0O == videoPlayerParams.A0O && this.A0N == videoPlayerParams.A0N) {
                return true;
            }
            z = false;
        }
        return z;
    }

    public int hashCode() {
        Object[] objArr = new Object[73];
        System.arraycopy(new Object[]{this.A0V, this.A0k, Integer.valueOf(this.A0M), Float.valueOf(this.A04), this.A0j, this.A0Y, Boolean.valueOf(this.A1N), Boolean.valueOf(this.A1g), this.A0U, Boolean.valueOf(this.A1C), Boolean.valueOf(this.A1b), Boolean.valueOf(this.A11), Boolean.valueOf(this.A10), Integer.valueOf(this.A0K), Integer.valueOf(this.A0A), Integer.valueOf(this.A09), Integer.valueOf(this.A08), Integer.valueOf(this.A0D), Boolean.valueOf(this.A1f), Boolean.valueOf(this.A12), Boolean.valueOf(this.A0z), Boolean.valueOf(this.A1J), this.A0c, Boolean.valueOf(this.A1F), Boolean.valueOf(this.A1G), Boolean.valueOf(this.A1A), Boolean.valueOf(this.A0x)}, 0, objArr, 0, 27);
        System.arraycopy(new Object[]{Boolean.valueOf(this.A16), Boolean.valueOf(this.A1I), Integer.valueOf(this.A0E), Boolean.valueOf(this.A1D), Boolean.valueOf(this.A1P), Boolean.valueOf(this.A19), Long.valueOf(this.A0P), Long.valueOf(this.A0Q), this.A0T, Boolean.valueOf(this.A0y), Boolean.valueOf(this.A1Q), Boolean.valueOf(this.A1j), Boolean.valueOf(this.A1k), Boolean.valueOf(this.A1B), Integer.valueOf(this.A0L), Boolean.valueOf(this.A1M), Integer.valueOf(this.A06), this.A0W, Boolean.valueOf(this.A1H), Boolean.valueOf(this.A13), Boolean.valueOf(this.A1T), this.A0a, this.A0f, Integer.valueOf(this.A0I), Integer.valueOf(this.A0H), Boolean.valueOf(this.A1Z), Integer.valueOf(this.A07)}, 0, objArr, 27, 27);
        System.arraycopy(new Object[]{this.A0R, Boolean.valueOf(this.A1R), Boolean.valueOf(this.A17), Boolean.valueOf(this.A1K), Boolean.valueOf(this.A1e), this.A0S, Integer.valueOf(this.A0F), Integer.valueOf(this.A0G), this.A0X, Boolean.valueOf(this.A1a), Boolean.valueOf(this.A15), Integer.valueOf(this.A0C), Boolean.valueOf(this.A14), Boolean.valueOf(this.A1d), Boolean.valueOf(this.A1i), Boolean.valueOf(this.A1E), this.A0e, this.A0g, Boolean.valueOf(this.A1h)}, 0, objArr, 54, 19);
        return Arrays.hashCode(objArr);
    }

    public String toString() {
        return 0Pz.A0W("VideoId: ", this.A0k);
    }

    @Override // android.os.Parcelable
    public void writeToParcel(Parcel parcel, int i) {
        11T.A0F(parcel, 0);
        parcel.writeString(this.A0Y.toString());
        parcel.writeParcelable(this.A0V, i);
        parcel.writeString(this.A0k);
        parcel.writeInt(this.A0M);
        parcel.writeFloat(this.A04);
        parcel.writeString(this.A0j);
        parcel.writeByte(this.A1N ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1F ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1G ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1A ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A0x ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A16 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1I ? (byte) 1 : (byte) 0);
        parcel.writeInt(this.A0E);
        parcel.writeByte(this.A1D ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1P ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A19 ? (byte) 1 : (byte) 0);
        parcel.writeLong(this.A0P);
        parcel.writeLong(this.A0Q);
        GraphQLVideoBroadcastStatus graphQLVideoBroadcastStatus = this.A0T;
        parcel.writeString(graphQLVideoBroadcastStatus != null ? graphQLVideoBroadcastStatus.name() : null);
        parcel.writeByte(this.A1g ? (byte) 1 : (byte) 0);
        parcel.writeInt(this.A0J);
        parcel.writeInt(this.A0B);
        parcel.writeInt(this.A05);
        parcel.writeParcelable(this.A0U, i);
        parcel.writeByte(this.A1C ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1b ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A11 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A10 ? (byte) 1 : (byte) 0);
        parcel.writeInt(this.A0K);
        parcel.writeInt(this.A0A);
        parcel.writeInt(this.A09);
        parcel.writeInt(this.A08);
        parcel.writeInt(this.A0D);
        parcel.writeByte(this.A1f ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A12 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A0z ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1J ? (byte) 1 : (byte) 0);
        parcel.writeString(this.A0c);
        Boolean bool = this.A0b;
        byte b = 1;
        parcel.writeByte(AnonymousClass001.A1T(bool) ? (byte) 1 : (byte) 0);
        if (bool != null) {
            parcel.writeByte(bool.booleanValue() ? (byte) 1 : (byte) 0);
        }
        parcel.writeByte(this.A0y ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1Q ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1j ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1k ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1B ? (byte) 1 : (byte) 0);
        parcel.writeInt(this.A0L);
        parcel.writeByte(this.A1M ? (byte) 1 : (byte) 0);
        parcel.writeInt(this.A06);
        parcel.writeInt(this.A0W.mValue);
        parcel.writeByte(this.A1H ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A13 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1T ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1L ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1c ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1l ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1o ? (byte) 1 : (byte) 0);
        parcel.writeInt(this.A0I);
        parcel.writeInt(this.A0H);
        String str = this.A0f;
        if (str == null) {
            b = 0;
        }
        parcel.writeByte(b);
        if (str != null) {
            parcel.writeString(str);
        }
        parcel.writeByte(this.A1Z ? (byte) 1 : (byte) 0);
        parcel.writeString(this.A0d);
        parcel.writeInt(this.A07);
        parcel.writeParcelable(new ParcelImpl(this.A0R), 0);
        parcel.writeByte(this.A00 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1R ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A17 ? (byte) 1 : (byte) 0);
        parcel.writeString(this.A0e);
        parcel.writeByte(this.A1K ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1e ? (byte) 1 : (byte) 0);
        1BL.A12(parcel, this.A0S);
        parcel.writeDouble(this.A03);
        parcel.writeInt(this.A0F);
        parcel.writeInt(this.A0G);
        parcel.writeByte(this.A1O ? (byte) 1 : (byte) 0);
        parcel.writeParcelable(this.A0X, i);
        parcel.writeByte(this.A1a ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A15 ? (byte) 1 : (byte) 0);
        parcel.writeInt(this.A0C);
        parcel.writeByte(this.A14 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1d ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1i ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1E ? (byte) 1 : (byte) 0);
        parcel.writeInt(this.A0O);
        parcel.writeInt(this.A0N);
        parcel.writeString(this.A0h);
        parcel.writeByte(this.A1V ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1W ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1X ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1Y ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1U ? (byte) 1 : (byte) 0);
        parcel.writeString(this.A0g);
        parcel.writeByte(this.A0s ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A0m ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A0r ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A0u ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1h ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1m ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A0w ? (byte) 1 : (byte) 0);
        parcel.writeString(this.A0i);
        parcel.writeByte(this.A1n ? (byte) 1 : (byte) 0);
        parcel.writeDouble(this.A01);
        parcel.writeDouble(this.A02);
        parcel.writeByte(this.A0o ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A0n ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A0q ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A0v ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A0t ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A0p ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A18 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A1S ? (byte) 1 : (byte) 0);
    }
}
