package com.facebook.video.heroplayer.ipc;

import X.4YU;
import X.4YV;
import X.6Cy;
import X.6Cz;
import X.6DD;
import X.AbstractC2326GOr;
import X.AnonymousClass001;
import X.FKb;
import X.GOo;
import android.os.Parcel;
import android.os.Parcelable;

/* loaded from: HttpTransferRequestedEvent.class */
public final class HttpTransferRequestedEvent extends 6Cy implements Parcelable {
    public static final Parcelable.Creator CREATOR = new FKb(9);
    public static final long serialVersionUID = -8315438654847404035L;
    public final long avgBitrate;
    public final int bufferedDurationMs;
    public final int bufferedDurationMsAtDataSpecCreation;
    public final 6DD cacheType;
    public final long cdnResponseTime;
    public final String codec;
    public final long confidenceBasedBitrateEstimate;
    public final int confidencePctForBitrateEstimate;
    public final String contentType;
    public final String dataSourceFactory;
    public final long dataSpecCreationTimeMs;
    public final String exceptionMessage;
    public final int expectedPredictedNumber;
    public final int firstChunkSize;
    public final boolean inRewoundState;
    public final boolean isChunkedTransfer;
    public final boolean isFBMS;
    public final boolean isFbPredictiveDASH;
    public final boolean isFirstTimePlay;
    public final boolean isInWarmup;
    public final boolean isLowestBitrate;
    public final boolean isManifestDynamic;
    public final boolean isPredictedURL;
    public final boolean isPrefetch;
    public final boolean isSkipAheadChunk;
    public final boolean isSpherical;
    public final boolean isSponsored;
    public final boolean isTemplatedManifest;
    public final int latestSegmentId;
    public final long manifestFirstSegmentStartTs;
    public final long manifestLastSegmentEndTs;
    public final long manifestNumSegments;
    public final int minimumLoadPositionMs;
    public final int networkPriority;
    public final long numSegmentsToEndOfManifest;
    public final String oneObserved;
    public final String oneReqWave;
    public final String oneResWave;
    public final String oneVariant;
    public final String playOrigin;
    public final String playSubOrigin;
    public final long playerId;
    public final String playerType;
    public final int positionInUnit;
    public final int predictedNumberMapping;
    public final String prefetchSource;
    public final String qualityLabel;
    public final long requestedLength;
    public final int segmentDurationMs;
    public final long segmentStartMs;
    public final long startVideoBandwidth;
    public final long startVideoTTFB;
    public final long startingByteOffset;
    public final int streamType;
    public final long timeMs;
    public final int transferSeqNum;
    public final long upstreamTTFB;
    public final String url;
    public final String videoBandwidthEstimateStr;
    public final String videoId;
    public final String vpSessionId;

    public HttpTransferRequestedEvent(6DD r302, String str, String str2, String str3, String str4, String str5, String str6, String str7, String str8, String str9, String str10, String str11, String str12, String str13, String str14, String str15, String str16, String str17, int i, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10, int i11, int i12, int i13, long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10, boolean z11, boolean z12, boolean z13, boolean z14) {
        super(6Cz.A0G);
        this.timeMs = j;
        this.videoId = str;
        this.playerId = j2;
        this.url = str2;
        this.exceptionMessage = str3;
        this.isPrefetch = z;
        this.prefetchSource = str4;
        this.transferSeqNum = i;
        this.cacheType = r302;
        this.isFirstTimePlay = z2;
        this.isInWarmup = z3;
        this.playOrigin = str5;
        this.playSubOrigin = str9;
        this.startingByteOffset = j3;
        this.requestedLength = j4;
        this.streamType = i2;
        this.segmentStartMs = j5;
        this.segmentDurationMs = i3;
        this.dataSourceFactory = str6;
        this.qualityLabel = str7;
        this.networkPriority = i4;
        this.avgBitrate = j6;
        this.isLowestBitrate = z4;
        this.bufferedDurationMs = i5;
        this.startVideoBandwidth = j7;
        this.startVideoTTFB = j8;
        this.isSpherical = z5;
        this.isSponsored = z6;
        this.isTemplatedManifest = z7;
        this.videoBandwidthEstimateStr = str8;
        this.upstreamTTFB = j9;
        this.manifestFirstSegmentStartTs = j10;
        this.manifestLastSegmentEndTs = j11;
        this.manifestNumSegments = j12;
        this.bufferedDurationMsAtDataSpecCreation = i6;
        this.dataSpecCreationTimeMs = j13;
        this.isFBMS = z8;
        this.isFbPredictiveDASH = z9;
        this.isSkipAheadChunk = z10;
        this.inRewoundState = z11;
        this.isManifestDynamic = z12;
        this.isChunkedTransfer = z13;
        this.isPredictedURL = z14;
        this.expectedPredictedNumber = i8;
        this.predictedNumberMapping = i7;
        this.numSegmentsToEndOfManifest = j14;
        this.codec = str10;
        this.cdnResponseTime = j15;
        this.contentType = str11;
        this.latestSegmentId = i9;
        this.confidenceBasedBitrateEstimate = j16;
        this.confidencePctForBitrateEstimate = i10;
        this.minimumLoadPositionMs = i11;
        this.oneReqWave = str12;
        this.oneResWave = str13;
        this.oneObserved = str14;
        this.oneVariant = str15;
        this.playerType = str16;
        this.positionInUnit = i12;
        this.vpSessionId = str17;
        this.firstChunkSize = i13;
    }

    public HttpTransferRequestedEvent(Parcel parcel) {
        super(6Cz.A0G);
        this.timeMs = parcel.readLong();
        this.videoId = AbstractC2326GOr.A0g(parcel);
        this.playerId = parcel.readLong();
        this.url = parcel.readString();
        this.exceptionMessage = parcel.readString();
        boolean z = false;
        this.isPrefetch = AnonymousClass001.A1Q(parcel.readByte(), 1);
        this.prefetchSource = AbstractC2326GOr.A0g(parcel);
        this.transferSeqNum = parcel.readInt();
        6DD r303 = (6DD) 4YV.A0l(parcel, 6DD.class);
        this.cacheType = r303 == null ? 6DD.A03 : r303;
        this.isFirstTimePlay = AnonymousClass001.A1Q(parcel.readByte(), 1);
        this.isInWarmup = AnonymousClass001.A1Q(parcel.readByte(), 1);
        this.playOrigin = AbstractC2326GOr.A0g(parcel);
        this.playSubOrigin = parcel.readString();
        this.startingByteOffset = parcel.readLong();
        this.requestedLength = parcel.readLong();
        this.streamType = parcel.readInt();
        this.segmentStartMs = parcel.readLong();
        this.segmentDurationMs = parcel.readInt();
        this.dataSourceFactory = AbstractC2326GOr.A0g(parcel);
        this.qualityLabel = AbstractC2326GOr.A0g(parcel);
        this.networkPriority = parcel.readInt();
        this.avgBitrate = parcel.readLong();
        this.isLowestBitrate = AnonymousClass001.A1Q(parcel.readByte(), 1);
        this.bufferedDurationMs = parcel.readInt();
        this.startVideoBandwidth = parcel.readLong();
        this.startVideoTTFB = parcel.readLong();
        this.isSpherical = AnonymousClass001.A1Q(parcel.readByte(), 1);
        this.isSponsored = AnonymousClass001.A1Q(parcel.readByte(), 1);
        this.isTemplatedManifest = AnonymousClass001.A1Q(parcel.readByte(), 1);
        this.videoBandwidthEstimateStr = AbstractC2326GOr.A0g(parcel);
        this.upstreamTTFB = parcel.readLong();
        this.manifestFirstSegmentStartTs = parcel.readLong();
        this.manifestLastSegmentEndTs = parcel.readLong();
        this.manifestNumSegments = parcel.readLong();
        this.bufferedDurationMsAtDataSpecCreation = parcel.readInt();
        this.dataSpecCreationTimeMs = parcel.readLong();
        this.isFBMS = AnonymousClass001.A1Q(parcel.readByte(), 1);
        this.isFbPredictiveDASH = AnonymousClass001.A1Q(parcel.readByte(), 1);
        this.isSkipAheadChunk = AnonymousClass001.A1Q(parcel.readByte(), 1);
        this.inRewoundState = AnonymousClass001.A1Q(parcel.readByte(), 1);
        this.isManifestDynamic = AnonymousClass001.A1Q(parcel.readByte(), 1);
        this.isChunkedTransfer = AnonymousClass001.A1Q(parcel.readByte(), 1);
        this.isPredictedURL = parcel.readByte() == 1 ? true : z;
        this.expectedPredictedNumber = parcel.readInt();
        this.predictedNumberMapping = parcel.readInt();
        this.numSegmentsToEndOfManifest = parcel.readLong();
        this.codec = parcel.readString();
        this.cdnResponseTime = parcel.readLong();
        this.contentType = AbstractC2326GOr.A0g(parcel);
        this.latestSegmentId = parcel.readInt();
        this.confidenceBasedBitrateEstimate = parcel.readLong();
        this.confidencePctForBitrateEstimate = parcel.readInt();
        this.minimumLoadPositionMs = parcel.readInt();
        this.oneReqWave = parcel.readString();
        this.oneResWave = parcel.readString();
        this.oneObserved = parcel.readString();
        this.oneVariant = parcel.readString();
        this.playerType = parcel.readString();
        this.positionInUnit = parcel.readInt();
        this.vpSessionId = parcel.readString();
        this.firstChunkSize = parcel.readInt();
    }

    @Override // android.os.Parcelable
    public int describeContents() {
        return 0;
    }

    public String toString() {
        StringBuilder A0k = AnonymousClass001.A0k();
        4YV.A1O("timeMs=", A0k, this.timeMs);
        4YU.A1S(", videoId=", this.videoId, A0k);
        4YV.A1O(", playerId=", A0k, this.playerId);
        4YU.A1S(", url=", this.url, A0k);
        4YU.A1S(", exception=", this.exceptionMessage, A0k);
        4YV.A1P(", isPrefetch=", A0k, this.isPrefetch);
        4YU.A1S(", prefetchSource=", this.prefetchSource, A0k);
        GOo.A1P(", seqNum=", A0k, this.transferSeqNum);
        4YU.A1S(", cacheType=", this.cacheType.mName, A0k);
        4YV.A1P(", isFirstPlay=", A0k, this.isFirstTimePlay);
        4YU.A1S(", playOrigin=", this.playOrigin, A0k);
        4YV.A1O(", startingByteOffset=", A0k, this.startingByteOffset);
        4YV.A1O(", requestedLength=", A0k, this.requestedLength);
        GOo.A1P(", streamType=", A0k, this.streamType);
        4YV.A1O(", segmentStart=", A0k, this.segmentStartMs);
        GOo.A1P(", segmentDuration=", A0k, this.segmentDurationMs);
        4YU.A1S(", dataSourceFactory=", this.dataSourceFactory, A0k);
        4YU.A1S(", qualityLabel=", this.qualityLabel, A0k);
        GOo.A1P(", networkPriority=", A0k, this.networkPriority);
        GOo.A1P(", bufferedDurationMs=", A0k, this.bufferedDurationMs);
        4YV.A1O(", startVideoBandwidth=", A0k, this.startVideoBandwidth);
        4YV.A1O(", startVideoTTFB=", A0k, this.startVideoTTFB);
        4YU.A1S(", videoBandwidthEstimateStr=", this.videoBandwidthEstimateStr, A0k);
        4YV.A1O(", upstreamTTFB=", A0k, this.upstreamTTFB);
        4YV.A1O(", manifestFirstSegmentStartTs=", A0k, this.manifestFirstSegmentStartTs);
        4YV.A1O(", manifestLastSegmentEndTs=", A0k, this.manifestLastSegmentEndTs);
        4YV.A1O(", manifestNumSegments=", A0k, this.manifestNumSegments);
        GOo.A1P(", bufferedDurationMsAtDataSpecCreation=", A0k, this.bufferedDurationMsAtDataSpecCreation);
        4YV.A1O(", dataSpecCreationTimeMs=", A0k, this.dataSpecCreationTimeMs);
        4YU.A1S(", playSubOrigin=", this.playSubOrigin, A0k);
        4YV.A1P(", isFBMS=", A0k, this.isFBMS);
        4YV.A1P(", isFbPredictiveDASH=", A0k, this.isFbPredictiveDASH);
        4YV.A1P(", isSkipAheadChunk=", A0k, this.isSkipAheadChunk);
        4YV.A1P(", inRewoundState=", A0k, this.inRewoundState);
        4YV.A1P(", isManifestDynamic=", A0k, this.isManifestDynamic);
        4YV.A1P(", isChunkedTransfer=", A0k, this.isChunkedTransfer);
        4YV.A1P(", isPredictedURL=", A0k, this.isPredictedURL);
        GOo.A1P(", expectedPredictedNumber=", A0k, this.expectedPredictedNumber);
        GOo.A1P(", predictedNumberMapping=", A0k, this.predictedNumberMapping);
        4YV.A1O(", numSegmentsToEndOfManifest= ", A0k, this.numSegmentsToEndOfManifest);
        4YU.A1S(", codec= ", this.codec, A0k);
        4YV.A1O(", cdnResponseTime= ", A0k, this.cdnResponseTime);
        4YU.A1S(", contentType= ", this.contentType, A0k);
        GOo.A1P(", latestSegmentId= ", A0k, this.latestSegmentId);
        4YV.A1O(", confidenceBasedBitrateEstimate=", A0k, this.confidenceBasedBitrateEstimate);
        GOo.A1P(", confidencePctForBitrateEstimate=", A0k, this.confidencePctForBitrateEstimate);
        GOo.A1P(", minimumLoadPositionMs=", A0k, this.minimumLoadPositionMs);
        4YU.A1S(", oneReqWave=", this.oneReqWave, A0k);
        4YU.A1S(", oneResWave=", this.oneResWave, A0k);
        4YU.A1S(", oneObserved=", this.oneObserved, A0k);
        4YU.A1S(", oneVariant=", this.oneVariant, A0k);
        4YU.A1S(", playerType=", this.playerType, A0k);
        GOo.A1P(", positionInUnit=", A0k, this.positionInUnit);
        4YU.A1S(", vpSessionId=", this.vpSessionId, A0k);
        GOo.A1P(", firstChunkSize=", A0k, this.firstChunkSize);
        return A0k.toString();
    }

    @Override // android.os.Parcelable
    public void writeToParcel(Parcel parcel, int i) {
        parcel.writeLong(this.timeMs);
        parcel.writeString(this.videoId);
        parcel.writeLong(this.playerId);
        parcel.writeString(this.url);
        parcel.writeString(this.exceptionMessage);
        parcel.writeByte(this.isPrefetch ? (byte) 1 : (byte) 0);
        parcel.writeString(this.prefetchSource);
        parcel.writeInt(this.transferSeqNum);
        parcel.writeValue(this.cacheType);
        parcel.writeByte(this.isFirstTimePlay ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.isInWarmup ? (byte) 1 : (byte) 0);
        parcel.writeString(this.playOrigin);
        parcel.writeString(this.playSubOrigin);
        parcel.writeLong(this.startingByteOffset);
        parcel.writeLong(this.requestedLength);
        parcel.writeInt(this.streamType);
        parcel.writeLong(this.segmentStartMs);
        parcel.writeInt(this.segmentDurationMs);
        parcel.writeString(this.dataSourceFactory);
        parcel.writeString(this.qualityLabel);
        parcel.writeInt(this.networkPriority);
        parcel.writeLong(this.avgBitrate);
        parcel.writeByte(this.isLowestBitrate ? (byte) 1 : (byte) 0);
        parcel.writeInt(this.bufferedDurationMs);
        parcel.writeLong(this.startVideoBandwidth);
        parcel.writeLong(this.startVideoTTFB);
        parcel.writeByte(this.isSpherical ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.isSponsored ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.isTemplatedManifest ? (byte) 1 : (byte) 0);
        parcel.writeString(this.videoBandwidthEstimateStr);
        parcel.writeLong(this.upstreamTTFB);
        parcel.writeLong(this.manifestFirstSegmentStartTs);
        parcel.writeLong(this.manifestLastSegmentEndTs);
        parcel.writeLong(this.manifestNumSegments);
        parcel.writeInt(this.bufferedDurationMsAtDataSpecCreation);
        parcel.writeLong(this.dataSpecCreationTimeMs);
        parcel.writeByte(this.isFBMS ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.isFbPredictiveDASH ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.isSkipAheadChunk ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.inRewoundState ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.isManifestDynamic ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.isChunkedTransfer ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.isPredictedURL ? (byte) 1 : (byte) 0);
        parcel.writeInt(this.expectedPredictedNumber);
        parcel.writeInt(this.predictedNumberMapping);
        parcel.writeLong(this.numSegmentsToEndOfManifest);
        parcel.writeString(this.codec);
        parcel.writeLong(this.cdnResponseTime);
        parcel.writeString(this.contentType);
        parcel.writeInt(this.latestSegmentId);
        parcel.writeLong(this.confidenceBasedBitrateEstimate);
        parcel.writeInt(this.confidencePctForBitrateEstimate);
        parcel.writeInt(this.minimumLoadPositionMs);
        parcel.writeString(this.oneReqWave);
        parcel.writeString(this.oneResWave);
        parcel.writeString(this.oneObserved);
        parcel.writeString(this.oneVariant);
        parcel.writeString(this.playerType);
        parcel.writeInt(this.positionInUnit);
        parcel.writeString(this.vpSessionId);
        parcel.writeInt(this.firstChunkSize);
    }
}
