package com.facebook.graphql.enums;

import X.1BK;
import X.DKF;
import java.util.HashSet;
import java.util.Set;

/* loaded from: GraphQLVersionedCapabilityTypeSet.class */
public final class GraphQLVersionedCapabilityTypeSet {
    public static final HashSet A00;

    static {
        String[] strArr = new String[45];
        A00 = DKF.A0w(new String[]{"NAMETAG", "OCR2GOCREDITCARD", "PYTORCHTEST", "RECOGNITION", "RINGTRYON", "SAFECHAT", "SALIENCY", "SCENEDEPTH", "SCENEDEPTHWITHFALLBACK", "SCENEUNDERSTANDING", "SEGMENTANYTHING", "SEGMENTATION", "SKYSEGMENTATION", "TARGETRECOGNITION", "UTWONET", "VIDEOHIGHLIGHTS", "VIDEOHIGHLIGHTSTEMPORAL", "XRAY"}, strArr, 1BK.A1W(new String[]{"BIBYTEDOC", "BIDEEPTEXT", "BIXRAY", "BODYTRACKER", "BODYTRACKING", "BODYTRACKING3D", "CONVO2EMOTION", "DEPTHESTIMATION", "EGODETECTORTRACKER", "ENLIGHTENGAN", "FACEEXPRESSIONFITTING", "FACEEXPRESSIONFITTINGRTRRETARGETING", "FACEWAVE", "FACETRACKER", "GAZECORRECTION", "HAIRSEGMENTATION", "HANDGESTURE", "HANDTRACKER", "IGREELSXRAY", "IIFACETRACKER", "IIIDDETECTOR", "IIREDUCEDFACETRACKER", "MSUGGESTIONSCORE", "METADETTRACK", "MOBILEVISIONIMAGEUNDERSTANDING", "MULTICLASSSEGMENTATION", "MULTITASKPEOPLESEGMENTATION"}, strArr) ? 1 : 0, 27, 18);
    }

    public static final Set getSet() {
        return A00;
    }
}
