package com.facebook.graphql.enums;

import X.1BK;
import X.DKF;
import com.facebookpay.offsite.models.message.OffsiteInitAvailabilityRequestKt;
import java.util.HashSet;
import java.util.Set;

/* loaded from: GraphQLAREffectMLModelAssetTypeSet.class */
public final class GraphQLAREffectMLModelAssetTypeSet {
    public static final HashSet A00;

    static {
        String[] strArr = new String[51];
        A00 = DKF.A0w(new String[]{"M_SUGGESTIONS_CORE_STICKER_SENDER_INTENT_INIT", "M_SUGGESTIONS_CORE_STICKER_SENDER_INTENT_PREDICT", "M_SUGGESTIONS_CORE_STICKER_SENDER_TAG_INIT", "M_SUGGESTIONS_CORE_STICKER_SENDER_TAG_PREDICT", "NAMETAG_DETECTION_INIT", "NAMETAG_DETECTION_PRED", "NAMETAG_OCR_INIT", "NAMETAG_OCR_PRED", "OCR2GO_CONFIG", "OCR2GO_DET_MODEL", "OCR2GO_RCG_MODEL", "PYTORCH_MODEL", "RECOGNITION_CLASSIFICATION_INIT", "RECOGNITION_DETECTION_INIT", "RUNTIME_RIG_RETARGETING_CONFIG", "TARGET_RECOGNITION_CLASSIFICATION_INIT", "TARGET_RECOGNITION_CLASSIFICATION_PRED", "TARGET_RECOGNITION_DETECTION_INIT", "TARGET_RECOGNITION_DETECTION_PRED", OffsiteInitAvailabilityRequestKt.DEFAULT_PARTNER_ID, "XRAY_CLASSES", "XRAY_CONFIGURATION", "XRAY_INIT_NET", "XRAY_PREDICT_NET"}, strArr, 1BK.A1W(new String[]{"BODY_TRACKING_3D_DETECTION", "BODY_TRACKING_3D_LANDMARK", "CAFFE2_INIT_NET", "CAFFE2_PREDICT_NET", "EXECUTORCH_INIT_NET", "EXECUTORCH_PREDICT_NET", "EXPRESSION_FITTING", "EXPRESSION_FITTING_EXECUTORCH", "FACE_TRACKER_FACE_ALIGN", "FACE_TRACKER_FACE_ALIGN_EXECUTORCH", "FACE_TRACKER_FACE_CONTOUR", "FACE_TRACKER_FACE_CONTOUR_EXECUTORCH", "FACE_TRACKER_FACE_DETECT", "FACE_TRACKER_FACE_DETECT_EXECUTORCH", "FACE_TRACKER_FACE_MESH", "FACE_TRACKER_FACE_MESH_EXECUTORCH", "MULTICLASS_INIT_NET", "MULTICLASS_PREDICT_NET", "M_SUGGESTIONS_CORE_P13N_FILTERING_FEATURES", "M_SUGGESTIONS_CORE_P13N_FILTERING_INIT", "M_SUGGESTIONS_CORE_P13N_FILTERING_PREDICT", "M_SUGGESTIONS_CORE_SENSITIVITY_INIT", "M_SUGGESTIONS_CORE_SENSITIVITY_PREDICT", "M_SUGGESTIONS_CORE_STICKER_RECEIVER_INTENT_INIT", "M_SUGGESTIONS_CORE_STICKER_RECEIVER_INTENT_PREDICT", "M_SUGGESTIONS_CORE_STICKER_RECEIVER_TAG_INIT", "M_SUGGESTIONS_CORE_STICKER_RECEIVER_TAG_PREDICT"}, strArr) ? 1 : 0, 27, 24);
    }

    public static final Set getSet() {
        return A00;
    }
}
